/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:12:56 AM Central European Standard Time
* Operating System: Versie 10.10.2 (build 14C109)
* Image Source: /Applications/iTunes.app/Contents/MacOS/iTunes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <iTunes/iTunes-Structs.h>
#import <AppKit/NSTextField.h>

@class NSArray, NSString;

@interface ITAutoCompleteTextField : NSTextField {

	NSArray* _completionArray;
	NSString* _foundString;
	NSRange _foundRange;

}

@property (nonatomic,retain) NSArray * completionArray;              //@synthesize completionArray=_completionArray - In the implementation block
@property (nonatomic,retain) NSString * foundString;                 //@synthesize foundString=_foundString - In the implementation block
@property (assign,nonatomic) NSRange foundRange;                     //@synthesize foundRange=_foundRange - In the implementation block
-(void)setCompletionArray:(NSArray *)arg1 ;
-(NSArray *)completionArray;
-(id)ITTextFormatter;
-(char)isLengthChecked;
-(char)isLengthValidForString:(id)arg1 ;
-(void)setFoundString:(NSString *)arg1 ;
-(void)setFoundRange:(NSRange)arg1 ;
-(id)findStringWithPrefix:(id)arg1 inArray:(id)arg2 ;
-(NSString *)foundString;
-(NSRange)foundRange;
-(id)init;
-(void)dealloc;
-(id)initWithFrame:(CGRect)arg1 ;
-(char)textView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(void)textDidChange:(id)arg1 ;
-(void)awakeFromNib;
@end

