/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:12:56 AM Central European Standard Time
* Operating System: Versie 10.10.2 (build 14C109)
* Image Source: /Applications/iTunes.app/Contents/MacOS/iTunes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <iTunes/iTunes-Structs.h>
#import <Foundation/NSFormatter.h>

@interface ITTextFormatter : NSFormatter {

	long long _maxUTF8Length;
	long long _maxLength;
	char _isInteger;
	char _isTime;

}

@property (assign,nonatomic) long long maxLength;                  //@synthesize maxLength=_maxLength - In the implementation block
@property (assign,nonatomic) long long maxUTF8Length;              //@synthesize maxUTF8Length=_maxUTF8Length - In the implementation block
@property (assign,nonatomic) char isInteger;                       //@synthesize isInteger=_isInteger - In the implementation block
@property (assign,nonatomic) char isTime;                          //@synthesize isTime=_isTime - In the implementation block
+(id)formatter;
-(void)setIsInteger:(char)arg1 ;
-(char)isInteger;
-(void)setIsTime:(char)arg1 ;
-(char)isTime;
-(void)setMaxUTF8Length:(long long)arg1 ;
-(long long)maxUTF8Length;
-(char)isLengthChecked;
-(char)isLengthValidForString:(id)arg1 ;
-(char)isValidIntegerString:(id)arg1 ;
-(char)isValidTimeString:(id)arg1 ;
-(long long)maxLength;
-(void)setMaxLength:(long long)arg1 ;
-(char)isPartialStringValid:(id)arg1 newEditingString:(id*)arg2 errorDescription:(id*)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)getObjectValue:(id*)arg1 forString:(id)arg2 errorDescription:(id*)arg3 ;
-(id)stringForObjectValue:(id)arg1 ;
@end

