/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:12:56 AM Central European Standard Time
* Operating System: Versie 10.10.2 (build 14C109)
* Image Source: /Applications/iTunes.app/Contents/MacOS/iTunes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <iTunes/iTunes-Structs.h>
#import <iTunes/NSCopying.h>

@interface RelativeDate : NSObject <NSCopying> {

	long long relativeValue;
	int dateUnits;

}

@property (nonatomic,readonly) int dateUnits; 
@property (nonatomic,readonly) long long relativeValue; 
-(long long)relativeValue;
-(id)initWithValue:(long long)arg1 units:(int)arg2 ;
-(int)dateUnits;
-(id)description;
-(char)isEqual:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

