/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:12:56 AM Central European Standard Time
* Operating System: Versie 10.10.2 (build 14C109)
* Image Source: /Applications/iTunes.app/Contents/MacOS/iTunes
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <AppKit/NSPredicateEditorRowTemplate.h>

@class NSPopUpButton;

@interface TrackKindsRowTemplate : NSPredicateEditorRowTemplate {

	NSPopUpButton* _keyPathPopup;
	NSPopUpButton* _operatorPopup;
	NSPopUpButton* _trackKindsPopup;

}

@property (readonly) NSPopUpButton * keyPathPopup;                 //@synthesize keyPathPopup=_keyPathPopup - In the implementation block
@property (readonly) NSPopUpButton * operatorPopup;                //@synthesize operatorPopup=_operatorPopup - In the implementation block
@property (readonly) NSPopUpButton * trackKindsPopup;              //@synthesize trackKindsPopup=_trackKindsPopup - In the implementation block
-(void)loadViewsIfNecessary;
-(NSPopUpButton *)keyPathPopup;
-(NSPopUpButton *)operatorPopup;
-(NSPopUpButton *)trackKindsPopup;
-(void)dealloc;
-(void)setPredicate:(id)arg1 ;
-(id)itemTitles;
-(id)templateViews;
-(double)matchForPredicate:(id)arg1 ;
-(id)displayableSubpredicatesOfPredicate:(id)arg1 ;
-(id)predicateWithSubpredicates:(id)arg1 ;
@end

