/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:18:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Install OS X Yosemite.app/Contents/PlugIns/IA.bundle/Contents/MacOS/IA
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSError;

@interface IASoftwareUpdateCatalog : NSObject {

	NSDictionary* _catalog;
	NSError* _error;

}
+(id)sharedCatalog;
-(void)_fetchCatalog;
-(id)_softwareUpdateCatalogURL;
-(void)_finishedLoadingCatalog:(id)arg1 ;
-(void)startLoadingCatalog;
-(id)catalogAsPropertyList;
-(id)overriddenCatalogURL;
-(void)dealloc;
-(id)error;
@end

