/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:57:44 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Stickies.app/Contents/MacOS/Stickies
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Stickies/Stickies-Structs.h>
#import <AppKit/NSDocumentController.h>

@class NSView, NSPopUpButton, NSMenu, NSTimer, StickiesService, NSData, NSWindow;

@interface NoteController : NSDocumentController {

	NSView* mExportAccessoryView;
	NSPopUpButton* mExportFormatPopUp;
	NSMenu* mColorMenu;
	NSTimer* mSaveTimer;
	StickiesService* mStickyService;
	NSData* _databaseForArrangeUndo;
	NSWindow* mLastFrontWindow;
	char mIsDirty;
	CGPoint mNextCascadePoint;

}
-(CGPoint)nextCascadePoint;
-(void)setNextCascadePoint:(CGPoint)arg1 ;
-(id)exportAccessoryView;
-(id)exportFormatPopUp;
-(char)_openDatabaseAtPath:(id)arg1 ;
-(id)_openDocumentWithDocument:(id)arg1 ;
-(char)_unarchiveStickies;
-(void)populateColorMenuSwatches;
-(void)saveAllDocumentsMenuAction:(id)arg1 ;
-(void)arrange:(id)arg1 ;
-(void)changeExportFormat:(id)arg1 ;
-(void)closeWindow:(id)arg1 ;
-(void)set_databaseForArrangeUndo:(id)arg1 ;
-(void)undoArrange:(id)arg1 ;
-(void)setSaveTimer:(id)arg1 ;
-(void)importText:(id)arg1 ;
-(id)makeNewDocumentWithPasteboard:(id)arg1 ;
-(void)applicationDidFinishLaunching:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)setIsDirty:(char)arg1 ;
-(void)dealloc;
-(char)isDirty;
-(void)windowDidBecomeKey:(id)arg1 ;
-(char)validateMenuItem:(id)arg1 ;
-(id)frontWindow;
-(void)showHelp:(id)arg1 ;
-(void)application:(id)arg1 runTest:(unsigned long long)arg2 duration:(double)arg3 ;
-(void)awakeFromNib;
-(id)makeUntitledDocumentOfType:(id)arg1 ;
-(void)reviewUnsavedDocumentsWithAlertTitle:(id)arg1 cancellable:(char)arg2 delegate:(id)arg3 didReviewAllSelector:(SEL)arg4 contextInfo:(void*)arg5 ;
-(void)orderFrontStandardAboutPanel:(id)arg1 ;
@end

