/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:39 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/systemstats
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <systemstats/Timeline.h>

@class NSString, NSUUID;

@interface BootTimeline : Timeline {

	NSString* _systemVersion;
	NSUUID* _uuid;
	NSUUID* _lastUUID;
	NSString* _boardId;

}

@property (readonly) NSString * systemVersion;              //@synthesize systemVersion=_systemVersion - In the implementation block
@property (readonly) NSUUID * uuid;                         //@synthesize uuid=_uuid - In the implementation block
@property (readonly) NSUUID * lastUUID;                     //@synthesize lastUUID=_lastUUID - In the implementation block
@property (readonly) NSString * boardId;                    //@synthesize boardId=_boardId - In the implementation block
-(unsigned long long)endWallTime;
-(unsigned long long)startWallTime;
-(NSString *)boardId;
-(id)initWithUUID:(id)arg1 andLastUUID:(id)arg2 andEvents:(id)arg3 ;
-(id)initWithUUID:(id)arg1 andEvents:(id)arg2 ;
-(NSUUID *)lastUUID;
-(NSUUID *)uuid;
-(NSString *)systemVersion;
@end

