/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:39 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/systemstats
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <systemstats/systemstats-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <systemstats/NSCopying.h>

@interface PackageEnergyStatistics : PBCodable <NSCopying> {

	unsigned long long _absoluteTime;
	unsigned long long _energyModelCpuMillijoules;
	unsigned long long _energyModelGpuMillijoules;
	unsigned long long _energyModelMillijoules;
	unsigned long long _maxbusdelay;
	unsigned long long _pkgC0Residency;
	unsigned long long _pkgCanyResidency;
	unsigned long long _pkgCmaxResidency;
	unsigned long long _pkgFreq;
	unsigned long long _pkgFreqNominal;
	unsigned long long _qosBgTime;
	unsigned long long _qosIdleTime;
	SCD_Struct_Sl3 _has;

}

@property (assign,nonatomic) char hasAbsoluteTime; 
@property (assign,nonatomic) unsigned long long absoluteTime;                           //@synthesize absoluteTime=_absoluteTime - In the implementation block
@property (assign,nonatomic) char hasEnergyModelMillijoules; 
@property (assign,nonatomic) unsigned long long energyModelMillijoules;                 //@synthesize energyModelMillijoules=_energyModelMillijoules - In the implementation block
@property (assign,nonatomic) char hasPkgC0Residency; 
@property (assign,nonatomic) unsigned long long pkgC0Residency;                         //@synthesize pkgC0Residency=_pkgC0Residency - In the implementation block
@property (assign,nonatomic) char hasPkgCanyResidency; 
@property (assign,nonatomic) unsigned long long pkgCanyResidency;                       //@synthesize pkgCanyResidency=_pkgCanyResidency - In the implementation block
@property (assign,nonatomic) char hasPkgCmaxResidency; 
@property (assign,nonatomic) unsigned long long pkgCmaxResidency;                       //@synthesize pkgCmaxResidency=_pkgCmaxResidency - In the implementation block
@property (assign,nonatomic) char hasPkgFreq; 
@property (assign,nonatomic) unsigned long long pkgFreq;                                //@synthesize pkgFreq=_pkgFreq - In the implementation block
@property (assign,nonatomic) char hasPkgFreqNominal; 
@property (assign,nonatomic) unsigned long long pkgFreqNominal;                         //@synthesize pkgFreqNominal=_pkgFreqNominal - In the implementation block
@property (assign,nonatomic) char hasMaxbusdelay; 
@property (assign,nonatomic) unsigned long long maxbusdelay;                            //@synthesize maxbusdelay=_maxbusdelay - In the implementation block
@property (assign,nonatomic) char hasQosBgTime; 
@property (assign,nonatomic) unsigned long long qosBgTime;                              //@synthesize qosBgTime=_qosBgTime - In the implementation block
@property (assign,nonatomic) char hasQosIdleTime; 
@property (assign,nonatomic) unsigned long long qosIdleTime;                            //@synthesize qosIdleTime=_qosIdleTime - In the implementation block
@property (assign,nonatomic) char hasEnergyModelCpuMillijoules; 
@property (assign,nonatomic) unsigned long long energyModelCpuMillijoules;              //@synthesize energyModelCpuMillijoules=_energyModelCpuMillijoules - In the implementation block
@property (assign,nonatomic) char hasEnergyModelGpuMillijoules; 
@property (assign,nonatomic) unsigned long long energyModelGpuMillijoules;              //@synthesize energyModelGpuMillijoules=_energyModelGpuMillijoules - In the implementation block
-(unsigned long long)absoluteTime;
-(void)setAbsoluteTime:(unsigned long long)arg1 ;
-(char)hasAbsoluteTime;
-(void)setHasAbsoluteTime:(char)arg1 ;
-(unsigned long long)pkgFreq;
-(unsigned long long)energyModelCpuMillijoules;
-(unsigned long long)energyModelGpuMillijoules;
-(unsigned long long)pkgCanyResidency;
-(unsigned long long)pkgCmaxResidency;
-(unsigned long long)pkgFreqNominal;
-(unsigned long long)energyModelMillijoules;
-(char)hasPkgCanyResidency;
-(char)hasEnergyModelMillijoules;
-(char)hasEnergyModelCpuMillijoules;
-(char)hasEnergyModelGpuMillijoules;
-(void)setEnergyModelMillijoules:(unsigned long long)arg1 ;
-(void)setHasEnergyModelMillijoules:(char)arg1 ;
-(void)setPkgC0Residency:(unsigned long long)arg1 ;
-(void)setHasPkgC0Residency:(char)arg1 ;
-(char)hasPkgC0Residency;
-(void)setPkgCanyResidency:(unsigned long long)arg1 ;
-(void)setHasPkgCanyResidency:(char)arg1 ;
-(void)setPkgCmaxResidency:(unsigned long long)arg1 ;
-(void)setHasPkgCmaxResidency:(char)arg1 ;
-(char)hasPkgCmaxResidency;
-(void)setPkgFreq:(unsigned long long)arg1 ;
-(void)setHasPkgFreq:(char)arg1 ;
-(char)hasPkgFreq;
-(void)setPkgFreqNominal:(unsigned long long)arg1 ;
-(void)setHasPkgFreqNominal:(char)arg1 ;
-(char)hasPkgFreqNominal;
-(void)setMaxbusdelay:(unsigned long long)arg1 ;
-(void)setHasMaxbusdelay:(char)arg1 ;
-(char)hasMaxbusdelay;
-(void)setQosBgTime:(unsigned long long)arg1 ;
-(void)setHasQosBgTime:(char)arg1 ;
-(char)hasQosBgTime;
-(void)setQosIdleTime:(unsigned long long)arg1 ;
-(void)setHasQosIdleTime:(char)arg1 ;
-(char)hasQosIdleTime;
-(void)setEnergyModelCpuMillijoules:(unsigned long long)arg1 ;
-(void)setHasEnergyModelCpuMillijoules:(char)arg1 ;
-(void)setEnergyModelGpuMillijoules:(unsigned long long)arg1 ;
-(void)setHasEnergyModelGpuMillijoules:(char)arg1 ;
-(unsigned long long)pkgC0Residency;
-(unsigned long long)maxbusdelay;
-(unsigned long long)qosBgTime;
-(unsigned long long)qosIdleTime;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(id)prettyPrint;
-(id)description;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
@end

