/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:40 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/systemstats
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <systemstats/systemstats-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <systemstats/NSCopying.h>

@class NSString, NSData;

@interface ProcessUsage : PBCodable <NSCopying> {

	unsigned long long _anonmemSize;
	unsigned long long _childElapsedAbstime;
	unsigned long long _childInterruptWkups;
	unsigned long long _childPageins;
	unsigned long long _childPkgIdleWkups;
	unsigned long long _childSystemTime;
	unsigned long long _childUserTime;
	unsigned long long _compressedSize;
	long long _exitStatus;
	unsigned long long _interruptWkups;
	unsigned long long _ioaccelAllocatedSize;
	unsigned long long _ioaccelCachedSize;
	unsigned long long _ioaccelDirtySize;
	unsigned long long _ioaccelPurgeableSize;
	unsigned long long _ioaccelResidentSize;
	unsigned long long _ioaccelWiredSize;
	unsigned long long _nowAbstime;
	unsigned long long _pageins;
	unsigned long long _parentUniqueid;
	unsigned long long _physFootprint;
	unsigned long long _pid;
	unsigned long long _pkgIdleWkups;
	unsigned long long _ppid;
	unsigned long long _procExitAbstime;
	unsigned long long _procStartAbstime;
	unsigned long long _residentSize;
	unsigned long long _responsiblePid;
	unsigned long long _responsibleUniqueid;
	unsigned long long _systemTime;
	unsigned long long _uid;
	unsigned long long _uniqueid;
	unsigned long long _userTime;
	unsigned long long _wiredSize;
	NSString* _bundleIdentifier;
	NSString* _displayName;
	NSString* _name;
	NSData* _uuid;
	SCD_Struct_Pr12 _has;

}

@property (nonatomic,readonly) char hasName; 
@property (nonatomic,retain) NSString * name;                                      //@synthesize name=_name - In the implementation block
@property (assign,nonatomic) char hasPid; 
@property (assign,nonatomic) unsigned long long pid;                               //@synthesize pid=_pid - In the implementation block
@property (assign,nonatomic) char hasExitStatus; 
@property (assign,nonatomic) long long exitStatus;                                 //@synthesize exitStatus=_exitStatus - In the implementation block
@property (nonatomic,readonly) char hasUuid; 
@property (nonatomic,retain) NSData * uuid;                                        //@synthesize uuid=_uuid - In the implementation block
@property (assign,nonatomic) char hasUserTime; 
@property (assign,nonatomic) unsigned long long userTime;                          //@synthesize userTime=_userTime - In the implementation block
@property (assign,nonatomic) char hasSystemTime; 
@property (assign,nonatomic) unsigned long long systemTime;                        //@synthesize systemTime=_systemTime - In the implementation block
@property (assign,nonatomic) char hasPkgIdleWkups; 
@property (assign,nonatomic) unsigned long long pkgIdleWkups;                      //@synthesize pkgIdleWkups=_pkgIdleWkups - In the implementation block
@property (assign,nonatomic) char hasInterruptWkups; 
@property (assign,nonatomic) unsigned long long interruptWkups;                    //@synthesize interruptWkups=_interruptWkups - In the implementation block
@property (assign,nonatomic) char hasPageins; 
@property (assign,nonatomic) unsigned long long pageins;                           //@synthesize pageins=_pageins - In the implementation block
@property (assign,nonatomic) char hasWiredSize; 
@property (assign,nonatomic) unsigned long long wiredSize;                         //@synthesize wiredSize=_wiredSize - In the implementation block
@property (assign,nonatomic) char hasResidentSize; 
@property (assign,nonatomic) unsigned long long residentSize;                      //@synthesize residentSize=_residentSize - In the implementation block
@property (assign,nonatomic) char hasPhysFootprint; 
@property (assign,nonatomic) unsigned long long physFootprint;                     //@synthesize physFootprint=_physFootprint - In the implementation block
@property (assign,nonatomic) char hasProcStartAbstime; 
@property (assign,nonatomic) unsigned long long procStartAbstime;                  //@synthesize procStartAbstime=_procStartAbstime - In the implementation block
@property (assign,nonatomic) char hasProcExitAbstime; 
@property (assign,nonatomic) unsigned long long procExitAbstime;                   //@synthesize procExitAbstime=_procExitAbstime - In the implementation block
@property (assign,nonatomic) char hasNowAbstime; 
@property (assign,nonatomic) unsigned long long nowAbstime;                        //@synthesize nowAbstime=_nowAbstime - In the implementation block
@property (assign,nonatomic) char hasPpid; 
@property (assign,nonatomic) unsigned long long ppid;                              //@synthesize ppid=_ppid - In the implementation block
@property (assign,nonatomic) char hasResponsiblePid; 
@property (assign,nonatomic) unsigned long long responsiblePid;                    //@synthesize responsiblePid=_responsiblePid - In the implementation block
@property (assign,nonatomic) char hasUid; 
@property (assign,nonatomic) unsigned long long uid;                               //@synthesize uid=_uid - In the implementation block
@property (assign,nonatomic) char hasChildUserTime; 
@property (assign,nonatomic) unsigned long long childUserTime;                     //@synthesize childUserTime=_childUserTime - In the implementation block
@property (assign,nonatomic) char hasChildSystemTime; 
@property (assign,nonatomic) unsigned long long childSystemTime;                   //@synthesize childSystemTime=_childSystemTime - In the implementation block
@property (assign,nonatomic) char hasChildPkgIdleWkups; 
@property (assign,nonatomic) unsigned long long childPkgIdleWkups;                 //@synthesize childPkgIdleWkups=_childPkgIdleWkups - In the implementation block
@property (assign,nonatomic) char hasChildInterruptWkups; 
@property (assign,nonatomic) unsigned long long childInterruptWkups;               //@synthesize childInterruptWkups=_childInterruptWkups - In the implementation block
@property (assign,nonatomic) char hasChildPageins; 
@property (assign,nonatomic) unsigned long long childPageins;                      //@synthesize childPageins=_childPageins - In the implementation block
@property (assign,nonatomic) char hasChildElapsedAbstime; 
@property (assign,nonatomic) unsigned long long childElapsedAbstime;               //@synthesize childElapsedAbstime=_childElapsedAbstime - In the implementation block
@property (assign,nonatomic) char hasIoaccelAllocatedSize; 
@property (assign,nonatomic) unsigned long long ioaccelAllocatedSize;              //@synthesize ioaccelAllocatedSize=_ioaccelAllocatedSize - In the implementation block
@property (assign,nonatomic) char hasIoaccelResidentSize; 
@property (assign,nonatomic) unsigned long long ioaccelResidentSize;               //@synthesize ioaccelResidentSize=_ioaccelResidentSize - In the implementation block
@property (assign,nonatomic) char hasIoaccelWiredSize; 
@property (assign,nonatomic) unsigned long long ioaccelWiredSize;                  //@synthesize ioaccelWiredSize=_ioaccelWiredSize - In the implementation block
@property (assign,nonatomic) char hasIoaccelDirtySize; 
@property (assign,nonatomic) unsigned long long ioaccelDirtySize;                  //@synthesize ioaccelDirtySize=_ioaccelDirtySize - In the implementation block
@property (assign,nonatomic) char hasIoaccelCachedSize; 
@property (assign,nonatomic) unsigned long long ioaccelCachedSize;                 //@synthesize ioaccelCachedSize=_ioaccelCachedSize - In the implementation block
@property (assign,nonatomic) char hasIoaccelPurgeableSize; 
@property (assign,nonatomic) unsigned long long ioaccelPurgeableSize;              //@synthesize ioaccelPurgeableSize=_ioaccelPurgeableSize - In the implementation block
@property (nonatomic,readonly) char hasDisplayName; 
@property (nonatomic,retain) NSString * displayName;                               //@synthesize displayName=_displayName - In the implementation block
@property (assign,nonatomic) char hasUniqueid; 
@property (assign,nonatomic) unsigned long long uniqueid;                          //@synthesize uniqueid=_uniqueid - In the implementation block
@property (assign,nonatomic) char hasParentUniqueid; 
@property (assign,nonatomic) unsigned long long parentUniqueid;                    //@synthesize parentUniqueid=_parentUniqueid - In the implementation block
@property (assign,nonatomic) char hasResponsibleUniqueid; 
@property (assign,nonatomic) unsigned long long responsibleUniqueid;               //@synthesize responsibleUniqueid=_responsibleUniqueid - In the implementation block
@property (nonatomic,readonly) char hasBundleIdentifier; 
@property (nonatomic,retain) NSString * bundleIdentifier;                          //@synthesize bundleIdentifier=_bundleIdentifier - In the implementation block
@property (assign,nonatomic) char hasAnonmemSize; 
@property (assign,nonatomic) unsigned long long anonmemSize;                       //@synthesize anonmemSize=_anonmemSize - In the implementation block
@property (assign,nonatomic) char hasCompressedSize; 
@property (assign,nonatomic) unsigned long long compressedSize;                    //@synthesize compressedSize=_compressedSize - In the implementation block
-(char)hasInterruptWkups;
-(unsigned long long)interruptWkups;
-(char)hasPkgIdleWkups;
-(unsigned long long)pkgIdleWkups;
-(unsigned long long)absoluteTime;
-(void)setHasUid:(char)arg1 ;
-(void)setPkgIdleWkups:(unsigned long long)arg1 ;
-(void)setHasPkgIdleWkups:(char)arg1 ;
-(void)setInterruptWkups:(unsigned long long)arg1 ;
-(void)setHasInterruptWkups:(char)arg1 ;
-(unsigned long long)pageins;
-(void)setPageins:(unsigned long long)arg1 ;
-(long long)exitStatus;
-(unsigned long long)nowAbstime;
-(unsigned long long)procExitAbstime;
-(unsigned long long)systemTime;
-(unsigned long long)userTime;
-(unsigned long long)procStartAbstime;
-(unsigned long long)residentSize;
-(char)hasPageins;
-(char)hasIoaccelAllocatedSize;
-(unsigned long long)ioaccelAllocatedSize;
-(void)setIoaccelAllocatedSize:(unsigned long long)arg1 ;
-(char)hasIoaccelResidentSize;
-(unsigned long long)ioaccelResidentSize;
-(void)setIoaccelResidentSize:(unsigned long long)arg1 ;
-(char)hasIoaccelWiredSize;
-(unsigned long long)ioaccelWiredSize;
-(void)setIoaccelWiredSize:(unsigned long long)arg1 ;
-(char)hasIoaccelDirtySize;
-(unsigned long long)ioaccelDirtySize;
-(void)setIoaccelDirtySize:(unsigned long long)arg1 ;
-(char)hasIoaccelCachedSize;
-(unsigned long long)ioaccelCachedSize;
-(void)setIoaccelCachedSize:(unsigned long long)arg1 ;
-(char)hasIoaccelPurgeableSize;
-(unsigned long long)ioaccelPurgeableSize;
-(void)setIoaccelPurgeableSize:(unsigned long long)arg1 ;
-(void)setHasPageins:(char)arg1 ;
-(void)setHasIoaccelAllocatedSize:(char)arg1 ;
-(void)setHasIoaccelResidentSize:(char)arg1 ;
-(void)setHasIoaccelWiredSize:(char)arg1 ;
-(void)setHasIoaccelDirtySize:(char)arg1 ;
-(void)setHasIoaccelCachedSize:(char)arg1 ;
-(void)setHasIoaccelPurgeableSize:(char)arg1 ;
-(char)hasPid;
-(char)hasExitStatus;
-(void)setExitStatus:(long long)arg1 ;
-(char)hasUuid;
-(char)hasUserTime;
-(void)setUserTime:(unsigned long long)arg1 ;
-(char)hasSystemTime;
-(void)setSystemTime:(unsigned long long)arg1 ;
-(char)hasWiredSize;
-(unsigned long long)wiredSize;
-(void)setWiredSize:(unsigned long long)arg1 ;
-(char)hasResidentSize;
-(void)setResidentSize:(unsigned long long)arg1 ;
-(char)hasPhysFootprint;
-(unsigned long long)physFootprint;
-(void)setPhysFootprint:(unsigned long long)arg1 ;
-(char)hasProcStartAbstime;
-(void)setProcStartAbstime:(unsigned long long)arg1 ;
-(char)hasProcExitAbstime;
-(void)setProcExitAbstime:(unsigned long long)arg1 ;
-(char)hasNowAbstime;
-(void)setNowAbstime:(unsigned long long)arg1 ;
-(char)hasPpid;
-(void)setPpid:(unsigned long long)arg1 ;
-(char)hasResponsiblePid;
-(char)hasChildUserTime;
-(unsigned long long)childUserTime;
-(void)setChildUserTime:(unsigned long long)arg1 ;
-(char)hasChildSystemTime;
-(unsigned long long)childSystemTime;
-(void)setChildSystemTime:(unsigned long long)arg1 ;
-(char)hasChildPkgIdleWkups;
-(unsigned long long)childPkgIdleWkups;
-(void)setChildPkgIdleWkups:(unsigned long long)arg1 ;
-(char)hasChildInterruptWkups;
-(unsigned long long)childInterruptWkups;
-(void)setChildInterruptWkups:(unsigned long long)arg1 ;
-(char)hasChildPageins;
-(unsigned long long)childPageins;
-(void)setChildPageins:(unsigned long long)arg1 ;
-(char)hasChildElapsedAbstime;
-(unsigned long long)childElapsedAbstime;
-(void)setChildElapsedAbstime:(unsigned long long)arg1 ;
-(char)hasUniqueid;
-(unsigned long long)uniqueid;
-(void)setUniqueid:(unsigned long long)arg1 ;
-(char)hasParentUniqueid;
-(unsigned long long)parentUniqueid;
-(void)setParentUniqueid:(unsigned long long)arg1 ;
-(char)hasResponsibleUniqueid;
-(unsigned long long)responsibleUniqueid;
-(void)setResponsibleUniqueid:(unsigned long long)arg1 ;
-(char)hasAnonmemSize;
-(unsigned long long)anonmemSize;
-(void)setAnonmemSize:(unsigned long long)arg1 ;
-(char)hasCompressedSize;
-(void)setHasPid:(char)arg1 ;
-(void)setHasExitStatus:(char)arg1 ;
-(void)setHasUserTime:(char)arg1 ;
-(void)setHasSystemTime:(char)arg1 ;
-(void)setHasWiredSize:(char)arg1 ;
-(void)setHasResidentSize:(char)arg1 ;
-(void)setHasPhysFootprint:(char)arg1 ;
-(void)setHasProcStartAbstime:(char)arg1 ;
-(void)setHasProcExitAbstime:(char)arg1 ;
-(void)setHasNowAbstime:(char)arg1 ;
-(void)setHasPpid:(char)arg1 ;
-(void)setHasResponsiblePid:(char)arg1 ;
-(void)setHasChildUserTime:(char)arg1 ;
-(void)setHasChildSystemTime:(char)arg1 ;
-(void)setHasChildPkgIdleWkups:(char)arg1 ;
-(void)setHasChildInterruptWkups:(char)arg1 ;
-(void)setHasChildPageins:(char)arg1 ;
-(void)setHasChildElapsedAbstime:(char)arg1 ;
-(void)setHasUniqueid:(char)arg1 ;
-(void)setHasParentUniqueid:(char)arg1 ;
-(void)setHasResponsibleUniqueid:(char)arg1 ;
-(void)setHasAnonmemSize:(char)arg1 ;
-(void)setHasCompressedSize:(char)arg1 ;
-(id)UUID;
-(NSData *)uuid;
-(void)setUuid:(NSData *)arg1 ;
-(unsigned long long)pid;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(char)hasName;
-(unsigned long long)compressedSize;
-(void)setCompressedSize:(unsigned long long)arg1 ;
-(void)setResponsiblePid:(unsigned long long)arg1 ;
-(unsigned long long)responsiblePid;
-(unsigned long long)ppid;
-(void)setPid:(unsigned long long)arg1 ;
-(id)prettyPrint;
-(void)setBundleIdentifier:(NSString *)arg1 ;
-(char)hasBundleIdentifier;
-(char)hasUid;
-(char)hasDisplayName;
-(void)dealloc;
-(id)description;
-(void)setName:(NSString *)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)name;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)bundleIdentifier;
-(id)dictionaryRepresentation;
-(NSString *)displayName;
-(void)setDisplayName:(NSString *)arg1 ;
-(unsigned long long)uid;
-(void)setUid:(unsigned long long)arg1 ;
@end

