/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:39 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/systemstats
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <systemstats/Summary.h>

@class NSMutableDictionary, NSString;

@interface ProcessSummary : Summary {

	double _elapsedTime;
	double _cpuTime;
	double _interrupts;
	double _idleWakeups;
	double _spawns;
	double _pageins;
	double _maxResidentSize;
	double _maxWired;
	unsigned long long _stillrunning;
	double _runtime;
	NSMutableDictionary* _subprocesses;
	NSString* _label;
	NSString* _displayName;

}

@property (assign) double elapsedTime;                              //@synthesize elapsedTime=_elapsedTime - In the implementation block
@property (assign) double cpuTime;                                  //@synthesize cpuTime=_cpuTime - In the implementation block
@property (assign) double interrupts;                               //@synthesize interrupts=_interrupts - In the implementation block
@property (assign) double idleWakeups;                              //@synthesize idleWakeups=_idleWakeups - In the implementation block
@property (assign) double spawns;                                   //@synthesize spawns=_spawns - In the implementation block
@property (assign) double pageins;                                  //@synthesize pageins=_pageins - In the implementation block
@property (assign) double maxResidentSize;                          //@synthesize maxResidentSize=_maxResidentSize - In the implementation block
@property (assign) double maxWired;                                 //@synthesize maxWired=_maxWired - In the implementation block
@property (assign) unsigned long long stillrunning;                 //@synthesize stillrunning=_stillrunning - In the implementation block
@property (assign) double runtime;                                  //@synthesize runtime=_runtime - In the implementation block
@property (readonly) double powerScore; 
@property (retain) NSMutableDictionary * subprocesses;              //@synthesize subprocesses=_subprocesses - In the implementation block
@property (retain) NSString * label;                                //@synthesize label=_label - In the implementation block
@property (retain) NSString * displayName;                          //@synthesize displayName=_displayName - In the implementation block
-(double)cpuTime;
-(double)interrupts;
-(double)idleWakeups;
-(double)spawns;
-(long long)compareCPUTime:(id)arg1 ;
-(long long)compareInterrupts:(id)arg1 ;
-(long long)compareSpawns:(id)arg1 ;
-(void)setCpuTime:(double)arg1 ;
-(void)setInterrupts:(double)arg1 ;
-(void)setIdleWakeups:(double)arg1 ;
-(void)setSpawns:(double)arg1 ;
-(id)subprocessesSortedBySelector:(SEL)arg1 ;
-(long long)compareMaxResidentSize:(id)arg1 ;
-(double)maxResidentSize;
-(long long)comparePowerScores:(id)arg1 ;
-(double)powerScore;
-(unsigned long long)stillrunning;
-(double)runtime;
-(double)maxWired;
-(double)pageins;
-(NSMutableDictionary *)subprocesses;
-(long long)compareInterruptsPerCPUSecond:(id)arg1 ;
-(long long)compareMaxWired:(id)arg1 ;
-(long long)comparePageins:(id)arg1 ;
-(long long)compareRuntimes:(id)arg1 ;
-(void)setPageins:(double)arg1 ;
-(void)setMaxResidentSize:(double)arg1 ;
-(void)setMaxWired:(double)arg1 ;
-(void)setStillrunning:(unsigned long long)arg1 ;
-(void)setRuntime:(double)arg1 ;
-(void)setSubprocesses:(NSMutableDictionary *)arg1 ;
-(void)setElapsedTime:(double)arg1 ;
-(double)elapsedTime;
-(id)init;
-(void)setLabel:(NSString *)arg1 ;
-(NSString *)displayName;
-(void)setDisplayName:(NSString *)arg1 ;
-(NSString *)label;
@end

