/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:39 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/systemstats
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <systemstats/systemstats-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <systemstats/NSCopying.h>

@interface SSDLPSRResidency : PBCodable <NSCopying> {

	unsigned long long _absoluteTime;
	long long _ssdNum;
	unsigned long long _timeActive;
	unsigned long long _timeLpsr;
	unsigned long long _timeOff;
	unsigned long long _timePause;
	SCD_Struct_SS10 _has;

}

@property (assign,nonatomic) unsigned long long absoluteTime;              //@synthesize absoluteTime=_absoluteTime - In the implementation block
@property (assign,nonatomic) char hasSsdNum; 
@property (assign,nonatomic) long long ssdNum;                             //@synthesize ssdNum=_ssdNum - In the implementation block
@property (assign,nonatomic) char hasTimeOff; 
@property (assign,nonatomic) unsigned long long timeOff;                   //@synthesize timeOff=_timeOff - In the implementation block
@property (assign,nonatomic) char hasTimePause; 
@property (assign,nonatomic) unsigned long long timePause;                 //@synthesize timePause=_timePause - In the implementation block
@property (assign,nonatomic) char hasTimeLpsr; 
@property (assign,nonatomic) unsigned long long timeLpsr;                  //@synthesize timeLpsr=_timeLpsr - In the implementation block
@property (assign,nonatomic) char hasTimeActive; 
@property (assign,nonatomic) unsigned long long timeActive;                //@synthesize timeActive=_timeActive - In the implementation block
-(unsigned long long)absoluteTime;
-(void)setAbsoluteTime:(unsigned long long)arg1 ;
-(unsigned long long)timeOff;
-(unsigned long long)timeLpsr;
-(unsigned long long)timePause;
-(unsigned long long)timeActive;
-(void)setSsdNum:(long long)arg1 ;
-(void)setHasSsdNum:(char)arg1 ;
-(char)hasSsdNum;
-(void)setTimeOff:(unsigned long long)arg1 ;
-(void)setHasTimeOff:(char)arg1 ;
-(char)hasTimeOff;
-(void)setTimePause:(unsigned long long)arg1 ;
-(void)setHasTimePause:(char)arg1 ;
-(char)hasTimePause;
-(void)setTimeLpsr:(unsigned long long)arg1 ;
-(void)setHasTimeLpsr:(char)arg1 ;
-(char)hasTimeLpsr;
-(void)setTimeActive:(unsigned long long)arg1 ;
-(void)setHasTimeActive:(char)arg1 ;
-(char)hasTimeActive;
-(long long)ssdNum;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(id)prettyPrint;
-(id)description;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
@end

