#import <systemstats/SleepSummarizer.h>
#import <systemstats/DarkWakeSummarizer.h>
#import <systemstats/WakeSummarizer.h>
#import <systemstats/Coalition.h>
#import <systemstats/CoalitionSummary.h>
#import <systemstats/CoalitionSummarizer.h>
#import <systemstats/SSDThrottleTime.h>
#import <systemstats/Options.h>
#import <systemstats/BatteryChargeLevel.h>
#import <systemstats/SleepWake.h>
#import <systemstats/ACPowerSummarizer.h>
#import <systemstats/BatteryPowerSummarizer.h>
#import <systemstats/SSDThrottleContext.h>
#import <systemstats/SSDThrottleSummarizer.h>
#import <systemstats/PanelSelfRefresh.h>
#import <systemstats/CoalitionUsage.h>
#import <systemstats/LogStartsV0.h>
#import <systemstats/FanContext.h>
#import <systemstats/FanSummarizer.h>
#import <systemstats/SMCKeySampleContext.h>
#import <systemstats/SMCKeySampleSummarizer.h>
#import <systemstats/SMCKeySampleSummary.h>
#import <systemstats/SmcKeys.h>
#import <systemstats/HashFactory.h>
#import <systemstats/PowerStateChange.h>
#import <systemstats/CPUBootContext.h>
#import <systemstats/CPUSummarizer.h>
#import <systemstats/WiFiSummarizer.h>
#import <systemstats/DiscreteGraphicsSummarizer.h>
#import <systemstats/BluetoothSummarizer.h>
#import <systemstats/Device.h>
#import <systemstats/DeviceSummarizer.h>
#import <systemstats/BatterySummarizer.h>
#import <systemstats/AbsoluteTimeline.h>
#import <systemstats/Timeline.h>
#import <systemstats/BootTimeline.h>
#import <systemstats/Histogram.h>
#import <systemstats/BrightnessSummarizer.h>
#import <systemstats/SmcKey.h>
#import <systemstats/MessageTraceCoalition.h>
#import <systemstats/XCPMTiers.h>
#import <systemstats/LogStartsV1.h>
#import <systemstats/Interpolator.h>
#import <systemstats/IncreasingInterpolator.h>
#import <systemstats/SawtoothInterpolator.h>
#import <systemstats/Ledger.h>
#import <systemstats/AggregateInterpolator.h>
#import <systemstats/AbsoluteLedger.h>
#import <systemstats/SSDLPSRSummarizer.h>
#import <systemstats/DateChange.h>
#import <systemstats/XCPMTierNumbered.h>
#import <systemstats/Domain.h>
#import <systemstats/RelativeTimeDomain.h>
#import <systemstats/WallTimeDomain.h>
#import <systemstats/AbsoluteDomain.h>
#import <systemstats/DateDomain.h>
#import <systemstats/AllDomain.h>
#import <systemstats/BootDomain.h>
#import <systemstats/PostInstallDomain.h>
#import <systemstats/TimeChange.h>
#import <systemstats/Summary.h>
#import <systemstats/CPUSummary.h>
#import <systemstats/DeviceSummary.h>
#import <systemstats/IOSummary.h>
#import <systemstats/SSDThrottleSummary.h>
#import <systemstats/SSDLPSRSummary.h>
#import <systemstats/PSRSummary.h>
#import <systemstats/MemorySummary.h>
#import <systemstats/PowerSummary.h>
#import <systemstats/ProcessSummary.h>
#import <systemstats/FanSummary.h>
#import <systemstats/Model.h>
#import <systemstats/SSDLPSRResidency.h>
#import <systemstats/IOContext.h>
#import <systemstats/IOSummarizer.h>
#import <systemstats/KeyboardBrightnessSummarizer.h>
#import <systemstats/AbsTime.h>
#import <systemstats/AbsRange.h>
#import <systemstats/Cstate.h>
#import <systemstats/ThermalLevels.h>
#import <systemstats/ThermalContext.h>
#import <systemstats/ThermalSummary.h>
#import <systemstats/ThermalSummarizer.h>
#import <systemstats/DataSet.h>
#import <systemstats/PackageEnergyStatistics.h>
#import <systemstats/UsageSummarizer.h>
#import <systemstats/UserActiveSummarizer.h>
#import <systemstats/UserIdleSummarizer.h>
#import <systemstats/DeviceChange.h>
#import <systemstats/FanState.h>
#import <systemstats/SystemIO.h>
#import <systemstats/PSRContext.h>
#import <systemstats/PSRSummarizer.h>
#import <systemstats/DisplayBrightness.h>
#import <systemstats/SystemMemory.h>
#import <systemstats/GpuCstates.h>
#import <systemstats/UserIdle.h>
#import <systemstats/InterruptVector.h>
#import <systemstats/KeyboardBrightness.h>
#import <systemstats/MemoryContext.h>
#import <systemstats/MemorySummarizer.h>
#import <systemstats/XCPMTierNamed.h>
#import <systemstats/StandbyContext.h>
#import <systemstats/StandbySummarizer.h>
#import <systemstats/StandbySummary.h>
#import <systemstats/Cstates.h>
#import <systemstats/BluetoothPowerResidency.h>
#import <systemstats/ProcessUsage.h>
#import <systemstats/Interrupts.h>
#import <systemstats/Process.h>
#import <systemstats/Job.h>
#import <systemstats/ProcessBootContext.h>
#import <systemstats/ProcessSummarizer.h>
#import <systemstats/InterpolatorContext.h>
#import <systemstats/Summarizer.h>
#import <systemstats/TimeAtTier.h>
