/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 11:24:00 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Digital Color Meter.app/Contents/MacOS/Digital Color Meter
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Digital Color Meter/Digital Color Meter-Structs.h>
#import <AppKit/NSView.h>

@class NSColor;

@interface ColorView : NSView {

	NSColor* _color;

}

@property (retain) NSColor * color;              //@synthesize color=_color - In the implementation block
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(char)isOpaque;
-(void)setColor:(NSColor *)arg1 ;
-(NSColor *)color;
@end

