/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:38 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/spindump
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <spindump/SPWatchdog.h>

@interface SPSleepWakeFailure : SPWatchdog
-(id)initWithStackshotFile:(const char*)arg1 andDataFile:(const char*)arg2 withSignature:(const char*)arg3 ;
@end

