/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:10:39 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/0xED.app/Contents/MacOS/0xED
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <AppKit/NSWindowController.h>
#import <0xED/UserModifiedTextField.h>

@class NSTextField, NSButton, PathComplete, DownloadPanelWindowController, NSURLDownload;

@interface OpenDocumentByPathController : NSWindowController <UserModifiedTextField> {

	NSTextField* m_pTextField;
	NSButton* openButton;
	PathComplete* pathComplete;
	DownloadPanelWindowController* downloadPanelController;
	NSURLDownload* downloadURL;

}
-(void)textViewDidModify;
-(char)isValidFtpURL:(id)arg1 ;
-(char)isValidHttpURL:(id)arg1 ;
-(char)isValidFilePath:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)cancel:(id)arg1 ;
-(void)open:(id)arg1 ;
-(id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2 ;
-(void)sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void*)arg3 ;
-(void)windowDidLoad;
@end

