/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:40 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/usernoted
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <usernoted/NCConnection.h>

@class NSString, NSData, NSDictionary, NCSourceIdentifier;

@interface NCClientConnection : NCConnection {

	NSString* _sourceIdentity;
	NSString* _applicationIdentity;
	NSString* _verifiedForPush;
	NSString* _pushEnvironment;
	NSString* _pushIdentity;
	NSData* _pushToken;
	NSDictionary* _entitlementDictionary;
	NCSourceIdentifier* _sourceIdentifier;
	char _acceptsAppActionOnBehalfOfApplication;
	char _actsOnBehalfOfApplication;
	char _connectedThroughTestApp;
	char _isWebConnection;
	char _systemNotificationConnection;
	char _isSocialConnection;
	char _internalPushClientEntitled;
	int _centerType;

}

@property (retain) NCSourceIdentifier * sourceIdentifier;                     //@synthesize sourceIdentifier=_sourceIdentifier - In the implementation block
@property (readonly) NSString * applicationIdentity;                          //@synthesize applicationIdentity=_applicationIdentity - In the implementation block
@property (readonly) NSString * sourceIdentity;                               //@synthesize sourceIdentity=_sourceIdentity - In the implementation block
@property (readonly) NSString * pushEnvironment;                              //@synthesize pushEnvironment=_pushEnvironment - In the implementation block
@property (readonly) NSString * pushIdentity;                                 //@synthesize pushIdentity=_pushIdentity - In the implementation block
@property (nonatomic,readonly) NSString * pushLiverpoolIdentity; 
@property (retain) NSData * pushToken;                                        //@synthesize pushToken=_pushToken - In the implementation block
@property (readonly) int centerType;                                          //@synthesize centerType=_centerType - In the implementation block
@property (assign) char acceptsAppActionOnBehalfOfApplication;                //@synthesize acceptsAppActionOnBehalfOfApplication=_acceptsAppActionOnBehalfOfApplication - In the implementation block
@property (readonly) char actsOnBehalfOfApplication;                          //@synthesize actsOnBehalfOfApplication=_actsOnBehalfOfApplication - In the implementation block
@property (readonly) char systemNotificationConnection;                       //@synthesize systemNotificationConnection=_systemNotificationConnection - In the implementation block
@property (readonly) char connectedThroughTestApp;                            //@synthesize connectedThroughTestApp=_connectedThroughTestApp - In the implementation block
@property (readonly) char isWebConnection;                                    //@synthesize isWebConnection=_isWebConnection - In the implementation block
@property (readonly) char isSocialConnection;                                 //@synthesize isSocialConnection=_isSocialConnection - In the implementation block
@property (readonly) char internalPushClientEntitled;                         //@synthesize internalPushClientEntitled=_internalPushClientEntitled - In the implementation block
@property (readonly) NSDictionary * entitlementDictionary;                    //@synthesize entitlementDictionary=_entitlementDictionary - In the implementation block
-(char)actsOnBehalfOfApplication;
-(char)connectedThroughTestApp;
-(char)internalPushClientEntitled;
-(void)handleIncomingEvent:(id)arg1 ;
-(NSString *)applicationIdentity;
-(id)initConnection:(id)arg1 isDaemon:(char)arg2 ;
-(id)initWebConnection:(id)arg1 ;
-(id)initSocialConnection:(id)arg1 ;
-(NSString *)pushEnvironment;
-(void)client_scheduleNotification:(id)arg1 app:(id)arg2 immediate:(char)arg3 ;
-(void)client_cancelScheduledNotification:(id)arg1 app:(id)arg2 ;
-(void)client_removeDeliveredNotification:(id)arg1 app:(id)arg2 ;
-(int)centerType;
-(id)client_getDeliveredNotificationsForApplication:(id)arg1 ;
-(void)client_setScheduledNotifications:(id)arg1 app:(id)arg2 ;
-(void)client_clearNotificationsForApp:(id)arg1 ;
-(void)client_setDeliveredNotifications:(id)arg1 app:(id)arg2 ;
-(char)acceptsAppActionOnBehalfOfApplication;
-(char)_validateSystemConnection:(id)arg1 identifier:(id)arg2 testApplication:(char*)arg3 ;
-(char)_validateSocialConnection:(id)arg1 identifier:(id)arg2 testApplication:(char*)arg3 ;
-(char)_validateConnection:(id)arg1 canTalkOnBehalfOfApplication:(id)arg2 testApplication:(char*)arg3 ;
-(void)_registerConnectionIdentity:(id)arg1 ;
-(void)_getMaxPresented:(id)arg1 ;
-(void)_scheduleNotification:(id)arg1 ;
-(void)_getScheduledNotifications:(id)arg1 ;
-(void)_setScheduledNotifications:(id)arg1 ;
-(void)_cancelScheduledNotification:(id)arg1 ;
-(void)_getDeliveredNotifications:(id)arg1 ;
-(void)_clearDeliveredNotifications:(id)arg1 ;
-(void)_removeDeliveredNotification:(id)arg1 ;
-(void)_getDisplayedNotifications:(id)arg1 ;
-(void)_removeAllDisplayedNotifications:(id)arg1 ;
-(void)_registerRemotePushConnection:(id)arg1 ;
-(void)_unRegisterRemotePushConnection:(id)arg1 ;
-(void)_clientSetConnectionInfo:(id)arg1 ;
-(void)_getReversedDeliverySetting:(id)arg1 ;
-(void)_setReversedDeliverySetting:(id)arg1 ;
-(void)_shouldPresentReply:(id)arg1 ;
-(void)_retrievePushToken:(id)arg1 ;
-(void)_webGetIdentifiers:(id)arg1 ;
-(void)_unregisterIdentifier:(id)arg1 ;
-(void)_getDNDState:(id)arg1 ;
-(void)_getToday:(BOOL)arg1 forSummary:(id)arg2 ;
-(void)_setToday:(BOOL)arg1 forSummary:(id)arg2 ;
-(void)_getNotificationsDisabled:(id)arg1 ;
-(void)_setNotificationProgress:(id)arg1 ;
-(void)_getNotificationsPrefs:(id)arg1 ;
-(char)_verifyIdentity:(id)arg1 isDaemon:(char)arg2 ;
-(char)verifyPush:(id)arg1 ;
-(NSString *)pushIdentity;
-(void)setAcceptsAppActionOnBehalfOfApplication:(char)arg1 ;
-(NSString *)pushLiverpoolIdentity;
-(NSString *)sourceIdentity;
-(NSDictionary *)entitlementDictionary;
-(char)systemNotificationConnection;
-(char)isWebConnection;
-(char)isSocialConnection;
-(void)_removeDisplayedNotification:(id)arg1 ;
-(void)setSourceIdentifier:(NCSourceIdentifier *)arg1 ;
-(id)description;
-(NSData *)pushToken;
-(void)setPushToken:(NSData *)arg1 ;
-(NCSourceIdentifier *)sourceIdentifier;
-(void)_setDeliveredNotifications:(id)arg1 ;
@end

