/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 9:01:35 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Volumes/YosInst/Applications/Utilities/Startup Disk.app/Contents/MacOS/Startup Disk
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SystemSearcherProtocol;
@class NSLock, NSObject;

@interface SDSystemSearcher : NSObject {

	NSLock* _pauseLock;
	char _oldWorld;
	char _canBootLegacyOS;
	NSObject*<SystemSearcherProtocol> _delegate;

}
-(id)initWithDelegate:(id)arg1 onOldWorld:(char)arg2 canBootLegacyOS:(char)arg3 ;
-(void)setSearchPaused:(char)arg1 ;
-(void)searchForSystemOnVolume:(id)arg1 ;
-(char)_checkVolumeForObviousSystemFolders:(id)arg1 ;
-(char)_checkForOSXVariants:(id)arg1 ;
-(char)_checkForMSVariants:(id)arg1 ;
-(char)_isElTorroBootableOpticalMedia:(id)arg1 ;
-(char)_caseInsensitiveDirPath:(id)arg1 contains:(id)arg2 actualName:(id*)arg3 ;
-(char)_checkForOpticalVariants:(id)arg1 ;
-(void)_searchForMSSystems:(id)arg1 ;
-(void)_searchForOpticalSystems:(id)arg1 ;
-(void)dealloc;
@end

