/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:15:49 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSOperationQueue, NSMutableString, NSMutableDictionary;

@interface XRSpace : NSObject {

	NSOperationQueue* _queue;
	NSMutableString* _tag;
	unsigned long long _seqNum;
	NSMutableDictionary* _userDataByToken;

}
-(id)afterOperation:(id)arg1 block:(/*^block*/id)arg2 ;
-(id)afterOperationsRunBlock:(id)arg1 ;
-(id)userDataForToken:(id)arg1 ;
-(id)storeUserData:(id)arg1 ;
-(void)removeUserDataForToken:(id)arg1 ;
-(id)spaceName;
-(char)isSerial;
-(void)_postQueueStateChanged;
-(char)isOpValidForSpace:(id)arg1 ;
-(char)currentlyInThisSpace;
-(id)afterOperation:(id)arg1 spaceBlock:(/*^block*/id)arg2 ;
-(void)replaceUserData:(id)arg1 forToken:(id)arg2 ;
-(char)isBusy;
-(unsigned long long)operationCount;
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)addOperation:(id)arg1 ;
-(id)initWithQueue:(id)arg1 ;
@end

