/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:02 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKAssetEpub.bundle/Contents/MacOS/BKAssetEpub
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BKAssetEpub/BKAssetEpub-Structs.h>
#import <BKAssetEpub/BKUserStyleSheetGeneratorStyle.h>

@class NSString;

@interface BKContentStyle : NSObject <BKUserStyleSheetGeneratorStyle> {

	char _autoHyphenate;
	char _optimizeLegibility;
	char _justification;
	float _lineHeight;
	float _fontSize;
	NSString* _fontFamily;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) NSString * fontFamily;                 //@synthesize fontFamily=_fontFamily - In the implementation block
@property (assign,nonatomic) float lineHeight;                      //@synthesize lineHeight=_lineHeight - In the implementation block
@property (assign,nonatomic) float fontSize;                        //@synthesize fontSize=_fontSize - In the implementation block
@property (assign,nonatomic) char autoHyphenate;                    //@synthesize autoHyphenate=_autoHyphenate - In the implementation block
@property (assign,nonatomic) char optimizeLegibility;               //@synthesize optimizeLegibility=_optimizeLegibility - In the implementation block
@property (assign,nonatomic) char justification;                    //@synthesize justification=_justification - In the implementation block
+(id)fontNameFromSummaryString:(id)arg1 ;
-(id)css_fontFamily;
-(char)css_optimizeLegibility;
-(char)css_autoHyphenate;
-(char)css_justification;
-(id)initWithSummaryString:(id)arg1 ;
-(void)setAutoHyphenate:(char)arg1 ;
-(char)optimizeLegibility;
-(void)setOptimizeLegibility:(char)arg1 ;
-(id)initWithFontFamily:(id)arg1 andDetails:(id)arg2 ;
-(double)css_lineHeight;
-(char)autoHyphenate;
-(char)justification;
-(void)setJustification:(char)arg1 ;
-(NSString *)fontFamily;
-(void)setFontFamily:(NSString *)arg1 ;
-(float)lineHeight;
-(void)setLineHeight:(float)arg1 ;
-(id)summaryString;
-(id)init;
-(NSString *)description;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(float)fontSize;
-(void)setFontSize:(float)arg1 ;
@end

