/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:24 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKAssetEpub.bundle/Contents/MacOS/BKAssetEpub
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@protocol BKEpubPaginator, BKEpubWebPaginationInfo, BKWKURLLoaderBKCFIContext;
@class BKDocumentResult, BKDocument, BKWKLoaderPool;

@interface BKDocumentPaginationOperation : NSOperation {

	char _isFinished;
	char _isExecuting;
	char _isCancelled;
	char _isSuccess;
	char _isSpinningUpLoader;
	id<BKEpubPaginator> _paginationDelegate;
	BKDocumentResult* _result;
	BKDocument* _document;
	id<BKEpubWebPaginationInfo> _paginationInfo;
	BKWKLoaderPool* _pool;
	id<BKWKURLLoader><BKCFIContext> _loader;

}

@property (nonatomic,retain) id<BKEpubPaginator> paginationDelegate;                  //@synthesize paginationDelegate=_paginationDelegate - In the implementation block
@property (nonatomic,retain) BKDocumentResult * result;                               //@synthesize result=_result - In the implementation block
@property (assign,nonatomic,__weak) BKDocument * document;                            //@synthesize document=_document - In the implementation block
@property (nonatomic,retain) id<BKEpubWebPaginationInfo> paginationInfo;              //@synthesize paginationInfo=_paginationInfo - In the implementation block
@property (assign,nonatomic,__weak) BKWKLoaderPool * pool;                            //@synthesize pool=_pool - In the implementation block
@property (nonatomic,retain) id<BKWKURLLoader><BKCFIContext> loader;                  //@synthesize loader=_loader - In the implementation block
@property (assign,nonatomic) char isSpinningUpLoader;                                 //@synthesize isSpinningUpLoader=_isSpinningUpLoader - In the implementation block
-(BKWKLoaderPool *)pool;
-(id<BKEpubWebPaginationInfo>)paginationInfo;
-(void)setLoader:(id<BKWKURLLoader><BKCFIContext>)arg1 ;
-(char)isSuccess;
-(void)setIsSpinningUpLoader:(char)arg1 ;
-(id)initWithDocument:(id)arg1 paginationInfo:(id)arg2 pool:(id)arg3 ;
-(void)setPaginationDelegate:(id<BKEpubPaginator>)arg1 ;
-(char)isSpinningUpLoader;
-(void)p_returnLoaderToPool;
-(id<BKEpubPaginator>)paginationDelegate;
-(void)setPaginationInfo:(id<BKEpubWebPaginationInfo>)arg1 ;
-(char)isExecuting;
-(void)setPool:(BKWKLoaderPool *)arg1 ;
-(id<BKWKURLLoader><BKCFIContext>)loader;
-(void)_finish;
-(void)setResult:(BKDocumentResult *)arg1 ;
-(char)isConcurrent;
-(void)dealloc;
-(void)cancel;
-(BKDocument *)document;
-(char)isCancelled;
-(void)setDocument:(BKDocument *)arg1 ;
-(char)isFinished;
-(BKDocumentResult *)result;
-(void)main;
@end

