/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:24 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKAssetEpub.bundle/Contents/MacOS/BKAssetEpub
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BKAssetEpub/BKAssetEpub-Structs.h>
#import <BKPlatformCore/BKPlatformTOCViewController.h>
#import <BKAssetEpub/WKBrowsingContextLoadDelegate.h>
#import <BKAssetEpub/WKConnectionDelegate.h>
#import <BKAssetEpub/WKProcessGroupDelegate.h>
#import <BKAssetEpub/BKWKActionHandlerDelegate.h>
#import <BKAssetEpub/BKURLActionHandlerDelegate.h>

@protocol BKWKURLLoaderBKCFIContext;
@class NSView, NSTextField, WKProcessGroup, WKBrowsingContextGroup, WKView, WKConnection, BKWKLoaderPool, NSURL, NSDictionary, NSString;

@interface BKEpubTOCWebViewController : BKPlatformTOCViewController <WKBrowsingContextLoadDelegate, WKConnectionDelegate, WKProcessGroupDelegate, BKWKActionHandlerDelegate, BKURLActionHandlerDelegate> {

	NSView* _bgView;
	NSView* _webViewContainer;
	NSTextField* webViewHeaderTitle;
	WKProcessGroup* _processGroup;
	WKBrowsingContextGroup* _browsingContextGroup;
	WKView* _webView;
	WKConnection* _connection;
	BKWKLoaderPool* _loaderPool;
	id<BKWKURLLoader><BKCFIContext> _loader;
	NSURL* _url;
	NSDictionary* _tocData;
	NSString* _tocIdCssRules;

}

@property (nonatomic,retain) WKProcessGroup * processGroup;                              //@synthesize processGroup=_processGroup - In the implementation block
@property (nonatomic,retain) WKBrowsingContextGroup * browsingContextGroup;              //@synthesize browsingContextGroup=_browsingContextGroup - In the implementation block
@property (nonatomic,retain) WKView * webView;                                           //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) WKConnection * connection;                                  //@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) BKWKLoaderPool * loaderPool;                                //@synthesize loaderPool=_loaderPool - In the implementation block
@property (nonatomic,retain) id<BKWKURLLoader><BKCFIContext> loader;                     //@synthesize loader=_loader - In the implementation block
@property (nonatomic,retain) NSURL * url;                                                //@synthesize url=_url - In the implementation block
@property (retain) NSDictionary * tocData;                                               //@synthesize tocData=_tocData - In the implementation block
@property (nonatomic,retain) NSString * tocIdCssRules;                                   //@synthesize tocIdCssRules=_tocIdCssRules - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)assetEpubBundle;
+(id)tocPageOriginalInteractiveHTML:(id)arg1 cfiToIdMap:(id)arg2 loaderPool:(id)arg3 browsingContextGroup:(id)arg4 completionBlock:(/*^block*/id)arg5 ;
+(id)tocPageSyntheticInteractiveHTML:(id)arg1 rootNode:(id)arg2 tocIdCssRules:(id)arg3 chapterTopLevelFont:(id)arg4 chapterSubLevelFont:(id)arg5 loaderPool:(id)arg6 browsingContextGroup:(id)arg7 completionBlock:(/*^block*/id)arg8 ;
+(id)classNameFromNode:(id)arg1 selected:(char)arg2 ;
+(void)initialize;
-(void)highlightCurrentNode;
-(void)browsingContextControllerDidFailProvisionalLoad:(id)arg1 withError:(id)arg2 ;
-(void)browsingContextControllerDidFailLoad:(id)arg1 withError:(id)arg2 ;
-(BKWKLoaderPool *)loaderPool;
-(NSString *)tocIdCssRules;
-(void)setLoader:(id<BKWKURLLoader><BKCFIContext>)arg1 ;
-(void)actionHandlerWantsToHideCustomContextMenu:(id)arg1 ;
-(void)actionHandler:(id)arg1 hasUnhandledKeyEvent:(id)arg2 ;
-(char)actionHandlerRunJavaScriptConfirm:(id)arg1 title:(id)arg2 message:(id)arg3 ;
-(id)initWithRootNode:(id)arg1 tocIdCssRules:(id)arg2 loaderPool:(id)arg3 ;
-(void)actionHandler:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(void)actionHandler:(id)arg1 wantsToDisplayCustomContextMenuAtPoint:(CGPoint)arg2 ;
-(void)setTocData:(NSDictionary *)arg1 ;
-(NSDictionary *)tocData;
-(void)setLoaderPool:(BKWKLoaderPool *)arg1 ;
-(id)tocNodeForObject:(id)arg1 rootNode:(id)arg2 ;
-(void)applyClassName:(id)arg1 toHref:(id)arg2 ;
-(unsigned long long)tocDataIndexFromChapterHref:(id)arg1 ;
-(void)scrollToItemId:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)highlightCurrentNodeWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)installJavaScriptWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)_actionHandler:(id)arg1 displayHTML:(id)arg2 displayHref:(id)arg3 baseURL:(id)arg4 displayNonLinearURL:(id)arg5 ;
-(void)actionHandler:(id)arg1 handleAudioAction:(id)arg2 ;
-(void)actionHandler:(id)arg1 handleWarnAction:(id)arg2 ;
-(void)actionHandler:(id)arg1 displayHTML:(id)arg2 baseURL:(id)arg3 ;
-(void)actionHandler:(id)arg1 displayPopoverWithTitle:(id)arg2 html:(id)arg3 clientRects:(id)arg4 ;
-(void)actionHandler:(id)arg1 displayHref:(id)arg2 ;
-(void)actionHandler:(id)arg1 displayNonLinearURL:(id)arg2 ;
-(void)setTocIdCssRules:(NSString *)arg1 ;
-(id)urlHandlerForActionHandler:(id)arg1 ;
-(void)didLayoutPage:(OpaqueWKPageRef)arg1 milestones:(unsigned)arg2 typeRef:(void*)arg3 ;
-(WKView *)webView;
-(double)preferredHeight;
-(WKBrowsingContextGroup *)browsingContextGroup;
-(WKProcessGroup *)processGroup;
-(void)setBrowsingContextGroup:(WKBrowsingContextGroup *)arg1 ;
-(void)setProcessGroup:(WKProcessGroup *)arg1 ;
-(id<BKWKURLLoader><BKCFIContext>)loader;
-(void)setConnection:(WKConnection *)arg1 ;
-(void)setWebView:(WKView *)arg1 ;
-(void)browsingContextControllerDidFinishLoad:(id)arg1 ;
-(void)browsingContextControllerDidStartProvisionalLoad:(id)arg1 ;
-(void)connectionDidClose:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveMessageWithName:(id)arg2 body:(id)arg3 ;
-(id)processGroupWillCreateConnectionToWebProcessPlugIn:(id)arg1 ;
-(void)processGroup:(id)arg1 didCreateConnectionToWebProcessPlugIn:(id)arg2 ;
-(WKConnection *)connection;
-(void)openConnection;
-(void)teardown;
-(void)dealloc;
-(NSURL *)url;
-(void)layout;
-(void)setUrl:(NSURL *)arg1 ;
-(void)loadView;
@end

