/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:03 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKAssetEpub.bundle/Contents/MacOS/BKAssetEpub
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKNoteEditorControllerDelegate <NSObject>
@required
-(CGRect*)stickyViewFrameForNoteEditor:(id)arg1;
-(id)stickyContainerForNoteEditor:(id)arg1;
-(unsigned long long)edgeForNoteEditor:(id)arg1;
-(void)noteEditorDidBeginEditing:(id)arg1;
-(void)noteEditorDidFinishEditing:(id)arg1;
-(char)handleEditAnnotation:(id)arg1;

@end

