/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:02 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKAssetEpub.bundle/Contents/MacOS/BKAssetEpub
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKPlatformScrollSwipingControllerDelegate <NSObject>
@optional
-(double)scrollSwipingTargetWithProposedOffset:(double)arg1 currentOffset:(double)arg2 velocity:(double)arg3;

@required
-(CGSize*)scrollSwipingBoundsSize:(id)arg1;
-(double)scrollSwipingBaseOffset:(id)arg1;
-(void)scrollSwipingWillBegin:(id)arg1;
-(double)scrollSwipingMinOffset:(id)arg1 withOverscroll:(char)arg2;
-(double)scrollSwipingMaxOffset:(id)arg1 withOverscroll:(char)arg2;
-(void)scrollSwiping:(id)arg1 updateWithProgress:(double)arg2;
-(char)scrollSwipingAllowRubberbandOnMin:(id)arg1;
-(char)scrollSwipingAllowRubberbandOnMax:(id)arg1;
-(void)scrollSwiping:(id)arg1 didEndWithProgress:(double)arg2;

@end

