/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:24 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKAssetEpub.bundle/Contents/MacOS/BKAssetEpub
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKReflowableLiveResizeHandlerDelegate, BKEpubWebPaginationInfo;
@class BKWKLoaderPool, BKEpubDocumentView, NSView;

@interface BKReflowableLiveResizeHandler : NSObject {

	char _startingLiveResize;
	char _endedLiveResize;
	char _hasResized;
	char _torndown;
	id<BKReflowableLiveResizeHandlerDelegate> _delegate;
	BKWKLoaderPool* _loaderPool;
	BKEpubDocumentView* _primaryDocumentView;
	BKEpubDocumentView* _secondaryDocumentView;
	id<BKEpubWebPaginationInfo> _paginationInfo;
	NSView* _liveResizeView;

}

@property (nonatomic,retain) id<BKReflowableLiveResizeHandlerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) BKWKLoaderPool * loaderPool;                              //@synthesize loaderPool=_loaderPool - In the implementation block
@property (nonatomic,retain) BKEpubDocumentView * primaryDocumentView;                        //@synthesize primaryDocumentView=_primaryDocumentView - In the implementation block
@property (nonatomic,retain) BKEpubDocumentView * secondaryDocumentView;                      //@synthesize secondaryDocumentView=_secondaryDocumentView - In the implementation block
@property (nonatomic,retain) id<BKEpubWebPaginationInfo> paginationInfo;                      //@synthesize paginationInfo=_paginationInfo - In the implementation block
@property (nonatomic,retain) NSView * liveResizeView;                                         //@synthesize liveResizeView=_liveResizeView - In the implementation block
@property (assign,nonatomic) char startingLiveResize;                                         //@synthesize startingLiveResize=_startingLiveResize - In the implementation block
@property (assign,nonatomic) char endedLiveResize;                                            //@synthesize endedLiveResize=_endedLiveResize - In the implementation block
@property (assign,nonatomic) char hasResized;                                                 //@synthesize hasResized=_hasResized - In the implementation block
@property (assign,nonatomic) char torndown;                                                   //@synthesize torndown=_torndown - In the implementation block
-(double)singlePageWidth;
-(void)setTorndown:(char)arg1 ;
-(BKWKLoaderPool *)loaderPool;
-(id<BKEpubWebPaginationInfo>)paginationInfo;
-(char)torndown;
-(id)initWithLoaderPool:(id)arg1 paginationInfo:(id)arg2 ;
-(void)p_performBlock:(/*^block*/id)arg1 ;
-(NSView *)liveResizeView;
-(char)hasResized;
-(void)setPrimaryDocumentView:(BKEpubDocumentView *)arg1 ;
-(void)p_setupPrimaryViewAnnotations;
-(void)setSecondaryDocumentView:(BKEpubDocumentView *)arg1 ;
-(void)p_setupSecondaryViewAnnotations;
-(void)p_layoutDocumentViews;
-(char)startingLiveResize;
-(void)setStartingLiveResize:(char)arg1 ;
-(void)setLiveResizeView:(NSView *)arg1 ;
-(void)p_layoutLiveResizeView;
-(void)p_viewFrameDidChange:(id)arg1 ;
-(void)setLoaderPool:(BKWKLoaderPool *)arg1 ;
-(void)p_loadDocuments:(/*^block*/id)arg1 ;
-(void)setEndedLiveResize:(char)arg1 ;
-(void)p_updateHighlights;
-(void)setHasResized:(char)arg1 ;
-(BKEpubDocumentView *)primaryDocumentView;
-(BKEpubDocumentView *)secondaryDocumentView;
-(char)endedLiveResize;
-(void)willStartLiveResize:(/*^block*/id)arg1 ;
-(void)setPaginationInfo:(id<BKEpubWebPaginationInfo>)arg1 ;
-(void)didEndLiveResize;
-(void)teardown;
-(void)setDelegate:(id<BKReflowableLiveResizeHandlerDelegate>)arg1 ;
-(void)dealloc;
-(id<BKReflowableLiveResizeHandlerDelegate>)delegate;
@end

