/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:12:55 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iTunes.app/Contents/Frameworks/iPodUpdater.framework/iPodUpdater
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSFileHandle, NSDateFormatter;

@interface PodLogger : NSObject {

	int _loggingLevel;
	NSFileHandle* _logFile;
	NSDateFormatter* _formatter;

}
+(id)sharedLoggerWithPath:(id)arg1 ;
-(void)logType:(int)arg1 withString:(id)arg2 ;
-(void)logType:(int)arg1 withFormat:(id)arg2 ;
-(void)logType:(int)arg1 inFunction:(const char*)arg2 atLine:(int)arg3 withString:(id)arg4 ;
-(id)logStringForType:(int)arg1 ;
-(void)writeLineToLog:(id)arg1 ;
-(void)logType:(int)arg1 inFunction:(const char*)arg2 atLine:(int)arg3 withFormat:(id)arg4 ;
-(int)loggingLevel;
-(void)setLoggingLevel:(int)arg1 ;
-(id)initWithPath:(id)arg1 ;
@end

