/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:15:42 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/Frameworks/ITunesConnectFoundation.framework/ITunesConnectFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreFoundation/NSOutputStream.h>

@class NSOutputStream, NSError;

@interface MZBufferedOutputStream : NSOutputStream {

	NSOutputStream* _output;
	void* _opaque;
	NSError* _error;

}
-(id)initWithOutputStream:(id)arg1 bufferSize:(unsigned long long)arg2 ;
-(id)_flushByteQueue;
-(id)initWithOutputStream:(id)arg1 ;
-(unsigned long long)streamStatus;
-(id)streamError;
-(long long)write:(const char*)arg1 maxLength:(unsigned long long)arg2 ;
-(char)hasSpaceAvailable;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(id)delegate;
-(void)close;
-(void)open;
-(void)removeFromRunLoop:(id)arg1 forMode:(id)arg2 ;
-(char)setProperty:(id)arg1 forKey:(id)arg2 ;
-(void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2 ;
-(id)propertyForKey:(id)arg1 ;
@end

