/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:11:04 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/BKBookshelfCommonCore.framework/Versions/A/BKBookshelfCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BKBookshelfCommonCore/BKLibraryProgressStatus.h>

@class NSString;

@interface BKLibraryImportStatus : NSObject <BKLibraryProgressStatus> {

	NSString* _assetID;
	double _progressValue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * assetID;                  //@synthesize assetID=_assetID - In the implementation block
@property (nonatomic,readonly) double progressValue;                //@synthesize progressValue=_progressValue - In the implementation block
+(id)statusWithAssetID:(id)arg1 progressValue:(double)arg2 ;
-(NSString *)assetID;
-(id)initWithAssetID:(id)arg1 progressValue:(double)arg2 ;
-(void)updateWithStatus:(id)arg1 ;
-(double)progressValue;
-(NSString *)description;
@end

