/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:09 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Finder/Finder-Structs.h>
@class TIconView;

@interface TAccessibilityUIElement : NSObject {

	unsigned long long _index;
	TNSRef<NSString *> _title;
	TNSRef<TIconView *> _parent;
	NSRange _range;

}

@property (retain) TIconView * parent; 
-(id)initWithIndex:(unsigned long long)arg1 groupInfo:(id)arg2 parent:(id)arg3 ;
-(CGRect)axFrame;
-(id)axRole;
-(id)axTitle;
-(id)axHelp;
-(id)description;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)accessibilityFocusedUIElement;
-(id)accessibilityHitTest:(CGPoint)arg1 ;
-(char)accessibilityIsIgnored;
-(id)accessibilityAttributeNames;
-(id)accessibilityAttributeValue:(id)arg1 ;
-(id)accessibilityActionDescription:(id)arg1 ;
-(char)accessibilityIsAttributeSettable:(id)arg1 ;
-(void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2 ;
-(id)accessibilityActionNames;
-(void)accessibilityPerformAction:(id)arg1 ;
-(unsigned long long)index;
-(id)title;
-(TIconView *)parent;
-(void)setParent:(TIconView *)arg1 ;
@end

