/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:08 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Finder/Finder-Structs.h>
#import <QuartzCore/CALayer.h>

@interface TCA3PartLayer : CALayer {

	TNSRef<CALayer *> _left;
	TNSRef<CALayer *> _center;
	TNSRef<CALayer *> _centerFill;
	TNSRef<CALayer *> _right;
	TRef<CGImage *, TRetainReleasePolicy<CGImageRef> >* _image;
	double _leftWidth;
	double _rightWidth;
	double _scaleFactor;
	CGRect _imageContentsRect;

}

@property (assign,nonatomic) CGImageRef image; 
@property (assign,nonatomic) double leftWidth;               //@synthesize leftWidth=_leftWidth - In the implementation block
@property (assign,nonatomic) double rightWidth;              //@synthesize rightWidth=_rightWidth - In the implementation block
+(id)layerWithLeftWidth:(double)arg1 andRightWidth:(double)arg2 andScaleFactor:(double)arg3 ;
-(id)initWithLeftWidth:(double)arg1 andRightWidth:(double)arg2 andScaleFactor:(double)arg3 ;
-(void)updateSubViewsLayout:(const CGRect*)arg1 ;
-(void)setLeftWidth:(double)arg1 ;
-(void)setRightWidth:(double)arg1 ;
-(double)leftWidth;
-(double)rightWidth;
-(void)setBounds:(CGRect)arg1 ;
-(CGImageRef)image;
-(void)setImage:(CGImageRef)arg1 ;
@end

