/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:10 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Finder/Finder-Structs.h>
#import <Foundation/NSFormatter.h>

@interface TKindFormatter : NSFormatter {

	double _width;
	unordered_map<TString, std::__1::vector<TruncationTableElement, std::__1::allocator<TruncationTableElement> >, TStringCaseInsensitiveHash, TStringCaseInsensitiveCompare, std::__1::allocator<std::__1::pair<const TString, std::__1::vector<TruncationTableElement, std::__1::allocator<TruncationTableElement> > > > >* _truncationTables;

}
-(void)setWidth:(double)arg1 forAttributes:(id)arg2 ;
-(double)measureTemplate:(const TString*)arg1 forAttributes:(id)arg2 ;
-(id)init;
-(id)stringForObjectValue:(id)arg1 ;
@end

