/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:11 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Finder/Finder-Structs.h>
#import <AppKit/NSTableRowView.h>

@class TListViewController;

@interface TListRowView : NSTableRowView {

	TFENode* _node;
	TListViewController* _listViewController;
	BOOL _isDropTarget;

}

@property (assign,nonatomic) TFENode* node;                                         //@synthesize node=_node - In the implementation block
@property (assign,nonatomic) TListViewController * listViewController;              //@synthesize listViewController=_listViewController - In the implementation block
@property (assign,nonatomic) BOOL isDropTarget;                                     //@synthesize isDropTarget=_isDropTarget - In the implementation block
-(void)openNode;
-(TListViewController *)listViewController;
-(void)setListViewController:(TListViewController *)arg1 ;
-(void)setIsDropTarget:(BOOL)arg1 ;
-(void)updateCellSelectedStateAppearance;
-(BOOL)isDropTarget;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)updateLayer;
-(TFENode*)node;
-(void)setNode:(TFENode*)arg1 ;
@end

