/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:11 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Finder/Finder-Structs.h>
#import <AppKit/NSWindowController.h>
#import <Finder/NSWindowDelegate.h>

@class NSImageView, TTextField, NSString;

@interface TPBFNewMediaWindowController : NSWindowController <NSWindowDelegate> {

	NSImageView* _iconView;
	TTextField* _subTextField;
	unsigned long long _estimatedPBFSize;
	TFENode* _pbfNode;
	NSString* _subText;
	CGSize _subTextFieldSize;

}

@property (nonatomic,retain) NSString * subText;                               //@synthesize subText=_subText - In the implementation block
@property (assign,nonatomic) TFENode* pbfNode;                                 //@synthesize pbfNode=_pbfNode - In the implementation block
@property (assign,nonatomic) unsigned long long estimatedPBFSize;              //@synthesize estimatedPBFSize=_estimatedPBFSize - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)isWaitingForNewMedia;
+(id)controller;
-(TFENode*)pbfNode;
-(void)newMediaInserted;
-(void)setSubText:(NSString *)arg1 ;
-(void)setEstimatedPBFSize:(unsigned long long)arg1 ;
-(NSString *)subText;
-(void)setPbfNode:(TFENode*)arg1 ;
-(unsigned long long)estimatedPBFSize;
-(void)dealloc;
-(long long)runModal;
-(void)viewFrameChanged:(id)arg1 ;
-(void)cancel:(id)arg1 ;
-(void)windowWillClose:(id)arg1 ;
-(void)windowDidLoad;
@end

