/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:09 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Finder/Finder-Structs.h>
#import <Finder/TPropertyImageViewController.h>

@interface TPropertyIconController : TPropertyImageViewController {

	TFENodeVector* _nodes;
	BOOL _nodesHaveSameIcon;
	BOOL _nodesHaveCustomIcon;
	BOOL _nodesCanChangeIcon;

}
-(BOOL)validateCopy:(id)arg1 ;
-(BOOL)validateDelete:(id)arg1 ;
-(BOOL)validateCut:(id)arg1 ;
-(BOOL)validatePaste:(id)arg1 ;
-(BOOL)progressState:(unsigned*)arg1 amount:(unsigned*)arg2 cancellable:(BOOL*)arg3 ;
-(void)initCommon;
-(void)aboutToTearDown;
-(BOOL)canModifyNodes:(const TFENodeVector*)arg1 ;
-(void)updateWithNodes:(const TFENodeVector*)arg1 ;
-(void)copy:(id)arg1 ;
-(void)cut:(id)arg1 ;
-(void)paste:(id)arg1 ;
-(void)concludeDragOperation:(id)arg1 ;
-(void)delete:(id)arg1 ;
@end

