/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:08 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSViewController.h>

@interface TSaveSearchAccessoryViewController : NSViewController {

	BOOL _addToSidebar;
	BOOL _forceAddToSidebar;

}

@property (assign) BOOL addToSidebar;                   //@synthesize addToSidebar=_addToSidebar - In the implementation block
@property (assign) BOOL forceAddToSidebar;              //@synthesize forceAddToSidebar=_forceAddToSidebar - In the implementation block
-(BOOL)addToSidebar;
-(void)setAddToSidebar:(BOOL)arg1 ;
-(BOOL)forceAddToSidebar;
-(void)setForceAddToSidebar:(BOOL)arg1 ;
-(id)init;
@end

