/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:12 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Finder
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Finder/Finder-Structs.h>
#import <Finder/DMAsyncDelegate.h>

@class DMManager, DMEraseDisk;

@interface TVolumeEraseController : NSObject <DMAsyncDelegate> {

	TFENode* _destinationNode;
	int _error;
	/*function pointer*/void* _callback;
	unsigned _eraseAssertion;
	DMManager* _manager;
	DMEraseDisk* _diskEraser;
	TVolumeEraseTask* _task;

}
-(void)eraseVolumeWithSource:(const TFENode*)arg1 destinationToErase:(const TFENode*)arg2 callback:(/*function pointer*/void*)arg3 ;
-(void)handleCompletion;
-(void)dmAsyncStartedForDisk:(DADiskRef)arg1 ;
-(void)dmAsyncProgressForDisk:(DADiskRef)arg1 barberPole:(char)arg2 percent:(float)arg3 ;
-(void)dmAsyncMessageForDisk:(DADiskRef)arg1 string:(id)arg2 dictionary:(id)arg3 ;
-(void)dmAsyncFinishedForDisk:(DADiskRef)arg1 mainError:(int)arg2 detailError:(int)arg3 dictionary:(id)arg4 ;
@end

