/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:34 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/bluetoothaudiod
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <bluetoothaudiod/bluetoothaudiod-Structs.h>
@class NSRecursiveLock;

@interface RingBuffer : NSObject {

	IORingBufferMemory* mRingBufferMem;
	unsigned mRingBufferSize;
	unsigned mNumBufferEntries;
	unsigned mNumDroppedEntries;
	NSRecursiveLock* mLock;
	char mUseSegmentedData;

}
-(unsigned)numBufferEntries;
-(int)ringEnqueue:(char*)arg1 length:(unsigned)arg2 ;
-(int)ringDequeue:(char*)arg1 length:(unsigned*)arg2 ;
-(id)initWithCapacity:(unsigned)arg1 usesSegmentedData:(char)arg2 ;
-(char)isDataAvailable;
-(int)ringPeek:(char*)arg1 length:(unsigned*)arg2 ;
-(unsigned)bytesInBuffer;
-(int)attemptToEnqueue:(char*)arg1 length:(unsigned)arg2 ;
-(void)safeReadAtOffset:(unsigned)arg1 outBuffer:(char*)arg2 ofLength:(unsigned)arg3 ;
-(void)safeWriteAtOffset:(unsigned)arg1 inBuffer:(char*)arg2 ofLength:(unsigned)arg3 ;
-(char)isSpaceAvailableForData:(unsigned)arg1 ;
-(char)isUsingSegmentedData;
-(unsigned)numDroppedEntries;
-(unsigned)getRingCapacity;
-(double)getPercentageRingUsed;
-(void)clearStats;
-(void)finalize;
-(void)dealloc;
-(int)removeAllObjects;
@end

