/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:16 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/nesessionmanager
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSString, NSMutableArray, NSDictionary, NSObject;

@interface NESMPluginRegistry : NSObject {

	NSString* _primaryPluginType;
	NSMutableArray* _pluginRecords;
	NSDictionary* _appInfo;
	NSString* _primaryPluginHome;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (readonly) NSString * primaryPluginType;                  //@synthesize primaryPluginType=_primaryPluginType - In the implementation block
@property (retain) NSMutableArray * pluginRecords;                  //@synthesize pluginRecords=_pluginRecords - In the implementation block
@property (retain) NSDictionary * appInfo;                          //@synthesize appInfo=_appInfo - In the implementation block
@property (retain) NSString * primaryPluginHome;                    //@synthesize primaryPluginHome=_primaryPluginHome - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
+(id)sharedRegistryForPrimaryPluginType:(id)arg1 ;
-(id)copyInfoForAllPlugins;
-(id)initWithPrimaryPluginType:(id)arg1 ;
-(NSMutableArray *)pluginRecords;
-(void)setPluginRecords:(NSMutableArray *)arg1 ;
-(id)copyAppInfo;
-(void)setAppInfo:(NSDictionary *)arg1 ;
-(NSDictionary *)appInfo;
-(NSString *)primaryPluginType;
-(void)addPluginsInDirectory:(id)arg1 withPrimaryPluginType:(id)arg2 ;
-(NSString *)primaryPluginHome;
-(void)setPrimaryPluginHome:(NSString *)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

