/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 9:08:17 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Volumes/YosInst/System/Installation/CDIS/OS X Utilities.app/Contents/MacOS/OS X Utilities
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <OS X Utilities/OS X Utilities-Structs.h>
@class NSCell, NSBundle, NSImage;

@interface BatteryImageCreator : NSObject {

	NSCell* _batteryImageCell;
	unsigned long long _percentCharged;
	char _noBatt;
	char _isUPS;
	char _pluggedIn;
	char _needsReplacement;
	char _drawJuiceRed;
	char _isCharged;
	CGSize imageSize;
	NSBundle* _bundle;
	NSImage* _noBatImage;
	NSImage* _batFullyChargedImage;
	NSImage* _batChargingImage;
	NSImage* _batNeedsReplacementImage;
	NSImage* _batEmptyImage;
	NSImage* _batLevelBlackCapLeftImage;
	NSImage* _batLevelBlackCapRightImage;
	NSImage* _batLevelBlackMiddleImage;
	NSImage* _batLevelRedCapLeftImage;
	NSImage* _batLevelRedCapRightImage;
	NSImage* _batLevelRedMiddleImage;
	NSImage* _batLevelRedSingleImage;
	NSImage* _batLevelGreenCapLeftImage;
	NSImage* _batLevelGreenCapRightImage;
	NSImage* _batLevelGreenMiddleImage;
	NSImage* _splitBatteryChargedImage;
	NSImage* _batteryChargingImage;
	NSImage* _badBatteryImage;
	NSImage* _noBatteriesBatteryImage;
	NSImage* _splitBatteryEndImage;
	NSImage* _splitBatteryHeadImage;
	NSImage* _splitBatteryMidSectionImage;
	NSImage* _splitBatteryStretchImage;
	NSImage* _upsFullyChargedImage;
	NSImage* _upsChargingImage;
	NSImage* _upsEmptyImage;
	NSImage* _upsLevelBlackImage;
	NSImage* _upsLevelRedImage;

}

@property (readonly) NSImage * emptyBatteryImage;                     //@synthesize batEmptyImage=_batEmptyImage - In the implementation block
@property (readonly) NSImage * splitBatteryChargedImage;              //@synthesize splitBatteryChargedImage=_splitBatteryChargedImage - In the implementation block
@property (readonly) NSImage * badBatteryImage;                       //@synthesize badBatteryImage=_badBatteryImage - In the implementation block
@property (readonly) NSImage * noBatteriesBatteryImage;               //@synthesize noBatteriesBatteryImage=_noBatteriesBatteryImage - In the implementation block
@property (readonly) NSImage * batteryChargingImage;                  //@synthesize batteryChargingImage=_batteryChargingImage - In the implementation block
+(id)sharedImageCreatorWithBundle:(id)arg1 ;
-(id)singleBatteryImageForBattery:(id)arg1 partialOpacity:(char)arg2 menuDown:(char)arg3 ;
-(id)_loadImage:(id)arg1 fileName:(id)arg2 ofType:(id)arg3 ;
-(void)loadRedFillImages;
-(void)loadGreenFillImages;
-(void)loadBlackFillImages;
-(NSImage *)emptyBatteryImage;
-(NSImage *)emptyBatteryImage;
-(NSImage *)splitBatteryChargedImage;
-(NSImage *)splitBatteryChargedImage;
-(NSImage *)badBatteryImage;
-(NSImage *)badBatteryImage;
-(NSImage *)noBatteriesBatteryImage;
-(NSImage *)noBatteriesBatteryImage;
-(NSImage *)batteryChargingImage;
-(NSImage *)batteryChargingImage;
-(void)loadBatteryParts;
-(void)loadUPSImages;
-(id)_getJuiceMaxWidth:(unsigned long long)arg1 percentCharged:(double)arg2 colorCode:(int)arg3 opacity:(double)arg4 ;
-(id)upsImageForDict:(id)arg1 ;
-(void)setIsUPS:(char)arg1 ;
-(void)drawWithFrame:(CGRect)arg1 inView:(id)arg2 menuDown:(char)arg3 ;
-(id)initWithBundle:(id)arg1 ;
-(void)dealloc;
@end

