/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:14 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/mds
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSMutableDictionary;

@interface MDPListValidator : NSObject {

	NSDictionary* _schema;
	NSMutableDictionary* _uniqueStrings;

}
-(id)initWithSchema:(id)arg1 uniqueStrings:(char)arg2 ;
-(id)uniqueString:(id)arg1 ;
-(id)validateItem:(id)arg1 description:(id)arg2 ;
-(void)clearUniquedStrings;
-(id)validate:(id)arg1 ;
-(void)dealloc;
@end

