/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:14 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/mds
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableDictionary;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct {
	unsigned long long field1;
} SCD_Struct_MD1;

typedef struct MDCredential {
	unsigned cd_uid;
	int cd_ngids;
	unsigned cd_gids[16];
	int cd_pid;
	char cd_sandbox_container[1024];
} MDCredential;

typedef struct __MDPlistBytes* MDPlistBytesRef;

typedef struct __SecTask* SecTaskRef;

typedef struct {
	unsigned val[8];
} SCD_Struct_MD5;

typedef struct _MDPlistContainer* MDPlistContainerRef;

typedef struct __CFUUID* CFUUIDRef;

typedef struct __SIUserCtx* SIUserCtxRef;

typedef struct MDRawQueue {
	MDRawQueueBlock fFirstBlock;
	MDRawQueueBlock fLastBlock;
	unsigned fPopIndex;
	unsigned fPushIndex;
	BOOL fAllocated;
	unsigned fBlockAllocationSize;
	int fBlockCount;
	unsigned long long fByteCount;
	BOOL fDirectPushActive;
	MDRawQueueBlock fDirectPushSideBlock;
	unsigned fDirectPushFreeSpace;
	BOOL fRecycleBlocks;
	MDRawQueueBlock fFreeBlock;
	unsigned fAllocMinusFreed;
} MDRawQueue;

typedef struct timespec {
	long long tv_sec;
	long long tv_nsec;
} timespec;

typedef struct stat {
	int st_dev;
	unsigned short st_mode;
	unsigned short st_nlink;
	unsigned long long st_ino;
	unsigned st_uid;
	unsigned st_gid;
	int st_rdev;
	timespec st_atimespec;
	timespec st_mtimespec;
	timespec st_ctimespec;
	timespec st_birthtimespec;
	long long st_size;
	long long st_blocks;
	int st_blksize;
	unsigned st_flags;
	unsigned st_gen;
	int st_lspare;
	long long st_qspare[2];
} stat;

typedef struct fsid {
	int val[2];
} fsid;

typedef struct statfs {
	unsigned f_bsize;
	int f_iosize;
	unsigned long long f_blocks;
	unsigned long long f_bfree;
	unsigned long long f_bavail;
	unsigned long long f_files;
	unsigned long long f_ffree;
	fsid f_fsid;
	unsigned f_owner;
	unsigned f_type;
	unsigned f_flags;
	unsigned f_fssubtype;
	char f_fstypename[16];
	char f_mntonname[1024];
	char f_mntfromname[1024];
	unsigned f_reserved[8];
} statfs;

typedef struct vol_capabilities_attr {
	unsigned capabilities[4];
	unsigned valid[4];
} vol_capabilities_attr;

typedef struct attribute_set {
	unsigned commonattr;
	unsigned volattr;
	unsigned dirattr;
	unsigned fileattr;
	unsigned forkattr;
} attribute_set;

typedef struct vol_attributes_attr {
	attribute_set validattr;
	attribute_set nativeattr;
} vol_attributes_attr;

typedef struct __CFString* CFStringRef;

typedef struct __DADisk* DADiskRef;

typedef struct __CFURL* CFURLRef;

typedef struct {
	unsigned field1 : 1;
	unsigned field2 : 1;
	unsigned field3 : 1;
	unsigned field4 : 1;
	unsigned field5 : 1;
	unsigned field6 : 1;
	unsigned field7 : 1;
	unsigned field8 : 1;
	unsigned field9 : 1;
	unsigned field10 : 1;
	unsigned field11 : 1;
	unsigned field12 : 1;
	unsigned field13 : 1;
	unsigned field14 : 1;
	unsigned field15 : 1;
	unsigned field16 : 1;
} SCD_Struct_MD20;

typedef struct {
	unsigned field1;
	int field2;
	unsigned field3;
	unsigned field4;
	FSRef field5;
	int field6;
	int field7;
	short field8;
	MDCredential( field9;
	/*function pointer*/void* field10;
	= field11;
	unsigned field12;
	fsid) field13;
	SCD_Struct_MD20 field14;
	unsigned long long field15;
} SCD_Struct_MD21;

typedef struct __CFArray* CFArrayRef;

typedef struct __MDStoreOIDArray* MDStoreOIDArrayRef;

typedef struct __RLEOIDArray* RLEOIDArrayRef;

typedef struct {
	unsigned long long field1;
	unsigned long long field2;
	unsigned long long field3;
	unsigned long long field4;
	unsigned long long field5;
	unsigned long long field6;
	unsigned long long field7;
	unsigned long long field8;
	unsigned long long field9;
	unsigned long long field10;
	unsigned long long field11;
	unsigned long long field12;
} SCD_Struct_MD25;

typedef struct opaque_pthread_mutex_t {
	long long __sig;
	char __opaque[56];
} opaque_pthread_mutex_t;

typedef struct opaque_pthread_cond_t {
	long long __sig;
	char __opaque[40];
} opaque_pthread_cond_t;

typedef struct {
	long long field1;
	unsigned field2;
	unsigned field3;
	unsigned field4;
	int field5;
} SCD_Struct_MD28;

typedef struct __SIUINT64Set* SIUINT64SetRef;

typedef struct __DASession* DASessionRef;

typedef struct {
	unsigned long long value;
	unsigned long long auxValue;
	unsigned short auxValueIndex;
	unsigned short definesAuxValue;
	unsigned short subAuxValueIndex;
	unsigned short subAuxValueCount;
	unsigned short bundleIndex;
	unsigned short parentBundleIndex;
} SCD_Struct_MD31;

typedef struct task_power_info {
	unsigned long long total_user;
	unsigned long long total_system;
	unsigned long long task_interrupt_wakeups;
	unsigned long long task_platform_idle_wakeups;
	unsigned long long task_timer_wakeups_bin_1;
	unsigned long long task_timer_wakeups_bin_2;
} task_power_info;

typedef struct {
	int operation;
	unsigned owner;
	unsigned group;
	long long oid;
	int fsType;
	int transactionId;
	int importLevel;
	int flags;
	unsigned long long serialNumber;
	long long approximateTime;
	int remainingCount;
	int ignore;
	int pid;
	unsigned long long kernelTimeStamp;
} SCD_Struct_MD33;

typedef struct __asl_object_s* asl_object_sRef;

typedef struct {
	unsigned field1;
	unsigned field2;
	unsigned field3;
	unsigned field4;
	unsigned field5;
	int field6;
} SCD_Struct_MD35;

typedef struct __CFDate* CFDateRef;

typedef struct __CFSet* CFSetRef;

typedef struct _NSZone* NSZoneRef;

typedef struct {
	char didComplete;
	int requestID;
	int status;
	__MDStoreOIDArray oidArray;
	__MDPlistBytes valueBytes;
} SCD_Struct_MD39;

typedef struct {
	stat field1;
	char* field2;
	unsigned field3;
	int field4;
	char* field5;
	unsigned field6;
	int field7;
} SCD_Struct_MD40;

typedef struct {
	int field1;
	int field2;
	unsigned long long field3;
	long long field4;
	SCD_Struct_MD40 field5;
	SCD_Struct_MD40 field6;
} SCD_Struct_MD41;

typedef struct SQueue* SQueueRef;

typedef struct {
	long long previousOid;
	int oidIncrement;
	unsigned uidCache[4];
	unsigned gidCache[4];
	int runLength;
	unsigned long long runLengthDirectoryMask;
} SCD_Struct_St43;

typedef struct {
	int field1;
	unsigned long long field2;
	unsigned field3;
} SCD_Struct_St44;

typedef struct {
	int field1;
	long long field2;
	unsigned field3;
	unsigned field4;
	int field5;
	int field6;
	int field7;
	SCD_Struct_St44 field8[8];
	unsigned long long field9;
	unsigned char field10[4096];
} SCD_Struct_St45;

typedef struct __CFBag* CFBagRef;

typedef struct {
	long long _previousOid;
	int _uidCache[4];
	int _gidCache[4];
} SCD_Struct_MD47;

typedef struct SStack* SStackRef;

typedef struct {
	unsigned char field1[16];
	id field2;
} SCD_Struct_XP49;

typedef struct ConfStrOverridePaths {
	char* userDir;
	char* userTempDir;
	char* userCacheDir;
} ConfStrOverridePaths;

typedef struct __CFData* CFDataRef;

typedef struct _SI_PersistentIDStore* SI_PersistentIDStoreRef;

typedef struct __SIQuery* SIQueryRef;

typedef struct __SIResultQueue* SIResultQueueRef;

typedef struct __SIJobRef* SIJobRefRef;

typedef struct {
	int fd;
	long long startOffset;
	long long end;
	char* writeWindow;
	long long offset;
	int err;
} SCD_Struct_MD56;

typedef struct PossibleMovesHolder_s {
	char* data;
	PossibleFileMoves_s current;
	unsigned long long count;
	unsigned long long size;
} PossibleMovesHolder_s;

typedef struct __SI* SIRef;

typedef struct {
	unsigned field1;
	unsigned field2;
	unsigned field3;
	unsigned field4 : 6;
	unsigned field5 : 1;
	unsigned field6 : 1;
	unsigned field7 : 1;
	unsigned field8 : 1;
	unsigned field9 : 3;
	unsigned field10 : 1;
	unsigned field11 : 1;
	unsigned field12 : 3;
	unsigned field13 : 1;
	unsigned field14 : 1;
	unsigned field15 : 4;
} SCD_Struct_MD59;

typedef struct {
	unsigned char field1;
	unsigned char field2;
	unsigned char field3;
	unsigned char field4;
	unsigned char field5;
	unsigned char field6;
	unsigned char field7;
	unsigned char field8;
	unsigned char field9;
	unsigned char field10;
	unsigned char field11;
	unsigned char field12;
	unsigned char field13;
	unsigned char field14;
	unsigned char field15;
	unsigned char field16;
} SCD_Struct_MD60;

typedef struct {
	int st_dev;
	unsigned short st_mode;
	unsigned long long st_ino;
	unsigned st_uid;
	unsigned st_gid;
} SCD_Struct_FM61;

typedef struct {
	unsigned char byte0;
	unsigned char byte1;
	unsigned char byte2;
	unsigned char byte3;
	unsigned char byte4;
	unsigned char byte5;
	unsigned char byte6;
	unsigned char byte7;
	unsigned char byte8;
	unsigned char byte9;
	unsigned char byte10;
	unsigned char byte11;
	unsigned char byte12;
	unsigned char byte13;
	unsigned char byte14;
	unsigned char byte15;
} SCD_Struct_FM62;

typedef struct {
	SCD_Struct_MD31 field1;
	SCD_Struct_FM61 field2;
	SCD_Struct_FM61 field3;
	unsigned field4;
	unsigned field5;
	char* field6;
	char* field7;
} SCD_Struct_MD63;

typedef struct {
	int field1;
	unsigned long long field2;
	int field3;
	unsigned field4 : 10;
	0 field5;
	unsigned field6 : 1;
	unsigned field7 : 1;
	unsigned field8 : 1;
	unsigned field9 : 1;
	unsigned field10 : 3;
	unsigned field11 : 3;
	unsigned field12 : 13;
	unsigned field13 : 3;
	unsigned field14;
	unsigned field15;
	SCD_Struct_FM62 field16;
	SCD_Struct_MD63 field17;
	SCD_Struct_MD63 field18;
} SCD_Struct_MD64;

typedef struct FSRef {
	unsigned char hidden[80];
} FSRef;

typedef struct {
	unsigned spindleId;
	int fVolumeFd;
	unsigned fCallbackPort;
	unsigned fBackgroundCallbackPort;
	FSRef fFSRef;
	int fDev;
	int fFsid0;
	short fVRefNum;
	fsid fsid;
	/*function pointer*/void* ;
	unsigned ixbits;
	SCD_Struct_MD20) ;
	MDCredential user;
	unsigned long long fLowDiskSpaceState;
} SCD_Struct_MD66;

typedef struct {
	__CFUUID _uuid;
	char _hasPersistentUUID;
	char _suitableForPermissionPreHeat;
	double _recoverTimeStamp;
	long long _largestOid;
	unsigned long long _maxTransactionId;
	NSMutableDictionary* _storeProperties;
} SCD_Struct_MD67;

typedef struct {
	unsigned field1;
	int field2;
	unsigned field3;
	unsigned field4;
	MDCredential field5;
	int field6;
	int field7;
	short field8;
	fsid( field9;
	/*function pointer*/void* field10;
	= field11;
	unsigned field12;
	SCD_Struct_MD20) field13;
	FSRef field14;
	unsigned long long field15;
} SCD_Struct_MD68;

typedef struct __CFBinaryHeap* CFBinaryHeapRef;

typedef struct {
	unsigned long long tokenId;
} SCD_Struct_MD70;

typedef struct {
	unsigned field1;
	unsigned char field2;
} SCD_Struct_Fi71;

typedef struct {
	unsigned long long field1[32];
	id field2;
} SCD_Struct_MD72;

