/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:13 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/mds
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <mds/mds-Structs.h>
#import <mds/MDSSessionTask.h>
#import <mds/MDSBackupTask.h>

@protocol MDSBackupTask <MDSTask>
@end


@class NSString;

@interface MDSBackupTask : MDSSessionTask <MDSBackupTask> {

	char _isNormalBackup;
	char _isCatchup;
	char _wantsOids;
	RLEOIDArrayRef _oidArray;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initForOwner:(id)arg1 sourcePath:(const char*)arg2 backupPath:(const char*)arg3 normalBackup:(char)arg4 catchup:(char)arg5 wantsOids:(char)arg6 ;
-(char)forceThrottle;
-(void)setStoreToken:(unsigned)arg1 storeQueueToken:(unsigned long long)arg2 psidStore:(id)arg3 filter:(id)arg4 result:(int)arg5 ;
-(void)setTargetVolumeQueue:(unsigned long long)arg1 ;
-(char)useSourcePath;
-(void)backupClear;
-(int)indexFile:(char*)arg1 targetPath:(char*)arg2 backupAttr:(id)arg3 replyBlock:(/*^block*/id)arg4 ;
-(BOOL)wantOids;
-(BOOL)goodOid:(long long)arg1 ;
-(void)setQueue:(id)arg1 oidArray:(RLEOIDArrayRef)arg2 ;
-(void)dealloc;
-(NSString *)description;
-(int)source;
@end

