/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:45:07 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Photo Booth.app/Contents/MacOS/Photo Booth
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Photo Booth/Photo Booth-Structs.h>
#import <QuartzCore/CALayer.h>

@class NSMutableArray, NSArray;

@interface PageLayer : CALayer {

	NSMutableArray* _layers;
	NSArray* _compositions;
	NSMutableArray* _renderers;
	id _image;
	long long _pageIndex;

}

@property (readonly) long long pageIndex;                 //@synthesize pageIndex=_pageIndex - In the implementation block
@property (readonly) NSArray * compositions;              //@synthesize compositions=_compositions - In the implementation block
@property (readonly) NSArray * layers;                    //@synthesize layers=_layers - In the implementation block
@property (assign) CGPoint inputXY; 
@property (assign) double sliderValue; 
+(CGRect)rectForEffectOnPage:(long long)arg1 atIndex:(long long)arg2 givenCurrentPage:(long long)arg3 withSize:(CGSize)arg4 ;
+(CGRect)rectForEffectAtIndex:(long long)arg1 withSize:(CGSize)arg2 ;
+(double)xMargin;
+(double)yMargin;
+(double)interspace;
+(CATransform3D)transformForEffectAtIndex:(long long)arg1 withSize:(CGSize)arg2 ;
-(void)setInputXY:(CGPoint)arg1 ;
-(CGPoint)inputXY;
-(void)setSliderValue:(double)arg1 ;
-(double)sliderValue;
-(void)setDragAndDropHilite:(long long)arg1 ;
-(long long)dragAndDropHilite;
-(id)initWithPageIndex:(long long)arg1 compositions:(id)arg2 size:(CGSize)arg3 ;
-(void)relayoutFXLayers;
-(void)renderFXLayers;
-(NSArray *)layers;
-(long long)pageIndex;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(void)setNeedsDisplay;
-(id)actionForKey:(id)arg1 ;
-(void)displayIfNeeded;
-(id)renderingContext;
-(NSArray *)compositions;
@end

