/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:45:07 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Photo Booth.app/Contents/MacOS/Photo Booth
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Photo Booth/Photo Booth-Structs.h>
#import <AppKit/NSButtonCell.h>

@class NSImage;

@interface PBEffectPageButtonCell : NSButtonCell {

	NSImage* _downImage;

}
-(void)setDownImage:(id)arg1 ;
-(id)downImage;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)drawImage:(id)arg1 withFrame:(CGRect)arg2 inView:(id)arg3 ;
@end

