/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:45:07 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Photo Booth.app/Contents/MacOS/Photo Booth
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Photo Booth/Photo Booth-Structs.h>
#import <AppKit/NSTabView.h>

@interface PBTabViewWithGradientBackground : NSTabView {

	char _fullScreenMode;

}

@property (assign,nonatomic) char fullScreenMode;              //@synthesize fullScreenMode=_fullScreenMode - In the implementation block
-(void)setFullScreenMode:(char)arg1 ;
-(char)fullScreenMode;
-(void)applicationDidResignActive:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(char)isOpaque;
-(char)drawsBackground;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)awakeFromNib;
@end

