/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 11:39:10 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Grapher.app/Contents/MacOS/Grapher
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Grapher/Grapher-Structs.h>
#import <Grapher/CPLayoutDialog.h>
#import <Grapher/CPView2DSource.h>

@interface CPLayout2DDialog : CPLayoutDialog <CPView2DSource>
-(void)drawInteriorWithRect:(CGRect)arg1 inView:(id)arg2 ;
-(Class)viewClass;
@end

