/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:50:46 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuickTime Player/MGJob.h>

@class MGExportOperation, NSString, NSError;

@interface MGiTunesPublishJob : MGJob {

	MGExportOperation* _exportOperation;
	char _progressIndeterminate;
	float _progress;
	NSString* _name;
	NSString* _runningStatusString;
	NSError* _error;

}

@property (nonatomic,copy) NSString * name;                                                          //@synthesize name=_name - In the implementation block
@property (assign,nonatomic) float progress;                                                         //@synthesize progress=_progress - In the implementation block
@property (assign,getter=isProgressIndeterminate,nonatomic) char progressIndeterminate;              //@synthesize progressIndeterminate=_progressIndeterminate - In the implementation block
@property (nonatomic,copy) NSString * runningStatusString;                                           //@synthesize runningStatusString=_runningStatusString - In the implementation block
@property (nonatomic,copy) NSError * error;                                                          //@synthesize error=_error - In the implementation block
+(id)iTunesPublishJobWithMediaComposition:(id)arg1 exportParameters:(id)arg2 ;
-(NSString *)runningStatusString;
-(id)initWithMediaComposition:(id)arg1 exportParameters:(id)arg2 ;
-(void)setRunningStatusString:(NSString *)arg1 ;
-(void)setProgressIndeterminate:(char)arg1 ;
-(char)isProgressIndeterminate;
-(void)dealloc;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(NSError *)error;
-(void)setError:(NSError *)arg1 ;
-(float)progress;
-(void)setProgress:(float)arg1 ;
-(id)operations;
@end

