/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:50:46 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSWindowController.h>
#import <QuickTime Player/NSWindowRestoration.h>
#import <QuickTime Player/NSUserInterfaceValidations.h>

@class NSScrollView, NSCollectionView, NSTextField, NSArrayController, NSMutableArray, NSString, NSArray, MGJobManager;

@interface MGJobProcessingWindowController : NSWindowController <NSWindowRestoration, NSUserInterfaceValidations> {

	NSScrollView* jobsScrollView;
	NSCollectionView* jobsCollectionView;
	NSTextField* jobsCountField;
	NSArrayController* jobArrayController;
	char _didAutoShow;
	unsigned long long _countOfJobsToUnpublish;
	NSMutableArray* _unpublishFailedArray;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSArray * jobControllers; 
@property (nonatomic,readonly) char canClearJobControllers; 
@property (nonatomic,readonly) MGJobManager * jobManager; 
@property (nonatomic,readonly) unsigned long long countOfJobsToUnpublish; 
+(id)sharedJobProcessingWindowController;
+(id)keyPathsForValuesAffectingCanUnpublishSelectedJobController;
+(id)keyPathsForValuesAffectingCanClearJobControllers;
+(id)keyPathsForValuesAffectingJobControllers;
+(void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)autoShowWindow:(id)arg1 ;
-(NSArray *)jobControllers;
-(void)displayAlertForApplicationTermination;
-(void)updateJobControllersCountString;
-(void)jobPublishFinished:(id)arg1 ;
-(MGJobManager *)jobManager;
-(void)unpublish:(id)arg1 ;
-(char)canUnpublishSelectedJobController;
-(void)unpublishFromYouTube:(id)arg1 ;
-(char)canUnpublishSelectedJobControllersWithIdentifier:(id)arg1 ;
-(void)unpublishFromFlickr:(id)arg1 ;
-(void)unpublishSelectedJobControllers;
-(void)terminationAlertAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)deleteSelectedJobControllers;
-(void)unpublishCompleteAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)handleJobsUpdate;
-(void)unpublishJobController:(id)arg1 didFailWithError:(id)arg2 ;
-(void)handleUnpublishOver;
-(unsigned long long)countOfJobsToUnpublish;
-(char)canClearJobControllers;
-(void)clearFinishedJobControllers:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(char)validateUserInterfaceItem:(id)arg1 ;
-(void)close;
-(void)deleteForward:(id)arg1 ;
-(void)windowDidLoad;
-(void)deleteBackward:(id)arg1 ;
@end

