/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:50:47 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuickTime Player/MGJobController.h>

@class NSError, MGMediaDownloadJob, NSURL;

@interface MGMediaDownloadJobController : MGJobController {

	NSError* _error;
	MGMediaDownloadJob* _activeJob;
	NSURL* _outputURL;

}

@property (nonatomic,retain) MGMediaDownloadJob * activeJob;              //@synthesize activeJob=_activeJob - In the implementation block
@property (nonatomic,copy) NSURL * outputURL;                             //@synthesize outputURL=_outputURL - In the implementation block
+(id)keyPathsForValuesAffectingResultURL;
+(id)keyPathsForValuesAffectingError;
+(id)keyPathsForValuesAffectingStatusString;
-(id)resultURL;
-(char)canReveal;
-(id)savedDictionaryRepresentation;
-(MGMediaDownloadJob *)activeJob;
-(id)initWithSourceURL:(id)arg1 destinationURL:(id)arg2 hideExtension:(char)arg3 ;
-(void)setActiveJob:(MGMediaDownloadJob *)arg1 ;
-(char)restoreFromDictionaryRepresentation:(id)arg1 ;
-(NSURL *)outputURL;
-(void)setOutputURL:(NSURL *)arg1 ;
-(id)name;
-(id)identifier;
-(id)icon;
-(id)error;
-(id)statusString;
@end

