/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:50:47 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuickTime Player/QuickTime Player-Structs.h>
#import <AVKit/AVPlayerView.h>

@class NSArray;

@interface MGPlayerView : AVPlayerView {

	unsigned _excludedVideoRegionNeedsUpdate : 1;
	unsigned _intersectingDisplaysNeedUpdate : 1;
	unsigned _excludesVideoRegionFromScreenCapture : 1;
	unsigned _tracksIntersectingDisplays : 1;
	NSArray* _intersectingDisplayIDs;

}

@property (assign) char excludesVideoRegionFromScreenCapture; 
@property (assign) char tracksIntersectingDisplays; 
@property (readonly) NSArray * intersectingDisplayIDs; 
+(char)wantsPlayerLayerLayout;
-(void)updateExcludedVideoRegionIfNeeded;
-(void)updateIntersectingDisplaysIfNeeded;
-(void)windowDidChangeID:(id)arg1 ;
-(void)updateIntersectingDisplays;
-(void)updateExcludedVideoRegion;
-(void)setExcludedVideoRegionNeedsUpdate;
-(void)setIntersectingDisplaysNeedUpdate;
-(char)excludesVideoRegionFromScreenCapture;
-(char)tracksIntersectingDisplays;
-(void)setExcludesVideoRegionFromScreenCapture:(char)arg1 ;
-(void)setTracksIntersectingDisplays:(char)arg1 ;
-(NSArray *)intersectingDisplayIDs;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)viewDidMoveToWindow;
-(void)viewWillMoveToWindow:(id)arg1 ;
-(void)renewGState;
@end

