/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:50:46 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface MGSimpleBinder : NSObject {

	char _modifyingTarget;
	char _modifyingObservable;
	id _target;
	NSString* _binding;
	id _observable;
	NSString* _keyPath;
	NSDictionary* _options;

}

@property (__weak,readonly) id target;                    //@synthesize target=_target - In the implementation block
@property (readonly) NSString * binding;                  //@synthesize binding=_binding - In the implementation block
@property (readonly) id observable;                       //@synthesize observable=_observable - In the implementation block
@property (readonly) NSString * keyPath;                  //@synthesize keyPath=_keyPath - In the implementation block
@property (readonly) NSDictionary * options;              //@synthesize options=_options - In the implementation block
-(id)initWithTarget:(id)arg1 binding:(id)arg2 observable:(id)arg3 keyPath:(id)arg4 options:(id)arg5 ;
-(id)observable;
-(id)infoForBinding;
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(NSString *)binding;
-(id)target;
-(NSString *)keyPath;
-(NSDictionary *)options;
@end

