/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:50:47 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuickTime Player/MGMediaClipAssetProvider.h>

@class NSMapTable, NSString;

@interface MGSimpleMediaClipAssetProvider : NSObject <MGMediaClipAssetProvider> {

	NSMapTable* _assetsForMediaClips;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)assetForMediaClip:(id)arg1 ;
-(id)initWithAssetsForMediaClips:(id)arg1 ;
@end

