#import <QuickTime Player/MGOpenClipWindowController.h>
#import <QuickTime Player/MGBackgroundColorView.h>
#import <QuickTime Player/MGRecordingDocumentViewController.h>
#import <QuickTime Player/MGDocumentViewController.h>
#import <QuickTime Player/MGDocument.h>
#import <QuickTime Player/MGDeviceExportAccessoryWindowController.h>
#import <QuickTime Player/MGiTunesErrorRecoveryAttempter.h>
#import <QuickTime Player/MGShareToiTunesWindowController.h>
#import <QuickTime Player/MGDocumentWindowController.h>
#import <QuickTime Player/MGMediaComposition.h>
#import <QuickTime Player/MGSimpleBinder.h>
#import <QuickTime Player/MGDocumentController.h>
#import <QuickTime Player/MGPooledData.h>
#import <QuickTime Player/MGDataPool.h>
#import <QuickTime Player/MGJob.h>
#import <QuickTime Player/MGJobManager.h>
#import <QuickTime Player/MGPhotoLibraryUtilities.h>
#import <QuickTime Player/MGExportOperation.h>
#import <QuickTime Player/MGMovieExportSession.h>
#import <QuickTime Player/MGOpenURLPanel.h>
#import <QuickTime Player/MGApplicationDelegate.h>
#import <QuickTime Player/MGJobProcessingWindowController.h>
#import <QuickTime Player/MGiTunesPublishJob.h>
#import <QuickTime Player/MGAppleScriptPublishOperation.h>
#import <QuickTime Player/MGCaptureDeviceSelectionController.h>
#import <QuickTime Player/MGDeviceRecordingDocument.h>
#import <QuickTime Player/MGDeviceRecordingDocumentViewController.h>
#import <QuickTime Player/MGCaptureCompressionPreset.h>
#import <QuickTime Player/MGCaptureDeviceAndInputSourceSelectionController.h>
#import <QuickTime Player/MGShareToYouTubeWindowController.h>
#import <QuickTime Player/MGYouTubePublishJob.h>
#import <QuickTime Player/MGInspectorViewController.h>
#import <QuickTime Player/MGYouTubePublishOperation.h>
#import <QuickTime Player/MGFileInputStream.h>
#import <QuickTime Player/MGMultipartInputStream.h>
#import <QuickTime Player/MGMultipartDataPart.h>
#import <QuickTime Player/MGScreenRecordingDocument.h>
#import <QuickTime Player/MGPassThroughAnimator.h>
#import <QuickTime Player/MGApplication.h>
#import <QuickTime Player/MGURLComponent.h>
#import <QuickTime Player/MGAppendableData.h>
#import <QuickTime Player/MGReadOnlyRangeOfAppendableData.h>
#import <QuickTime Player/MGAtomicCancelationToken.h>
#import <QuickTime Player/MGInspectorWindowController.h>
#import <QuickTime Player/MGAudioAmplitudeExtractionSessionHelper.h>
#import <QuickTime Player/MGAudioAmplitudeExtractionSession.h>
#import <QuickTime Player/MGRecordingDocument.h>
#import <QuickTime Player/MGScreenRecordingDocumentViewController.h>
#import <QuickTime Player/MGConfirmationWindowController.h>
#import <QuickTime Player/MGEventHotKey.h>
#import <QuickTime Player/MGEventHotKeyMonitorToken.h>
#import <QuickTime Player/MGAudioOnlyRecordingDocument.h>
#import <QuickTime Player/MGYouTubePublishStatusOperation.h>
#import <QuickTime Player/MGAttributePair.h>
#import <QuickTime Player/MGCaptureDeviceInputSourcePair.h>
#import <QuickTime Player/MGAccessibilityFauxUIElement.h>
#import <QuickTime Player/MGDisabledColorTextFieldCell.h>
#import <QuickTime Player/MGCaptureAudioPreviewOutput.h>
#import <QuickTime Player/MGJobProgressCollectionViewItem.h>
#import <QuickTime Player/MGAlwaysAnimatedProgressIndicator.h>
#import <QuickTime Player/MGTableSelectionBox.h>
#import <QuickTime Player/MGItemOutletPreservingCollectionView.h>
#import <QuickTime Player/MGURLLinkTextFieldCell.h>
#import <QuickTime Player/MGFileNameFormatter.h>
#import <QuickTime Player/MGEstimatedDurationFormatter.h>
#import <QuickTime Player/MGProgressEstimator.h>
#import <QuickTime Player/MGQuartzComposerDocument.h>
#import <QuickTime Player/MGInlineButtonCell.h>
#import <QuickTime Player/MGPixelAlignedAntialiasingTextField.h>
#import <QuickTime Player/MGShadowedTextFieldCell.h>
#import <QuickTime Player/MGQuartzComposerDocumentViewController.h>
#import <QuickTime Player/MGQuartzComposerViewCompositionLayer.h>
#import <QuickTime Player/MGQuartzComposerView.h>
#import <QuickTime Player/MGCornerMaskWindow.h>
#import <QuickTime Player/MGScreenSelector.h>
#import <QuickTime Player/MGScreenSelectorOverlayWindow.h>
#import <QuickTime Player/MGScreenSelectorOverlayView.h>
#import <QuickTime Player/MGEncapsulatingBundle.h>
#import <QuickTime Player/MGAssetItem.h>
#import <QuickTime Player/MGExportPassthroughDescriptor.h>
#import <QuickTime Player/MGJobController.h>
#import <QuickTime Player/MGPlayerDocument.h>
#import <QuickTime Player/MGPlayerView.h>
#import <QuickTime Player/MGDataRateFormatter.h>
#import <QuickTime Player/MGAudioExtractor.h>
#import <QuickTime Player/MGAssetAudioExtractor.h>
#import <QuickTime Player/MGYouTubeJobController.h>
#import <QuickTime Player/MGYouTubeAccount.h>
#import <QuickTime Player/MGYouTubeAuthenticationViewController.h>
#import <QuickTime Player/MGAVFoundationExportSession.h>
#import <QuickTime Player/MGiTunesJobController.h>
#import <QuickTime Player/MGScrollEventHandlingHUDSlider.h>
#import <QuickTime Player/MGNetworkNotSetUpRecoveryAttempter.h>
#import <QuickTime Player/MGNetworkDiagnostics.h>
#import <QuickTime Player/MGBlockInvokingKeyValueObserver.h>
#import <QuickTime Player/MGAssetLoader.h>
#import <QuickTime Player/MGYouTubeUnpublishJob.h>
#import <QuickTime Player/MGYouTubeUnpublishOperation.h>
#import <QuickTime Player/MGRelatedItemFilePresenter.h>
#import <QuickTime Player/MGYouTubeUnpublishWindowController.h>
#import <QuickTime Player/MGYouTubeAuthenticationSheetController.h>
#import <QuickTime Player/MGEditViewController.h>
#import <QuickTime Player/MGMediaTrack.h>
#import <QuickTime Player/MGMediaClip.h>
#import <QuickTime Player/MGAVCompositionBuilder.h>
#import <QuickTime Player/MGAudioPlaybackViewController.h>
#import <QuickTime Player/MGLoadingViewController.h>
#import <QuickTime Player/MGVideoPlaybackViewController.h>
#import <QuickTime Player/MGExportPreset.h>
#import <QuickTime Player/MGMediaClipAssetCache.h>
#import <QuickTime Player/MGMediaCompositionPlayerItemController.h>
#import <QuickTime Player/MGAssetValidator.h>
#import <QuickTime Player/MGAudioOnlyRecordingDocumentViewController.h>
#import <QuickTime Player/MGOverlayButtonCell.h>
#import <QuickTime Player/MGOverlayButton.h>
#import <QuickTime Player/MGMediaCompositionUndoController.h>
#import <QuickTime Player/MGSingleJobProgressWindowController.h>
#import <QuickTime Player/MGMediaDownloadJob.h>
#import <QuickTime Player/MGMediaDownloadJobController.h>
#import <QuickTime Player/MGDesktopExportJob.h>
#import <QuickTime Player/MGDesktopExportJobController.h>
#import <QuickTime Player/MGPlayerDocumentDRMHandler.h>
#import <QuickTime Player/MGMediaCompositionSelectionController.h>
#import <QuickTime Player/MGActivityIndicatorView.h>
#import <QuickTime Player/MGMediaTrackViewItem.h>
#import <QuickTime Player/MGMediaCompositionView.h>
#import <QuickTime Player/MGMediaCompositionBackgroundView.h>
#import <QuickTime Player/MGMediaCompositionBorderView.h>
#import <QuickTime Player/MGMediaCompositionViewController.h>
#import <QuickTime Player/MGMediaTrackView.h>
#import <QuickTime Player/MGMediaTrackLayer.h>
#import <QuickTime Player/MGMediaTrackSpaceAvailableIndicatorView.h>
#import <QuickTime Player/MGMediaTrackViewController.h>
#import <QuickTime Player/MGPopover.h>
#import <QuickTime Player/MGPopoverPlayerItemContentViewController.h>
#import <QuickTime Player/MGPopoverPlayerItemView.h>
#import <QuickTime Player/MGSimpleMediaClipAssetProvider.h>
#import <QuickTime Player/MGMediaCompositionEditController.h>
#import <QuickTime Player/MGMediaCompositionEditControllerInternal.h>
#import <QuickTime Player/MGMediaClipPreviewProvider.h>
#import <QuickTime Player/MGFormatDescription.h>
#import <QuickTime Player/MGMediaClipPreview.h>
#import <QuickTime Player/MGMediaClipVideoPreview.h>
#import <QuickTime Player/MGMediaClipAudioPreview.h>
#import <QuickTime Player/MGVerticallyAlignedTextFieldCell.h>
#import <QuickTime Player/MGAssetCollectionDocument.h>
#import <QuickTime Player/MGAboutPanelController.h>
#import <QuickTime Player/MGModernizingViewController.h>
#import <QuickTime Player/MGPlaybackDocument.h>
#import <QuickTime Player/MGProgressIndicatorView.h>
#import <QuickTime Player/MGMessageTracerLogger.h>
