__mh_dylib_header
dyld_stub_binding_helper
+[GrowlApplicationBridge setGrowlDelegate:]
+[GrowlApplicationBridge growlDelegate]
+[GrowlApplicationBridge notifyWithTitle:description:notificationName:iconData:priority:isSticky:clickContext:]
+[GrowlApplicationBridge notifyWithTitle:description:notificationName:iconData:priority:isSticky:clickContext:identifier:]
+[GrowlApplicationBridge notifyWithDictionary:]
+[GrowlApplicationBridge isGrowlInstalled]
+[GrowlApplicationBridge isGrowlRunning]
+[GrowlApplicationBridge displayInstallationPromptIfNeeded]
+[GrowlApplicationBridge registerWithDictionary:]
+[GrowlApplicationBridge reregisterGrowlNotifications]
+[GrowlApplicationBridge setWillRegisterWhenGrowlIsReady:]
+[GrowlApplicationBridge willRegisterWhenGrowlIsReady]
+[GrowlApplicationBridge registrationDictionaryFromDelegate]
+[GrowlApplicationBridge registrationDictionaryFromBundle:]
+[GrowlApplicationBridge bestRegistrationDictionary]
+[GrowlApplicationBridge registrationDictionaryByFillingInDictionary:]
+[GrowlApplicationBridge registrationDictionaryByFillingInDictionary:restrictToKeys:]
+[GrowlApplicationBridge notificationDictionaryByFillingInDictionary:]
+[GrowlApplicationBridge frameworkInfoDictionary]
+[GrowlApplicationBridge _applicationNameForGrowlSearchingRegistrationDictionary:]
+[GrowlApplicationBridge growlNotificationWasClicked:]
+[GrowlApplicationBridge growlNotificationTimedOut:]
+[GrowlApplicationBridge connectionDidDie:]
+[GrowlApplicationBridge growlProxy]
+[GrowlApplicationBridge _growlIsReady:]
+[GrowlApplicationBridge launchApplicationWithBundleAtPath:openDocumentURL:]
+[GrowlApplicationBridge sendOpenEventToProcessWithProcessSerialNumber:openDocumentURL:]
+[GrowlApplicationBridge _launchGrowlIfInstalledWithRegistrationDictionary:]
+[GrowlApplicationBridge launchGrowlIfInstalled]
+[GrowlApplicationBridge getPSN:forAppWithBundleAtPath:]
+[GrowlApplicationBridge _applicationIconDataForGrowlSearchingRegistrationDictionary:]
__copyAllPreferencePaneBundles
__launchGrowlIfInstalledWithRegistrationDictionary
__growlNotificationWasClicked
__growlNotificationTimedOut
__growlIsReady
_copyFork
-[GrowlDelegate initWithAllNotifications:defaultNotifications:]
-[GrowlDelegate dealloc]
-[GrowlDelegate registrationDictionaryForGrowl]
-[GrowlDelegate applicationNameForGrowl]
-[GrowlDelegate setApplicationNameForGrowl:]
-[GrowlDelegate applicationIconDataForGrowl]
-[GrowlDelegate setApplicationIconDataForGrowl:]
+[GrowlPathUtilities bundleForProcessWithBundleIdentifier:]
+[GrowlPathUtilities runningHelperAppBundle]
+[GrowlPathUtilities growlPrefPaneBundle]
+[GrowlPathUtilities helperAppBundle]
+[GrowlPathUtilities searchPathForDirectory:inDomains:mustBeWritable:]
+[GrowlPathUtilities searchPathForDirectory:inDomains:]
+[GrowlPathUtilities growlSupportDirectory]
+[GrowlPathUtilities screenshotsDirectory]
+[GrowlPathUtilities ticketsDirectory]
+[GrowlPathUtilities nextScreenshotName]
+[GrowlPathUtilities nextScreenshotNameInDirectory:]
+[GrowlPathUtilities defaultSavePathForTicketWithApplicationName:]
-[NSImage(GrowlImageAdditions) drawScaledInRect:operation:fraction:]
-[NSImage(GrowlImageAdditions) adjustSizeToDrawAtSize:]
-[NSImage(GrowlImageAdditions) bestRepresentationForSize:]
-[NSImage(GrowlImageAdditions) representationOfSize:]
-[NSImage(GrowlImageAdditions) replacementObjectForPortCoder:]
___PRETTY_FUNCTION__.96477
 stub helpers
_growlLaunched
_appIconData
_appName
_cachedRegistrationDictionary
_delegate
_registerWhenGrowlIsReady
_growlProxy
_targetsToNotifyArray
_delegate
_registerWhenGrowlIsReady
_growlLaunched
_cachedRegistrationDictionary
_registeredForClickCallbacks
_helperAppBundle
_prefPaneBundle
.objc_category_name_NSImage_GrowlImageAdditions
_Growl_CopyRegistrationDictionaryFromBundle
_Growl_CopyRegistrationDictionaryFromDelegate
_Growl_CreateBestRegistrationDictionary
_Growl_CreateNotificationDictionaryByFillingInDictionary
_Growl_CreateRegistrationDictionaryByFillingInDictionary
_Growl_CreateRegistrationDictionaryByFillingInDictionaryRestrictedToKeys
_Growl_GetDelegate
_Growl_IsInstalled
_Growl_IsRunning
_Growl_LaunchIfInstalled
_Growl_NotifyWithTitleDescriptionNameIconPriorityStickyClickContext
_Growl_PostNotification
_Growl_PostNotificationWithDictionary
_Growl_RegisterWithDictionary
_Growl_Reregister
_Growl_SetDelegate
_Growl_SetWillRegisterWhenGrowlIsReady
_Growl_WillRegisterWhenGrowlIsReady
_OBJC_CLASS_$_GrowlApplicationBridge
_OBJC_CLASS_$_GrowlDelegate
_OBJC_CLASS_$_GrowlPathUtilities
_OBJC_IVAR_$_GrowlDelegate.applicationIconDataForGrowl
_OBJC_IVAR_$_GrowlDelegate.applicationNameForGrowl
_OBJC_IVAR_$_GrowlDelegate.registrationDictionary
_OBJC_METACLASS_$_GrowlApplicationBridge
_OBJC_METACLASS_$_GrowlDelegate
_OBJC_METACLASS_$_GrowlPathUtilities
_copyCString
_copyCurrentProcessName
_copyCurrentProcessPath
_copyCurrentProcessURL
_copyIconDataForPath
_copyIconDataForURL
_copyTemporaryFolderPath
_copyTemporaryFolderURL
_copyURLForApplication
_createAliasDataWithURL
_createDockDescriptionWithURL
_createFileSystemRepresentationOfString
_createFileURLWithAliasData
_createFileURLWithDockDescription
_createHostNameForAddressData
_createPropertyListFromURL
_createStringWithAddressData
_createStringWithContentsOfFile
_createStringWithDate
_createStringWithStringAndCharacterAndString
_createURLByCopyingFileFromURLToDirectoryURL
_createURLByMakingDirectoryAtURLWithName
_getBooleanForKey
_getIntegerForKey
_getObjectForKey
_readFile
_setBooleanForKey
_setIntegerForKey
_setObjectForKey
_AEDisposeDesc
_AESendMessage
_AEStreamClose
_AEStreamCreateEvent
_AEStreamWriteKeyDesc
_CFArrayAppendArray
_CFArrayAppendValue
_CFArrayCreate
_CFArrayCreateMutable
_CFArrayGetCount
_CFArrayGetValueAtIndex
_CFBooleanGetValue
_CFBundleCopyBundleURL
_CFBundleCopyResourceURL
_CFBundleCreate
_CFBundleCreateBundlesFromDirectory
_CFBundleGetBundleWithIdentifier
_CFBundleGetIdentifier
_CFBundleGetInfoDictionary
_CFBundleGetMainBundle
_CFCopyTypeIDDescription
_CFDataCreate
_CFDataCreateCopy
_CFDataCreateWithBytesNoCopy
_CFDataGetBytePtr
_CFDataGetLength
_CFDateFormatterCreate
_CFDateFormatterCreateStringWithDate
_CFDictionaryContainsKey
_CFDictionaryCreate
_CFDictionaryCreateCopy
_CFDictionaryCreateMutable
_CFDictionaryCreateMutableCopy
_CFDictionaryGetCount
_CFDictionaryGetTypeID
_CFDictionaryGetValue
_CFDictionaryRemoveValue
_CFDictionarySetValue
_CFEqual
_CFGetAllocator
_CFGetTypeID
_CFLocaleCopyCurrent
_CFMakeCollectable
_CFNotificationCenterAddObserver
_CFNotificationCenterGetDistributedCenter
_CFNotificationCenterPostNotification
_CFNotificationCenterRemoveEveryObserver
_CFNotificationCenterRemoveObserver
_CFNumberCreate
_CFNumberGetValue
_CFPropertyListCreateFromStream
_CFPropertyListWriteToStream
_CFReadStreamClose
_CFReadStreamCreateWithFile
_CFReadStreamOpen
_CFRelease
_CFRetain
_CFSetContainsValue
_CFStringCompare
_CFStringCreateByCombiningStrings
_CFStringCreateCopy
_CFStringCreateWithBytes
_CFStringCreateWithCString
_CFStringCreateWithCStringNoCopy
_CFStringCreateWithCharactersNoCopy
_CFStringCreateWithFormat
_CFStringGetCString
_CFStringGetCharacters
_CFStringGetFileSystemRepresentation
_CFStringGetLength
_CFStringGetMaximumSizeForEncoding
_CFStringGetMaximumSizeOfFileSystemRepresentation
_CFURLCopyFileSystemPath
_CFURLCopyLastPathComponent
_CFURLCopyScheme
_CFURLCreateCopyAppendingPathComponent
_CFURLCreateCopyDeletingLastPathComponent
_CFURLCreateFromFSRef
_CFURLCreateFromFileSystemRepresentation
_CFURLCreateWithFileSystemPath
_CFURLGetFSRef
_CFURLGetFileSystemRepresentation
_CFUUIDCreate
_CFUUIDCreateString
_CFWriteStreamClose
_CFWriteStreamCreateWithFile
_CFWriteStreamOpen
_CopyProcessName
_DisposeHandle
_FNNotify
_FSCopyAliasInfo
_FSFindFolder
_FSNewAlias
_FSRefMakePath
_GetHandleSize
_GetIconRefFromFileInfo
_GetMacOSStatusCommentString
_GetNextProcess
_GetProcessBundleLocation
_GetProcessInformation
_GetProcessPID
_HLock
_HUnlock
_IconRefToIconFamily
_LSFindApplicationForInfo
_LSOpenFromURLSpec
_NSConnectionDidDieNotification
_NSEqualSizes
_NSLog
_NSSearchPathForDirectoriesInDomains
_NSTemporaryDirectory
_OBJC_CLASS_$_NSArray
_OBJC_CLASS_$_NSAutoreleasePool
_OBJC_CLASS_$_NSBundle
_OBJC_CLASS_$_NSConnection
_OBJC_CLASS_$_NSDictionary
_OBJC_CLASS_$_NSDistributedNotificationCenter
_OBJC_CLASS_$_NSFileManager
_OBJC_CLASS_$_NSGraphicsContext
_OBJC_CLASS_$_NSImage
_OBJC_CLASS_$_NSMutableArray
_OBJC_CLASS_$_NSMutableDictionary
_OBJC_CLASS_$_NSMutableSet
_OBJC_CLASS_$_NSNotificationCenter
_OBJC_CLASS_$_NSNumber
_OBJC_CLASS_$_NSObject
_OBJC_CLASS_$_NSProcessInfo
_OBJC_CLASS_$_NSPropertyListSerialization
_OBJC_CLASS_$_NSString
_OBJC_CLASS_$_NSURL
_OBJC_EHTYPE_$_NSException
_OBJC_METACLASS_$_NSObject
_PBCloseForkSync
_PBCreateDirectoryUnicodeSync
_PBCreateFileUnicodeSync
_PBGetCatalogInfoSync
_PBIterateForksSync
_PBMakeFSRefUnicodeSync
_PBOpenForkSync
_PBReadForkSync
_PBWriteForkSync
_ProcessInformationCopyDictionary
_PtrToHand
_ReleaseIconRef
__Unwind_Resume
___CFConstantStringClassReference
___objc_personality_v0
__objc_empty_cache
__objc_empty_vtable
_calloc
_ceil
_close
_fclose
_floor
_fopen
_fread
_free
_fseek
_fstat
_ftell
_getcwd
_getnameinfo
_getpid
_inet_ntop
_kCFAllocatorDefault
_kCFAllocatorMalloc
_kCFAllocatorNull
_kCFBooleanFalse
_kCFBooleanTrue
_kCFBundleIdentifierKey
_kCFTypeArrayCallBacks
_kCFTypeDictionaryKeyCallBacks
_kCFTypeDictionaryValueCallBacks
_malloc
_memset
_objc_assign_global
_objc_assign_ivar
_objc_begin_catch
_objc_end_catch
_objc_msgSendSuper2_fixup
_objc_msgSend_fixup
_open
_snprintf
_strlen
dyld_stub_binder
