/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 11:05:38 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/ColorSync Utility.app/Contents/MacOS/ColorSync Utility
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ColorSync Utility/ColorSync Utility-Structs.h>
#import <AppKit/NSOpenGLView.h>

@interface ProfView3D : NSOpenGLView {

	unsigned _matchSpace;
	unsigned _plotSpace;
	float _angElevation;
	float _angAzimith;
	float _distance;
	CGPoint _dragStart;
	unsigned _numPoints;
	char* _rgbVals;
	CSUColor* _matchVals;
	float* _ijkVals;
	unsigned _numTilePoints;
	char* _rgbTileVals;
	CSUColor* _matchTileVals;
	float* _ijkTileVals;
	unsigned _numGroutPoints;
	CSUColor* _matchGroutVals;
	float* _ijkGroutVals;
	unsigned _holdSpace;
	unsigned _numHoldPoints;
	CSUColor* _matchHoldVals;
	float* _ijkHoldVals;
	unsigned char _showSpectrum;

}
-(void)adjustProjectionMatrix;
-(void)freeData;
-(void)freeHoldData;
-(char)setProfileGamut:(ColorSyncProfileRef)arg1 ;
-(void)setPlotSpace:(unsigned)arg1 ;
-(void)drawAxis;
-(void)drawControl;
-(CGRect)popupRect;
-(char)inPopupRect:(id)arg1 ;
-(void)changePlotSpace:(id)arg1 ;
-(void)compareHold:(id)arg1 ;
-(void)compareClear:(id)arg1 ;
-(void)spectrumShowHide:(id)arg1 ;
-(char)setProfile:(ColorSyncProfileRef)arg1 tagType:(unsigned)arg2 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(void)setFrameSize:(CGSize)arg1 ;
-(id)menuForEvent:(id)arg1 ;
-(void)resetCursorRects;
-(void)mouseDown:(id)arg1 ;
-(void)mouseDragged:(id)arg1 ;
-(void)awakeFromNib;
-(void)mouseUp:(id)arg1 ;
@end

