/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:25 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKEpubWebProcessPlugIn.bundle/Contents/MacOS/BKEpubWebProcessPlugIn
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray, NSString, NSURL;

@interface AEAnnotationGroupRTFGenerator : NSObject {

	char _citationsAllowed;
	NSArray* _annotations;
	NSString* _bookCitationString;
	NSString* _bookURLPrefix;
	NSURL* _bookURL;

}

@property (nonatomic,retain) NSArray * annotations;                                         //@synthesize annotations=_annotations - In the implementation block
@property (assign,getter=areCitationsAllowed,nonatomic) char citationsAllowed;              //@synthesize citationsAllowed=_citationsAllowed - In the implementation block
@property (nonatomic,copy) NSString * bookCitationString;                                   //@synthesize bookCitationString=_bookCitationString - In the implementation block
@property (nonatomic,copy) NSString * bookURLPrefix;                                        //@synthesize bookURLPrefix=_bookURLPrefix - In the implementation block
@property (nonatomic,copy) NSURL * bookURL;                                                 //@synthesize bookURL=_bookURL - In the implementation block
-(char)areCitationsAllowed;
-(void)setCitationsAllowed:(char)arg1 ;
-(NSURL *)bookURL;
-(id)p_attributedStringForAnnotation:(id)arg1 ;
-(id)p_dateStringForAnnotation:(id)arg1 ;
-(id)p_dateStringAttributesForAnnotation:(id)arg1 ;
-(id)p_pageNumberStringForAnnotation:(id)arg1 ;
-(id)p_pageNumberStringAttributesForAnnotation:(id)arg1 ;
-(id)p_highlightStringForAnnotation:(id)arg1 ;
-(id)p_highlightStringAttributesForAnnotation:(id)arg1 ;
-(id)p_noteStringForAnnotation:(id)arg1 ;
-(id)p_noteStringAttributesForAnnotation:(id)arg1 ;
-(NSString *)bookCitationString;
-(void)setBookCitationString:(NSString *)arg1 ;
-(NSString *)bookURLPrefix;
-(void)setBookURLPrefix:(NSString *)arg1 ;
-(void)setBookURL:(NSURL *)arg1 ;
-(NSArray *)annotations;
-(void)setAnnotations:(NSArray *)arg1 ;
-(id)attributedString;
@end

