/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:25 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKEpubWebProcessPlugIn.bundle/Contents/MacOS/BKEpubWebProcessPlugIn
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BKEpubWebProcessPlugIn/BKEpubWebProcessPlugIn-Structs.h>
#import <BKEpubWebProcessPlugIn/NSCoding.h>

@class NSString;

@interface IMBloomFilter : NSObject <NSCoding> {

	/*^block*/id _hashProvider;
	SCD_Struct_IM5 _specification;
	SCD_Struct_IM10 _bitVector;

}

@property (readonly) NSString * usageDescription; 
-(id)initWithSpecification:(SCD_Struct_IM5)arg1 hashProvider:(/*^block*/id)arg2 ;
-(char)mightContainKey:(const void*)arg1 ;
-(long long)indexSize;
-(NSString *)usageDescription;
-(void)addKey:(const void*)arg1 ;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
@end

