/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:05 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Contacts.app/Contents/MacOS/Contacts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ABMainWindowEditModeController <NSObject>
@property (assign,getter=isEditing,nonatomic) char editing; 
@property (nonatomic,readonly) char canEdit; 
@required
-(void)toggleEditing;
-(char)canEdit;
-(char)isEditing;
-(void)setEditing:(char)arg1;

@end

