/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Contacts.app/Contents/MacOS/Contacts
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Contacts/Contacts-Structs.h>
#import <AppKit/NSPrintInfo.h>

@class NSString, NSColor, NSFont, NSImage;

@interface ABPrintInfo : NSPrintInfo {

	int _units;
	char _isDirty;
	char _builtIn;
	char _isCustom;
	NSString* _layoutName;
	NSString* _paperName;
	NSString* _layoutInfo;
	long long _rows;
	long long _columns;
	double _verticalGutters;
	double _horizontalGutters;
	char _printCountry;
	char _printMyCountry;
	char _printCompany;
	unsigned long long _printCompanyOptions;
	NSColor* _color;
	NSFont* _font;
	NSImage* _fullImage;
	NSImage* _image;
	NSString* _imagePath;
	CGSize _paperSize;
	long long _orientation;

}
+(double)abPointsPerUnit:(int)arg1 ;
-(CGRect)abPaperRect;
-(void)abSetPaperSize:(CGSize)arg1 ;
-(CGSize)abPaperSize;
-(id)abLayoutName;
-(id)menuGrouping;
-(char)abCustom;
-(char)abIsDirty;
-(void)abSetCustom:(char)arg1 ;
-(int)abUnitType;
-(void)abSetUnitType:(int)arg1 ;
-(void)abSetImagePath:(id)arg1 ;
-(char)abPrintCountry;
-(char)abPrintMyCountry;
-(char)abPrintCompany;
-(unsigned long long)abPrintCompanyOptions;
-(id)abColor;
-(id)abImagePath;
-(id)abFont;
-(void)abSetPrintCountry:(char)arg1 ;
-(void)abSetPrintMyCountry:(char)arg1 ;
-(void)abSetPrintCompany:(char)arg1 ;
-(void)abSetPrintCompanyOptions:(unsigned long long)arg1 ;
-(void)abSetFont:(id)arg1 ;
-(void)abSetColor:(id)arg1 ;
-(id)abLayoutInfo;
-(void)abSetLayoutInfo:(id)arg1 ;
-(void)abSetLayoutName:(id)arg1 ;
-(double)abUnitsToPoints:(double)arg1 ;
-(id)abDictionaryRep;
-(double)abPointsToUnits:(double)arg1 ;
-(long long)abLabelCount;
-(CGSize)abLabelSize;
-(CGRect)abImageableRect;
-(double)abVerticalGutters;
-(double)abHorizontalGutters;
-(long long)abRows;
-(long long)abColumns;
-(void)abSetBuiltIn:(char)arg1 ;
-(void)abSetRows:(long long)arg1 ;
-(void)abSetColumns:(long long)arg1 ;
-(void)abSetVerticalGutters:(double)arg1 ;
-(void)abSetHorizontalGutters:(double)arg1 ;
-(void)abSetPaperName:(id)arg1 ;
-(CGRect)abImageRect;
-(ABBorderInset)abLabelInset;
-(void)combineWithLabelDescription:(id)arg1 ;
-(char)abEqualsSize:(CGSize)arg1 ;
-(CGSize)abSizeToUnits:(CGSize)arg1 ;
-(id)abPaperName;
-(void)abSetDirty:(char)arg1 ;
-(char)abBuiltIn;
-(void)setLabelInset:(ABBorderInset)arg1 ;
-(id)abImage;
-(void)finalize;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithDictionary:(id)arg1 ;
-(long long)orientation;
-(void)setOrientation:(long long)arg1 ;
@end

