/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:11:05 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/BKPlatformCore.framework/Versions/A/BKPlatformCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BKPlatformCore/BKPlatformCore-Structs.h>
#import <AppKit/NSTableRowView.h>

@interface BKPlatformBookmarkTableRowView : NSTableRowView
+(void)initialize;
-(id)p_tableView;
-(id)p_rowViewAtIndex:(long long)arg1 ;
-(void)p_drawOverlayColor:(id)arg1 inRect:(CGRect)arg2 ;
-(CGRect)p_separatorRect;
-(id)p_rowViewAboveMine;
-(id)p_twoRowViewsAboveMine;
-(id)p_rowViewBelowMine;
-(long long)interiorBackgroundStyle;
-(void)drawBackgroundInRect:(CGRect)arg1 ;
-(void)drawSelectionInRect:(CGRect)arg1 ;
@end

