/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 10:43:32 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Audio MIDI Setup.app/Contents/MacOS/Audio MIDI Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Audio MIDI Setup/Audio MIDI Setup-Structs.h>
#import <QuartzCore/CALayer.h>

@class NSString, CATextLayer;

@interface AMSDeviceLayer : CALayer {

	NSString* uid;
	CATextLayer* theLabel;
	CGColorRef color;
	char selected;
	char hasFocus;
	char enabled;

}

@property (assign) CGColorRef color; 
@property (retain) NSString * label; 
@property (assign) char selected; 
@property (assign) char hasFocus; 
@property (assign) char enabled; 
@property (retain) NSString * uid; 
-(CGSize)maxFrameSize;
-(CGSize)contentFrameSize;
-(CGSize)preferredSizeOfLayer:(id)arg1 ;
-(void)invalidateLayoutOfLayer:(id)arg1 ;
-(void)setHasFocus:(char)arg1 ;
-(char)enabled;
-(char)selected;
-(id)init;
-(void)setContentsScale:(double)arg1 ;
-(void)dealloc;
-(void)setBounds:(CGRect)arg1 ;
-(void)drawInContext:(CGContextRef)arg1 ;
-(void)setEnabled:(char)arg1 ;
-(void)setColor:(CGColorRef)arg1 ;
-(void)setLabel:(NSString *)arg1 ;
-(CGColorRef)color;
-(CGSize)minFrameSize;
-(NSString *)label;
-(void)setSelected:(char)arg1 ;
-(id)actionForLayer:(id)arg1 forKey:(id)arg2 ;
-(void)layoutSublayersOfLayer:(id)arg1 ;
-(NSString *)uid;
-(void)setUid:(NSString *)arg1 ;
-(char)hasFocus;
@end

