/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 10:43:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Audio MIDI Setup.app/Contents/MacOS/Audio MIDI Setup
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Audio MIDI Setup/Audio MIDI Setup-Structs.h>
#import <AppKit/NSView.h>

@class NSAttributedString, NSProgressIndicator;

@interface MessageView : NSView {

	NSAttributedString* mPanelLoadingString;
	CGSize mPLStringSize;
	NSProgressIndicator* mWaitBar;

}
+(id)getWrappedString:(id)arg1 forMaxWidth:(float)arg2 ;
-(id)initWithFrame:(CGRect)arg1 text:(id)arg2 hasProgressBar:(char)arg3 proportionalTextSize:(float)arg4 ;
-(id)initWithFrame:(CGRect)arg1 text:(id)arg2 hasProgressBar:(char)arg3 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(char)isFlipped;
-(void)viewWillMoveToWindow:(id)arg1 ;
@end

