/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:04 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKBookshelf.bundle/Contents/MacOS/BKBookshelf
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface BKBookshelfCollectionCategoryAllCollection : NSObject
-(id)sortKey;
-(id)collectionID;
-(char)isDefaultCollection;
-(id)booksPredicate;
-(char)canDeleteLibraryAsset:(id)arg1 ;
-(char)deleteRemovesFromCollection;
-(char)allowSortManual;
-(char)acceptsContentType:(short)arg1 ;
-(id)title;
-(id)localizedTitle;
@end

