/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:04 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/BKBookshelf.bundle/Contents/MacOS/BKBookshelf
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSCollectionView.h>
#import <BKBookshelf/BKBookshelfCategoryContentController.h>

@protocol BKBookshelfCategoryContentDelegate;
@class NSString, BKBookshelfCategory;

@interface BKBookshelfCollectionView : NSCollectionView <BKBookshelfCategoryContentController> {

	id<BKBookshelfCategoryContentDelegate> _contentDelegate;

}

@property (__weak) id<BKBookshelfCategoryContentDelegate> contentDelegate;              //@synthesize contentDelegate=_contentDelegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) BKBookshelfCategory * category; 
-(void)setContentDelegate:(id<BKBookshelfCategoryContentDelegate>)arg1 ;
-(id<BKBookshelfCategoryContentDelegate>)contentDelegate;
-(unsigned long long)draggingEntered:(id)arg1 ;
-(unsigned long long)draggingUpdated:(id)arg1 ;
-(char)performDragOperation:(id)arg1 ;
-(void)awakeFromNib;
-(char)prepareForDragOperation:(id)arg1 ;
-(id)newItemForRepresentedObject:(id)arg1 ;
-(BKBookshelfCategory *)category;
@end

