/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:31:18 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/FaceTime.app/Contents/MacOS/FaceTime
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FaceTime/FaceTime-Structs.h>
#import <FaceTime/WarningTextField.h>

@protocol ClickableTextFieldDelegate;
@interface ClickableTextField : WarningTextField {

	char _displayAsLink;
	id<ClickableTextFieldDelegate> _clickDelegate;

}

@property (assign,nonatomic,__weak) id<ClickableTextFieldDelegate> clickDelegate;              //@synthesize clickDelegate=_clickDelegate - In the implementation block
+(Class)cellClass;
-(id<ClickableTextFieldDelegate>)clickDelegate;
-(void)setDisplayAslink:(char)arg1 ;
-(void)setClickDelegate:(id<ClickableTextFieldDelegate>)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setTarget:(id)arg1 ;
-(void)setAction:(SEL)arg1 ;
-(void)setStringValue:(id)arg1 ;
-(void)resetCursorRects;
-(void)mouseDown:(id)arg1 ;
-(void)mouseDragged:(id)arg1 ;
-(void)mouseUp:(id)arg1 ;
@end

