/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:31:18 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/FaceTime.app/Contents/MacOS/FaceTime
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSView.h>

@protocol FTBlockListViewDelegate;
@interface FTBlockListView : NSView {

	id<FTBlockListViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FTBlockListViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)setDelegate:(id<FTBlockListViewDelegate>)arg1 ;
-(id<FTBlockListViewDelegate>)delegate;
-(void)viewDidMoveToWindow;
@end

