/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:23:52 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Calendar.app/Contents/MacOS/Calendar
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Calendar/Calendar-Structs.h>
#import <Calendar/CALCanvasGroup.h>

@class CALCanvasItem;

@interface CALCanvasSimpleButton : CALCanvasGroup {

	char _selected;
	CALCanvasItem* _idleItem;
	CALCanvasItem* _selectedItem;
	CALCanvasItem* _mouseOverItem;
	int _behavior;
	id _target;
	SEL _action;
	char _inTracking;
	char _grabbing;
	char _inRollOver;

}
+(id)simpleButtonWithTagID:(id)arg1 position:(CGPoint)arg2 size:(CGSize)arg3 canvas:(id)arg4 idleItem:(id)arg5 selectedItem:(id)arg6 mouseOverItem:(id)arg7 ;
+(id)simpleButtonWithTagID:(id)arg1 position:(CGPoint)arg2 size:(CGSize)arg3 canvas:(id)arg4 idleImageName:(id)arg5 selectedImageName:(id)arg6 mouseOverImageName:(id)arg7 ;
+(id)simpleToggleWithTagID:(id)arg1 position:(CGPoint)arg2 size:(CGSize)arg3 canvas:(id)arg4 idleItem:(id)arg5 selectedItem:(id)arg6 mouseOverItem:(id)arg7 ;
-(char)mouseDown:(id)arg1 sender:(id)arg2 ;
-(char)mouseUp:(id)arg1 sender:(id)arg2 ;
-(char)mouseExited:(id)arg1 sender:(id)arg2 ;
-(char)mouseEntered:(id)arg1 sender:(id)arg2 ;
-(id)initWithTagID:(id)arg1 position:(CGPoint)arg2 size:(CGSize)arg3 canvas:(id)arg4 idleItem:(id)arg5 selectedItem:(id)arg6 mouseOverItem:(id)arg7 behavior:(int)arg8 ;
-(void)updateAspect;
-(char)inRollOver;
-(id)mouseOverItem;
-(id)idleItem;
-(void)setInRollOver:(char)arg1 ;
-(void)setIdleItem:(id)arg1 ;
-(void)setMouseOverItem:(id)arg1 ;
-(void)setTarget:(id)arg1 action:(SEL)arg2 ;
-(char)mouseMoved:(id)arg1 sender:(id)arg2 ;
-(void)setSelectedItem:(id)arg1 ;
-(char)selected;
-(void)dealloc;
-(id)target;
-(SEL)action;
-(id)selectedItem;
-(void)setSelected:(char)arg1 ;
-(void)setBehavior:(int)arg1 ;
-(int)behavior;
@end

