/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:16:55 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Calendar.app/Contents/MacOS/Calendar
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Calendar/Calendar-Structs.h>
@interface CALRect : NSObject {

	CGRect _rect;

}
+(id)rectWithNSRect:(CGRect)arg1 ;
-(CGRect)NSRect;
-(id)setNSRect:(CGRect)arg1 ;
-(id)initWithNSRect:(CGRect)arg1 ;
-(id)description;
@end

