/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:23:52 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Calendar.app/Contents/MacOS/Calendar
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Calendar/Calendar-Structs.h>
#import <QuartzCore/CALayer.h>
#import <Calendar/CalUILayerDelegate.h>
#import <Calendar/NSAnimationDelegate.h>

@class NSMutableSet, NSClipView, CalUILayerOpacityAnimation, NSImage, NSString;

@interface CalUIDateTitleHUDContainerLayer : CALayer <CalUILayerDelegate, NSAnimationDelegate> {

	char _alignLeft;
	char _noAnimation;
	char _useParallax;
	char _inImplicitResizeAnimation;
	NSMutableSet* _huds;
	NSClipView* _clipView;
	CalUILayerOpacityAnimation* _animation;
	NSImage* _gradientImage;
	CGPoint _presentationOrigin;

}

@property (assign) char alignLeft;                                               //@synthesize alignLeft=_alignLeft - In the implementation block
@property (assign) char noAnimation;                                             //@synthesize noAnimation=_noAnimation - In the implementation block
@property (assign) char useParallax;                                             //@synthesize useParallax=_useParallax - In the implementation block
@property (retain) NSMutableSet * huds;                                          //@synthesize huds=_huds - In the implementation block
@property (__weak) NSClipView * clipView;                                        //@synthesize clipView=_clipView - In the implementation block
@property (assign) CGPoint presentationOrigin;                                   //@synthesize presentationOrigin=_presentationOrigin - In the implementation block
@property (retain) CalUILayerOpacityAnimation * animation;                       //@synthesize animation=_animation - In the implementation block
@property (__weak) id<CalUIDateTitleHUDContainerDelegate> delegate; 
@property (assign) char inImplicitResizeAnimation;                               //@synthesize inImplicitResizeAnimation=_inImplicitResizeAnimation - In the implementation block
@property (retain) NSImage * gradientImage;                                      //@synthesize gradientImage=_gradientImage - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)contentAreaWillBeginResizeLive:(char)arg1 ;
-(void)contentAreaDidEndResizeLive:(char)arg1 ;
-(void)setHuds:(NSMutableSet *)arg1 ;
-(void)setAlignLeft:(char)arg1 ;
-(void)setPresentationOrigin:(CGPoint)arg1 ;
-(void)setGradientImage:(NSImage *)arg1 ;
-(NSMutableSet *)huds;
-(id)hudsBelowDateTitleHUD;
-(void)_cancelOpacityAnimation;
-(void)removeHUDHostCompletionHandler;
-(char)alignLeft;
-(double)xOriginForHUD:(id)arg1 ;
-(CGPoint)presentationOrigin;
-(double)currentPresentationOrigin;
-(double)anchorYOriginInOverlayCoordsForHUD:(id)arg1 ;
-(char)useParallax;
-(char)alignRight;
-(void)updateHUDPositions;
-(id)nonvisibleHUDs;
-(void)setInImplicitResizeAnimation:(char)arg1 ;
-(void)layer:(id)arg1 boundsDidChange:(CGRect)arg2 ;
-(void)setShown:(char)arg1 withSuperlayer:(id)arg2 ;
-(void)setClipViewToMonitor:(id)arg1 ;
-(void)addHUD:(id)arg1 ;
-(void)removeHUD:(id)arg1 ;
-(char)noAnimation;
-(void)setNoAnimation:(char)arg1 ;
-(void)setUseParallax:(char)arg1 ;
-(char)inImplicitResizeAnimation;
-(NSImage *)gradientImage;
-(void)setAnimation:(CalUILayerOpacityAnimation *)arg1 ;
-(void)animationDidEnd:(id)arg1 ;
-(id)initWithDelegate:(id)arg1 ;
-(CalUILayerOpacityAnimation *)animation;
-(NSClipView *)clipView;
-(void)setClipView:(NSClipView *)arg1 ;
-(void)scrollView:(id)arg1 didChangePresentationOrigin:(CGPoint)arg2 active:(char)arg3 ;
@end

