/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:23:54 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Calendar.app/Contents/MacOS/Calendar
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Calendar/Calendar-Structs.h>
#import <AppKit/NSView.h>

@class CalUILayerBackedView, NSArray;

@interface CalUIBoxOccurrenceDashedBorder : NSView {

	char _capLeftSide;
	char _capRightSide;
	CalUILayerBackedView* _corners;
	NSArray* _dashViews;

}

@property (assign) char capLeftSide;                            //@synthesize capLeftSide=_capLeftSide - In the implementation block
@property (assign) char capRightSide;                           //@synthesize capRightSide=_capRightSide - In the implementation block
@property (retain) CalUILayerBackedView * corners;              //@synthesize corners=_corners - In the implementation block
@property (retain) NSArray * dashViews;                         //@synthesize dashViews=_dashViews - In the implementation block
-(void)setCorners:(CalUILayerBackedView *)arg1 ;
-(void)setDashViews:(NSArray *)arg1 ;
-(NSArray *)dashViews;
-(CalUILayerBackedView *)corners;
-(void)setCapLeftSide:(char)arg1 ;
-(void)setCapRightSide:(char)arg1 ;
-(char)capLeftSide;
-(char)capRightSide;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setColor:(id)arg1 ;
@end

