/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:24:58 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <IMCommonCore/SFUBufferedInputStream.h>

@protocol SFUBufferedInputStream <SFUInputStream>
@required
-(unsigned long long)readToOwnBuffer:(const char**)arg1 size:(unsigned long long)arg2;
-(char)seekWithinBufferToOffset:(long long)arg1;

@end


@protocol SFUInputStream;
@class NSString;

@interface SFUBufferedInputStream : NSObject <SFUBufferedInputStream> {

	id<SFUInputStream> mStream;
	char* mBuffer;
	unsigned long long mBufferSize;
	long long mBufferOffset;
	long long mBufferStart;
	long long mBufferEnd;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(unsigned long long)readToBuffer:(char*)arg1 size:(unsigned long long)arg2 ;
-(void)disableSystemCaching;
-(void)enableSystemCaching;
-(id)closeLocalStream;
-(unsigned long long)readToOwnBuffer:(const char**)arg1 size:(unsigned long long)arg2 ;
-(id)initWithStream:(id)arg1 bufferSize:(unsigned long long)arg2 ;
-(char)seekWithinBufferToOffset:(long long)arg1 ;
-(id)initWithStream:(id)arg1 dataLength:(long long)arg2 ;
-(void)seekToOffset:(long long)arg1 ;
-(char)canSeek;
-(long long)offset;
-(id)initWithStream:(id)arg1 ;
-(void)dealloc;
-(void)close;
@end

