/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:24:58 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <IMCommonCore/SFUOutputStream.h>

@protocol SFUOutputStream;
@class NSString;

@interface SFUZipDeflateOutputStream : NSObject <SFUOutputStream> {

	id<SFUOutputStream> mOutputStream;
	z_stream_s* mDeflateStream;
	char* mOutBuffer;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)closeLocalStream;
-(void)seekToOffset:(long long)arg1 whence:(int)arg2 ;
-(void)writeBuffer:(const char*)arg1 size:(unsigned long long)arg2 ;
-(char)canCreateInputStream;
-(id)initWithOutputStream:(id)arg1 ;
-(char)canSeek;
-(long long)offset;
-(id)inputStream;
-(void)dealloc;
-(void)close;
@end

