#import <ITunesSoftwareService/ITunesSoftwareService.h>
#import <ITunesSoftwareService/ITunesSoftwareApplicationDescription.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceImpl.h>
#import <ITunesSoftwareService/PNGInfo.h>
#import <ITunesSoftwareService/SIPSPNGAnalyzer.h>
#import <ITunesSoftwareService/XarCommandExecutor.h>
#import <ITunesSoftwareService/XarCommandExecutorResult.h>
#import <ITunesSoftwareService/AbstractDeviceValidationContext.h>
#import <ITunesSoftwareService/CodesignEntitlementAnalyzer.h>
#import <ITunesSoftwareService/DeviceContextIPad.h>
#import <ITunesSoftwareService/DeviceContextIPhone.h>
#import <ITunesSoftwareService/DeviceContextIPodTouch.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceApplicationVersionsResponse.h>
#import <ITunesSoftwareService/DeviceValidationContextFactory.h>
#import <ITunesSoftwareService/MachDwarfdumpAnalyzer.h>
#import <ITunesSoftwareService/MachDwarfdumpAnalyzerEntry.h>
#import <ITunesSoftwareService/ITunesPurpleSoftwarePackageBuilderWorker.h>
#import <ITunesSoftwareService/ITunesSoftwareDeviceDescription.h>
#import <ITunesSoftwareService/ITunesFirenzeSoftwarePackageBuilderWorker.h>
#import <ITunesSoftwareService/ITunesSoftwareXPCServiceVersionDescription.h>
#import <ITunesSoftwareService/FirenzeApplicationVerifier.h>
#import <ITunesSoftwareService/FirenzeApplicationArchiveVerifier.h>
#import <ITunesSoftwareService/ITunesAbstractVerifier.h>
#import <ITunesSoftwareService/FirenzeArchiveExpander.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceValidationConfiguration.h>
#import <ITunesSoftwareService/ITunesSoftwareVersionDescription.h>
#import <ITunesSoftwareService/ITunesSymlinkAnalyzer.h>
#import <ITunesSoftwareService/PurpleApplicationArchiveExpander.h>
#import <ITunesSoftwareService/MZWebServiceLookupSoftwareVersionsForApplication.h>
#import <ITunesSoftwareService/ITunesSoftwareExtensionVersionDescription.h>
#import <ITunesSoftwareService/ITunesCodesignAllocateExecutor.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceApplicationsResponse.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceResponse.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceUploadResponse.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceWorkSeriesFactory.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceFactoryDelegate.h>
#import <ITunesSoftwareService/ITunesSoftwareBundleDescription.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceSPIUsageResponse.h>
#import <ITunesSoftwareService/ITunesApplicationSPIExtractor.h>
#import <ITunesSoftwareService/ITunesApplicationSPIExtractorWorker.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceConnectedValidationResponse.h>
#import <ITunesSoftwareService/MachFileCommandExecutor.h>
#import <ITunesSoftwareService/ITunesSoftwareServicePathUtilities.h>
#import <ITunesSoftwareService/AbstractValidateSoftwareAttributes.h>
#import <ITunesSoftwareService/ITunesFirenzeSoftwareValidationWorker.h>
#import <ITunesSoftwareService/MZAbstractWebServiceFileSender.h>
#import <ITunesSoftwareService/MZWebServiceValidateSoftwareSPIUsage.h>
#import <ITunesSoftwareService/MZWebServiceLookupSoftwareVersions.h>
#import <ITunesSoftwareService/MZWebServiceValidateFirenzeProductAttributes.h>
#import <ITunesSoftwareService/MZWebServiceValidatePurpleSoftwareAttributes.h>
#import <ITunesSoftwareService/ITunesPurpleSoftwareInfoPlistLoader.h>
#import <ITunesSoftwareService/ITunesPurpleSoftwareSigningDescriber.h>
#import <ITunesSoftwareService/ITunesSigningAnalyzer.h>
#import <ITunesSoftwareService/ITunesSigningAnalyzerResult.h>
#import <ITunesSoftwareService/ITunesIconAnalyzer.h>
#import <ITunesSoftwareService/ITunesIconAnalyzerResult.h>
#import <ITunesSoftwareService/ITunesPurpleSoftwareArchitectureDescriber.h>
#import <ITunesSoftwareService/MachFileCommandArchitectureAnalyzer.h>
#import <ITunesSoftwareService/MachFileCommandArchitectureAnalyzerEntry.h>
#import <ITunesSoftwareService/MZWebServiceLookupSoftwareForBundleId.h>
#import <ITunesSoftwareService/MachLipoArchitectureAnalyzer.h>
#import <ITunesSoftwareService/MachLipoArchitectureAnalyzerEntry.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceCodesignParametersResponse.h>
#import <ITunesSoftwareService/ITunesSoftwareCodesignApplication.h>
#import <ITunesSoftwareService/ITunesSoftwareCodesignParameter.h>
#import <ITunesSoftwareService/MZWebServiceSoftwareCodesignParameters.h>
#import <ITunesSoftwareService/PNGAnalyzer.h>
#import <ITunesSoftwareService/MZWebServiceValidateHostedContentIAPPackage.h>
#import <ITunesSoftwareService/OtoolCommandExecutor.h>
#import <ITunesSoftwareService/OtoolCommandExecutorResult.h>
#import <ITunesSoftwareService/MZWebServiceLookupHostedContentInAppPurchasesForSoftware.h>
#import <ITunesSoftwareService/MZWebServiceLookupSoftwareWithHostedContent.h>
#import <ITunesSoftwareService/ITunesSoftwareServiceSymbolURLResponse.h>
#import <ITunesSoftwareService/ITunesInAppPurchasePackageBuilderWorker.h>
#import <ITunesSoftwareService/MZWebServiceLookupSymbolURLsForSoftwareVersion.h>
#import <ITunesSoftwareService/ITunesPurplePackageDescriberContext.h>
#import <ITunesSoftwareService/ITunesPurpleBundleDescriberContext.h>
#import <ITunesSoftwareService/ITunesPurpleProductMetadataDescriberContext.h>
#import <ITunesSoftwareService/ITunesSoftwareApplicationVersionDescription.h>
#import <ITunesSoftwareService/MachDwarfdumpExecutor.h>
#import <ITunesSoftwareService/ITunesPurpleProductMetadataDescriber.h>
#import <ITunesSoftwareService/ITunesPurpleBundleIconDescriber.h>
#import <ITunesSoftwareService/ITunesAbstractPurpleSoftwareDescriberContext.h>
#import <ITunesSoftwareService/ITunesPurpleFileOfInterest.h>
#import <ITunesSoftwareService/ITunesPurpleBundleLaunchImageDescriber.h>
#import <ITunesSoftwareService/MZWebServicePurpleArchiveExtractorWorker.h>
#import <ITunesSoftwareService/MZWebServiceFirenzeArchiveExtractorWorker.h>
#import <ITunesSoftwareService/ITunesContextualError.h>
#import <ITunesSoftwareService/ITunesSigningAnalyzerArchBound.h>
#import <ITunesSoftwareService/ITunesSigningAnalyzerArchBoundResult.h>
