/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:12:55 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iTunes.app/Contents/Frameworks/iPodUpdater.framework/Versions/A/Resources/UpdaterBackEnd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UpdaterBackEnd/UpdaterBackEnd-Structs.h>
#import <UpdaterBackEnd/UpdaterToolRequests.h>

@protocol BackendToolLogging;
@class NSConnection, NSMutableDictionary;

@interface UpdaterToolServer : NSObject <UpdaterToolRequests> {

	NSConnection* _connection;
	NSMutableDictionary* _devices;
	opaque_pthread_mutex_t _devicesArrayLock;
	char _reservedDevice[64];
	id<BackendToolLogging> _logger;
	DASessionRef _daSession;

}
+(void)copyRDisk:(const char*)arg1 toDisk:(char*)arg2 ;
+(id)deviceWithoutSlice:(id)arg1 ;
-(int)ensureFileOpened:(id)arg1 device:(id*)arg2 mode:(int)arg3 ;
-(int)read:(void*)arg1 length:(unsigned long long)arg2 from:(unsigned long long)arg3 forDevice:(id)arg4 ;
-(int)write:(const void*)arg1 length:(unsigned long long)arg2 to:(long long)arg3 forDevice:(id)arg4 ;
-(int)reserveDevice:(const char*)arg1 ;
-(id)deviceForPath:(id)arg1 ;
-(int)closeFile:(id)arg1 ;
-(id)commandStringFromArgs:(const char**)arg1 ;
-(int)checkDisk:(char*)arg1 withFormat:(int)arg2 ;
-(void)logCommand:(const char*)arg1 ;
-(void)closeAllFiles;
-(int)write:(id)arg1 atOffset:(unsigned long long)arg2 toDevice:(id)arg3 ;
-(int)readFromOffset:(unsigned long long)arg1 intoBuffer:(out id*)arg2 length:(unsigned long long)arg3 fromDevice:(id)arg4 ;
-(int)clearFromOffset:(unsigned long long)arg1 length:(unsigned long long)arg2 toDevice:(id)arg3 ;
-(void)doneWithDevice:(id)arg1 ;
-(int)openFile:(id)arg1 mode:(int)arg2 ;
-(int)tickleDevice:(id)arg1 ;
-(int)indicateDeviceWillBecomeUnmountable:(id)arg1 ;
-(int)format:(int)arg1 ofDevice:(id)arg2 usingFormat:(int)arg3 checkDiskAfterwards:(char)arg4 family:(unsigned)arg5 ;
-(oneway void)setLogger:(id)arg1 ;
-(void)serverThread;
-(int)releaseReservedDevice:(const char*)arg1 ;
-(void)logOpenFiles:(id)arg1 ;
-(void)diskPeek:(DADiskRef)arg1 ;
-(void)connectionDied:(id)arg1 ;
-(oneway void)quit;
-(id)init;
@end

