/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:15:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_object.h>
#import <libdispatch.dylib/OS_voucher.h>

@protocol OS_voucher
@end


@interface OS_voucher : OS_object <OS_voucher>
+(void)load;
-(void)_dispose;
-(id)init;
-(id)debugDescription;
-(void)_xref_dispose;
@end

