/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:58:57 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /sbin/emond
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary;

@interface GCDAsyncSpecialPacket : NSObject {

	NSDictionary* tlsSettings;

}
-(id)initWithTLSSettings:(id)arg1 ;
-(void)dealloc;
@end

