/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:15 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/mdmclient
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_xpc_object;
@class NSDictionary, NSObject;

@interface XPCServerMsgInfo : NSObject {

	NSDictionary* fMessageDict;
	NSObject*<OS_xpc_object> fConnection;
	NSObject*<OS_xpc_object> fMessage;

}
-(int)getCallerPID;
-(id)initWithMessage:(id)arg1 fromConnection:(id)arg2 ;
-(id)getMessageDict;
-(id)getCallerPath;
-(unsigned)getCallerUID;
-(void)dealloc;
@end

