/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 8:59:58 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Volumes/YosInst/Install OS X Yosemite.app/Contents/PlugIns/IA.bundle/Contents/MacOS/IA
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <IA/IA-Structs.h>
@interface IFDCustomizationController_10_6 : NSObject {

	IFDCustomizationController_Private* _private;

}
+(void)initialize;
-(id)allChoices;
-(char)_stateChanged;
-(void)_refreshStateAndSize:(char)arg1 ;
-(void)_addPackagesFromItem:(id)arg1 withCurrentCustomLocation:(id)arg2 selfContained:(char)arg3 toCustomization:(id)arg4 ;
-(void)_createItemsFromDistribution;
-(void)toggleItemSelection:(id)arg1 ;
-(unsigned long long)_sizeForItem:(id)arg1 forTarget:(id)arg2 includeUnselected:(char)arg3 ;
-(id)minimumInstallSizeIgnoringDiskContents:(char)arg1 ;
-(id)rootItem;
-(id)itemEnumeratorForItem:(id)arg1 onlyVisible:(char)arg2 ;
-(void)_addItemsFromItem:(id)arg1 toArray:(id)arg2 onlyVisible:(char)arg3 ;
-(void)_recursiveSetStateTo:(int)arg1 forItemAndChildrenOf:(id)arg2 ;
-(void)_evalAllItemAttrsExceptItem:(id)arg1 doInit:(char)arg2 ;
-(char)_recursiveCheckMixedStateForItem:(id)arg1 ;
-(char)setCustomLocation:(id)arg1 forChoice:(id)arg2 withError:(id*)arg3 ;
-(id)visibleChildrenForItem:(id)arg1 ;
-(id)totalDownloadBytes;
-(id)totalSelectedBytes;
-(id)customization;
-(id)childrenForItem:(id)arg1 ;
-(unsigned long long)_downloadKbytesForPackage:(id)arg1 ;
-(void)setTotalSelectedBytes:(id)arg1 ;
-(void)setTotalDownloadBytes:(id)arg1 ;
-(unsigned long long)_minimumRequiredSize:(id)arg1 ignoreDiskContents:(char)arg2 ;
-(unsigned long long)_maximumInstallSize:(id)arg1 ignoreDiskContents:(char)arg2 ;
-(id)initWithInstallController:(id)arg1 andTarget:(id)arg2 ;
-(void)setIgnoresContents:(char)arg1 ;
-(id)javaScriptRuntime;
-(char)_shouldAllowAlternateVolumeForChoice:(id)arg1 ;
-(char)validateCustomLocation:(id)arg1 forChoice:(id)arg2 ;
-(char)_refreshActionForItemAndCheckForUpgrades:(id)arg1 ;
-(void)setUpgrading:(char)arg1 ;
-(void)_refreshTotalSelectedAndDownloadSize;
-(void)_collectItemStateForItem:(id)arg1 ;
-(char)_isOSUpdate;
-(char)_evalItem:(id)arg1 forAttribute:(id)arg2 incrementOnEval:(int*)arg3 ;
-(char)_evalDynamicPkgRefsOnChoice:(id)arg1 incrementOnEval:(int*)arg2 ;
-(void)updateSizes;
-(id)bytesForItem:(id)arg1 ;
-(void)setDistantPackageDistance:(int)arg1 usingSourceManager:(id)arg2 ;
-(void)setInstallPadding:(unsigned long long)arg1 ;
-(void)setDownloadPadding:(unsigned long long)arg1 ;
-(char)shouldAllowInstallWithChecker:(id)arg1 findFiles:(char)arg2 outStatus:(int*)arg3 outSizeDeficit:(id*)arg4 ;
-(id)selectedBytesForItem:(id)arg1 ;
-(char)writeChoiceChangesToFileAtPath:(id)arg1 ;
-(id)selectedBytesOnTarget:(id)arg1 ;
-(id)installController;
-(id)minimumInstallSize;
-(id)maximumInstallSizeIgnoringDiskContents:(char)arg1 ;
-(char)ignoresContent;
-(char)_customLocationIsSelfContainedForChoice:(id)arg1 ;
-(char)upgrading;
-(char)applyChoiceChangesForFileAtPath:(id)arg1 ;
-(id)itemEnumeratorForItem:(id)arg1 ;
-(id)choiceForIdentifier:(id)arg1 ;
-(id)distribution;
-(void)dealloc;
-(id)target;
-(void)reset;
@end

