/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:23 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/IMPlatformCore.framework/Versions/A/IMPlatformCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <IMPlatformCore/IMPlatformCore-Structs.h>
#import <IMPlatformCore/IMFourStateImageButton.h>

@interface IMWindowControlButton : IMFourStateImageButton {

	long long _type;

}
+(void)initialize;
-(void)setupArtwork;
-(void)setDefaultState;
-(void)updateWindowState;
-(id)initWithFrame:(CGRect)arg1 type:(long long)arg2 ;
-(void)dealloc;
-(char)acceptsFirstResponder;
-(char)acceptsFirstMouse:(id)arg1 ;
-(void)viewDidMoveToWindow;
-(void)mouseDown:(id)arg1 ;
-(char)shouldDelayWindowOrderingForEvent:(id)arg1 ;
@end

