/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 9:08:13 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Volumes/YosInst/System/Installation/CDIS/NetRestore.app/Contents/MacOS/NetRestore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <NetRestore/NSApplicationDelegate.h>

@class IASLogWindowController, NSTask, NSWindow, NSString;

@interface NRAppDelegate : NSObject <NSApplicationDelegate> {

	IASLogWindowController* _logWindowController;
	char _allowUnpromptedQuit;
	NSTask* _utilityTask;
	NSWindow* _window;

}

@property (assign) NSWindow * window;                               //@synthesize window=_window - In the implementation block
@property (assign) char allowUnpromptedQuit;                        //@synthesize allowUnpromptedQuit=_allowUnpromptedQuit - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_launchUtilityApplication:(id)arg1 ;
-(void)_helperAppExited:(id)arg1 ;
-(void)_launchHelperAppWithPath:(id)arg1 withFinishedSelector:(SEL)arg2 ;
-(void)_addUtilityMenus;
-(void)logWindowWillClose;
-(void)_helperAppLaunchedNotification:(id)arg1 ;
-(char)_shouldDisplayRAIDUtility;
-(void)showLogWindow:(id)arg1 ;
-(char)allowUnpromptedQuit;
-(void)setAllowUnpromptedQuit:(char)arg1 ;
-(void)applicationWillFinishLaunching:(id)arg1 ;
-(void)applicationDidFinishLaunching:(id)arg1 ;
-(NSWindow *)window;
-(unsigned long long)applicationShouldTerminate:(id)arg1 ;
-(void)setWindow:(NSWindow *)arg1 ;
@end

