/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 1:31:20 PM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/VoiceOver Utility.app/Contents/OtherBinaries/VoiceOverUtilityCacheBuilder.app/Contents/MacOS/VoiceOver Utility
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <VoiceOver Utility/CommanderPrefs.h>
#import <VoiceOver Utility/InputTableViewDelegate.h>
#import <VoiceOver Utility/NSTableViewDataSource.h>

@class AddRemoveBar, NSMutableArray, NSString;

@interface CommanderKeyboardBasePrefs : CommanderPrefs <InputTableViewDelegate, NSTableViewDataSource> {

	AddRemoveBar* _addRemoveSegmentedControl;
	NSMutableArray* _commanderKeys;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)newEntry:(id)arg1 ;
-(id)keyPathForRow:(long long)arg1 ;
-(id)commandForRow:(long long)arg1 ;
-(void)initializeCommander;
-(char)tableViewCaptureDeleteKeyPress:(id)arg1 ;
-(id)encodedKeyForKey:(id)arg1 ;
-(void)pressAddRemoveSegmentedControl:(id)arg1 ;
-(id)keyboardKeyForRow:(long long)arg1 ;
-(void)deleteEncodedKey:(id)arg1 ;
-(void)addCommandRow:(id)arg1 ;
-(void)removeCommandRow:(id)arg1 ;
-(void)_deleteCommandAlertDidEndSelector:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(char)isValidRow:(long long)arg1 ;
-(id)init;
-(void)dealloc;
-(char)tableView:(id)arg1 shouldEditTableColumn:(id)arg2 row:(long long)arg3 ;
-(void)tableViewSelectionDidChange:(id)arg1 ;
-(long long)numberOfRowsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3 ;
-(char)textShouldEndEditing:(id)arg1 ;
-(void)awakeFromNib;
@end

