/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:43 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSURL, NSString;

@interface MapsPaths : NSObject {

	NSURL* _libraryURL;
	NSString* _mapsDirectory;
	NSString* _bookmarksSettingsPath;
	NSString* _geoBookmarksSettingsPath;
	NSString* _directionsSettingsPath;
	NSString* _historySettingsPath;
	NSString* _geoHistorySettingsPath;
	NSString* _failedSearchesSettingsPath;
	NSString* _failedGeoSearchesSettingsPath;
	NSString* _failedDirectionsSettingsPath;
	NSString* _failedGeoDirectionsSettingsPath;
	NSString* _transitAppRankerPath;
	NSString* _pinsSettingsPath;

}

@property (nonatomic,readonly) NSString * mapsDirectory;                                //@synthesize mapsDirectory=_mapsDirectory - In the implementation block
@property (nonatomic,readonly) NSString * bookmarksSettingsPath;                        //@synthesize bookmarksSettingsPath=_bookmarksSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * geoBookmarksSettingsPath;                     //@synthesize geoBookmarksSettingsPath=_geoBookmarksSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * directionsSettingsPath;                       //@synthesize directionsSettingsPath=_directionsSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * historySettingsPath;                          //@synthesize historySettingsPath=_historySettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * geoHistorySettingsPath;                       //@synthesize geoHistorySettingsPath=_geoHistorySettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * failedSearchesSettingsPath;                   //@synthesize failedSearchesSettingsPath=_failedSearchesSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * failedGeoSearchesSettingsPath;                //@synthesize failedGeoSearchesSettingsPath=_failedGeoSearchesSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * failedGeoDirectionsSettingsPath;              //@synthesize failedGeoDirectionsSettingsPath=_failedGeoDirectionsSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * failedDirectionsSettingsPath;                 //@synthesize failedDirectionsSettingsPath=_failedDirectionsSettingsPath - In the implementation block
@property (nonatomic,readonly) NSString * transitAppRankerPath;                         //@synthesize transitAppRankerPath=_transitAppRankerPath - In the implementation block
@property (nonatomic,readonly) NSString * pinsSettingsPath;                             //@synthesize pinsSettingsPath=_pinsSettingsPath - In the implementation block
+(id)storageLocationsSetAtLocation:(long long)arg1 ;
+(id)geoBookmarksSettingsPath;
+(id)geoHistorySettingsPath;
+(id)mapsDirectory;
+(id)bookmarksSettingsPath;
+(id)directionsSettingsPath;
+(id)historySettingsPath;
+(id)failedSearchesSettingsPath;
+(id)failedGeoSearchesSettingsPath;
+(id)failedDirectionsSettingsPath;
+(id)failedGeoDirectionsSettingsPath;
+(id)transitAppRankerPath;
+(id)pinsSettingsPath;
-(NSString *)geoBookmarksSettingsPath;
-(NSString *)geoHistorySettingsPath;
-(id)initWithLibraryDirectoryURL:(id)arg1 ;
-(NSString *)mapsDirectory;
-(NSString *)bookmarksSettingsPath;
-(NSString *)directionsSettingsPath;
-(NSString *)historySettingsPath;
-(NSString *)failedSearchesSettingsPath;
-(NSString *)failedGeoSearchesSettingsPath;
-(NSString *)failedDirectionsSettingsPath;
-(NSString *)failedGeoDirectionsSettingsPath;
-(NSString *)transitAppRankerPath;
-(NSString *)pinsSettingsPath;
@end

