/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:42 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <AppKit/NSViewController.h>
#import <Maps/NSTableViewDelegate.h>
#import <Maps/NSTableViewDataSource.h>
#import <Maps/MapsDebugViewController.h>

@protocol MapsDebugViewControllerDelegate, MapsDebugViewControllerNavigationDelegate;
@class NSTableView, NSMutableArray, NSArray, NSMapTable, NSString;

@interface MapsDebugValuesViewController : NSViewController <NSTableViewDelegate, NSTableViewDataSource, MapsDebugViewController> {

	NSTableView* _tableView;
	NSMutableArray* _sections;
	NSArray* _rows;
	NSMapTable* _rowsToCellViews;
	char _isMakingViewsToFitOnly;
	id<MapsDebugViewControllerDelegate> _delegate;
	id<MapsDebugViewControllerNavigationDelegate> _navigationDelegate;
	NSString* _navigationDestinationTitle;
	/*^block*/id _prepareContentBlock;

}

@property (nonatomic,copy) NSString * navigationDestinationTitle;                                                  //@synthesize navigationDestinationTitle=_navigationDestinationTitle - In the implementation block
@property (nonatomic,copy) id prepareContentBlock;                                                                 //@synthesize prepareContentBlock=_prepareContentBlock - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<MapsDebugViewControllerDelegate> delegate;                                  //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<MapsDebugViewControllerNavigationDelegate> navigationDelegate;              //@synthesize navigationDelegate=_navigationDelegate - In the implementation block
+(id)navigationDestinationTitle;
+(void)_endBuiltInSheet:(id)arg1 ;
-(void)setPrepareContentBlock:(id)arg1 ;
-(id)_rows;
-(NSString *)navigationDestinationTitle;
-(id)prepareContentBlock;
-(void)loadContentNowIfNeeded;
-(id)_sections;
-(void)willNavigateToSubsequentController:(id)arg1 ;
-(void)segueToViewController:(id)arg1 ;
-(void)addSectionWithTitle:(id)arg1 content:(/*^block*/id)arg2 ;
-(void)setNavigationDestinationTitle:(NSString *)arg1 ;
-(void)addSection:(id)arg1 ;
-(id<MapsDebugViewControllerNavigationDelegate>)navigationDelegate;
-(void)setNavigationDelegate:(id<MapsDebugViewControllerNavigationDelegate>)arg1 ;
-(void)setDelegate:(id<MapsDebugViewControllerDelegate>)arg1 ;
-(id)title;
-(id<MapsDebugViewControllerDelegate>)delegate;
-(void)reloadData;
-(void)loadView;
-(id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3 ;
-(char)tableView:(id)arg1 shouldSelectRow:(long long)arg2 ;
-(double)tableView:(id)arg1 heightOfRow:(long long)arg2 ;
-(char)tableView:(id)arg1 isGroupRow:(long long)arg2 ;
-(long long)numberOfRowsInTableView:(id)arg1 ;
-(CGSize)preferredContentSize;
-(void)prepareContent;
@end

