/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:43 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSViewController.h>

@class MKMapItem, MKStarRatingView;

@interface NVCalloutBubbleViewController : NSViewController {

	MKMapItem* _mapItem;
	MKStarRatingView* _starRating;

}

@property (nonatomic,retain) MKMapItem * mapItem;                               //@synthesize mapItem=_mapItem - In the implementation block
@property (assign,nonatomic,__weak) MKStarRatingView * starRating;              //@synthesize starRating=_starRating - In the implementation block
-(MKStarRatingView *)starRating;
-(void)setStarRating:(MKStarRatingView *)arg1 ;
-(MKMapItem *)mapItem;
-(void)setMapItem:(MKMapItem *)arg1 ;
-(void)awakeFromNib;
@end

