/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:43 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/NSWindowDelegate.h>

@class NSMutableSet, NSString;

@interface NVDetachedInfoCardWindowsManager : NSObject <NSWindowDelegate> {

	NSMutableSet* _detachedWindows;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(id)detachedWindows;
-(void)unsafeRestoreStateWithCoder:(id)arg1 ;
-(id)newWindowPlaceCard:(id)arg1 inFrame:(CGRect)arg2 ;
-(void)updateBookmarks;
-(void)closeDetachableWindow:(id)arg1 ;
-(id)init;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)restoreStateWithCoder:(id)arg1 ;
-(void)windowWillClose:(id)arg1 ;
@end

