/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:43 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_semaphore, NVPrintSnapshotsFetcherDelegate;
@class NSMutableArray, NSObject, NSArray;

@interface NVPrintSnapshotsFetcher : NSObject {

	NSMutableArray* snapshotJobs;
	char _wasFetchWithCompletionCalled;
	NSObject*<OS_dispatch_semaphore> previousJobDone;
	id<NVPrintSnapshotsFetcherDelegate> _delegate;
	NSArray* _snapshotOptions;

}

@property (nonatomic,readonly) char wasFetchWithCompletionCalled; 
@property (assign,nonatomic,__weak) id<NVPrintSnapshotsFetcherDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSArray * snapshotOptions;                                        //@synthesize snapshotOptions=_snapshotOptions - In the implementation block
@property (nonatomic,readonly) unsigned long long numberToFetch; 
-(void)waitForSnapshotAtIndex:(unsigned long long)arg1 ;
-(void)setSnapshotOptions:(NSArray *)arg1 ;
-(char)wasFetchWithCompletionCalled;
-(void)fetchWithCompletion:(/*^block*/id)arg1 ;
-(NSArray *)snapshotOptions;
-(unsigned long long)numberToFetch;
-(void)setDelegate:(id<NVPrintSnapshotsFetcherDelegate>)arg1 ;
-(id<NVPrintSnapshotsFetcherDelegate>)delegate;
@end

