/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:42 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <AppKit/NSWindowController.h>
#import <Maps/NSWindowDelegate.h>
#import <Maps/NVReportAProblemViewControllerDelegate.h>

@class NSMutableDictionary, NSIndexSet, MapsRAPNotificationsAvailabilityProvider, NVRPDebugNotificationRequestWindowController, NVRAPAcknowledgmentViewController, NSView, NSLayoutConstraint, NVPlace, NVMainWindowController, NSArray, NSString;

@interface NVReportAProblemChooserWindowController : NSWindowController <NSWindowDelegate, NVReportAProblemViewControllerDelegate> {

	char _loaded;
	NSMutableDictionary* _controllers;
	NSIndexSet* _availableTypes;
	MapsRAPNotificationsAvailabilityProvider* _notificationsAvailabilityChecker;
	NVRPDebugNotificationRequestWindowController* _debugNotificationRequestController;
	NVRAPAcknowledgmentViewController* _thankYou;
	NSView* _contentView;
	NSLayoutConstraint* _windowWidthConstraint;
	NSLayoutConstraint* _windowHeightConstraint;
	NVPlace* _fromPlace;
	NVMainWindowController* _mainWindowController;
	NSView* _container;
	NSLayoutConstraint* _containerHeightConstraint;
	NSLayoutConstraint* _containerWidthConstraint;
	unsigned long long _currentType;

}

@property (nonatomic,retain) NVPlace * fromPlace;                                                //@synthesize fromPlace=_fromPlace - In the implementation block
@property (assign,nonatomic,__weak) NVMainWindowController * mainWindowController;               //@synthesize mainWindowController=_mainWindowController - In the implementation block
@property (assign,nonatomic,__weak) NSView * container;                                          //@synthesize container=_container - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * containerHeightConstraint;              //@synthesize containerHeightConstraint=_containerHeightConstraint - In the implementation block
@property (assign,nonatomic,__weak) NSLayoutConstraint * containerWidthConstraint;               //@synthesize containerWidthConstraint=_containerWidthConstraint - In the implementation block
@property (assign,nonatomic) unsigned long long currentType;                                     //@synthesize currentType=_currentType - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * controllers; 
@property (nonatomic,readonly) NSArray * typeIndices; 
@property (nonatomic,readonly) NSArray * typeStrings; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NVPlace *)fromPlace;
-(NVMainWindowController *)mainWindowController;
-(void)reportAProblemViewController:(id)arg1 didFinishSubmittingWithOutcome:(id)arg2 ;
-(void)setMainWindowController:(NVMainWindowController *)arg1 ;
-(void)updateContainerSize;
-(unsigned long long)currentType;
-(NSLayoutConstraint *)containerHeightConstraint;
-(NSLayoutConstraint *)containerWidthConstraint;
-(NSArray *)typeIndices;
-(void)setCurrentReportAProblemType:(unsigned long long)arg1 animated:(char)arg2 ;
-(void)setCurrentType:(unsigned long long)arg1 ;
-(id)initWithMainWindowController:(id)arg1 availableTypes:(id)arg2 place:(id)arg3 ;
-(void)changeReportAProblemType:(id)arg1 ;
-(void)setFromPlace:(NVPlace *)arg1 ;
-(void)setContainerHeightConstraint:(NSLayoutConstraint *)arg1 ;
-(void)setContainerWidthConstraint:(NSLayoutConstraint *)arg1 ;
-(NSMutableDictionary *)controllers;
-(NSArray *)typeStrings;
-(void)awakeFromNib;
-(id)windowNibName;
-(NSView *)container;
-(void)setContainer:(NSView *)arg1 ;
-(void)cleanup;
@end

