/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:39:43 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Maps.app/Contents/MacOS/Maps
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NVSideViewController, NSArray, NVPlace;

@interface NVSearchController : NSObject {

	NVSideViewController* sideViewController;

}

@property (copy) NSArray * searchPlaces; 
@property (nonatomic,retain) NVPlace * selectedSearchPlace; 
+(id)keyPathsForValuesAffectingSelectedSearchPlace;
-(NSArray *)searchPlaces;
-(void)setSearchPlaces:(NSArray *)arg1 ;
-(id)sideViewController;
-(NVPlace *)selectedSearchPlace;
-(void)setSelectedSearchPlace:(NVPlace *)arg1 ;
@end

