/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:17 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_source, SDBonjourPublisherDelegate;
#import <sharingd/sharingd-Structs.h>
@class NSNumber, SDStatusMonitor, NSObject, NSMutableDictionary;

@interface SDBonjourPublisher : NSObject {

	NSNumber* _port;
	long long _retryCount;
	OpaqueSecIdentityRefRef _identity;
	CFNetServiceRef _service;
	SDStatusMonitor* _monitor;
	NSObject*<OS_dispatch_source> _restartTimer;
	NSMutableDictionary* _txtRecord;
	NSMutableDictionary* _properties;
	id<SDBonjourPublisherDelegate> _delegate;

}

@property (__weak) id<SDBonjourPublisherDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)somethingChanged:(id)arg1 ;
-(void)setMyPictureAndHash;
-(void)updateTXTRecordAndNotify;
-(void)setSecIdentity:(OpaqueSecIdentityRefRef)arg1 ;
-(void)publishCallBack:(SCD_Struct_SD7*)arg1 ;
-(void)publish;
-(void)addObservers;
-(void)removeObservers;
-(void)setDelegate:(id<SDBonjourPublisherDelegate>)arg1 ;
-(void)dealloc;
-(void)stop;
-(void)start;
-(void)invalidate;
-(id<SDBonjourPublisherDelegate>)delegate;
-(id)initWithPort:(id)arg1 ;
@end

