/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:18 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <sharingd/SDBonjourBrowserDelegate.h>

@protocol SDWindowsBrowserDelegate;
@class SDBonjourBrowser, NSString, NSArray;

@interface SDWindowsBrowser : NSObject <SDBonjourBrowserDelegate> {

	SDBonjourBrowser* _browser;
	NSString* _workgroup;
	id<SDWindowsBrowserDelegate> _delegate;

}

@property (copy,readonly) NSArray * nodes; 
@property (copy,readonly) NSString * workgroup;                        //@synthesize workgroup=_workgroup - In the implementation block
@property (__weak) id<SDWindowsBrowserDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)bonjourNodesDidChange:(id)arg1 ;
-(NSString *)workgroup;
-(id)initWithWorkgroup:(id)arg1 ;
-(void)setDelegate:(id<SDWindowsBrowserDelegate>)arg1 ;
-(void)dealloc;
-(void)stop;
-(void)start;
-(id<SDWindowsBrowserDelegate>)delegate;
-(NSArray *)nodes;
@end

