#import <Automator/AMDocument.h>
#import <Automator/AMAppDelegate.h>
#import <Automator/AMScriptingElement.h>
#import <Automator/AMScriptingSetting.h>
#import <Automator/AMScriptingVariable.h>
#import <Automator/AMScriptingRequiredResource.h>
#import <Automator/AMScriptingAction.h>
#import <Automator/AMAutomatorApplication.h>
#import <Automator/AMDocumentProgressController.h>
#import <Automator/AMLoadingErrorsDisplayController.h>
#import <Automator/AMDocumentWindowController.h>
#import <Automator/AMDocumentWindow.h>
#import <Automator/AMDocumentWindowTitleCell.h>
#import <Automator/AMFadeWindowEffect.h>
#import <Automator/AMWindowAnimation.h>
#import <Automator/AMMiniDisplayWindow.h>
#import <Automator/AMMiniDisplay.h>
#import <Automator/AMLogViewController.h>
#import <Automator/AMVariablesViewController.h>
#import <Automator/AMVariablesTableView.h>
#import <Automator/AMWorkflowLog.h>
#import <Automator/AMDocumentController.h>
#import <Automator/AMWorkflowLogEntry.h>
#import <Automator/AMPluginInstallerController.h>
#import <Automator/AMWorkflowPersonalityInstallerController.h>
#import <Automator/AMActionInstallerController.h>
#import <Automator/AMSizingImageView.h>
#import <Automator/AMPluginCustomSaveWindowController.h>
#import <Automator/AUCodeSigning.h>
