/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:14 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ProtocolBuffer/PBRequester.h>

@interface CLALSRequester : PBRequester {

	int tag;
	int type;
	double timestamp;
	char processingCellTowers;
	char processingWirelessAPs;
	char finished;

}

@property (assign) int tag; 
@property (assign) int type; 
@property (assign) double timestamp; 
@property (assign) char processingCellTowers; 
@property (assign) char processingWirelessAPs; 
@property (assign) char finished; 
-(void)setProcessingCellTowers:(char)arg1 ;
-(void)setProcessingWirelessAPs:(char)arg1 ;
-(char)processingCellTowers;
-(char)processingWirelessAPs;
-(void)setTimestamp:(double)arg1 ;
-(void)setTag:(int)arg1 ;
-(int)tag;
-(double)timestamp;
-(int)type;
-(void)setType:(int)arg1 ;
-(void)setFinished:(char)arg1 ;
-(char)finished;
@end

