/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:15 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/locationd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol CLNotifierServiceProtocol <CLIntersiloServiceProtocol>
@required
-(void)register:(byref id)arg1 forNotification:(int)arg2 registrationInfo:(id)arg3;
-(void)unregister:(byref id)arg1 forNotification:(int)arg2;
-(void)forget:(byref id)arg1;

@end

