/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:37:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Mail.app/Contents/MacOS/Mail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Mail/Mail-Structs.h>
@class NSArray;

@interface _CellFindStore : NSObject {

	char _matchesAreValid;
	NSArray* _matches;
	CGRect _visibleRectInCell;
	CGRect _cellRectInContainingView;
	CGRect _visibleRectInContainingView;

}

@property (nonatomic,retain) NSArray * matches;                               //@synthesize matches=_matches - In the implementation block
@property (assign,nonatomic) char matchesAreValid;                            //@synthesize matchesAreValid=_matchesAreValid - In the implementation block
@property (assign,nonatomic) CGRect visibleRectInCell;                        //@synthesize visibleRectInCell=_visibleRectInCell - In the implementation block
@property (assign,nonatomic) CGRect cellRectInContainingView;                 //@synthesize cellRectInContainingView=_cellRectInContainingView - In the implementation block
@property (assign,nonatomic) CGRect visibleRectInContainingView;              //@synthesize visibleRectInContainingView=_visibleRectInContainingView - In the implementation block
-(char)matchesAreValid;
-(void)setMatchesAreValid:(char)arg1 ;
-(void)setCellRectInContainingView:(CGRect)arg1 ;
-(CGRect)visibleRectInCell;
-(CGRect)cellRectInContainingView;
-(void)setVisibleRectInCell:(CGRect)arg1 ;
-(void)setVisibleRectInContainingView:(CGRect)arg1 ;
-(CGRect)visibleRectInContainingView;
-(NSArray *)matches;
-(void)setMatches:(NSArray *)arg1 ;
@end

