/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:37:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Mail.app/Contents/MacOS/Mail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSPopUpButton.h>

@class NSString, NSURL, NSMenu;

@interface AppleScriptPopUpButton : NSPopUpButton {

	char _amIAwake;
	NSString* _previouslySelectedItem;
	NSURL* _applicationScriptsDirectoryURL;
	id _delegate;
	NSMenu* _appleScriptFilesMenu;

}

@property (nonatomic,retain) NSString * previouslySelectedItem;                   //@synthesize previouslySelectedItem=_previouslySelectedItem - In the implementation block
@property (nonatomic,retain) NSURL * applicationScriptsDirectoryURL;              //@synthesize applicationScriptsDirectoryURL=_applicationScriptsDirectoryURL - In the implementation block
@property (assign,nonatomic,__weak) id delegate;                                  //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSMenu * appleScriptFilesMenu;                       //@synthesize appleScriptFilesMenu=_appleScriptFilesMenu - In the implementation block
@property (assign,nonatomic) char amIAwake;                                       //@synthesize amIAwake=_amIAwake - In the implementation block
-(char)amIAwake;
-(void)setAmIAwake:(char)arg1 ;
-(void)setApplicationScriptsDirectoryURL:(NSURL *)arg1 ;
-(NSMenu *)appleScriptFilesMenu;
-(void)setAppleScriptFilesMenu:(NSMenu *)arg1 ;
-(void)_configureAppleScriptFilesMenu;
-(NSURL *)applicationScriptsDirectoryURL;
-(void)_popupMenuChanged:(id)arg1 ;
-(id)_appleScriptFilesFromMagicDirectory;
-(void)resetPopUp;
-(void)setPreviouslySelectedItem:(NSString *)arg1 ;
-(NSString *)previouslySelectedItem;
-(void)selectAppleScriptPath:(id)arg1 ;
-(id)selectedAppleScriptPath;
-(void)_invalidateAppleScriptFilesMenu;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(id)delegate;
-(id)menu;
-(void)viewDidMoveToWindow;
-(void)awakeFromNib;
@end

