/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:37:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Mail.app/Contents/MacOS/Mail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface FlagIconFactory : NSObject
+(id)iconForFlag:(char)arg1 ;
+(id)colorForFlag:(char)arg1 ;
+(id)displayNameForFlag:(char)arg1 ;
+(char)colorForKey:(id)arg1 ;
-(id)valueForKey:(id)arg1 ;
@end

