/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:37:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Mail.app/Contents/MacOS/Mail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Mail/MCActivityTarget.h>

@class NSMutableSet, NSArray, NSString;

@interface GenericAttachmentFetcher : NSObject <MCActivityTarget> {

	NSMutableSet* _attachmentsBeingDownloaded;
	NSArray* _attachments;
	GenericAttachmentFetcher* _me;

}

@property (nonatomic,copy) NSArray * attachments;                        //@synthesize attachments=_attachments - In the implementation block
@property (nonatomic,retain) GenericAttachmentFetcher * me;              //@synthesize me=_me - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_downloadCompleted:(id)arg1 ;
-(void)beginBackgroundLoad;
-(void)didFinishBackgroundLoadOfAttachment:(id)arg1 ;
-(void)downloadedAllAttachments;
-(void)didSaveAttachment:(id)arg1 toPath:(id)arg2 ;
-(void)didSaveAttachments:(id)arg1 paths:(id)arg2 ;
-(double)temporaryFolderTimeout;
-(void)_saveAttachments:(id)arg1 itemManager:(id)arg2 ;
-(void)cancelBackgroundLoad;
-(id)downloadedAttachments;
-(void)beginSaveOfAttachments:(id)arg1 toTemporaryFolderWithName:(id)arg2 taskName:(id)arg3 ;
-(GenericAttachmentFetcher *)me;
-(id)initWithAttachments:(id)arg1 ;
-(void)setMe:(GenericAttachmentFetcher *)arg1 ;
-(id)init;
-(void)dealloc;
-(NSArray *)attachments;
-(void)setAttachments:(NSArray *)arg1 ;
@end

