/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:37:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Mail.app/Contents/MacOS/Mail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Mail/AccountInfoTabOwner.h>
#import <Mail/MCActivityTarget.h>
#import <Mail/NSOutlineViewDataSource.h>
#import <Mail/NSOutlineViewDelegate.h>

@class MCActivityMonitor, NSWindow, NSView, NSSearchField, NSOutlineView, NSButton, NSProgressIndicator, NSTextField, NSImageView, MFIMAPAccount, IMAPGateway, NSPredicate, NSArray, MCInvocationQueue, NSString;

@interface IMAPMailboxes : NSObject <AccountInfoTabOwner, MCActivityTarget, NSOutlineViewDataSource, NSOutlineViewDelegate> {

	MCActivityMonitor* _mailboxListMonitor;
	NSWindow* _window;
	NSView* _mailboxesView;
	NSSearchField* _searchField;
	NSOutlineView* _mailboxesOutline;
	NSButton* _subscribeButton;
	NSButton* _unsubscribeButton;
	NSProgressIndicator* _fetchProgressIndicator;
	NSTextField* _fetchStatusField;
	NSImageView* _statusImageView;
	MFIMAPAccount* _account;
	IMAPGateway* _gateway;
	NSPredicate* _predicate;
	NSArray* _mailboxes;
	NSArray* _filteredMailboxes;
	MCInvocationQueue* _subscribeQueue;

}

@property (nonatomic,retain) NSWindow * window;                                                //@synthesize window=_window - In the implementation block
@property (assign,nonatomic,__weak) NSView * mailboxesView;                                    //@synthesize mailboxesView=_mailboxesView - In the implementation block
@property (assign,nonatomic,__weak) NSSearchField * searchField;                               //@synthesize searchField=_searchField - In the implementation block
@property (assign,nonatomic,__weak) NSOutlineView * mailboxesOutline;                          //@synthesize mailboxesOutline=_mailboxesOutline - In the implementation block
@property (assign,nonatomic,__weak) NSButton * subscribeButton;                                //@synthesize subscribeButton=_subscribeButton - In the implementation block
@property (assign,nonatomic,__weak) NSButton * unsubscribeButton;                              //@synthesize unsubscribeButton=_unsubscribeButton - In the implementation block
@property (assign,nonatomic,__weak) NSProgressIndicator * fetchProgressIndicator;              //@synthesize fetchProgressIndicator=_fetchProgressIndicator - In the implementation block
@property (assign,nonatomic,__weak) NSTextField * fetchStatusField;                            //@synthesize fetchStatusField=_fetchStatusField - In the implementation block
@property (assign,nonatomic,__weak) NSImageView * statusImageView;                             //@synthesize statusImageView=_statusImageView - In the implementation block
@property (nonatomic,retain) MFIMAPAccount * account;                                          //@synthesize account=_account - In the implementation block
@property (nonatomic,retain) IMAPGateway * gateway;                                            //@synthesize gateway=_gateway - In the implementation block
@property (nonatomic,retain) NSPredicate * predicate;                                          //@synthesize predicate=_predicate - In the implementation block
@property (nonatomic,copy) NSArray * mailboxes;                                                //@synthesize mailboxes=_mailboxes - In the implementation block
@property (nonatomic,copy) NSArray * filteredMailboxes;                                        //@synthesize filteredMailboxes=_filteredMailboxes - In the implementation block
@property (nonatomic,retain) MCInvocationQueue * subscribeQueue;                               //@synthesize subscribeQueue=_subscribeQueue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setupUIWithAccount:(id)arg1 ;
-(void)setMailboxes:(NSArray *)arg1 ;
-(void)accountInfoWillHideView:(id)arg1 ;
-(void)accountInfoWillShowView:(id)arg1 ;
-(NSOutlineView *)mailboxesOutline;
-(void)setMailboxesOutline:(NSOutlineView *)arg1 ;
-(NSView *)mailboxesView;
-(void)setMailboxesView:(NSView *)arg1 ;
-(void)_clearFilteredMailboxes;
-(NSProgressIndicator *)fetchProgressIndicator;
-(NSTextField *)fetchStatusField;
-(NSImageView *)statusImageView;
-(id)_alertIcon;
-(void)_fetchMailboxListingForAccount:(id)arg1 ;
-(NSButton *)subscribeButton;
-(NSButton *)unsubscribeButton;
-(void)_updateUIForOnlineState:(id)arg1 ;
-(void)setFilteredMailboxes:(NSArray *)arg1 ;
-(void)_reallySetSubscribedState:(char)arg1 forMailboxPath:(id)arg2 parentMailbox:(id)arg3 account:(id)arg4 refreshListing:(char)arg5 ;
-(id)_recursivelyCreateMailboxEntriesForList:(id)arg1 subscribedList:(id)arg2 inLocalPath:(id)arg3 remotePath:(id)arg4 forAccount:(id)arg5 ;
-(void)_mailboxFetchCompleted:(id)arg1 forAccount:(id)arg2 ;
-(void)_reallyStartSubscriptionRequest:(id)arg1 ;
-(MCInvocationQueue *)subscribeQueue;
-(void)setSubscribeQueue:(MCInvocationQueue *)arg1 ;
-(void)_reallyStopSubscriptionRequest:(id)arg1 refreshList:(id)arg2 ;
-(void)_setSubscribedState:(char)arg1 forMailboxPath:(id)arg2 parentUid:(id)arg3 ;
-(void)_updateEntryTreeForChangedEntry:(id)arg1 oldValue:(char)arg2 ;
-(void)_handleSubscriptionRequest:(char)arg1 forItem:(id)arg2 refreshSet:(id)arg3 recursive:(char)arg4 ;
-(void)_startSubscriptionRequest;
-(void)_stopSubscriptionRequest:(id)arg1 ;
-(void)_handleSubscriptionRequest:(char)arg1 ;
-(NSArray *)filteredMailboxes;
-(void)_clearFilteredMailboxes:(id)arg1 ;
-(id)_mailboxEntryForPath:(id)arg1 ;
-(void)_handleError:(id)arg1 settingSubscribedState:(id)arg2 forMailboxPath:(id)arg3 account:(id)arg4 ;
-(void)subscribeButtonClicked:(id)arg1 ;
-(void)unsubscribeButtonClicked:(id)arg1 ;
-(void)filterMailboxList:(id)arg1 ;
-(id)_mailboxEntryForMailbox:(id)arg1 ;
-(void)setSubscribeButton:(NSButton *)arg1 ;
-(void)setUnsubscribeButton:(NSButton *)arg1 ;
-(void)setFetchProgressIndicator:(NSProgressIndicator *)arg1 ;
-(void)setFetchStatusField:(NSTextField *)arg1 ;
-(void)setStatusImageView:(NSImageView *)arg1 ;
-(NSSearchField *)searchField;
-(void)setSearchField:(NSSearchField *)arg1 ;
-(IMAPGateway *)gateway;
-(void)setGateway:(IMAPGateway *)arg1 ;
-(NSArray *)mailboxes;
-(void)_setupNotifications;
-(id)init;
-(void)dealloc;
-(NSWindow *)window;
-(id)view;
-(void)setWindow:(NSWindow *)arg1 ;
-(void)setPredicate:(NSPredicate *)arg1 ;
-(void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4 ;
-(char)outlineView:(id)arg1 shouldSelectItem:(id)arg2 ;
-(long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2 ;
-(id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3 ;
-(char)outlineView:(id)arg1 isItemExpandable:(id)arg2 ;
-(id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3 ;
-(void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4 ;
-(NSPredicate *)predicate;
-(void)setUIEnabled:(char)arg1 ;
-(MFIMAPAccount *)account;
-(void)setAccount:(MFIMAPAccount *)arg1 ;
@end

