/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:37:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Mail.app/Contents/MacOS/Mail
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MessageTransferDelegate <NSObject>
@required
-(void)unhideMessagesForMessageTransfer:(id)arg1;
-(void)transfer:(id)arg1 didCompleteWithError:(id)arg2;
-(id)undoManagerForMessageTransfer:(id)arg1;
-(void)messageTransferDidUndoTransferOfMessages:(id)arg1;
-(void)hideMessagesForMessageTransfer:(id)arg1;
-(void)messageTransferDidTransferMessages:(id)arg1;

@end

