/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 10:12:18 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Activity Monitor.app/Contents/MacOS/Activity Monitor
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Activity Monitor/Activity Monitor-Structs.h>
#import <AppKit/NSView.h>

@class NSView;

@interface CenteredView : NSView {

	NSView* _viewToCenter;
	NSView* _centeredLabel;

}

@property (retain) NSView * viewToCenter;               //@synthesize viewToCenter=_viewToCenter - In the implementation block
@property (retain) NSView * centeredLabel;              //@synthesize centeredLabel=_centeredLabel - In the implementation block
-(NSView *)viewToCenter;
-(NSView *)centeredLabel;
-(void)setViewToCenter:(NSView *)arg1 ;
-(void)setCenteredLabel:(NSView *)arg1 ;
-(void)awakeFromNib;
-(void)resizeWithOldSuperviewSize:(CGSize)arg1 ;
-(void)resizeSubviewsWithOldSize:(CGSize)arg1 ;
@end

