/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 10:12:18 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Activity Monitor.app/Contents/MacOS/Activity Monitor
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Activity Monitor/Activity Monitor-Structs.h>
@class NSNumber, NSString, NSImage, NSArray;

@interface SMProcess : NSObject {

	char _hung;
	NSNumber* _combinedPowerScore;
	NSNumber* _combinedAveragePowerScore;
	char _placeholder;
	char _foregroundApp;
	char _historicalProcess;
	char _updated;
	char _marked;
	char _usesDiscreteGPU;
	char _childUsesDiscreteGPU;
	char _compositeProcess;
	char _appSleepState;
	int _architecture;
	int _hangs;
	int _sandboxState;
	NSNumber* _pid;
	NSNumber* _ppid;
	NSNumber* _responsible_pid;
	NSNumber* _uid;
	NSNumber* _suid;
	NSNumber* _graphicalParentPid;
	NSNumber* _pgid;
	NSString* _command;
	NSString* _processName;
	double _cpuUsage;
	double _cpuUsedSeconds;
	NSNumber* _contextSwitches;
	NSNumber* _faults;
	NSNumber* _machCalls;
	NSNumber* _msgsRcvd;
	NSNumber* _msgsSent;
	NSNumber* _ports;
	NSNumber* _threads;
	NSNumber* _pageIns;
	NSNumber* _unixSyscalls;
	NSNumber* _residentSize;
	NSNumber* _anonymousMemory;
	NSNumber* _compressedMemory;
	NSNumber* _virtualSize;
	NSNumber* _privateMemory;
	NSNumber* _sharedMemory;
	NSNumber* _purgeableMemory;
	NSNumber* _idleWakeups;
	NSNumber* _idleWakeupsDelta;
	NSNumber* _averagePowerScore;
	NSNumber* _powerScore;
	LSASNRef _asn;
	NSImage* _icon;
	unsigned long long _procFlags;
	NSString* _bundleIdentifier;
	NSString* _executablePath;
	unsigned long long _allAssertions;
	NSNumber* _totalPowerScore;
	NSString* _combinedPowerScoreDescription;
	NSString* _combinedAveragePowerScoreDescription;
	NSNumber* _combinedIdleWakeupsDelta;
	NSNumber* _bytesWritten;
	NSNumber* _bytesWrittenDelta;
	NSNumber* _bytesRead;
	NSNumber* _bytesReadDelta;
	NSNumber* _txBytes;
	NSNumber* _rxBytes;
	NSNumber* _txPackets;
	NSNumber* _rxPackets;
	NSNumber* _txBytesDelta;
	NSNumber* _rxBytesDelta;
	NSNumber* _txPacketsDelta;
	NSNumber* _rxPacketsDelta;
	NSString* _username;
	NSString* _appSleepDescription;
	NSString* _instantOffDescription;
	NSString* _sandboxDescription;
	NSString* _architectureDescription;
	NSString* _cpuUsageDescription;
	NSString* _cpuUsedSecondsDescription;
	NSString* _powerScoreDescription;
	NSString* _averagePowerScoreDescription;
	double _cpuUsageDelta;
	NSNumber* _contextSwitchesDelta;
	NSNumber* _faultsDelta;
	NSNumber* _machCallsDelta;
	NSNumber* _msgsSentDelta;
	NSNumber* _msgsRcvdDelta;
	NSNumber* _portsDelta;
	NSNumber* _threadsDelta;
	NSNumber* _pageInsDelta;
	NSNumber* _unixSyscallsDelta;
	NSNumber* _residentSizeDelta;
	NSNumber* _anonymousMemoryDelta;
	NSNumber* _compressedMemoryDelta;
	NSNumber* _virtualSizeDelta;
	NSNumber* _privateMemoryDelta;
	NSNumber* _sharedMemoryDelta;
	NSNumber* _purgeableMemoryDelta;
	unsigned long long _totalNanoSeconds;
	unsigned long long _procStatus;

}

@property (getter=isPlaceholder) char placeholder;                                  //@synthesize placeholder=_placeholder - In the implementation block
@property (retain) NSNumber * pid;                                                  //@synthesize pid=_pid - In the implementation block
@property (retain) NSNumber * ppid;                                                 //@synthesize ppid=_ppid - In the implementation block
@property (retain) NSNumber * responsible_pid;                                      //@synthesize responsible_pid=_responsible_pid - In the implementation block
@property (retain) NSNumber * uid;                                                  //@synthesize uid=_uid - In the implementation block
@property (retain) NSNumber * suid;                                                 //@synthesize suid=_suid - In the implementation block
@property (retain) NSNumber * graphicalParentPid;                                   //@synthesize graphicalParentPid=_graphicalParentPid - In the implementation block
@property (retain) NSNumber * pgid;                                                 //@synthesize pgid=_pgid - In the implementation block
@property (retain) NSString * command;                                              //@synthesize command=_command - In the implementation block
@property (retain) NSString * processName;                                          //@synthesize processName=_processName - In the implementation block
@property (assign) int architecture;                                                //@synthesize architecture=_architecture - In the implementation block
@property (assign) double cpuUsage;                                                 //@synthesize cpuUsage=_cpuUsage - In the implementation block
@property (assign) double cpuUsedSeconds;                                           //@synthesize cpuUsedSeconds=_cpuUsedSeconds - In the implementation block
@property (retain) NSNumber * contextSwitches;                                      //@synthesize contextSwitches=_contextSwitches - In the implementation block
@property (retain) NSNumber * faults;                                               //@synthesize faults=_faults - In the implementation block
@property (retain) NSNumber * machCalls;                                            //@synthesize machCalls=_machCalls - In the implementation block
@property (retain) NSNumber * msgsRcvd;                                             //@synthesize msgsRcvd=_msgsRcvd - In the implementation block
@property (retain) NSNumber * msgsSent;                                             //@synthesize msgsSent=_msgsSent - In the implementation block
@property (retain) NSNumber * ports;                                                //@synthesize ports=_ports - In the implementation block
@property (retain) NSNumber * threads;                                              //@synthesize threads=_threads - In the implementation block
@property (retain) NSNumber * pageIns;                                              //@synthesize pageIns=_pageIns - In the implementation block
@property (retain) NSNumber * unixSyscalls;                                         //@synthesize unixSyscalls=_unixSyscalls - In the implementation block
@property (retain) NSNumber * residentSize;                                         //@synthesize residentSize=_residentSize - In the implementation block
@property (retain) NSNumber * anonymousMemory;                                      //@synthesize anonymousMemory=_anonymousMemory - In the implementation block
@property (retain) NSNumber * compressedMemory;                                     //@synthesize compressedMemory=_compressedMemory - In the implementation block
@property (retain) NSNumber * virtualSize;                                          //@synthesize virtualSize=_virtualSize - In the implementation block
@property (retain) NSNumber * privateMemory;                                        //@synthesize privateMemory=_privateMemory - In the implementation block
@property (retain) NSNumber * sharedMemory;                                         //@synthesize sharedMemory=_sharedMemory - In the implementation block
@property (retain) NSNumber * purgeableMemory;                                      //@synthesize purgeableMemory=_purgeableMemory - In the implementation block
@property (retain) NSNumber * idleWakeups;                                          //@synthesize idleWakeups=_idleWakeups - In the implementation block
@property (retain) NSNumber * idleWakeupsDelta;                                     //@synthesize idleWakeupsDelta=_idleWakeupsDelta - In the implementation block
@property (retain) NSNumber * averagePowerScore;                                    //@synthesize averagePowerScore=_averagePowerScore - In the implementation block
@property (retain) NSNumber * powerScore;                                           //@synthesize powerScore=_powerScore - In the implementation block
@property (assign) LSASNRef asn;                                                    //@synthesize asn=_asn - In the implementation block
@property (retain) NSImage * icon;                                                  //@synthesize icon=_icon - In the implementation block
@property (assign) int hangs;                                                       //@synthesize hangs=_hangs - In the implementation block
@property (assign) unsigned long long procFlags;                                    //@synthesize procFlags=_procFlags - In the implementation block
@property (retain) NSString * bundleIdentifier;                                     //@synthesize bundleIdentifier=_bundleIdentifier - In the implementation block
@property (retain) NSString * executablePath;                                       //@synthesize executablePath=_executablePath - In the implementation block
@property (readonly) NSArray * webKitActiveURLs; 
@property (getter=isForegroundApp) char foregroundApp;                              //@synthesize foregroundApp=_foregroundApp - In the implementation block
@property (getter=isHistoricalProcess) char historicalProcess;                      //@synthesize historicalProcess=_historicalProcess - In the implementation block
@property (assign) unsigned long long allAssertions;                                //@synthesize allAssertions=_allAssertions - In the implementation block
@property (readonly) unsigned long long assertionCount; 
@property (retain) NSNumber * totalPowerScore;                                      //@synthesize totalPowerScore=_totalPowerScore - In the implementation block
@property (retain) NSNumber * combinedPowerScore; 
@property (retain) NSString * combinedPowerScoreDescription;                        //@synthesize combinedPowerScoreDescription=_combinedPowerScoreDescription - In the implementation block
@property (retain) NSNumber * combinedAveragePowerScore; 
@property (retain) NSString * combinedAveragePowerScoreDescription;                 //@synthesize combinedAveragePowerScoreDescription=_combinedAveragePowerScoreDescription - In the implementation block
@property (retain) NSNumber * combinedIdleWakeupsDelta;                             //@synthesize combinedIdleWakeupsDelta=_combinedIdleWakeupsDelta - In the implementation block
@property (retain) NSNumber * bytesWritten;                                         //@synthesize bytesWritten=_bytesWritten - In the implementation block
@property (retain) NSNumber * bytesWrittenDelta;                                    //@synthesize bytesWrittenDelta=_bytesWrittenDelta - In the implementation block
@property (retain) NSNumber * bytesRead;                                            //@synthesize bytesRead=_bytesRead - In the implementation block
@property (retain) NSNumber * bytesReadDelta;                                       //@synthesize bytesReadDelta=_bytesReadDelta - In the implementation block
@property (retain) NSNumber * txBytes;                                              //@synthesize txBytes=_txBytes - In the implementation block
@property (retain) NSNumber * rxBytes;                                              //@synthesize rxBytes=_rxBytes - In the implementation block
@property (retain) NSNumber * txPackets;                                            //@synthesize txPackets=_txPackets - In the implementation block
@property (retain) NSNumber * rxPackets;                                            //@synthesize rxPackets=_rxPackets - In the implementation block
@property (retain) NSNumber * txBytesDelta;                                         //@synthesize txBytesDelta=_txBytesDelta - In the implementation block
@property (retain) NSNumber * rxBytesDelta;                                         //@synthesize rxBytesDelta=_rxBytesDelta - In the implementation block
@property (retain) NSNumber * txPacketsDelta;                                       //@synthesize txPacketsDelta=_txPacketsDelta - In the implementation block
@property (retain) NSNumber * rxPacketsDelta;                                       //@synthesize rxPacketsDelta=_rxPacketsDelta - In the implementation block
@property (retain) NSString * username;                                             //@synthesize username=_username - In the implementation block
@property (retain) NSString * appSleepDescription;                                  //@synthesize appSleepDescription=_appSleepDescription - In the implementation block
@property (retain) NSString * instantOffDescription;                                //@synthesize instantOffDescription=_instantOffDescription - In the implementation block
@property (retain) NSString * sandboxDescription;                                   //@synthesize sandboxDescription=_sandboxDescription - In the implementation block
@property (retain) NSString * architectureDescription;                              //@synthesize architectureDescription=_architectureDescription - In the implementation block
@property (retain) NSString * cpuUsageDescription;                                  //@synthesize cpuUsageDescription=_cpuUsageDescription - In the implementation block
@property (retain) NSString * cpuUsedSecondsDescription;                            //@synthesize cpuUsedSecondsDescription=_cpuUsedSecondsDescription - In the implementation block
@property (retain) NSString * powerScoreDescription;                                //@synthesize powerScoreDescription=_powerScoreDescription - In the implementation block
@property (retain) NSString * averagePowerScoreDescription;                         //@synthesize averagePowerScoreDescription=_averagePowerScoreDescription - In the implementation block
@property (readonly) NSString * graphicCardDescription; 
@property (readonly) NSString * powerAssertionDescription; 
@property (readonly) NSString * powerAssertionFullDescription; 
@property (getter=isUpdated) char updated;                                          //@synthesize updated=_updated - In the implementation block
@property (getter=isMarked) char marked;                                            //@synthesize marked=_marked - In the implementation block
@property (getter=isHung) char hung; 
@property (getter=isUsingDiscreteGPU) char usesDiscreteGPU;                         //@synthesize usesDiscreteGPU=_usesDiscreteGPU - In the implementation block
@property (getter=hasChildUsingDiscreteGPU) char childUsesDiscreteGPU;              //@synthesize childUsesDiscreteGPU=_childUsesDiscreteGPU - In the implementation block
@property (getter=isCompositeProcess) char compositeProcess;                        //@synthesize compositeProcess=_compositeProcess - In the implementation block
@property (assign) double cpuUsageDelta;                                            //@synthesize cpuUsageDelta=_cpuUsageDelta - In the implementation block
@property (retain) NSNumber * contextSwitchesDelta;                                 //@synthesize contextSwitchesDelta=_contextSwitchesDelta - In the implementation block
@property (retain) NSNumber * faultsDelta;                                          //@synthesize faultsDelta=_faultsDelta - In the implementation block
@property (retain) NSNumber * machCallsDelta;                                       //@synthesize machCallsDelta=_machCallsDelta - In the implementation block
@property (retain) NSNumber * msgsSentDelta;                                        //@synthesize msgsSentDelta=_msgsSentDelta - In the implementation block
@property (retain) NSNumber * msgsRcvdDelta;                                        //@synthesize msgsRcvdDelta=_msgsRcvdDelta - In the implementation block
@property (retain) NSNumber * portsDelta;                                           //@synthesize portsDelta=_portsDelta - In the implementation block
@property (retain) NSNumber * threadsDelta;                                         //@synthesize threadsDelta=_threadsDelta - In the implementation block
@property (retain) NSNumber * pageInsDelta;                                         //@synthesize pageInsDelta=_pageInsDelta - In the implementation block
@property (retain) NSNumber * unixSyscallsDelta;                                    //@synthesize unixSyscallsDelta=_unixSyscallsDelta - In the implementation block
@property (retain) NSNumber * residentSizeDelta;                                    //@synthesize residentSizeDelta=_residentSizeDelta - In the implementation block
@property (retain) NSNumber * anonymousMemoryDelta;                                 //@synthesize anonymousMemoryDelta=_anonymousMemoryDelta - In the implementation block
@property (retain) NSNumber * compressedMemoryDelta;                                //@synthesize compressedMemoryDelta=_compressedMemoryDelta - In the implementation block
@property (retain) NSNumber * virtualSizeDelta;                                     //@synthesize virtualSizeDelta=_virtualSizeDelta - In the implementation block
@property (retain) NSNumber * privateMemoryDelta;                                   //@synthesize privateMemoryDelta=_privateMemoryDelta - In the implementation block
@property (retain) NSNumber * sharedMemoryDelta;                                    //@synthesize sharedMemoryDelta=_sharedMemoryDelta - In the implementation block
@property (retain) NSNumber * purgeableMemoryDelta;                                 //@synthesize purgeableMemoryDelta=_purgeableMemoryDelta - In the implementation block
@property (readonly) char isSpotlightFamily; 
@property (readonly) char isWebKitPlugin; 
@property (readonly) char isTimeMachineFamily; 
@property (readonly) char isPhotostream; 
@property (assign) int sandboxState;                                                //@synthesize sandboxState=_sandboxState - In the implementation block
@property (assign) unsigned long long totalNanoSeconds;                             //@synthesize totalNanoSeconds=_totalNanoSeconds - In the implementation block
@property (assign) unsigned long long procStatus;                                   //@synthesize procStatus=_procStatus - In the implementation block
@property (assign) char appSleepState;                                              //@synthesize appSleepState=_appSleepState - In the implementation block
+(id)stringWithNoDecimalForNumber:(id)arg1 ;
-(NSArray *)webKitActiveURLs;
-(NSNumber *)responsible_pid;
-(char)isWebKitPlugin;
-(NSNumber *)totalPowerScore;
-(char)isSpotlightFamily;
-(char)isTimeMachineFamily;
-(char)isForegroundApp;
-(char)isHistoricalProcess;
-(char)isPhotostream;
-(void)updateWithSysmonRow:(id)arg1 sampleInterval:(double)arg2 inspected:(char)arg3 ;
-(void)setCombinedPowerScore:(NSNumber *)arg1 ;
-(void)setCombinedIdleWakeupsDelta:(NSNumber *)arg1 ;
-(void)setCombinedAveragePowerScore:(NSNumber *)arg1 ;
-(id)initWithSysmonRow:(id)arg1 sampleInterval:(double)arg2 ;
-(NSString *)cpuUsageDescription;
-(double)cpuUsage;
-(void)overrideProcessName:(id)arg1 ;
-(void)overrideBundleIdentifier:(id)arg1 ;
-(void)overrideProcessIcon:(id)arg1 ;
-(char)isCompositeProcess;
-(void)convertToPlaceholder;
-(void)overrideResponsiblePID:(id)arg1 ;
-(void)setHistoricalProcess:(char)arg1 ;
-(void)setTotalPowerScore:(NSNumber *)arg1 ;
-(void)setUsesDiscreteGPU:(char)arg1 ;
-(void)setAllAssertions:(unsigned long long)arg1 ;
-(NSNumber *)combinedPowerScore;
-(NSNumber *)powerScore;
-(NSNumber *)combinedAveragePowerScore;
-(NSNumber *)averagePowerScore;
-(NSNumber *)combinedIdleWakeupsDelta;
-(NSNumber *)idleWakeupsDelta;
-(char)isUsingDiscreteGPU;
-(void)setChildUsesDiscreteGPU:(char)arg1 ;
-(void)convertToCompositeProcess;
-(void)aggregateWithProcess:(id)arg1 ;
-(id)initWithName:(id)arg1 powerScore:(id)arg2 icon:(id)arg3 bundeIdentifier:(id)arg4 ;
-(void)convertToPlaceholderWithResponsiblePID:(id)arg1 ;
-(void)updateWithNetStatDictionary:(id)arg1 ;
-(char)isMarked;
-(CPSProcessSerNum)psn;
-(void)setMarked:(char)arg1 ;
-(NSString *)powerAssertionFullDescription;
-(char)isHung;
-(NSString *)combinedPowerScoreDescription;
-(NSString *)powerScoreDescription;
-(NSString *)combinedAveragePowerScoreDescription;
-(NSString *)averagePowerScoreDescription;
-(NSString *)architectureDescription;
-(NSString *)instantOffDescription;
-(NSString *)sandboxDescription;
-(NSString *)appSleepDescription;
-(NSString *)cpuUsedSecondsDescription;
-(NSString *)graphicCardDescription;
-(NSString *)powerAssertionDescription;
-(double)cpuUsageDelta;
-(void)updateLaunchServicesInfo;
-(void)setHung:(char)arg1 ;
-(NSNumber *)suid;
-(NSNumber *)contextSwitches;
-(NSNumber *)contextSwitchesDelta;
-(NSNumber *)faults;
-(NSNumber *)faultsDelta;
-(NSNumber *)machCalls;
-(NSNumber *)machCallsDelta;
-(NSNumber *)msgsRcvd;
-(NSNumber *)msgsRcvdDelta;
-(NSNumber *)msgsSent;
-(NSNumber *)msgsSentDelta;
-(NSNumber *)pageIns;
-(NSNumber *)pageInsDelta;
-(NSNumber *)portsDelta;
-(NSNumber *)threadsDelta;
-(NSNumber *)unixSyscalls;
-(NSNumber *)unixSyscallsDelta;
-(NSNumber *)privateMemory;
-(NSNumber *)privateMemoryDelta;
-(NSNumber *)residentSize;
-(NSNumber *)residentSizeDelta;
-(NSNumber *)sharedMemory;
-(NSNumber *)sharedMemoryDelta;
-(NSNumber *)virtualSize;
-(NSNumber *)virtualSizeDelta;
-(NSNumber *)graphicalParentPid;
-(NSNumber *)pgid;
-(double)cpuUsedSeconds;
-(int)hangs;
-(unsigned long long)assertionCount;
-(void)setCpuUsage:(double)arg1 ;
-(void)setFaults:(NSNumber *)arg1 ;
-(void)setMachCalls:(NSNumber *)arg1 ;
-(void)setMsgsRcvd:(NSNumber *)arg1 ;
-(void)setMsgsSent:(NSNumber *)arg1 ;
-(void)setPageIns:(NSNumber *)arg1 ;
-(void)setPorts:(NSNumber *)arg1 ;
-(void)setPrivateMemory:(NSNumber *)arg1 ;
-(void)setResidentSize:(NSNumber *)arg1 ;
-(void)setSharedMemory:(NSNumber *)arg1 ;
-(void)setUnixSyscalls:(NSNumber *)arg1 ;
-(void)setVirtualSize:(NSNumber *)arg1 ;
-(void)setHangs:(int)arg1 ;
-(unsigned long long)procStatus;
-(void)setAppSleepState:(char)arg1 ;
-(void)setAppSleepDescription:(NSString *)arg1 ;
-(void)setProcStatus:(unsigned long long)arg1 ;
-(void)setArchitecture:(int)arg1 ;
-(id)_architectureDescription;
-(void)setArchitectureDescription:(NSString *)arg1 ;
-(LSASNRef)asn;
-(void)setAsn:(LSASNRef)arg1 ;
-(void)setForegroundApp:(char)arg1 ;
-(void)setResponsible_pid:(NSNumber *)arg1 ;
-(void)setCompositeProcess:(char)arg1 ;
-(void)setPowerScore:(NSNumber *)arg1 ;
-(void)setPowerScoreDescription:(NSString *)arg1 ;
-(void)setAveragePowerScore:(NSNumber *)arg1 ;
-(void)setAveragePowerScoreDescription:(NSString *)arg1 ;
-(int)sandboxState;
-(void)setSandboxState:(int)arg1 ;
-(void)setSandboxDescription:(NSString *)arg1 ;
-(void)setInstantOffDescription:(NSString *)arg1 ;
-(id)_stringWithOneDecimalForNumber:(id)arg1 ;
-(void)setCpuUsageDescription:(NSString *)arg1 ;
-(void)setCpuUsageDelta:(double)arg1 ;
-(void)_updateCPUUsage:(double)arg1 ;
-(void)setExecutablePath:(NSString *)arg1 ;
-(void)setCpuUsedSecondsDescription:(NSString *)arg1 ;
-(void)setCpuUsedSeconds:(double)arg1 ;
-(char)appSleepState;
-(void)_updateSandboxInfo;
-(void)_updateInstantOffInfo;
-(void)setCombinedPowerScoreDescription:(NSString *)arg1 ;
-(char)hasChildUsingDiscreteGPU;
-(void)setCombinedAveragePowerScoreDescription:(NSString *)arg1 ;
-(unsigned long long)allAssertions;
-(id)initWithName:(id)arg1 icon:(id)arg2 bundeIdentifier:(id)arg3 ;
-(void)setPpid:(NSNumber *)arg1 ;
-(void)setSuid:(NSNumber *)arg1 ;
-(void)setGraphicalParentPid:(NSNumber *)arg1 ;
-(void)setPgid:(NSNumber *)arg1 ;
-(void)setContextSwitches:(NSNumber *)arg1 ;
-(void)setThreads:(NSNumber *)arg1 ;
-(NSNumber *)anonymousMemory;
-(void)setAnonymousMemory:(NSNumber *)arg1 ;
-(NSNumber *)compressedMemory;
-(void)setCompressedMemory:(NSNumber *)arg1 ;
-(NSNumber *)purgeableMemory;
-(void)setPurgeableMemory:(NSNumber *)arg1 ;
-(NSNumber *)idleWakeups;
-(void)setIdleWakeups:(NSNumber *)arg1 ;
-(void)setIdleWakeupsDelta:(NSNumber *)arg1 ;
-(unsigned long long)procFlags;
-(void)setProcFlags:(unsigned long long)arg1 ;
-(NSNumber *)bytesWritten;
-(void)setBytesWritten:(NSNumber *)arg1 ;
-(NSNumber *)bytesWrittenDelta;
-(void)setBytesWrittenDelta:(NSNumber *)arg1 ;
-(void)setBytesRead:(NSNumber *)arg1 ;
-(NSNumber *)bytesReadDelta;
-(void)setBytesReadDelta:(NSNumber *)arg1 ;
-(NSNumber *)txBytes;
-(void)setTxBytes:(NSNumber *)arg1 ;
-(NSNumber *)rxBytes;
-(void)setRxBytes:(NSNumber *)arg1 ;
-(NSNumber *)txPackets;
-(void)setTxPackets:(NSNumber *)arg1 ;
-(NSNumber *)rxPackets;
-(void)setRxPackets:(NSNumber *)arg1 ;
-(NSNumber *)txBytesDelta;
-(void)setTxBytesDelta:(NSNumber *)arg1 ;
-(NSNumber *)rxBytesDelta;
-(void)setRxBytesDelta:(NSNumber *)arg1 ;
-(NSNumber *)txPacketsDelta;
-(void)setTxPacketsDelta:(NSNumber *)arg1 ;
-(NSNumber *)rxPacketsDelta;
-(void)setRxPacketsDelta:(NSNumber *)arg1 ;
-(void)setContextSwitchesDelta:(NSNumber *)arg1 ;
-(void)setFaultsDelta:(NSNumber *)arg1 ;
-(void)setMachCallsDelta:(NSNumber *)arg1 ;
-(void)setMsgsSentDelta:(NSNumber *)arg1 ;
-(void)setMsgsRcvdDelta:(NSNumber *)arg1 ;
-(void)setPortsDelta:(NSNumber *)arg1 ;
-(void)setThreadsDelta:(NSNumber *)arg1 ;
-(void)setPageInsDelta:(NSNumber *)arg1 ;
-(void)setUnixSyscallsDelta:(NSNumber *)arg1 ;
-(void)setResidentSizeDelta:(NSNumber *)arg1 ;
-(NSNumber *)anonymousMemoryDelta;
-(void)setAnonymousMemoryDelta:(NSNumber *)arg1 ;
-(NSNumber *)compressedMemoryDelta;
-(void)setCompressedMemoryDelta:(NSNumber *)arg1 ;
-(void)setVirtualSizeDelta:(NSNumber *)arg1 ;
-(void)setPrivateMemoryDelta:(NSNumber *)arg1 ;
-(void)setSharedMemoryDelta:(NSNumber *)arg1 ;
-(NSNumber *)purgeableMemoryDelta;
-(void)setPurgeableMemoryDelta:(NSNumber *)arg1 ;
-(unsigned long long)totalNanoSeconds;
-(void)setTotalNanoSeconds:(unsigned long long)arg1 ;
-(void)setCommand:(NSString *)arg1 ;
-(int)architecture;
-(NSString *)username;
-(void)setUsername:(NSString *)arg1 ;
-(void)setUpdated:(char)arg1 ;
-(NSNumber *)pid;
-(void)setPlaceholder:(char)arg1 ;
-(NSNumber *)bytesRead;
-(NSNumber *)ports;
-(NSNumber *)threads;
-(NSNumber *)ppid;
-(void)setPid:(NSNumber *)arg1 ;
-(char)isPlaceholder;
-(void)setProcessName:(NSString *)arg1 ;
-(void)setBundleIdentifier:(NSString *)arg1 ;
-(id)init;
-(void)dealloc;
-(id)description;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(void)setIcon:(NSImage *)arg1 ;
-(NSImage *)icon;
-(NSString *)bundleIdentifier;
-(NSString *)processName;
-(NSString *)executablePath;
-(NSString *)command;
-(NSNumber *)uid;
-(void)setUid:(NSNumber *)arg1 ;
-(char)isUpdated;
@end

