/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 1:23:02 PM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Keychain Access.app/Contents/MacOS/Keychain Access
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Keychain Access/Keychain Access-Structs.h>
@class NSWindow, KCAOutlineView, KeychainStore, NSTextField, PreviewController, NSMutableAttributedString, NSString, NSMutableArray, NSArray, StoreViewingAttributes, NSMenu, SFCertificateImportManager, NSEnumerator, SFKeychain;

@interface ItemListController : NSObject {

	NSWindow* _window;
	KCAOutlineView* _outlineView;
	KeychainStore* _store;
	NSTextField* _statusText;
	PreviewController* _previewController;
	NSMutableAttributedString* _attrString;
	id _category;
	id _searchField;
	id _infoButton;
	id _addItemButton;
	id _importAccessoryView;
	id _importAccessoryViewKeychains;
	id _exportAccessoryView;
	id _exportAccessoryViewFormat;
	NSString* _displayName;
	NSMutableArray* _selection;
	NSMutableArray* _draggedKeychainItems;
	NSArray* _certTypes;
	OpaqueSecKeychainRefRef _currentKeychainRef;
	StoreViewingAttributes* _viewingAttributes;
	NSMenu* _sortMenu;
	SFCertificateImportManager* _importMgr;
	NSEnumerator* _importFileNamesEnumerator;
	SFKeychain* _importKC;

}
+(id)certsForItems:(id)arg1 ;
+(id)sharedItemListController;
-(OpaqueSecKeychainRefRef)secKeychainRef;
-(void)setCurrentCategory:(id)arg1 refresh:(char)arg2 ;
-(void)refreshItems;
-(void)updateTableHeaderToMatchCurrentSort;
-(void)updatMenuToMatchCurrentSort;
-(void)doubleClickAction:(id)arg1 ;
-(void)_storeStructureChangedGlobalBroadcast;
-(void)focusSearch:(id)arg1 ;
-(void)newIdentityPrefItem:(id)arg1 ;
-(void)newCertificatePrefItem:(id)arg1 ;
-(char)canExport;
-(void)getInfo:(id)arg1 ;
-(id)keychainItems;
-(void)resetColumns;
-(void)hideDateModifiedColumn:(char)arg1 ;
-(void)hideExpiresColumn:(char)arg1 ;
-(void)updateAndRefresh;
-(id)currentCategory;
-(void)setKeychainStore:(id)arg1 ;
-(char)reloadStoreForCurrentKeychain;
-(void)updateSortAndItems;
-(void)_updateContextMenu;
-(void)_storeStructureChanged;
-(char)clipboardHasItems;
-(id)selectionAllLevels:(char)arg1 ;
-(char)_isInSearchContext;
-(id)displayNameForCurrentKeychain;
-(char)isPrivateKeySelected;
-(void)deleteItemsSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)toggleLock:(id)arg1 ;
-(void)exportFile:(id)arg1 ;
-(char)isPasswordOrNoteSelected;
-(char)isPublicKeySelected;
-(char)isCertSelected;
-(char)isSingleCertSelected;
-(id)_exportFilenameExtension;
-(void)_exportSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)import:(id)arg1 toKeychain:(id)arg2 ;
-(void)_importSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)_processImportFile:(id)arg1 toKeychain:(id)arg2 ;
-(id)_filesToImportFromInputArray:(id)arg1 ;
-(void)_didEndCertificate:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)newSecureNoteItem:(id)arg1 ;
-(void)newPasswordItem:(id)arg1 ;
-(char)isCertificatesCategorySelected;
-(char)isMyCertificatesCategorySelected;
-(char)isKeysCategorySelected;
-(void)_updateSearchAfterModification;
-(char)isKeyCategorySelected;
-(long long)sortOrderToColumnKey:(id)arg1 ;
-(void)sortByName:(id)arg1 ;
-(id)columnKeyToSortOrder:(long long)arg1 ;
-(void)setSortMenu:(id)arg1 ;
-(id)certTypes;
-(void)returnKeyPressed;
-(char)setCurrentKeychain:(OpaqueSecKeychainRefRef)arg1 displayName:(id)arg2 ;
-(id)getCurrentKeychain;
-(void)pasteDraggedItemsToKeychain:(OpaqueSecKeychainRefRef)arg1 cut:(char)arg2 ;
-(void)makeDefault:(id)arg1 ;
-(char)isIdentitySelected;
-(char)canCopyToClipboard;
-(char)selectedItemHasGoThere;
-(void)exportMenuItemHandler:(id)arg1 ;
-(void)sortAscending:(id)arg1 ;
-(void)sortDescending:(id)arg1 ;
-(void)sortByKind:(id)arg1 ;
-(void)sortByKeychain:(id)arg1 ;
-(void)sortByModDate:(id)arg1 ;
-(void)sortByExpirationDate:(id)arg1 ;
-(id)draggedItems;
-(id)store;
-(void)doSearch:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)copy:(id)arg1 ;
-(void)cut:(id)arg1 ;
-(void)paste:(id)arg1 ;
-(void)awakeFromNib;
-(void)addItem:(id)arg1 ;
-(void)delete:(id)arg1 ;
-(char)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3 ;
-(void)outlineView:(id)arg1 didClickTableColumn:(id)arg2 ;
-(void)outlineViewSelectionDidChange:(id)arg1 ;
-(long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2 ;
-(id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3 ;
-(char)outlineView:(id)arg1 isItemExpandable:(id)arg2 ;
-(id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3 ;
-(char)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3 ;
-(unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4 ;
-(char)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4 ;
-(id)outlineView:(id)arg1 namesOfPromisedFilesDroppedAtDestination:(id)arg2 forDraggedItems:(id)arg3 ;
-(id)selection;
-(char)hasSelection;
-(void)export:(id)arg1 ;
-(void)import:(id)arg1 ;
-(char)hasFocus;
@end

