/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 1:23:02 PM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Keychain Access.app/Contents/MacOS/Keychain Access
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol KCUserAgent
@required
+(char)currentlyOnMainThread;
-(void)makeObject:(id)arg1 performSelectorInMainThread:(SEL)arg2 withObject:(id)arg3;
-(void)makeObject:(id)arg1 performSelectorInMainThread:(SEL)arg2 withObject:(id)arg3 withObject:(id)arg4;
-(void)showThreadIsBusy;
-(void)doneBeingBusy;
-(char)isMainThreadBusy;
-(void)postNotificationInMainThread:(id)arg1;

@end

