/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 11:14:39 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/Console.app/Contents/MacOS/Console
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source;
@class NSString, NSObject;

@interface FileSystemWatcherNode : NSObject {

	char _needsFire;
	NSString* _path;
	NSObject*<OS_dispatch_queue> _volumeq;
	NSObject*<OS_dispatch_source> _source;
	FileSystemWatcherNode* _parent;
	NSObject*<OS_dispatch_source> _timer;

}

@property (retain) NSString * path;                                   //@synthesize path=_path - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> volumeq;              //@synthesize volumeq=_volumeq - In the implementation block
@property (retain) NSObject*<OS_dispatch_source> source;              //@synthesize source=_source - In the implementation block
@property (retain) FileSystemWatcherNode * parent;                    //@synthesize parent=_parent - In the implementation block
@property (retain) NSObject*<OS_dispatch_source> timer;               //@synthesize timer=_timer - In the implementation block
@property (assign) char needsFire;                                    //@synthesize needsFire=_needsFire - In the implementation block
-(NSObject*<OS_dispatch_queue>)volumeq;
-(void)setVolumeq:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)enableWatchingNode:(int)arg1 ;
-(void)enableWatchingForCreation;
-(void)disableWatchingForCreation;
-(void)disableWatchingNode;
-(void)parentNodeDidChange:(id)arg1 ;
-(void)setNeedsFire:(char)arg1 ;
-(char)needsFire;
-(NSObject*<OS_dispatch_source>)timer;
-(void)setTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)dealloc;
-(NSString *)path;
-(id)initWithPath:(id)arg1 ;
-(void)setPath:(NSString *)arg1 ;
-(NSObject*<OS_dispatch_source>)source;
-(void)setSource:(NSObject*<OS_dispatch_source>)arg1 ;
-(FileSystemWatcherNode *)parent;
-(void)setParent:(FileSystemWatcherNode *)arg1 ;
-(void)event;
@end

