/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:40:57 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Messages.app/Contents/MacOS/Messages
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Messages/Messages-Structs.h>
#import <AppKit/NSPanel.h>

@interface ARDHUDPanel : NSPanel {

	char _mouseIsDown;
	char _didPerformMove;

}
-(void)_finishWindowDrag;
-(void)sendEvent:(id)arg1 ;
-(char)canBecomeMainWindow;
-(char)canBecomeKeyWindow;
-(double)animationResizeTime:(CGRect)arg1 ;
@end

