/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:40:58 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Messages.app/Contents/MacOS/Messages
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Messages/FrameListener.h>

@class QCCompositionPickerPanel, Texture, NSString;

@interface EffectsPickerController : NSObject <FrameListener> {

	QCCompositionPickerPanel* _picker;
	Texture* _texture;
	char _isRunning;
	double _lastDeliveredFrameTime;
	unsigned long long _maxFPS;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)showEffectsPanel;
+(void)hideEffectsPanel;
+(char)isVisible;
-(void)stopVideo;
-(void)startVideo;
-(void)showEffectsPanel;
-(void)frameNotifier:(id)arg1 postedNewFrame:(id)arg2 ;
-(void)hideEffectsPanel;
-(void)_compositionBackdropChanged:(id)arg1 ;
-(void)_auxVideoControllerChanged:(id)arg1 ;
-(void)setMaxFPS:(unsigned long long)arg1 ;
-(void)_didEndFullScreen:(id)arg1 ;
-(id)_setPosterFrameForFile:(id)arg1 composition:(id)arg2 ;
-(id)_posterFrameForFile:(id)arg1 composition:(id)arg2 ;
-(unsigned long long)maxFPS;
-(id)init;
-(void)dealloc;
-(void)windowDidBecomeKey:(id)arg1 ;
-(char)isVisible;
-(void)windowWillClose:(id)arg1 ;
-(void)windowDidExpose:(id)arg1 ;
-(void)windowDidResignKey:(id)arg1 ;
-(void)compositionPickerView:(id)arg1 willSelectComposition:(id)arg2 ;
-(void)compositionPickerView:(id)arg1 didSelectComposition:(id)arg2 ;
-(void)compositionPickerView:(id)arg1 didLoadComposition:(id)arg2 ;
-(char)compositionPickerView:(id)arg1 keyDown:(id)arg2 ;
-(unsigned long long)compositionPickerView:(id)arg1 draggingEnteredComposition:(id)arg2 sender:(id)arg3 ;
-(char)compositionPickerView:(id)arg1 performDragOperationOnComposition:(id)arg2 sender:(id)arg3 ;
@end

