/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:40:57 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Messages.app/Contents/MacOS/Messages
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSActivityApplicationDelegate <NSApplicationDelegate>
@optional
-(void)application:(id)arg1 didRestoreActivity:(id)arg2 windows:(id)arg3;
-(char)application:(id)arg1 willSaveActivity:(id)arg2;
-(void)application:(id)arg1 restoreWindowForActivity:(id)arg2 identifier:(id)arg3 coder:(id)arg4 completionHandler:(/*^block*/id)arg5;
-(char)application:(id)arg1 openActivity:(id)arg2;

@end

