/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:40:57 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Messages.app/Contents/MacOS/Messages
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <IMCore/IMServiceImpl.h>

@class NSImage, NSArray;

@interface Service : IMServiceImpl {

	NSImage* _serviceIcon;
	NSArray* _defaultBuddyIcons;
	NSArray* _defaultBuddyImages;
	char _defaultBuddyIconChecked;
	char _serviceIconChecked;
	char _customCanonicalFormOfID;

}
+(void)daemonWillConnect:(id)arg1 ;
+(void)daemonDidConnect:(id)arg1 ;
+(void)daemonConnectionLost:(id)arg1 ;
+(void)disconnectAllServices;
+(id)allServices;
+(id)allServicesNonBlocking;
+(char)connectToDaemon;
+(void)initialize;
-(long long)compareNames:(id)arg1 ;
-(Class)accountClass;
-(void)dealloc;
-(id)icon;
@end

