/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:55:41 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Spotify.app/Contents/Resources/Libraries/Growl 1.3.1.framework/Growl
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Growl/GNTPOutgoingItem.h>

@class NSData;

@interface GrowlGNTPEncryptedHeaders : NSObject <GNTPOutgoingItem> {

	NSData* _headers;

}

@property (retain) NSData * headers;              //@synthesize headers=_headers - In the implementation block
+(id)headerItemFromData:(id)arg1 error:(id*)arg2 ;
-(id)GNTPRepresentationAsString;
-(id)GNTPRepresentation;
-(id)initForData:(id)arg1 error:(id*)arg2 ;
-(NSData *)headers;
-(void)setHeaders:(NSData *)arg1 ;
@end

