/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:05 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class Tile;

@interface DOCKInstallOperation : NSObject {

	Tile* _tile;
	Tile* _other;
	int _operation;

}

@property (nonatomic,readonly) Tile * tile;                //@synthesize tile=_tile - In the implementation block
@property (nonatomic,readonly) Tile * other;               //@synthesize other=_other - In the implementation block
@property (nonatomic,readonly) int operation;              //@synthesize operation=_operation - In the implementation block
-(id)initWithTile:(id)arg1 otherTile:(id)arg2 operation:(int)arg3 ;
-(Tile *)other;
-(int)operation;
-(Tile *)tile;
-(BOOL)perform;
@end

