/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Dock/Dock-Structs.h>
#import <Dock/Tile.h>
#import <Dock/DOCKStackActionHandling.h>
#import <Dock/DOCKStackExpandedDataSource.h>
#import <Dock/DOCKStackCollapsedDataSource.h>

@class DOCKStack, NSMutableArray, NSArray, NSString;

@interface DOCKScreenSharingTile : Tile <DOCKStackActionHandling, DOCKStackExpandedDataSource, DOCKStackCollapsedDataSource> {

	DOCKStack* _stack;
	NSMutableArray* _items;
	unsigned char _viewAs;
	int _preferredItemSize;
	NSArray* _sortedTypeAheadArray;
	char _ignoreNextDoAction;
	char _onlyShowBackToMyMac;
	SFBrowserRef _browser;

}

@property (assign,nonatomic) unsigned char viewAs;                              //@synthesize viewAs=_viewAs - In the implementation block
@property (assign,nonatomic) int preferredItemSize;                             //@synthesize preferredItemSize=_preferredItemSize - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) const char* messageTracerStackType; 
-(char)doAction:(unsigned)arg1 fromKeyboard:(char)arg2 ;
-(OpaqueMenuRefRef)createMenu:(/*function pointer*/void*)arg1 options:(int)arg2 ;
-(CFArrayRef)axCopyAttributeNames;
-(char)showMenu:(char)arg1 options:(int)arg2 ;
-(BOOL)allowsForcedSpringing;
-(void)spring:(unsigned)arg1 ;
-(id)copyTilePlist;
-(void)collapseStack;
-(int)preferredItemSize;
-(void)setPreferredItemSize:(int)arg1 ;
-(id)copyInstallDictionary:(int)arg1 ;
-(int)axCopyAttributeValue:(CFStringRef)arg1 value:(const void*)arg2 ;
-(id)initWithPlist:(id)arg1 ;
-(void)setViewAs:(unsigned char)arg1 ;
-(id)initWithBackToMyMac:(char)arg1 ;
-(const char*)messageTracerStackType;
-(char)performStackActionAtIndex:(unsigned long long)arg1 withEvent:(id)arg2 sender:(id)arg3 ;
-(void)beginStackTypeAhead:(id)arg1 ;
-(unsigned long long)indexForStackTypeAhead:(id)arg1 ;
-(void)endStackTypeAhead;
-(void)showStackAsMenu:(char)arg1 ;
-(unsigned long long)numberOfExpandedStackItems;
-(id)expandedStackValueForKey:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3 maximumViewableItems:(unsigned long long)arg4 ;
-(id)expandedStackValueForKey:(id)arg1 withInfo:(id)arg2 ;
-(unsigned long long)numberOfCollapsedStackItems;
-(id)collapsedStackValueForKey:(id)arg1 atIndex:(unsigned long long)arg2 ;
-(unsigned char)viewAs;
-(void)_itemsUpdated;
-(void)_browserCallback:(SFBrowserRef)arg1 node:(SFNodeRef)arg2 protocol:(CFStringRef)arg3 error:(int)arg4 ;
-(void)doCommand:(unsigned)arg1 ;
-(id)stack;
-(void)dealloc;
-(id)typeString;
@end

