/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:05 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface DOCKRecentsModel : NSObject {

	id _icon;
	NSString* _displayName;
	id _item;

}

@property (nonatomic,readonly) id icon;                             //@synthesize icon=_icon - In the implementation block
@property (nonatomic,readonly) NSString * displayName;              //@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,readonly) id item;                             //@synthesize item=_item - In the implementation block
-(id)icon;
-(long long)compare:(id)arg1 ;
-(NSString *)displayName;
-(id)initWithSharedFileListItem:(id)arg1 ;
-(id)item;
@end

