/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:05 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ECBezelIconList <NSObject>
@required
-(void)bezelIconListCancel:(id)arg1;
-(void)bezelIconList:(id)arg1 performActionAtIndex:(unsigned long long)arg2;
-(void)bezelIconList:(id)arg1 handleKeyboardEvent:(id)arg2;
-(BOOL)bezelIconList:(id)arg1 itemSelectedAtIndex:(unsigned long long)arg2 forDrag:(OpaqueCoreDrag*)arg3;
-(BOOL)bezelIconList:(id)arg1 itemDroppedAtIndex:(unsigned long long)arg2 forDrag:(OpaqueCoreDrag*)arg3;
-(void)bezelIconList:(id)arg1 itemSelectedAtIndex:(unsigned long long)arg2;

@end

