/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <QuartzCore/CALayer.h>
#import <Dock/ECEventHandlingDelegate.h>

@class ECPager, NSMutableArray, NSArray, NSString;

@interface ECPagerControlLayer : CALayer <ECEventHandlingDelegate> {

	ECPager* _pager;
	NSMutableArray* _indicatorLayers;

}

@property (nonatomic,readonly) NSArray * indicatorLayers;              //@synthesize indicatorLayers=_indicatorLayers - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)leftMouseUp:(id)arg1 inLayer:(id)arg2 ;
-(char)leftMouseDown:(id)arg1 inLayer:(id)arg2 ;
-(char)leftMouseDragged:(id)arg1 inLayer:(id)arg2 ;
-(id)initWithPager:(id)arg1 ;
-(NSArray *)indicatorLayers;
-(void)layout;
@end

