/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Dock/ECPagerLayer.h>

@class ECSBGroup, ECSBLabelLayer, CALayer;

@interface ECSBGroupLayer : ECPagerLayer {

	ECSBGroup* _group;
	ECSBLabelLayer* _labelLayer;
	CALayer* _labelEditLayer;
	CALayer* _backdropLayer;
	CALayer* _tintLayer;
	CALayer* _maskLayer;
	CALayer* _maskContainerLayer;
	unsigned long long _numberOfColumns;
	unsigned long long _numberOfRows;
	unsigned _leftMouseDown : 1;
	unsigned _leftKeyDownHandled : 1;
	unsigned _mouseDragged : 1;
	unsigned _mouseDownOutsideGroup : 1;

}

@property (nonatomic,__weak,readonly) ECSBGroup * group;                        //@synthesize group=_group - In the implementation block
@property (nonatomic,readonly) ECSBLabelLayer * labelLayer;                     //@synthesize labelLayer=_labelLayer - In the implementation block
@property (nonatomic,readonly) CALayer * backdropLayer;                         //@synthesize backdropLayer=_backdropLayer - In the implementation block
@property (nonatomic,readonly) CALayer * labelEditLayer;                        //@synthesize labelEditLayer=_labelEditLayer - In the implementation block
@property (nonatomic,readonly) unsigned long long numberOfColumns;              //@synthesize numberOfColumns=_numberOfColumns - In the implementation block
@property (nonatomic,readonly) unsigned long long numberOfRows;                 //@synthesize numberOfRows=_numberOfRows - In the implementation block
-(id)initWithGroup:(id)arg1 groupPager:(id)arg2 ;
-(char)leftMouseDown:(id)arg1 ;
-(char)leftMouseUp:(id)arg1 ;
-(char)leftMouseDragged:(id)arg1 ;
-(char)gesture:(id)arg1 ;
-(CALayer *)labelEditLayer;
-(void)_showPagerElements:(BOOL)arg1 ;
-(void)_showItemElements:(BOOL)arg1 ;
-(void)_minimizePagerElements;
-(void)_minimizeItemLayers;
-(void)_removeItemLayerFilters;
-(void)_showItemLayers;
-(void)prepareForAnimatedShow;
-(void)animatedShow;
-(void)prepareForAnimatedHide;
-(void)animatedHide;
-(ECSBGroup *)group;
-(ECSBLabelLayer *)labelLayer;
-(void)layout;
-(unsigned long long)numberOfRows;
-(char)scrollWheel:(id)arg1 ;
-(unsigned long long)numberOfColumns;
-(CALayer *)backdropLayer;
@end

