/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Dock/ECSBItem.h>

@class NSMutableArray;

@interface ECSBContainerItem : ECSBItem {

	NSMutableArray* _items;

}

@property (nonatomic,retain) NSMutableArray * items;                          //@synthesize items=_items - In the implementation block
@property (nonatomic,readonly) unsigned long long numberOfItems; 
-(void)moveItem:(id)arg1 toIndex:(unsigned long long)arg2 ;
-(id)itemForClientItem:(id)arg1 ;
-(void)setItems:(NSMutableArray *)arg1 ;
-(id)init;
-(unsigned long long)numberOfItems;
-(unsigned long long)indexOfItem:(id)arg1 ;
-(void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2 ;
-(id)itemAtIndex:(unsigned long long)arg1 ;
-(NSMutableArray *)items;
-(void)addItem:(id)arg1 ;
-(void)removeItem:(id)arg1 ;
@end

