/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:06 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ECSBDataSource <NSObject>
@required
-(void)setValue:(id)arg1 forKey:(id)arg2 ofItem:(id)arg3;
-(id)valueForKey:(id)arg1 ofItem:(id)arg2 withInfo:(id)arg3;

@end

