/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 7:58:07 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Users/joris/Desktop/SysDecrypts/64-Bit/Dock
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray, NSString, NSArray;

@interface LPStorageTransaction : NSObject {

	NSMutableArray* _blocks;
	NSString* _uuid;
	int _dbref;

}

@property (nonatomic,readonly) int dbref;                     //@synthesize dbref=_dbref - In the implementation block
@property (nonatomic,readonly) NSString * uuid;               //@synthesize uuid=_uuid - In the implementation block
@property (nonatomic,readonly) NSArray * blocks;              //@synthesize blocks=_blocks - In the implementation block
-(id)initWithDatabaseReference:(int)arg1 ;
-(int)dbref;
-(NSArray *)blocks;
-(NSString *)uuid;
-(void)addBlock:(/*^block*/id)arg1 ;
@end

