/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:33:50 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Font Book.app/Contents/MacOS/Font Book
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Font Book/Font Book-Structs.h>
#import <Font Book/FBLockingObject.h>
#import <Font Book/NSCopying.h>
#import <Font Book/NSCoding.h>

@class NSURL, FBUniqueString, NSArray, NSString;

@interface FBFile : FBLockingObject <NSCopying, NSCoding> {

	NSURL* _url;
	FBUniqueString* _searchContent;
	char _typeDetermined;
	char _isLWFN;
	char _isFFIL;
	NSArray* _LWFNFiles;
	FBFile* _associatedFFIL;
	long long domain;

}

@property (assign) long long domain; 
@property (retain,readonly) NSString * name; 
@property (retain,readonly) NSString * path; 
@property (retain,readonly) NSString * extension; 
@property (retain,readonly) NSURL * url; 
@property (readonly) char isFFIL; 
@property (readonly) char isLWFN; 
@property (retain,readonly) FBFile * associatedFFIL; 
+(int)domainForURL:(id)arg1 ;
+(id)fileWithURL:(id)arg1 ;
+(id)facesWithFiles:(id)arg1 ;
+(char)isURLofTypeLWFN:(id)arg1 ;
+(id)installableFilesForArray:(id)arg1 ;
+(void)moveFilesToTrash:(id)arg1 ;
+(void)showFilesInFinder:(id)arg1 ;
+(int)domainForContainer:(id)arg1 ;
+(id)_systemFontsURL;
+(id)_autoActivationFontsURL;
+(id)_localFontsURL;
+(id)_networkFontsURL;
+(id)_userFontsURL;
+(id)_bundleURL;
+(char)isURLofTypeFFIL:(id)arg1 ;
+(id)_lwfnFilesForFFILURL:(id)arg1 ;
+(id)lwfnFilesForFFILURL:(id)arg1 ;
+(id)associatedFFILsForURL:(id)arg1 ;
+(char)isFontURL:(id)arg1 ;
+(id)filesInDir:(id)arg1 ;
+(id)associatedFFILForURL:(id)arg1 ;
+(id)domainURLs;
+(char)_isURLWithLWFNs:(id)arg1 ;
+(void)clearCacheEntryforURL:(id)arg1 ;
+(void)resetLWFNCache;
+(id)_fontsFolderInDomain:(unsigned long long)arg1 ;
+(char)_isURL:(id)arg1 ofType:(unsigned)arg2 ;
+(id)fileWithPath:(id)arg1 ;
+(void)initialize;
+(id)_hfsTypeAsStringFromURL:(id)arg1 ;
-(char)isLWFN;
-(char)isInstallable;
-(void)setSearchContent:(id)arg1 ;
-(FBFile *)associatedFFIL;
-(id)fontFiles:(char)arg1 ;
-(char)isFFIL;
-(id)searchableContent;
-(id)lwfnFiles;
-(id)filesWithExtension:(id)arg1 ;
-(id)appleScriptID;
-(id)appleScriptName;
-(id)appleScriptLocalizedName;
-(id)appleScriptFiles;
-(id)applescriptDescription;
-(id)appleScriptFaces;
-(id)appleScriptFamilies;
-(id)appleScriptDomains;
-(char)isFontFile;
-(char)isInstalledFontFile;
-(id)_copyToFile:(id)arg1 ;
-(id)copiedFontFile:(id)arg1 ;
-(id)_uniqueFontFiles;
-(void)_determineFileType;
-(id)copyToFile:(id)arg1 ;
-(id)subDirectories;
-(void)_warnOfUninstallableFontFile:(id)arg1 ;
-(void)_warnOfInaccessibleFontFile:(id)arg1 ;
-(void)setDomain:(long long)arg1 ;
-(char)isProtected;
-(id)faces;
-(NSString *)extension;
-(void)dealloc;
-(id)description;
-(NSString *)path;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSURL *)url;
-(NSString *)name;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)domain;
-(id)objectSpecifier;
-(long long)compare:(id)arg1 ;
-(void)remove;
-(id)initWithURL:(id)arg1 ;
-(char)isDirectory;
-(id)parent;
-(void)moveToTrash;
@end

