/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:33:50 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Font Book.app/Contents/MacOS/Font Book
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Font Book/Font Book-Structs.h>
#import <AppKit/NSWindowController.h>
#import <Font Book/NSToolbarDelegate.h>
#import <Font Book/NSAnimationDelegate.h>

@protocol FBPluginProtocol;
@class NSArray, NSSpeechSynthesizer, FBFontViewController, FBCollectionViewController, FBMultiPreviewController, FBDuplicateResolutionWindowController, FBProgressWindowController, FBPrintController, NSMenu, FBBackgroundView, NSBox, NSSplitView, NSToolbar, NSSegmentedControl, FBSearchController, NSToolbarItem, NSButton, NSWindow, NSTextField, NSPredicateEditor, FBSmartCollection, FBLanguagePicker, NSUndoManager, NSString, FBGroup, NSDrawer, NSView, NSResponder, NSPrintOperation, NSMutableArray, NSTimer, NSNumberFormatter, NSImage;

@interface FBUIController : NSWindowController <NSToolbarDelegate, NSAnimationDelegate> {

	NSArray* _smartCollectionSheetTopObjects;
	NSSpeechSynthesizer* _speechSynthesizer;
	char _isChangingFullScreenMode;
	char _canChangePreviewType;
	char _canChangeLanguage;
	char _accessAppleInternalFeatures;
	char _isCollapsingPreview;
	char _isAnimatingWindowResize;
	char _didAwakeFromNib;
	char _isCollapsing;
	char _isAnimating;
	FBFontViewController* _fontController;
	FBCollectionViewController* _collectionController;
	FBMultiPreviewController* _previewController;
	FBDuplicateResolutionWindowController* _duplicatePanelController;
	FBProgressWindowController* _progressWindowController;
	FBPrintController* _printController;
	NSMenu* _collectionContextMenu;
	NSMenu* _fontContextMenu;
	FBBackgroundView* _mainBackgroundView;
	NSBox* _mainSplitViewContainer;
	NSSplitView* _mainSplitView;
	NSToolbar* _toolbar;
	NSSegmentedControl* _setPreviewTypeControl;
	NSMenu* _searchPopupMenu;
	FBSearchController* _searchController;
	NSToolbarItem* _searchFieldItem;
	NSBox* _collectionControlsGroup;
	NSButton* _collectionAddButton;
	NSButton* _fontAddButton;
	NSButton* _enableDisableFontsButton;
	NSWindow* _editSmartCollectionSheet;
	NSTextField* _selectedSmartCollectionNameField;
	NSPredicateEditor* _predicateEditor;
	FBSmartCollection* _smartCollectionToEdit;
	FBLanguagePicker* _languagesSubmenu;
	NSUndoManager* _undoManager;
	double _previewWidth;
	NSString* _previewStatus;
	FBGroup* _installationDestination;
	NSArray* _objectsToProcess;
	id<FBPluginProtocol> _plugin;
	NSDrawer* _drawer;
	NSView* _savedPreviewView;
	double _savedPreviewWidth;
	NSResponder* _scratchResponder;
	NSPrintOperation* _printOperation;
	NSMutableArray* _inaccessibleFiles;
	NSMutableArray* _postScriptNameFreeFiles;
	NSMutableArray* _uninstallableFontFiles;
	NSTimer* _waitingForDataTimer;
	unsigned long long _resizingMask;
	id _storedFirstResponder;
	NSNumberFormatter* _formatter;

}

@property (assign) char allowSpokenAnnouncements; 
@property (assign) char showLockedFonts; 
@property (assign) char useAlternateDomainNames; 
@property (assign) char showAdditionalFontInfo; 
@property (assign) char showFontUse; 
@property (assign) char useNewUI; 
@property (assign) char showLanguageCodes; 
@property (assign) char fullValidatorReports; 
@property (assign) char allValidatorTests; 
@property (assign) FBFontViewController * fontController;                                         //@synthesize fontController=_fontController - In the implementation block
@property (assign) FBCollectionViewController * collectionController;                             //@synthesize collectionController=_collectionController - In the implementation block
@property (assign) FBMultiPreviewController * previewController;                                  //@synthesize previewController=_previewController - In the implementation block
@property (assign) FBDuplicateResolutionWindowController * duplicatePanelController;              //@synthesize duplicatePanelController=_duplicatePanelController - In the implementation block
@property (assign) FBProgressWindowController * progressWindowController;                         //@synthesize progressWindowController=_progressWindowController - In the implementation block
@property (assign) FBPrintController * printController;                                           //@synthesize printController=_printController - In the implementation block
@property (assign) NSMenu * collectionContextMenu;                                                //@synthesize collectionContextMenu=_collectionContextMenu - In the implementation block
@property (assign) NSMenu * fontContextMenu;                                                      //@synthesize fontContextMenu=_fontContextMenu - In the implementation block
@property (assign) FBBackgroundView * mainBackgroundView;                                         //@synthesize mainBackgroundView=_mainBackgroundView - In the implementation block
@property (assign) NSBox * mainSplitViewContainer;                                                //@synthesize mainSplitViewContainer=_mainSplitViewContainer - In the implementation block
@property (assign) NSSplitView * mainSplitView;                                                   //@synthesize mainSplitView=_mainSplitView - In the implementation block
@property (assign) NSToolbar * toolbar;                                                           //@synthesize toolbar=_toolbar - In the implementation block
@property (assign) NSSegmentedControl * setPreviewTypeControl;                                    //@synthesize setPreviewTypeControl=_setPreviewTypeControl - In the implementation block
@property (assign) NSMenu * searchPopupMenu;                                                      //@synthesize searchPopupMenu=_searchPopupMenu - In the implementation block
@property (assign) FBSearchController * searchController;                                         //@synthesize searchController=_searchController - In the implementation block
@property (assign) NSToolbarItem * searchFieldItem;                                               //@synthesize searchFieldItem=_searchFieldItem - In the implementation block
@property (assign) NSBox * collectionControlsGroup;                                               //@synthesize collectionControlsGroup=_collectionControlsGroup - In the implementation block
@property (assign) NSButton * collectionAddButton;                                                //@synthesize collectionAddButton=_collectionAddButton - In the implementation block
@property (assign) NSButton * fontAddButton;                                                      //@synthesize fontAddButton=_fontAddButton - In the implementation block
@property (assign) NSButton * enableDisableFontsButton;                                           //@synthesize enableDisableFontsButton=_enableDisableFontsButton - In the implementation block
@property (assign) NSWindow * editSmartCollectionSheet;                                           //@synthesize editSmartCollectionSheet=_editSmartCollectionSheet - In the implementation block
@property (assign) NSTextField * selectedSmartCollectionNameField;                                //@synthesize selectedSmartCollectionNameField=_selectedSmartCollectionNameField - In the implementation block
@property (assign) NSPredicateEditor * predicateEditor;                                           //@synthesize predicateEditor=_predicateEditor - In the implementation block
@property (assign) FBSmartCollection * smartCollectionToEdit;                                     //@synthesize smartCollectionToEdit=_smartCollectionToEdit - In the implementation block
@property (assign) FBLanguagePicker * languagesSubmenu;                                           //@synthesize languagesSubmenu=_languagesSubmenu - In the implementation block
@property (assign) NSUndoManager * undoManager;                                                   //@synthesize undoManager=_undoManager - In the implementation block
@property (assign) char isChangingFullScreenMode;                                                 //@synthesize isChangingFullScreenMode=_isChangingFullScreenMode - In the implementation block
@property (assign) char canChangePreviewType;                                                     //@synthesize canChangePreviewType=_canChangePreviewType - In the implementation block
@property (assign) char canChangeLanguage;                                                        //@synthesize canChangeLanguage=_canChangeLanguage - In the implementation block
@property (readonly) char allPreviewModesAvailable; 
@property (assign) char previewHidden; 
@property (assign) double previewWidth;                                                           //@synthesize previewWidth=_previewWidth - In the implementation block
@property (copy) NSString * previewStatus;                                                        //@synthesize previewStatus=_previewStatus - In the implementation block
@property (copy,readonly) NSString * currentSampleLanguage; 
@property (retain,readonly) NSArray * selectedFonts; 
@property (retain,readonly) NSArray * selectedFaces; 
@property (retain,readonly) NSArray * selectedFamilies; 
@property (retain,readonly) NSArray * selectedCollections; 
@property (retain) FBGroup * installationDestination;                                             //@synthesize installationDestination=_installationDestination - In the implementation block
@property (copy) NSArray * objectsToProcess;                                                      //@synthesize objectsToProcess=_objectsToProcess - In the implementation block
@property (assign) char accessAppleInternalFeatures;                                              //@synthesize accessAppleInternalFeatures=_accessAppleInternalFeatures - In the implementation block
@property (retain) id<FBPluginProtocol> plugin;                                                   //@synthesize plugin=_plugin - In the implementation block
@property (retain) NSDrawer * drawer;                                                             //@synthesize drawer=_drawer - In the implementation block
@property (assign) NSView * savedPreviewView;                                                     //@synthesize savedPreviewView=_savedPreviewView - In the implementation block
@property (assign) double savedPreviewWidth;                                                      //@synthesize savedPreviewWidth=_savedPreviewWidth - In the implementation block
@property (assign) char isCollapsingPreview;                                                      //@synthesize isCollapsingPreview=_isCollapsingPreview - In the implementation block
@property (assign) char isAnimatingWindowResize;                                                  //@synthesize isAnimatingWindowResize=_isAnimatingWindowResize - In the implementation block
@property (assign) NSResponder * scratchResponder;                                                //@synthesize scratchResponder=_scratchResponder - In the implementation block
@property (assign) NSPrintOperation * printOperation;                                             //@synthesize printOperation=_printOperation - In the implementation block
@property (assign) NSMutableArray * inaccessibleFiles;                                            //@synthesize inaccessibleFiles=_inaccessibleFiles - In the implementation block
@property (assign) NSMutableArray * postScriptNameFreeFiles;                                      //@synthesize postScriptNameFreeFiles=_postScriptNameFreeFiles - In the implementation block
@property (assign) NSMutableArray * uninstallableFontFiles;                                       //@synthesize uninstallableFontFiles=_uninstallableFontFiles - In the implementation block
@property (assign) char didAwakeFromNib;                                                          //@synthesize didAwakeFromNib=_didAwakeFromNib - In the implementation block
@property (assign) NSTimer * waitingForDataTimer;                                                 //@synthesize waitingForDataTimer=_waitingForDataTimer - In the implementation block
@property (assign) char isCollapsing;                                                             //@synthesize isCollapsing=_isCollapsing - In the implementation block
@property (assign) char isAnimating;                                                              //@synthesize isAnimating=_isAnimating - In the implementation block
@property (assign) unsigned long long resizingMask;                                               //@synthesize resizingMask=_resizingMask - In the implementation block
@property (assign) double hideDelta; 
@property (assign) id storedFirstResponder;                                                       //@synthesize storedFirstResponder=_storedFirstResponder - In the implementation block
@property (retain) NSNumberFormatter * formatter;                                                 //@synthesize formatter=_formatter - In the implementation block
@property (retain,readonly) NSImage * lockImageForCurrentFace; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)warningImageScaledToHeight:(double)arg1 ;
+(id)windowKeyBackgroundColor;
+(id)windowNotKeyBackgroundColor;
+(id)uiController;
+(void)initialize;
-(void)disableFonts:(id)arg1 ;
-(void)enableFonts:(id)arg1 ;
-(char)allowSpokenAnnouncements;
-(void)_speakText:(id)arg1 ;
-(void)addLibrary:(id)arg1 ;
-(char)showLockedFonts;
-(FBCollectionViewController *)collectionController;
-(void)showPreviewWindowForFace:(id)arg1 ;
-(void)removeFonts:(id)arg1 ;
-(void)previewFonts:(id)arg1 ;
-(NSArray *)selectedFaces;
-(char)didAwakeFromNib;
-(void)addCollectionOrSmartCollection:(id)arg1 ;
-(NSButton *)collectionAddButton;
-(void)setCollectionAddButton:(NSButton *)arg1 ;
-(void)selectGroup:(id)arg1 edit:(char)arg2 ;
-(void)resolveDuplicatesWithSelectedFaces:(id)arg1 ;
-(void)_resolveSelectedDuplicatesAutomatically;
-(char)useNewUI;
-(void)setUseNewUI:(char)arg1 ;
-(char)previewHidden;
-(NSString *)currentSampleLanguage;
-(void)setCanChangeLanguage:(char)arg1 ;
-(void)disableGroups:(id)arg1 ;
-(void)enableGroups:(id)arg1 ;
-(char)showAdditionalFontInfo;
-(char)showLanguageCodes;
-(void)selectFamiliesAndFaces:(id)arg1 andOpenPreview:(char)arg2 ;
-(void)savePersistentInfo;
-(void)applicationDidFinishLaunching;
-(void)selfTestIterateCollections;
-(void)selfTestSearchPerformance:(long long)arg1 ;
-(void)selfTestIterateAllFontsPerformance:(long long)arg1 ;
-(void)setInstallationDestination:(FBGroup *)arg1 ;
-(void)setObjectsToProcess:(NSArray *)arg1 ;
-(void)setInaccessibleFiles:(NSMutableArray *)arg1 ;
-(void)setUninstallableFontFiles:(NSMutableArray *)arg1 ;
-(void)setPostScriptNameFreeFiles:(NSMutableArray *)arg1 ;
-(id)_accessAppleInternalFeatures;
-(id)_appleInternalPrefSet;
-(void)setAccessAppleInternalFeatures:(char)arg1 ;
-(FBGroup *)installationDestination;
-(NSArray *)objectsToProcess;
-(FBPrintController *)printController;
-(NSPrintOperation *)printOperation;
-(NSMutableArray *)inaccessibleFiles;
-(NSMutableArray *)postScriptNameFreeFiles;
-(NSMutableArray *)uninstallableFontFiles;
-(NSTimer *)waitingForDataTimer;
-(NSSegmentedControl *)setPreviewTypeControl;
-(NSSplitView *)mainSplitView;
-(NSButton *)enableDisableFontsButton;
-(NSButton *)fontAddButton;
-(void)_inaccessibleFileEncountered:(id)arg1 ;
-(void)_setupSmartCollectionsPredicateEditor;
-(NSToolbarItem *)searchFieldItem;
-(void)setDidAwakeFromNib:(char)arg1 ;
-(NSMenu *)collectionContextMenu;
-(FBFontViewController *)fontController;
-(NSMenu *)fontContextMenu;
-(void)setIsChangingFullScreenMode:(char)arg1 ;
-(NSDrawer *)drawer;
-(void)setSmartCollectionToEdit:(FBSmartCollection *)arg1 ;
-(NSTextField *)selectedSmartCollectionNameField;
-(NSPredicateEditor *)predicateEditor;
-(NSWindow *)editSmartCollectionSheet;
-(void)_smartCollectionAddAndEditDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)_smartCollectionEditDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)setPreviewStatus:(NSString *)arg1 ;
-(void)_updateStatusBar:(id)arg1 ;
-(void)setIsAnimatingWindowResize:(char)arg1 ;
-(void)setIsCollapsingPreview:(char)arg1 ;
-(void)setCollectionController:(FBCollectionViewController *)arg1 ;
-(void)_addController:(id)arg1 toView:(id)arg2 ;
-(void)setFontController:(FBFontViewController *)arg1 ;
-(FBMultiPreviewController *)previewController;
-(void)setPreviewController:(FBMultiPreviewController *)arg1 ;
-(FBDuplicateResolutionWindowController *)duplicatePanelController;
-(void)setDuplicatePanelController:(FBDuplicateResolutionWindowController *)arg1 ;
-(void)_buildCollapsedConstraintsForPreview;
-(void)_buildExpandedConstraintsForPreview;
-(char)accessAppleInternalFeatures;
-(void)_extendedSamplesChanged:(id)arg1 ;
-(void)_downloadFailed:(id)arg1 ;
-(void)_doDuplicateResolutionOfFace:(id)arg1 ;
-(void)_resolveDuplicatesManually:(id)arg1 ;
-(void)_postScriptNameFreeFileEncountered:(id)arg1 ;
-(void)_couldNotInstallFont:(id)arg1 ;
-(void)_warnOfUninstalledFonts:(id)arg1 ;
-(void)_modelDidInitialize:(id)arg1 ;
-(void)_selectGroup:(id)arg1 ;
-(void)_selectGroupWithoutEdit:(id)arg1 ;
-(void)_startWaitingForData:(id)arg1 ;
-(void)_validateFiles:(id)arg1 ;
-(void)updatePreviewStatus:(id)arg1 ;
-(void)operationDidStart:(id)arg1 ;
-(void)operationWillEnd:(id)arg1 ;
-(void)selectedFontItemsDidChange:(id)arg1 ;
-(void)_previewModeDidChange:(id)arg1 ;
-(void)_enableSearchField:(id)arg1 ;
-(void)_addFontsToGroup:(id)arg1 ;
-(void)_localeDidChange:(id)arg1 ;
-(void)_addHiddenMenuItems;
-(void)_loadPlugin;
-(void)setStoredFirstResponder:(id)arg1 ;
-(void)showBusy:(char)arg1 ;
-(void)resumeSuspendedAppleEvents;
-(NSArray *)selectedFonts;
-(NSArray *)selectedCollections;
-(void)setCanChangePreviewType:(char)arg1 ;
-(id)filteredDescriptor:(id)arg1 ;
-(id)getContextMenu;
-(void)selectLastSelectedFamily;
-(void)updateWindowMinSize;
-(void)doSmartCollectionAddAndEdit:(id)arg1 ;
-(void)doSmartCollectionEdit:(id)arg1 ;
-(NSImage *)lockImageForCurrentFace;
-(char)allPreviewModesAvailable;
-(void)setPreviewPaneHidden:(char)arg1 display:(char)arg2 ;
-(void)switchToInfoMode;
-(void)selectLibrary:(id)arg1 edit:(char)arg2 ;
-(void)setPreviewHidden:(char)arg1 ;
-(double)hideDelta;
-(void)setHideDelta:(double)arg1 ;
-(char)suspendAppleEventIfBusy;
-(NSArray *)selectedFamilies;
-(id)selectedSmartCollection;
-(void)disableFontArray:(id)arg1 ;
-(void)setProgressWindowController:(FBProgressWindowController *)arg1 ;
-(void)setPrintController:(FBPrintController *)arg1 ;
-(void)setCollectionContextMenu:(NSMenu *)arg1 ;
-(void)setFontContextMenu:(NSMenu *)arg1 ;
-(FBBackgroundView *)mainBackgroundView;
-(void)setMainBackgroundView:(FBBackgroundView *)arg1 ;
-(NSBox *)mainSplitViewContainer;
-(void)setMainSplitViewContainer:(NSBox *)arg1 ;
-(void)setMainSplitView:(NSSplitView *)arg1 ;
-(void)setSetPreviewTypeControl:(NSSegmentedControl *)arg1 ;
-(NSMenu *)searchPopupMenu;
-(void)setSearchPopupMenu:(NSMenu *)arg1 ;
-(void)setSearchFieldItem:(NSToolbarItem *)arg1 ;
-(NSBox *)collectionControlsGroup;
-(void)setCollectionControlsGroup:(NSBox *)arg1 ;
-(void)setFontAddButton:(NSButton *)arg1 ;
-(void)setEnableDisableFontsButton:(NSButton *)arg1 ;
-(void)setEditSmartCollectionSheet:(NSWindow *)arg1 ;
-(void)setSelectedSmartCollectionNameField:(NSTextField *)arg1 ;
-(void)setPredicateEditor:(NSPredicateEditor *)arg1 ;
-(FBSmartCollection *)smartCollectionToEdit;
-(FBLanguagePicker *)languagesSubmenu;
-(void)setLanguagesSubmenu:(FBLanguagePicker *)arg1 ;
-(char)isChangingFullScreenMode;
-(char)canChangePreviewType;
-(char)canChangeLanguage;
-(double)previewWidth;
-(void)setPreviewWidth:(double)arg1 ;
-(NSString *)previewStatus;
-(void)setDrawer:(NSDrawer *)arg1 ;
-(NSView *)savedPreviewView;
-(void)setSavedPreviewView:(NSView *)arg1 ;
-(double)savedPreviewWidth;
-(void)setSavedPreviewWidth:(double)arg1 ;
-(char)isCollapsingPreview;
-(char)isAnimatingWindowResize;
-(NSResponder *)scratchResponder;
-(void)setScratchResponder:(NSResponder *)arg1 ;
-(void)setPrintOperation:(NSPrintOperation *)arg1 ;
-(void)setWaitingForDataTimer:(NSTimer *)arg1 ;
-(void)setIsCollapsing:(char)arg1 ;
-(id)storedFirstResponder;
-(void)_addFiles:(id)arg1 toGroup:(id)arg2 ;
-(void)_addActivatedFontsToGroup:(id)arg1 ;
-(void)_makeChangesToSelectedSmartCollection;
-(void)_stopWaitingForData:(id)arg1 ;
-(void)_resolveDuplicatesDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)_resolveDuplicatedFaces:(id)arg1 warnIfMovingToTrash:(char)arg2 ;
-(void)_activateFontsAndAddToGroup:(id)arg1 ;
-(char)_isProcessingObjects;
-(void)_abortLengthyOperation;
-(void)_warnOfInaccessibleFiles;
-(void)_warnOfPostScriptNameFreeFiles;
-(char)_checkFamily:(id)arg1 forFile:(id)arg2 ;
-(void)_updateLanguagesMenu:(id)arg1 ;
-(void)DEBUGDumpWindowView:(id)arg1 ;
-(void)DEBUGDumpWindowViewConstraints:(id)arg1 ;
-(void)DEBUGDumpWindowViewSubtreeDescription:(id)arg1 ;
-(void)_toggleAllowSpokenAnnouncements;
-(void)_toggleShowLockedFonts;
-(void)_toggleUseAlternateDomainNames;
-(char)useAlternateDomainNames;
-(void)_toggleShowAdditionalFontInfo;
-(void)_toggleShowFontUse;
-(char)showFontUse;
-(void)_toggleUseNewUI;
-(void)_toggleShowLanguageCodes;
-(void)_toggleFullValidatorReports;
-(char)fullValidatorReports;
-(void)_toggleAllValidatorTests;
-(char)allValidatorTests;
-(id)_appleInternalPrefPath;
-(void)appleInternalSetValue:(id)arg1 forKey:(id)arg2 ;
-(void)_toggleAppleInternalPref;
-(void)_removeExistingConstraints;
-(void)_buildLockedConstraintsForPreview;
-(id)appleInternalValueForKey:(id)arg1 ;
-(char)appleInternalBoolForKey:(id)arg1 ;
-(void)appleInternalSetBool:(char)arg1 forKey:(id)arg2 ;
-(void)setAllowSpokenAnnouncements:(char)arg1 ;
-(void)setShowFontUse:(char)arg1 ;
-(void)setShowLanguageCodes:(char)arg1 ;
-(void)setShowLockedFonts:(char)arg1 ;
-(void)setUseAlternateDomainNames:(char)arg1 ;
-(void)setShowAdditionalFontInfo:(char)arg1 ;
-(void)setFullValidatorReports:(char)arg1 ;
-(void)setAllValidatorTests:(char)arg1 ;
-(void)addSmartCollection:(id)arg1 ;
-(void)hidePreview:(id)arg1 ;
-(void)_duplicateAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)_accumulateFilesForValidation:(id)arg1 forGroup:(id)arg2 to:(id)arg3 controller:(id)arg4 ;
-(void)_validateFilesInArray:(id)arg1 forGroup:(id)arg2 controller:(id)arg3 ;
-(void)_accumulateFacesForValidation:(id)arg1 forGroup:(id)arg2 to:(id)arg3 controller:(id)arg4 ;
-(void)pageLayoutPanelDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)editSmartCollection:(id)arg1 ;
-(void)addFonts:(id)arg1 ;
-(void)resolveDuplicates:(id)arg1 ;
-(void)selectDuplicates:(id)arg1 ;
-(void)restoreStandardFonts:(id)arg1 ;
-(void)showFontFileInFinder:(id)arg1 ;
-(void)openFontURL:(id)arg1 ;
-(void)switchPreviewMode:(id)arg1 ;
-(void)resetPreviewMode:(id)arg1 ;
-(void)showInfo:(id)arg1 ;
-(void)hideInfo:(id)arg1 ;
-(void)exportFonts:(id)arg1 ;
-(void)validateFonts:(id)arg1 ;
-(void)validateFiles:(id)arg1 ;
-(void)saveValidationReport:(id)arg1 ;
-(void)selectSearchField:(id)arg1 ;
-(void)pageLayout:(id)arg1 ;
-(void)disableNonSystemFonts:(id)arg1 ;
-(void)enableDisableGroups:(id)arg1 ;
-(void)resetPreview:(id)arg1 ;
-(void)_validateFacesInArray:(id)arg1 ;
-(void)cancelSmartCollectionEdit:(id)arg1 ;
-(void)finishSmartCollectionEdit:(id)arg1 ;
-(void)setViewType:(id)arg1 ;
-(void)customizeToolbar:(id)arg1 ;
-(void)createCollectionFromText:(id)arg1 userData:(id)arg2 error:(id*)arg3 ;
-(void)createLibraryFromText:(id)arg1 userData:(id)arg2 error:(id*)arg3 ;
-(void)displayFontInformation:(id)arg1 userData:(id)arg2 error:(id*)arg3 ;
-(void)setPlugin:(id<FBPluginProtocol>)arg1 ;
-(char)isCollapsing;
-(void)removeGroups:(id)arg1 ;
-(void)showPreferences:(id)arg1 ;
-(void)printOperationDidRun:(id)arg1 success:(char)arg2 contextInfo:(void*)arg3 ;
-(id<FBPluginProtocol>)plugin;
-(void)renameGroup:(id)arg1 ;
-(char)isBusy;
-(void)startProgressIndicator;
-(void)stopProgressIndicator;
-(void)setIsAnimating:(char)arg1 ;
-(void)_hidePreview;
-(void)_showPreview;
-(void)addCollection:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(void)setToolbar:(NSToolbar *)arg1 ;
-(NSToolbar *)toolbar;
-(char)isAnimating;
-(void)animationDidEnd:(id)arg1 ;
-(char)validateMenuItem:(id)arg1 ;
-(void)setResizingMask:(unsigned long long)arg1 ;
-(void)submenuAction:(id)arg1 ;
-(void)print:(id)arg1 ;
-(NSNumberFormatter *)formatter;
-(void)setFormatter:(NSNumberFormatter *)arg1 ;
-(NSUndoManager *)undoManager;
-(CGSize)windowWillResize:(id)arg1 toSize:(CGSize)arg2 ;
-(void)awakeFromNib;
-(void)windowWillClose:(id)arg1 ;
-(void)setUndoManager:(NSUndoManager *)arg1 ;
-(id)windowNibName;
-(id)windowWillReturnUndoManager:(id)arg1 ;
-(void)windowWillEnterFullScreen:(id)arg1 ;
-(void)windowDidEnterFullScreen:(id)arg1 ;
-(void)windowWillExitFullScreen:(id)arg1 ;
-(void)windowDidExitFullScreen:(id)arg1 ;
-(void)windowDidLoad;
-(unsigned long long)resizingMask;
-(id)panel:(id)arg1 userEnteredFilename:(id)arg2 confirmed:(char)arg3 ;
-(FBProgressWindowController *)progressWindowController;
-(FBSearchController *)searchController;
-(void)setSearchController:(FBSearchController *)arg1 ;
-(void)showPreview:(id)arg1 ;
@end

