/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:40 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/wirelessproxd
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <wirelessproxd/CBPeripheralManagerDelegate.h>
#import <wirelessproxd/CBPeripheralDelegate.h>
#import <wirelessproxd/XPCConnectionDelegate.h>

@class XPCConnection, CBPeripheralManager, CBMutableService, CBMutableCharacteristic, NSData, NSMutableDictionary, NSString, NSMutableSet, NSTimer;

@interface WPDContinuity : NSObject <CBPeripheralManagerDelegate, CBPeripheralDelegate, XPCConnectionDelegate> {

	char _isScanning;
	char _isAdvertising;
	char _isServiceAdded;
	long long _advertisingType;
	long long _scanningType;
	XPCConnection* _connection;
	CBPeripheralManager* _peripheralManager;
	CBMutableService* _continuityService;
	CBMutableCharacteristic* _continuityCharacteristic;
	NSData* _advertisingPayload;
	NSData* _advertisingData;
	NSData* _scanningData;
	NSMutableDictionary* _scanningPeers;
	NSString* _processName;
	NSMutableDictionary* _peers;
	NSData* _sendDataPayload;
	NSMutableSet* _currentScanSet;
	NSTimer* _advertisingTimer;
	NSTimer* _scanningTimer;

}

@property (assign) char isScanning;                                                           //@synthesize isScanning=_isScanning - In the implementation block
@property (assign) char isAdvertising;                                                        //@synthesize isAdvertising=_isAdvertising - In the implementation block
@property (assign) char isServiceAdded;                                                       //@synthesize isServiceAdded=_isServiceAdded - In the implementation block
@property (assign) long long advertisingType;                                                 //@synthesize advertisingType=_advertisingType - In the implementation block
@property (assign) long long scanningType;                                                    //@synthesize scanningType=_scanningType - In the implementation block
@property (nonatomic,retain) XPCConnection * connection;                                      //@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) CBPeripheralManager * peripheralManager;                         //@synthesize peripheralManager=_peripheralManager - In the implementation block
@property (nonatomic,retain) CBMutableService * continuityService;                            //@synthesize continuityService=_continuityService - In the implementation block
@property (nonatomic,retain) CBMutableCharacteristic * continuityCharacteristic;              //@synthesize continuityCharacteristic=_continuityCharacteristic - In the implementation block
@property (nonatomic,retain) NSData * advertisingPayload;                                     //@synthesize advertisingPayload=_advertisingPayload - In the implementation block
@property (nonatomic,retain) NSData * advertisingData;                                        //@synthesize advertisingData=_advertisingData - In the implementation block
@property (nonatomic,retain) NSData * scanningData;                                           //@synthesize scanningData=_scanningData - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * scanningPeers;                             //@synthesize scanningPeers=_scanningPeers - In the implementation block
@property (retain) NSString * processName;                                                    //@synthesize processName=_processName - In the implementation block
@property (retain) NSMutableDictionary * peers;                                               //@synthesize peers=_peers - In the implementation block
@property (nonatomic,retain) NSData * sendDataPayload;                                        //@synthesize sendDataPayload=_sendDataPayload - In the implementation block
@property (retain) NSMutableSet * currentScanSet;                                             //@synthesize currentScanSet=_currentScanSet - In the implementation block
@property (retain) NSTimer * advertisingTimer;                                                //@synthesize advertisingTimer=_advertisingTimer - In the implementation block
@property (retain) NSTimer * scanningTimer;                                                   //@synthesize scanningTimer=_scanningTimer - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)sendNotification:(id)arg1 ;
-(void)setIsAdvertising:(char)arg1 ;
-(CBMutableCharacteristic *)continuityCharacteristic;
-(void)setContinuityCharacteristic:(CBMutableCharacteristic *)arg1 ;
-(void)bluetoothBandwidthstatusNotification:(id)arg1 ;
-(void)connectionDied;
-(void)setIsServiceAdded:(char)arg1 ;
-(void)createContinuityService;
-(char)isServiceAdded;
-(CBMutableService *)continuityService;
-(CBPeripheralManager *)peripheralManager;
-(void)msgStartAdvertise:(id)arg1 ;
-(void)msgStopAdvertising:(id)arg1 ;
-(void)msgStartScan:(id)arg1 ;
-(void)msgStopScan:(id)arg1 ;
-(void)msgConnectToPeer:(id)arg1 ;
-(void)msgDisconnectFromPeer:(id)arg1 ;
-(void)msgSendData:(id)arg1 ;
-(void)msgStartTrackingPeer:(id)arg1 ;
-(void)msgStopTrackingPeer:(id)arg1 ;
-(void)setContinuityService:(CBMutableService *)arg1 ;
-(void)invalidateAdvertisingTimer;
-(void)setAdvertisingType:(long long)arg1 ;
-(void)setAdvertisingPayload:(NSData *)arg1 ;
-(long long)advertisingType;
-(void)advertise:(long long)arg1 ;
-(NSData *)advertisingPayload;
-(void)setAdvertisingData:(NSData *)arg1 ;
-(NSData *)advertisingData;
-(void)advertisingTimerFired:(id)arg1 ;
-(void)setAdvertisingTimer:(NSTimer *)arg1 ;
-(NSTimer *)advertisingTimer;
-(NSTimer *)scanningTimer;
-(void)setScanningTimer:(NSTimer *)arg1 ;
-(void)invalidateScanningTimer;
-(NSMutableSet *)currentScanSet;
-(NSMutableDictionary *)scanningPeers;
-(void)setIsScanning:(char)arg1 ;
-(void)setScanningType:(long long)arg1 ;
-(long long)scanningType;
-(void)setScanningData:(NSData *)arg1 ;
-(void)continuityPeripheralDiscovered:(id)arg1 ;
-(void)continuityPeripheralLost:(id)arg1 ;
-(void)continuityTetheringSourceDiscovered:(id)arg1 ;
-(void)continuityTetheringSourceLost:(id)arg1 ;
-(void)continuityTetheringTargetDiscovered:(id)arg1 ;
-(void)continuityTetheringTargetLost:(id)arg1 ;
-(NSData *)scanningData;
-(void)agressiveScanningTimerFired:(id)arg1 ;
-(char)isScanning;
-(void)setSendDataPayload:(NSData *)arg1 ;
-(void)sendWriteRequest:(id)arg1 ;
-(NSData *)sendDataPayload;
-(void)setCurrentScanSet:(NSMutableSet *)arg1 ;
-(void)messageArrived:(id)arg1 ;
-(id)initWithConnection:(id)arg1 processName:(id)arg2 ;
-(void)devicesDiscovered:(id)arg1 ;
-(void)peripheralDidFailToConnect:(id)arg1 error:(id)arg2 ;
-(void)peripheralDidConnect:(id)arg1 ;
-(void)peripheralDidDisconnect:(id)arg1 error:(id)arg2 ;
-(void)setPeripheralManager:(CBPeripheralManager *)arg1 ;
-(void)setScanningPeers:(NSMutableDictionary *)arg1 ;
-(void)peripheral:(id)arg1 didDiscoverServices:(id)arg2 ;
-(void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3 ;
-(void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3 ;
-(void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3 ;
-(void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3 ;
-(void)peripheralManagerDidUpdateState:(id)arg1 ;
-(void)peripheralManagerDidStartAdvertising:(id)arg1 error:(id)arg2 ;
-(void)peripheralManager:(id)arg1 didAddService:(id)arg2 error:(id)arg3 ;
-(void)peripheralManager:(id)arg1 central:(id)arg2 didSubscribeToCharacteristic:(id)arg3 ;
-(void)peripheralManager:(id)arg1 central:(id)arg2 didUnsubscribeFromCharacteristic:(id)arg3 ;
-(void)peripheralManager:(id)arg1 didReceiveWriteRequests:(id)arg2 ;
-(void)peripheralManagerIsReadyToUpdateSubscribers:(id)arg1 ;
-(void)setConnection:(XPCConnection *)arg1 ;
-(XPCConnection *)connection;
-(void)setProcessName:(NSString *)arg1 ;
-(char)isAdvertising;
-(void)dealloc;
-(NSString *)processName;
-(long long)deviceType:(long long)arg1 ;
-(NSMutableDictionary *)peers;
-(void)setPeers:(NSMutableDictionary *)arg1 ;
@end

