/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKMacHighlightViewProviding <NSObject>
@required
-(Class)highlightViewClass;
-(double)highlightViewHeightForAnnotation:(id)arg1 width:(double)arg2 font:(id)arg3;
-(void)initializeHighlightView:(id)arg1;

@end

