/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBAReaderKit/iBAReaderKit-Structs.h>
#import <iBAReaderKit/TSDGLParticleSystem.h>

@class TSDGLVoronoiTriangleData;

@interface KNBuildCrumbleSystem : TSDGLParticleSystem {

	TSDGLVoronoiTriangleData* _voronoiTriangleData;
	SCD_Struct_KN34* _cellParameters;
	double _speedMaxLimiter;
	double _speedMax;
	double _rotationMax;
	double _lifeSpanRandomness;
	double _lifeSpanDelay;

}

@property (assign,nonatomic) double speedMaxLimiter;                 //@synthesize speedMaxLimiter=_speedMaxLimiter - In the implementation block
@property (assign,nonatomic) double speedMax;                        //@synthesize speedMax=_speedMax - In the implementation block
@property (assign,nonatomic) double rotationMax;                     //@synthesize rotationMax=_rotationMax - In the implementation block
@property (assign,nonatomic) double lifeSpanRandomness;              //@synthesize lifeSpanRandomness=_lifeSpanRandomness - In the implementation block
@property (assign,nonatomic) double lifeSpanDelay;                   //@synthesize lifeSpanDelay=_lifeSpanDelay - In the implementation block
+(unsigned long long)numberOfVerticesPerParticle;
+(char)willOverrideGeometry;
-(void)setSpeedMaxLimiter:(double)arg1 ;
-(double)lifeSpanRandomness;
-(void)setLifeSpanDelay:(double)arg1 ;
-(void)setRotationMax:(double)arg1 ;
-(double)speedMax;
-(double)speedMaxLimiter;
-(void)setSpeedMax:(double)arg1 ;
-(double)lifeSpanDelay;
-(void)setLifeSpanRandomness:(double)arg1 ;
-(void)p_setupParameters;
-(double)rotationMax;
-(id)initWithNumberOfParticles:(unsigned long long)arg1 objectSize:(CGSize)arg2 slideSize:(CGSize)arg3 duration:(double)arg4 direction:(unsigned long long)arg5 shader:(id)arg6 percentOfCellsToSplit:(double)arg7 ;
-(SCD_Struct_KN10)vertexPositionAtVertexIndex:(unsigned long long)arg1 particleIndexPoint:(CGPoint)arg2 ;
-(SCD_Struct_KN10)centerAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN9)speedAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN9)rotationAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN10)lifeSpanAtIndexPoint:(CGPoint)arg1 ;
-(void)dealloc;
@end

