/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:09 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBAReaderKit/iBAReaderKit-Structs.h>
#import <iBAReaderKit/TSDGLParticleSystem.h>

@interface KNBuildFireworksSystem : TSDGLParticleSystem {

	SCD_Struct_KN35 _startingColorRGB;
	char _didDrawCenterBurst;
	double _lifeSpanMinDuration;
	double _colorRandomness;
	SCD_Struct_KN36 _lifeSpan;
	double _maxDistance;
	double _fireworkStartingPositionX;
	CGSize _randomParticleSizeMinMax;
	CGPoint _randomParticleSpeedMinMax;
	CGPoint _startingPoint;

}

@property (assign,nonatomic) double lifeSpanMinDuration;                     //@synthesize lifeSpanMinDuration=_lifeSpanMinDuration - In the implementation block
@property (assign,nonatomic) double colorRandomness;                         //@synthesize colorRandomness=_colorRandomness - In the implementation block
@property (assign,nonatomic) SCD_Struct_KN36 lifeSpan;                       //@synthesize lifeSpan=_lifeSpan - In the implementation block
@property (assign,nonatomic) double maxDistance;                             //@synthesize maxDistance=_maxDistance - In the implementation block
@property (assign,nonatomic) CGSize randomParticleSizeMinMax;                //@synthesize randomParticleSizeMinMax=_randomParticleSizeMinMax - In the implementation block
@property (assign,nonatomic) CGPoint randomParticleSpeedMinMax;              //@synthesize randomParticleSpeedMinMax=_randomParticleSpeedMinMax - In the implementation block
@property (assign,nonatomic) double fireworkStartingPositionX;               //@synthesize fireworkStartingPositionX=_fireworkStartingPositionX - In the implementation block
@property (assign,nonatomic) char didDrawCenterBurst;                        //@synthesize didDrawCenterBurst=_didDrawCenterBurst - In the implementation block
@property (nonatomic,readonly) CGPoint startingPoint;                        //@synthesize startingPoint=_startingPoint - In the implementation block
+(char)willOverrideColors;
+(char)willOverrideStartingPoints;
-(void)setupWithTexture:(id)arg1 particleTextureSize:(CGSize)arg2 reverseDrawOrder:(char)arg3 ;
-(double)speedMax;
-(void)setRandomParticleSizeMinMax:(CGSize)arg1 ;
-(void)setColorRandomness:(double)arg1 ;
-(void)setLifeSpanMinDuration:(double)arg1 ;
-(void)setRandomParticleSpeedMinMax:(CGPoint)arg1 ;
-(void)setFireworkStartingPositionX:(double)arg1 ;
-(char)didDrawCenterBurst;
-(void)setDidDrawCenterBurst:(char)arg1 ;
-(double)fireworkStartingPositionX;
-(CGPoint)randomParticleSpeedMinMax;
-(CGSize)randomParticleSizeMinMax;
-(double)lifeSpanMinDuration;
-(CGPoint)startingPointAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN35)speedAtIndexPoint:(CGPoint)arg1 ;
-(double)scaleAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN36)lifeSpanAtIndexPoint:(CGPoint)arg1 ;
-(SCD_Struct_KN37)colorAtIndexPoint:(CGPoint)arg1 ;
-(void)setMaxDistance:(double)arg1 ;
-(double)colorRandomness;
-(CGPoint)startingPoint;
-(void)setLifeSpan:(SCD_Struct_KN36)arg1 ;
-(SCD_Struct_KN36)lifeSpan;
-(double)maxDistance;
@end

