/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBAReaderKit/KNAnimationEffect.h>
#import <iBAReaderKit/KNFrameAnimator.h>

@class TSDGLMotionBlurEffect, TSDGLShader, TSDGLDataBuffer, NSArray, NSString;

@interface KNTransitionTwist : KNAnimationEffect <KNFrameAnimator> {

	TSDGLMotionBlurEffect* _motionBlurEffect;
	TSDGLShader* _colorShader;
	TSDGLShader* _velocityShader;
	TSDGLDataBuffer* _colorDataBuffer;
	TSDGLDataBuffer* _velocityDataBuffer;
	NSArray* _colorBufferAttributes;
	NSArray* _velocityBufferAttributes;
	unsigned long long _colorPositionAttributeIndex;
	unsigned long long _colorTexCoordAttributeIndex;
	unsigned long long _colorNormalAttributeIndex;
	unsigned long long _velocityPositionAttributeIndex;
	unsigned long long _velocityPrevPositionAttributeIndex;
	long long _numPoints;
	double _twistyness;
	char _shouldDrawMotionBlur;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(int)animationCategory;
+(id)supportedTypes;
+(id)animationFilter;
+(unsigned long long)directionType;
+(id)animationName;
-(double)fx:(double)arg1 withPercent:(double)arg2 ;
-(void)drawGrid:(id)arg1 ;
-(void)createArrays:(id)arg1 ;
-(void)p_teardown;
-(void)renderFrameWithContext:(id)arg1 ;
-(void)update:(id)arg1 withPercent:(double)arg2 direction:(unsigned long long)arg3 ;
-(void)animationDidEndWithContext:(id)arg1 ;
-(id)initWithAnimationContext:(id)arg1 ;
-(void)animationWillBeginWithContext:(id)arg1 ;
-(void)p_drawTwistWithVelocity:(char)arg1 percent:(double)arg2 texture:(id)arg3 oldTexture:(id)arg4 ;
-(void)dealloc;
@end

