/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:09 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <iBAReaderKit/iBAReaderKit-Structs.h>
@class NSString, NSBundle, NSDictionary, NSArray, KPFGingerEvent, NSMutableDictionary;

@interface KPFGingerSlide : NSObject {

	NSString* mSlideTag;
	NSString* mBaseResourcePath;
	NSBundle* mKPFBundle;
	NSDictionary* mKPFDictionary;
	NSDictionary* mTexturesDictionary;
	NSArray* mEventsArray;
	NSArray* mEffectsArray;
	KPFGingerEvent* mCurrentEvent;
	KPFGingerEvent* mNextEvent;
	unsigned long long mCurrentEventIndex;
	unsigned long long mEventCount;
	KPFGingerEvent* mHyperLinkedEvent;
	NSMutableDictionary* mTextureCache;
	NSMutableDictionary* mMoviesDict;
	char mMediaPlaybackIsPaused;

}

@property (nonatomic,readonly) KPFGingerEvent * currentEvent; 
@property (nonatomic,readonly) KPFGingerEvent * nextEvent; 
@property (nonatomic,readonly) unsigned long long curentEventIndex; 
@property (nonatomic,readonly) NSString * slideTag; 
@property (nonatomic,readonly) unsigned long long eventCount; 
@property (nonatomic,readonly) KPFGingerEvent * hyperLinkedEvent; 
@property (nonatomic,readonly) char mediaPlaybackIsPaused; 
-(char)containsMovie;
-(CGImageRef)newImageForTextureName:(id)arg1 ;
-(void)playMovieForObjectID:(id)arg1 afterDelay:(double)arg2 ;
-(void)stopMovieForObjectID:(id)arg1 ;
-(void)newMovieForTextureName:(id)arg1 movieDict:(id)arg2 withObjectID:(id)arg3 ;
-(id)movieForObjectID:(id)arg1 ;
-(CGImageRef)CGImageForTextureName:(id)arg1 ;
-(id)movieNameForTextureName:(id)arg1 ;
-(CGSize)textureSizeForName:(id)arg1 ;
-(char)nextEventContainsMovie;
-(void)renderSlideWithSession:(id)arg1 ;
-(void)renderHyperLinkedSlideWithSlideTag:(id)arg1 withSession:(id)arg2 ;
-(KPFGingerEvent *)hyperLinkedEvent;
-(void)pauseMediaPlayback;
-(void)resumeMediaPlayback;
-(char)decrementCurrentEventIndex;
-(void)renderCurrentEventWithSession:(id)arg1 ;
-(unsigned long long)curentEventIndex;
-(char)incrementCurrentEventIndex;
-(char)mediaPlaybackIsPaused;
-(void)animateSlideWithSession:(id)arg1 ;
-(id)p_hyperlinksArray;
-(id)p_texturesDictionary;
-(id)p_urlForResource:(id)arg1 ;
-(void)p_movieEndCallback:(id)arg1 ;
-(id)initWithSlideDictionary:(id)arg1 slideTag:(id)arg2 baseResourcePath:(id)arg3 ;
-(id)p_eventsArray;
-(void)stopAllMovies;
-(KPFGingerEvent *)nextEvent;
-(id)p_urlForMovie:(id)arg1 ;
-(unsigned long long)eventCount;
-(NSString *)slideTag;
-(id)p_effectsArray;
-(void)teardown;
-(void)dealloc;
-(KPFGingerEvent *)currentEvent;
@end

