/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface THApplePubController : NSObject
+(char)readContainersInNode:(id)arg1 ;
+(char)readAppPubFileToDocumentRoot:(id)arg1 url:(id)arg2 error:(id*)arg3 ;
@end

