/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:09 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol BKAsset;
@class NSURL, NSString;

@interface THAsset : NSObject {

	NSURL* mURL;
	NSString* mAssetID;
	NSString* mType;
	id<BKAsset> mAsset;
	char _isManagedBook;

}

@property (nonatomic,readonly) NSString * assetType; 
@property (nonatomic,readonly) NSString * assetID; 
@property (nonatomic,readonly) NSURL * url; 
@property (nonatomic,readonly) NSURL * storeUrl; 
@property (nonatomic,readonly) NSString * author; 
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * storeID; 
@property (nonatomic,readonly) NSString * genre; 
@property (nonatomic,readonly) char isSample; 
@property (nonatomic,readonly) char isManagedBook;                //@synthesize isManagedBook=_isManagedBook - In the implementation block
+(id)assetWithURL:(id)arg1 assetID:(id)arg2 type:(id)arg3 ;
+(char)asset:(id)arg1 isSameAsAsset:(id)arg2 ;
+(id)assetWithURL:(id)arg1 assetID:(id)arg2 ;
+(id)assetWithAsset:(id)arg1 ;
-(NSURL *)storeUrl;
-(char)isManagedBook;
-(NSString *)assetID;
-(NSString *)assetType;
-(id)initWithURL:(id)arg1 assetID:(id)arg2 type:(id)arg3 ;
-(id)initWithURL:(id)arg1 assetID:(id)arg2 ;
-(NSString *)genre;
-(id)initWithAsset:(id)arg1 ;
-(NSString *)storeID;
-(NSString *)author;
-(void)dealloc;
-(NSURL *)url;
-(NSString *)title;
-(char)isSample;
@end

