/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:07 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol THBookNavigation <THLinkTraversalDelegate>
@optional
-(void)didJumpToPageLocation:(id)arg1;
-(void)willJumpToPageLocation:(id)arg1;

@required
-(void)showCoverPage;
-(void)closeDocument;
-(char)isNotesFullscreenVisible;
-(void)showOverlayScrim;
-(void)hideOverlayScrim;
-(void)showTOC;
-(unsigned long long)currentAbsolutePageIndex;
-(char)isGlossaryVisible;
-(void)showGlossaryView;
-(void)recordOutgoingMajorNavigationJump;
-(void)followAbsolutePageIndex:(unsigned long long)arg1;
-(id)bookLinkResolver;
-(void)showGlossaryViewWithAnchor:(id)arg1;
-(void)navigationUnitDidChange:(id)arg1;
-(id)anchorFromLink:(id)arg1;
-(void)showIntroMedia;

@end

