/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 5:25:09 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBAReaderKit/iBAReaderKit-Structs.h>
#import <iBAReaderKit/TSDLayout.h>
#import <iBAReaderKit/TSDWrappableParent.h>

@interface THGlossaryEntryFloatingLayout : TSDLayout <TSDWrappableParent>

@property (nonatomic,readonly) int wrapContainerMode; 
-(id)childrenForWrappingDependents;
-(int)wrapContainerMode;
-(id)descendentWrappables;
-(void)p_addWrappingRequirementsForLayout:(id)arg1 toArray:(id)arg2 ;
-(void)updateChildrenFromInfo;
-(CGRect)boundingBoxForChildren;
-(CGSize)maximumFrameSizeForChild:(id)arg1 ;
-(id)floatingLayouts;
-(id)computeLayoutGeometry;
-(id)additionalDependenciesForChildLayout:(id)arg1 ;
@end

