/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBAReaderKit/iBAReaderKit-Structs.h>
#import <AppKit/NSWindow.h>

@class THOverlayHelperView, NSView;

@interface THOverlayHelperWindow : NSWindow {

	THOverlayHelperView* _helperView;
	NSView* parentView;
	long long order;
	char followsMouse;

}

@property (retain) THOverlayHelperView * helperView;              //@synthesize helperView=_helperView - In the implementation block
-(void)parentViewChanged:(id)arg1 ;
-(void)parentViewDidMoveToWindow;
-(THOverlayHelperView *)helperView;
-(void)parentViewWillMoveToWindow:(id)arg1 ;
-(void)setHelperView:(THOverlayHelperView *)arg1 ;
-(id)initWithContentRect:(CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(char)arg4 parentView:(id)arg5 helperView:(id)arg6 ordered:(long long)arg7 followsMouse:(char)arg8 ;
-(void)dealloc;
-(char)isMainWindow;
@end

