/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:26 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol THPageViewProviderDelegate <NSObject>
@optional
-(unsigned long long)pageViewProvider:(id)arg1 absolutePageIndexForPageInfo:(id)arg2;

@required
-(void)pageViewProviderViewsAdded:(id)arg1;
-(unsigned long long)pageViewProviderStartAbsolutePageIndex:(id)arg1;
-(CGRect*)pageViewProviderUnclippedVisibleBounds:(id)arg1;

@end

