/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:28 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <iBAReaderKit/iBAReaderKit-Structs.h>
@interface THPagePositionController : NSObject {

	CGSize mPageSize;
	char mShouldEnablePaging;
	char mPageHorizontally;

}

@property (nonatomic,readonly) char pageHorizontally; 
@property (nonatomic,readonly) CGSize pageSize; 
@property (nonatomic,readonly) char shouldEnablePaging; 
+(CGSize)pageSizeForLandscape;
+(id)flowPositionerWithPageSize:(CGSize)arg1 ;
+(CGSize)pageSizeForPortrait;
+(id)paginatedPositionerWithPageSize:(CGSize)arg1 ;
-(CGSize)pageSize;
-(NSRange)visibleRelativePageIndexRangeForRect:(CGRect)arg1 withPadding:(char)arg2 pageCount:(unsigned long long)arg3 ;
-(unsigned long long)mostVisibleRelativePageIndexForCanvasBoundsRect:(CGRect)arg1 ;
-(void)arrangeLayouts:(id)arg1 ;
-(CGRect)pageRectForRelativePageIndex:(unsigned long long)arg1 ;
-(CGPoint)pageOriginForRelativePageIndex:(unsigned long long)arg1 ;
-(CGSize)canvasSizeForPageCount:(unsigned long long)arg1 ;
-(CGSize)sequentialSizeFromPageSizes:(id)arg1 ;
-(char)pageHorizontally;
-(char)shouldEnablePaging;
-(CGSize)pageSizeWithZeroInPagingDirection;
-(CGSize)offsetSize:(CGSize)arg1 inPagingDirectionWithOffset:(CGSize)arg2 ;
-(id)initWithPageSize:(CGSize)arg1 enablePaging:(char)arg2 pageHorizontally:(char)arg3 ;
-(CGSize)p_sequentialPageSizeOffsetFromPageSize:(CGSize)arg1 ;
-(CGPoint)sectionOriginWithPrecedingSectionSizes:(id)arg1 ;
-(unsigned long long)relativePageIndexFromCanvasPoint:(CGPoint)arg1 ;
-(CGRect)offsetRect:(CGRect)arg1 inPagingDirectionWithOffset:(CGPoint)arg2 ;
@end

