/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:26 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class NSView, NSViewController;


@protocol THWExpandedViewControllerDelegate <NSObject>
@property (nonatomic,readonly) NSView * rootSuperview; 
@property (nonatomic,readonly) NSViewController * rootSuperviewController; 
@property (nonatomic,readonly) NSView * expandedWindowHostView; 
@property (nonatomic,readonly) double forcedRotationAngle; 
@property (nonatomic,readonly) CGSize windowMinSize; 
@property (nonatomic,readonly) char isFreeTransformInProgress; 
@optional
-(id)expandedViewControllerLayerToAnimateUnder:(id)arg1;
-(void)expandedViewControllerDidPresentHTMLContent:(id)arg1;

@required
-(NSViewController *)rootSuperviewController;
-(CGSize)windowMinSize;
-(double)forcedRotationAngle;
-(void)expandedViewControllerDidCancelDismiss:(id)arg1;
-(char)inFlowMode;
-(NSView *)expandedWindowHostView;
-(id)expandableRepForInfo:(id)arg1;
-(char)isFreeTransformInProgress;
-(NSView *)rootSuperview;
-(void)expandedViewControllerWillBeginDismissing:(id)arg1;
-(void)expandedViewControllerWillDismiss:(id)arg1;
-(void)expandedViewControllerDidDismiss:(id)arg1;
-(void)expandedViewController:(id)arg1 handleHyperlinkWithURL:(id)arg2;
-(void)expandedViewControllerWillPresent:(id)arg1;
-(void)expandedViewControllerDidPresent:(id)arg1;
-(void)expandedViewControllerWantsDismiss:(id)arg1;

@end

