/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <iBAReaderKit/TSPObject.h>
#import <iBAReaderKit/TSKDocumentObject.h>

@class THDrawableStorage, TSUPointerKeyDictionary;

@interface THWGutterDrawableStorage : TSPObject <TSKDocumentObject> {

	THDrawableStorage* mDrawableStorage;
	TSUPointerKeyDictionary* mDrawablePositionings;
	char mShouldUseGutterOrder;

}

@property (assign,nonatomic) char shouldUseGutterOrder; 
@property (nonatomic,retain) THDrawableStorage * drawableStorage; 
@property (nonatomic,retain) TSUPointerKeyDictionary * drawablePositionings; 
-(char)shouldUseGutterOrder;
-(void)willBeRemovedFromDocumentRoot:(id)arg1 ;
-(void)wasRemovedFromDocumentRoot:(id)arg1 ;
-(void)setDrawableStorage:(THDrawableStorage *)arg1 ;
-(id)orderedDrawables;
-(void)setDrawablePositionings:(TSUPointerKeyDictionary *)arg1 ;
-(id)positioningOfDrawable:(id)arg1 ;
-(THDrawableStorage *)drawableStorage;
-(id)drawables;
-(TSUPointerKeyDictionary *)drawablePositionings;
-(void)wasAddedToDocumentRoot:(id)arg1 context:(id)arg2 ;
-(void)willBeAddedToDocumentRoot:(id)arg1 context:(id)arg2 ;
-(void)addDrawable:(id)arg1 positioning:(id)arg2 insertContext:(id)arg3 ;
-(void)setShouldUseGutterOrder:(char)arg1 ;
-(void)dealloc;
-(id)initWithContext:(id)arg1 ;
@end

