/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol TSWPEditingControllerDelegate <NSObject>
@property (nonatomic,readonly) char editorShouldAlwaysBeInParagraphMode; 
@property (nonatomic,readonly) char editorAllowsEditMenu; 
@property (nonatomic,readonly) char editorAllowsMagnifier; 
@property (nonatomic,readonly) char editorAllowsParagraphMode; 
@property (nonatomic,readonly) char editorAllowsKeyboard; 
@property (nonatomic,readonly) char editorAllowsCaret; 
@property (nonatomic,readonly) char editorAllowsHyperlinkInteraction; 
@property (nonatomic,readonly) char editorAllowsRubyInteraction; 
@property (nonatomic,readonly) char editorAllowsListInteraction; 
@optional
-(void)editingController:(id)arg1 willDeleteCharactersInRange:(NSRange)arg2;
-(char)willChangeContentOffsetIfKeyboardHidden;
-(void)showCustomEditMenuForStorage:(id)arg1 range:(NSRange)arg2;
-(void)knobTrackingDidBegin;
-(void)knobTrackingDidEnd;
-(char)editorShouldAlwaysBeInParagraphMode;
-(char)editorAllowsEditMenu;
-(char)editorAllowsMagnifier;
-(char)editorAllowsParagraphMode;
-(id)styleProviderForStorage:(id)arg1;
-(char)editorAllowsKeyboard;
-(char)editorAllowsListInteraction;
-(char)editorAllowsHyperlinkInteraction;
-(char)editorAllowsRubyInteraction;
-(void)didSetTappedSelectionWithWPEditor:(id)arg1 onWPRep:(id)arg2;
-(void)filterPasteboardTextStorages:(id)arg1 forTargetStorage:(id)arg2;
-(char)editorAllowsCaret;
-(char)disallowEditingOfTextStringWithStorage:(id)arg1;

@end

