/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/PlugIns/iBAReaderKit.bundle/Contents/MacOS/iBAReaderKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol TSWTransportControlSlave
@required
-(void)transportControlSlaveGotoNext;
-(char)transportControlSlaveSupportsSound;
-(void)transportControlSlaveEnableSound:(char)arg1;
-(void)transportControlSlaveGotoLast;
-(char)transportControlSlaveCanMute;
-(void)transportControlSlaveGotoIndex:(unsigned long long)arg1;
-(void)transportControlSlaveToggleSound;
-(unsigned long long)transportControlSlaveIndex;
-(void)transportControlSlaveGotoPrev;
-(void)transportControlSlaveGotoFirst;
-(unsigned long long)transportControlSlaveCount;
-(char)transportControlSlaveCanGotoPrev;
-(char)transportControlSlaveCanGotoNext;
-(char)transportControlSlaveCanGotoFirst;
-(char)transportControlSlaveCanGotoLast;

@end

