/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 9:01:37 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Volumes/YosInst/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_source;
@class NSString, NSAttributedString, NSObject;

@interface TTProcessInfo : NSObject {

	NSString* _name;
	NSAttributedString* _displayName;
	int _pid;
	int _ppid;
	int _pgid;
	unsigned _euid;
	NSString* _user;
	char _hasCTTY;
	int _tdev;
	NSString* _tty;
	NSString* _tt;
	char _isBase;
	char _isCommand;
	char _isShell;
	char _isTerminalTTY;
	char _isForeground;
	char _isFrontmost;
	char _isDirty;
	char _status;
	NSString* _kind;
	long long _indent;
	NSObject*<OS_dispatch_source> _dispatchSource;

}

@property (retain) NSString * name;                                                     //@synthesize name=_name - In the implementation block
@property (retain) NSAttributedString * displayName;                                    //@synthesize displayName=_displayName - In the implementation block
@property (assign) int pid;                                                             //@synthesize pid=_pid - In the implementation block
@property (assign) int ppid;                                                            //@synthesize ppid=_ppid - In the implementation block
@property (assign) int pgid;                                                            //@synthesize pgid=_pgid - In the implementation block
@property (assign) unsigned euid;                                                       //@synthesize euid=_euid - In the implementation block
@property (readonly) NSString * user; 
@property (assign) char hasCTTY;                                                        //@synthesize hasCTTY=_hasCTTY - In the implementation block
@property (assign) int tdev;                                                            //@synthesize tdev=_tdev - In the implementation block
@property (readonly) NSString * tty; 
@property (readonly) NSString * tt; 
@property (assign) char isBase;                                                         //@synthesize isBase=_isBase - In the implementation block
@property (assign) char isCommand;                                                      //@synthesize isCommand=_isCommand - In the implementation block
@property (assign) char isShell;                                                        //@synthesize isShell=_isShell - In the implementation block
@property (assign) char isTerminalTTY;                                                  //@synthesize isTerminalTTY=_isTerminalTTY - In the implementation block
@property (assign) char isForeground;                                                   //@synthesize isForeground=_isForeground - In the implementation block
@property (assign) char isFrontmost;                                                    //@synthesize isFrontmost=_isFrontmost - In the implementation block
@property (assign) char isDirty;                                                        //@synthesize isDirty=_isDirty - In the implementation block
@property (assign) char status;                                                         //@synthesize status=_status - In the implementation block
@property (retain) NSString * kind;                                                     //@synthesize kind=_kind - In the implementation block
@property (assign) long long indent;                                                    //@synthesize indent=_indent - In the implementation block
@property (assign,nonatomic) NSObject*<OS_dispatch_source> dispatchSource;              //@synthesize dispatchSource=_dispatchSource - In the implementation block
-(char)hasCTTY;
-(int)tdev;
-(NSString *)tty;
-(NSObject*<OS_dispatch_source>)dispatchSource;
-(void)setDispatchSource:(NSObject*<OS_dispatch_source>)arg1 ;
-(NSString *)tt;
-(void)setPpid:(int)arg1 ;
-(int)pgid;
-(void)setPgid:(int)arg1 ;
-(void)setEuid:(unsigned)arg1 ;
-(void)setHasCTTY:(char)arg1 ;
-(void)setTdev:(int)arg1 ;
-(char)isBase;
-(void)setIsBase:(char)arg1 ;
-(char)isCommand;
-(void)setIsCommand:(char)arg1 ;
-(char)isShell;
-(void)setIsShell:(char)arg1 ;
-(char)isTerminalTTY;
-(void)setIsTerminalTTY:(char)arg1 ;
-(void)setIsForeground:(char)arg1 ;
-(char)isFrontmost;
-(void)setIsFrontmost:(char)arg1 ;
-(long long)indent;
-(void)setIndent:(long long)arg1 ;
-(NSString *)user;
-(unsigned)euid;
-(int)pid;
-(char)isForeground;
-(int)ppid;
-(void)setPid:(int)arg1 ;
-(void)setIsDirty:(char)arg1 ;
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(void)setName:(NSString *)arg1 ;
-(char)isDirty;
-(char)isEqual:(id)arg1 ;
-(NSString *)name;
-(char)status;
-(NSAttributedString *)displayName;
-(void)setDisplayName:(NSAttributedString *)arg1 ;
-(NSString *)kind;
-(void)setKind:(NSString *)arg1 ;
-(void)setStatus:(char)arg1 ;
@end

