/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 9:01:37 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Volumes/YosInst/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Terminal/Terminal-Structs.h>
#import <Terminal/NSCopying.h>
#import <Terminal/NSCoding.h>

@class NSString;

@interface TTUUID : NSObject <NSCopying, NSCoding> {

	CFUUIDRef _uuid;
	NSString* _uuidString;

}
+(id)UUID;
-(id)initWithUUIDRef:(CFUUIDRef)arg1 ;
-(CFUUIDRef)UUIDRef;
-(id)init;
-(void)dealloc;
-(id)description;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)initWithString:(id)arg1 ;
-(id)string;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)stringValue;
-(long long)compare:(id)arg1 ;
@end

