/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:17 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/SafariNotificationAgent
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <SafariNotificationAgent/NSXPCListenerDelegate.h>

@class NSMutableDictionary, NSString;

@interface SafariNotificationAgentDelegate : NSObject <NSXPCListenerDelegate> {

	NSMutableDictionary* _centers;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)tryToRegisterRemoteNotificationPermission:(id)arg1 ;
-(void)unregisterRemoteNotificationPermission:(id)arg1 ;
-(void)forgetRemoteNotificationPermissionForWebsite:(id)arg1 ;
-(id)_ensureCenterDelegate:(id)arg1 ;
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(void)updateDeviceTokens;
-(id)init;
@end

