/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:34:21 PM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/lib/system/libxpc.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <libxpc.dylib/OS_xpc_object.h>
#import <libxpc.dylib/OS_xpc_uint64.h>

@protocol OS_xpc_uint64 <OS_xpc_object>
@end


@interface OS_xpc_uint64 : OS_xpc_object <OS_xpc_uint64>
+(void)load;
@end

