/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:43:41 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Notes.app/Contents/MacOS/Notes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Notes/Notes-Structs.h>
#import <Notes/MCAccountProxyManager.h>

@class NSMapTable, NSTimer, NSMutableArray, NSOperationQueue, NSString;

@interface AccountManager : NSObject <MCAccountProxyManager> {

	NSMapTable* _accounts;
	NSTimer* _fetchTimer;
	NSMutableArray* _certificatesAlreadyPrompted;
	char _isSyncing;
	char _isOffline;
	char _deduplicatedAccounts;
	NSOperationQueue* _invalidationQueue;

}

@property (assign) char isSyncing;                                      //@synthesize isSyncing=_isSyncing - In the implementation block
@property (assign) char isOffline;                                      //@synthesize isOffline=_isOffline - In the implementation block
@property (readonly) NSOperationQueue * invalidationQueue;              //@synthesize invalidationQueue=_invalidationQueue - In the implementation block
@property (assign) char deduplicatedAccounts;                           //@synthesize deduplicatedAccounts=_deduplicatedAccounts - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)allocWithZone:(NSZone*)arg1 ;
+(id)sharedInstance;
-(void)_networkConfigurationChanged:(id)arg1 ;
-(void)_mainContextObjectsDidChange:(id)arg1 ;
-(void)_webAuthenticationCompleted:(id)arg1 ;
-(void)_fetchTimerFired:(id)arg1 ;
-(void)performFetch;
-(void)_reloadAccounts;
-(void)_performFetchForAccountsWithIdentifiers:(id)arg1 ;
-(char)deduplicatedAccounts;
-(id)_deduplicatedAccountIDsWithContext:(id)arg1 error:(id*)arg2 ;
-(void)setDeduplicatedAccounts:(char)arg1 ;
-(NSOperationQueue *)invalidationQueue;
-(void)_testForAccountSyncStatus;
-(void)_showWebAuthenticationPanelForAccount:(id)arg1 ;
-(void)_showCertificateTrustPanelForAccount:(id)arg1 ;
-(void)_testForAccountState;
-(void)_folderListSelectionDidChange:(id)arg1 ;
-(void)setIsSyncing:(char)arg1 ;
-(void)startFetchTimer;
-(void)stopFetchTimer;
-(void)performFetchForAccount:(id)arg1 ;
-(id)allAccountProxies;
-(void)setIsOffline:(char)arg1 ;
-(id)init;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(char)isOffline;
-(id)accountProxyForAccount:(id)arg1 ;
-(char)isSyncing;
@end

