/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:43:41 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Notes.app/Contents/MacOS/Notes
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSVisualEffectView.h>

@class NSLayoutConstraint;

@interface FolderListView : NSVisualEffectView {

	NSLayoutConstraint* _widthConstraint;

}

@property (nonatomic,retain) NSLayoutConstraint * widthConstraint;              //@synthesize widthConstraint=_widthConstraint - In the implementation block
-(NSLayoutConstraint *)widthConstraint;
-(void)setWidthConstraint:(NSLayoutConstraint *)arg1 ;
-(void)awakeFromNib;
@end

