/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:22 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/IMCommonCore.framework/Versions/A/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSDate, NSString;

@interface BKSeriesCheck : NSManagedObject

@property (nonatomic,retain) NSDate * dateChecked; 
@property (nonatomic,retain) NSString * adamId; 
+(id)predicateForSeriesCheckWithAdamIDsInList:(id)arg1 ;
+(id)insertSeriesCheckWithAdamId:(id)arg1 intoManagedObjectContext:(id)arg2 ;
+(id)adamIDsNeedingToBeCheckedFromAdamIDs:(id)arg1 inManagedObjectContext:(id)arg2 ;
+(void)recordAdamIDsAsChecked:(id)arg1 inManagedObjectContext:(id)arg2 ;
+(char)shouldRecheckAdamID:(id)arg1 inManagedObjectContext:(id)arg2 ;
+(id)fetchRequest;
@end

