/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:11:07 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/IMCommonCore.framework/Versions/A/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <IMCommonCore/NSCoding.h>

@class NSString;

@interface IMBloomFilter : NSObject <NSCoding> {

	/*^block*/id _hashProvider;
	SCD_Struct_IM0 _specification;
	SCD_Struct_IM19 _bitVector;

}

@property (readonly) NSString * usageDescription; 
-(id)initWithSpecification:(SCD_Struct_IM0)arg1 hashProvider:(/*^block*/id)arg2 ;
-(char)mightContainKey:(const void*)arg1 ;
-(long long)indexSize;
-(NSString *)usageDescription;
-(void)addKey:(const void*)arg1 ;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
@end

