/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:22 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/iBooks.app/Contents/Frameworks/IMCommonCore.framework/Versions/A/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <IMCommonCore/SFUOutputStream.h>

@protocol SFUOutputStream;
@class SFUCryptor, NSString;

@interface SFUCryptoOutputStream : NSObject <SFUOutputStream> {

	id<SFUOutputStream> mBaseStream;
	SFUCryptor* mCryptor;
	char mIsClosed;
	char mComputeCrc32;
	unsigned mCrc32;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)encodedLengthForDataLength:(unsigned long long)arg1 key:(id)arg2 ;
-(id)closeLocalStream;
-(void)seekToOffset:(long long)arg1 whence:(int)arg2 ;
-(id)initForEncryptionWithOutputStream:(id)arg1 key:(id)arg2 computeCrc32:(char)arg3 ;
-(void)writeBuffer:(const char*)arg1 size:(unsigned long long)arg2 ;
-(char)canCreateInputStream;
-(id)initForEncryptionWithOutputStream:(id)arg1 key:(id)arg2 ;
-(char)canSeek;
-(long long)offset;
-(unsigned)crc32;
-(id)inputStream;
-(void)dealloc;
-(void)close;
@end

