/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 3:57:34 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/sbin/blued
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface InteropUtilities : NSObject
+(char)isModel:(int)arg1 ;
+(char*)getAFHMapForWiFiChannel:(unsigned short)arg1 numFrequenciesBlockedUpFromCenter:(unsigned char)arg2 numFrequenciesBlockedDownFromCenter:(unsigned char)arg3 LEAFHMask:(unsigned long long*)arg4 ;
+(float)frequencyOfChannel:(int)arg1 ;
+(int)channelOfFrequency:(float)arg1 ;
@end

