-[NSExtension(ExtensionStateManagement) _extensionState]
-[NSExtension(ExtensionStateManagement) _setExtensionState:]
-[NSExtension(ExtensionStateManagement) _isMarkedNew]
-[NSExtension(ExtensionStateManagement) _didShowExtensionManagementInterface]
-[NSExtension(ExtensionStateManagement) _didShowNewExtensionIndicator]
-[NSExtension(ExtensionStateManagement) _resetExtensionState]
_initNSDictionary
_NSDictionaryFunction
_initNSDate
_NSDateFunction
_initNSCalendar
_NSCalendarFunction
+[NSExtensionItem supportsSecureCoding]
-[NSExtensionItem init]
-[NSExtensionItem initWithCoder:]
-[NSExtensionItem dealloc]
-[NSExtensionItem encodeWithCoder:]
-[NSExtensionItem copyWithZone:]
-[NSExtensionItem setAttributedTitle:]
-[NSExtensionItem attributedTitle]
-[NSExtensionItem setAttributedContentText:]
-[NSExtensionItem attributedContentText]
-[NSExtensionItem setAttachments:]
-[NSExtensionItem attachments]
-[NSExtensionItem setUserInfo:]
-[NSExtensionItem userInfo]
-[NSExtensionItem description]
-[NSExtensionItem _matchingDictionaryRepresentation]
___Block_byref_object_copy_
___Block_byref_object_dispose_
___52-[NSExtensionItem _matchingDictionaryRepresentation]_block_invoke
___52-[NSExtensionItem _matchingDictionaryRepresentation]_block_invoke_2
___copy_helper_block_
___destroy_helper_block_
___copy_helper_block_88
___destroy_helper_block_89
___52-[NSExtensionItem _matchingDictionaryRepresentation]_block_invoke104
___copy_helper_block_107
___destroy_helper_block_108
+[NSExtension initialize]
+[NSExtension _shouldLogExtensionDiscovery]
+[NSExtension extensionsWithMatchingAttributes:error:]
___54+[NSExtension extensionsWithMatchingAttributes:error:]_block_invoke
___copy_helper_block_181
___destroy_helper_block_182
+[NSExtension extensionWithIdentifier:error:]
+[NSExtension beginMatchingExtensionsWithAttributes:completion:]
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke_2
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke_3
___copy_helper_block_196
___destroy_helper_block_197
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke204
___copy_helper_block_206
___destroy_helper_block_207
___copy_helper_block_212
___destroy_helper_block_213
___copy_helper_block_217
___destroy_helper_block_218
+[NSExtension endMatchingExtensions:]
-[NSExtension _initWithPKPlugin:]
-[NSExtension init]
-[NSExtension dealloc]
-[NSExtension hash]
-[NSExtension isEqual:]
-[NSExtension description]
-[NSExtension optedIn]
-[NSExtension attemptOptIn:]
-[NSExtension attemptOptOut:]
-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke_2
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke_3
___copy_helper_block_280
___destroy_helper_block_281
___copy_helper_block_284
___destroy_helper_block_285
___copy_helper_block_288
___destroy_helper_block_289
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke293
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke_2294
___copy_helper_block_297
___destroy_helper_block_298
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke303
___copy_helper_block_306
___destroy_helper_block_307
___copy_helper_block_310
___destroy_helper_block_311
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke314
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke_2315
___copy_helper_block_316
___destroy_helper_block_317
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke322
___copy_helper_block_323
___destroy_helper_block_324
___copy_helper_block_327
___destroy_helper_block_328
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke333
___copy_helper_block_338
___destroy_helper_block_339
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke353
___copy_helper_block_354
___destroy_helper_block_355
-[NSExtension beginExtensionRequestWithInputItems:listenerEndpoint:completion:]
___79-[NSExtension beginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke
___79-[NSExtension beginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke_2
___copy_helper_block_365
___destroy_helper_block_366
___copy_helper_block_369
___destroy_helper_block_370
-[NSExtension beginExtensionRequestWithInputItems:completion:]
-[NSExtension cancelExtensionRequestWithIdentifier:]
___52-[NSExtension cancelExtensionRequestWithIdentifier:]_block_invoke
__NSExtensionTearDownRequestWithIdentifier
___copy_helper_block_379
___destroy_helper_block_380
-[NSExtension pidForRequestIdentifier:]
-[NSExtension objectForInfoDictionaryKey:]
-[NSExtension icons]
-[NSExtension _extensionBundle]
-[NSExtension _extensionContextForUUID:]
-[NSExtension _itemProviderForPayload:extensionContext:]
-[NSExtension _isPhotoServiceAccessGranted]
___43-[NSExtension _isPhotoServiceAccessGranted]_block_invoke
___43-[NSExtension _isPhotoServiceAccessGranted]_block_invoke_2
___copy_helper_block_414
___destroy_helper_block_415
-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]
___85-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]_block_invoke
___85-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]_block_invoke_2
___copy_helper_block_427
___destroy_helper_block_428
___85-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]_block_invoke431
___copy_helper_block_432
___destroy_helper_block_433
___copy_helper_block_436
___destroy_helper_block_437
-[NSExtension _cancelRequestWithError:forExtensionContextWithUUID:completion:]
___78-[NSExtension _cancelRequestWithError:forExtensionContextWithUUID:completion:]_block_invoke
___78-[NSExtension _cancelRequestWithError:forExtensionContextWithUUID:completion:]_block_invoke_2
___copy_helper_block_442
___destroy_helper_block_443
___copy_helper_block_446
___destroy_helper_block_447
-[NSExtension _loadItemForPayload:contextIdentifier:completionHandler:]
___71-[NSExtension _loadItemForPayload:contextIdentifier:completionHandler:]_block_invoke
___71-[NSExtension _loadItemForPayload:contextIdentifier:completionHandler:]_block_invoke_2
___copy_helper_block_454
___destroy_helper_block_455
___copy_helper_block_461
___destroy_helper_block_462
-[NSExtension _loadPreviewImageForPayload:contextIdentifier:completionHandler:]
___79-[NSExtension _loadPreviewImageForPayload:contextIdentifier:completionHandler:]_block_invoke
___79-[NSExtension _loadPreviewImageForPayload:contextIdentifier:completionHandler:]_block_invoke_2
___copy_helper_block_465
___destroy_helper_block_466
___copy_helper_block_471
___destroy_helper_block_472
-[NSExtension _openURL:completion:]
___35-[NSExtension _openURL:completion:]_block_invoke
___copy_helper_block_479
___destroy_helper_block_480
-[NSExtension _isSystemExtension]
-[NSExtension _plugInProcessIdentifier]
-[NSExtension _safelyBeginUsing:]
___33-[NSExtension _safelyBeginUsing:]_block_invoke
___33-[NSExtension _safelyBeginUsing:]_block_invoke_2
___33-[NSExtension _safelyBeginUsing:]_block_invoke_3
___33-[NSExtension _safelyBeginUsing:]_block_invoke_4
___copy_helper_block_499
___destroy_helper_block_500
___33-[NSExtension _safelyBeginUsing:]_block_invoke503
___33-[NSExtension _safelyBeginUsing:]_block_invoke_2504
___copy_helper_block_505
___destroy_helper_block_506
___33-[NSExtension _safelyBeginUsing:]_block_invoke509
___copy_helper_block_510
___destroy_helper_block_511
___copy_helper_block_514
___destroy_helper_block_515
___33-[NSExtension _safelyBeginUsing:]_block_invoke521
___copy_helper_block_522
___destroy_helper_block_523
___copy_helper_block_529
___destroy_helper_block_530
___copy_helper_block_534
___destroy_helper_block_535
___copy_helper_block_538
___destroy_helper_block_539
-[NSExtension _safelyEndUsing:]
___31-[NSExtension _safelyEndUsing:]_block_invoke
___31-[NSExtension _safelyEndUsing:]_block_invoke_2
___31-[NSExtension _safelyEndUsing:]_block_invoke_3
___copy_helper_block_542
___destroy_helper_block_543
___copy_helper_block_548
___destroy_helper_block_549
___copy_helper_block_552
___destroy_helper_block_553
-[NSExtension _kill:]
-[NSExtension identifier]
-[NSExtension setIdentifier:]
-[NSExtension version]
-[NSExtension setVersion:]
-[NSExtension attributes]
-[NSExtension setAttributes:]
-[NSExtension infoDictionary]
-[NSExtension setInfoDictionary:]
-[NSExtension extensionPointIdentifier]
-[NSExtension setExtensionPointIdentifier:]
-[NSExtension requestCompletionBlock]
-[NSExtension setRequestCompletionBlock:]
-[NSExtension requestCancellationBlock]
-[NSExtension setRequestCancellationBlock:]
-[NSExtension requestInterruptionBlock]
-[NSExtension setRequestInterruptionBlock:]
-[NSExtension _plugIn]
-[NSExtension _setPlugIn:]
-[NSExtension _setExtensionBundle:]
-[NSExtension _requestPostCompletionBlock]
-[NSExtension set_requestPostCompletionBlock:]
-[NSExtension _requestPostCompletionBlockWithItems]
-[NSExtension set_requestPostCompletionBlockWithItems:]
-[NSExtension _extensionExpirationIdentifiers]
-[NSExtension _setExtensionExpirationsIdentifiers:]
-[NSExtension _extensionServiceConnections]
-[NSExtension _setExtensionServiceConnections:]
-[NSExtension _extensionContexts]
-[NSExtension _setExtensionContexts:]
-[NSExtension _safePluginQueue]
-[NSExtension set_safePluginQueue:]
__NSExtensionPingLaunchdAfterEvent
____NSExtensionGetBundleHelperConnection_block_invoke
_initNSXPCInterface
_NSXPCInterfaceFunction
_initNSBundle
_NSBundleFunction
____NSExtensionGetLocalizedInfoDictionaryObjectForPlugInWithUUIDAndKeys_block_invoke
____NSExtensionGetLocalizedInfoDictionaryObjectForPlugInWithUUIDAndKeys_block_invoke_2
___copy_helper_block_772
___destroy_helper_block_773
____NSExtensionTearDownRequestWithIdentifier_block_invoke
____NSExtensionTearDownRequestWithIdentifier_block_invoke_2
___copy_helper_block_782
___destroy_helper_block_783
___copy_helper_block_787
___destroy_helper_block_788
____NSExtensionErrorCleanupHandler_block_invoke
___copy_helper_block_795
___destroy_helper_block_796
_initNSXPCConnection
_NSXPCConnectionFunction
_initPKHost
_PKHostFunction
_initkUTTypeData
_kUTTypeDataFunction
_initkUTTypeURL
_kUTTypeURLFunction
_initNSAttributedString
_NSAttributedStringFunction
_initNSRTFTextDocumentType
_NSRTFTextDocumentTypeFunction
_initNSDocumentTypeDocumentAttribute
_NSDocumentTypeDocumentAttributeFunction
-[_NSExtensionContextTransactionHolder dealloc]
+[_NSExtensionContextVendor _sharedExtensionContextVendor]
___58+[_NSExtensionContextVendor _sharedExtensionContextVendor]_block_invoke
+[_NSExtensionContextVendor _startListening]
___44+[_NSExtensionContextVendor _startListening]_block_invoke
+[_NSExtensionContextVendor _extensionDictionary]
___49+[_NSExtensionContextVendor _extensionDictionary]_block_invoke
+[_NSExtensionContextVendor _extensionPrincipalClass]
___53+[_NSExtensionContextVendor _extensionPrincipalClass]_block_invoke
+[_NSExtensionContextVendor _extensionMainStoryboard]
+[_NSExtensionContextVendor _extensionContextClass]
___51+[_NSExtensionContextVendor _extensionContextClass]_block_invoke
+[_NSExtensionContextVendor _completionConcurrentQueue]
___55+[_NSExtensionContextVendor _completionConcurrentQueue]_block_invoke
+[_NSExtensionContextVendor _expirationConcurrentQueue]
___55+[_NSExtensionContextVendor _expirationConcurrentQueue]_block_invoke
-[_NSExtensionContextVendor dealloc]
-[_NSExtensionContextVendor listener:shouldAcceptNewConnection:]
-[_NSExtensionContextVendor _shouldCreatePrincipalObject]
-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke
___Block_byref_object_copy_
___Block_byref_object_dispose_
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke102
___copy_helper_block_
___destroy_helper_block_
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke109
___copy_helper_block_110
___destroy_helper_block_111
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke116
___copy_helper_block_117
___destroy_helper_block_118
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke130
___copy_helper_block_134
___destroy_helper_block_135
___copy_helper_block_140
___destroy_helper_block_141
-[_NSExtensionContextVendor _tearDownContextWithUUID:]
___54-[_NSExtensionContextVendor _tearDownContextWithUUID:]_block_invoke
___54-[_NSExtensionContextVendor _tearDownContextWithUUID:]_block_invoke_2
___copy_helper_block_150
___destroy_helper_block_151
___copy_helper_block_154
___destroy_helper_block_155
-[_NSExtensionContextVendor _extensionContextForUUID:]
-[_NSExtensionContextVendor _setPrincipalObject:forUUID:]
-[_NSExtensionContextVendor _extensionServiceConnections]
-[_NSExtensionContextVendor _setExtensionServiceConnections:]
-[_NSExtensionContextVendor _extensionContexts]
-[_NSExtensionContextVendor _setExtensionContexts:]
-[_NSExtensionContextVendor _extensionPrincipalObjects]
-[_NSExtensionContextVendor _setExtensionPrincipalObjects:]
+[NSExtensionContext(NSVendorSupport) _extensionContextForIdentifier:]
+[NSExtensionContext initialize]
+[NSExtensionContext _extensionContextHostProtocolAllowedClassesForItems]
___73+[NSExtensionContext _extensionContextHostProtocolAllowedClassesForItems]_block_invoke
+[NSExtensionContext _extensionContextHostProtocol]
___51+[NSExtensionContext _extensionContextHostProtocol]_block_invoke
___copy_helper_block_275
___destroy_helper_block_276
+[NSExtensionContext _extensionContextVendorProtocol]
___53+[NSExtensionContext _extensionContextVendorProtocol]_block_invoke
___copy_helper_block_280
___destroy_helper_block_281
+[NSExtensionContext _extensionAuxiliaryHostProtocol]
+[NSExtensionContext _extensionAuxiliaryVendorProtocol]
+[NSExtensionContext supportsSecureCoding]
-[NSExtensionContext _derivedExtensionAuxiliaryHostProtocol]
___60-[NSExtensionContext _derivedExtensionAuxiliaryHostProtocol]_block_invoke
___60-[NSExtensionContext _derivedExtensionAuxiliaryHostProtocol]_block_invoke_2
___copy_helper_block_297
___destroy_helper_block_298
-[NSExtensionContext initWithInputItems:listenerEndpoint:contextUUID:]
-[NSExtensionContext initWithInputItems:contextUUID:]
-[NSExtensionContext initWithInputItems:]
-[NSExtensionContext init]
-[NSExtensionContext initWithCoder:]
-[NSExtensionContext copyWithZone:]
-[NSExtensionContext encodeWithCoder:]
-[NSExtensionContext invalidate]
-[NSExtensionContext dealloc]
-[NSExtensionContext _isHost]
-[NSExtensionContext _completeRequestReturningItemsSecondHalf:]
-[NSExtensionContext completeRequestReturningItems:completionHandler:]
___70-[NSExtensionContext completeRequestReturningItems:completionHandler:]_block_invoke
___70-[NSExtensionContext completeRequestReturningItems:completionHandler:]_block_invoke_2
___copy_helper_block_345
___destroy_helper_block_346
___copy_helper_block_351
___destroy_helper_block_352
-[NSExtensionContext cancelRequestWithError:]
___45-[NSExtensionContext cancelRequestWithError:]_block_invoke
___45-[NSExtensionContext cancelRequestWithError:]_block_invoke_2
___copy_helper_block_355
___destroy_helper_block_356
___copy_helper_block_359
___destroy_helper_block_360
-[NSExtensionContext openURL:completionHandler:]
___48-[NSExtensionContext openURL:completionHandler:]_block_invoke
___48-[NSExtensionContext openURL:completionHandler:]_block_invoke_2
___copy_helper_block_364
___destroy_helper_block_365
___copy_helper_block_368
___destroy_helper_block_369
-[NSExtensionContext _loadItemForPayload:completionHandler:]
___60-[NSExtensionContext _loadItemForPayload:completionHandler:]_block_invoke
___copy_helper_block_374
___destroy_helper_block_375
-[NSExtensionContext _loadPreviewImageForPayload:completionHandler:]
___68-[NSExtensionContext _loadPreviewImageForPayload:completionHandler:]_block_invoke
___copy_helper_block_379
___destroy_helper_block_380
-[NSExtensionContext _openURL:completion:]
___42-[NSExtensionContext _openURL:completion:]_block_invoke
___copy_helper_block_386
___destroy_helper_block_387
-[NSExtensionContext description]
-[NSExtensionContext _willPerformHostCallback:]
___47-[NSExtensionContext _willPerformHostCallback:]_block_invoke
___47-[NSExtensionContext _willPerformHostCallback:]_block_invoke_2
___copy_helper_block_406
___destroy_helper_block_407
-[NSExtensionContext ___nsx_pingHost:]
-[NSExtensionContext listener:shouldAcceptNewConnection:]
-[NSExtensionContext didConnectToVendor:]
-[NSExtensionContext inputItems]
-[NSExtensionContext _setInputItems:]
-[NSExtensionContext _UUID]
-[NSExtensionContext set_UUID:]
-[NSExtensionContext _requestCleanUpBlock]
-[NSExtensionContext _setRequestCleanUpBlock:]
-[NSExtensionContext _extensionHostProxy]
-[NSExtensionContext _setExtensionHostProxy:]
-[NSExtensionContext _extensionVendorProxy]
-[NSExtensionContext _setExtensionVendorProxy:]
-[NSExtensionContext _auxiliaryConnection]
-[NSExtensionContext _setAuxiliaryConnection:]
-[NSExtensionContext _auxiliaryListener]
-[NSExtensionContext _setAuxiliaryListener:]
-[NSExtensionContext _principalObject]
-[NSExtensionContext _setPrincipalObject:]
____NSExtensionCompleteRequestReturningItemsContinuation_block_invoke
____NSExtensionCompleteRequestReturningItemsContinuation_block_invoke_2
____NSExtensionCompleteRequestReturningItemsContinuation_block_invoke_3
___copy_helper_block_486
___destroy_helper_block_487
___copy_helper_block_490
___destroy_helper_block_491
____NSExtensionCompleteRequestReturningItemsContinuation_block_invoke496
____NSExtensionCompleteRequestReturningItemsContinuation_block_invoke_2499
___copy_helper_block_500
___destroy_helper_block_501
___copy_helper_block_504
___destroy_helper_block_505
___copy_helper_block_508
___destroy_helper_block_509
_initNSUUID
_NSUUIDFunction
_initNSXPCInterface
_NSXPCInterfaceFunction
_initNSXPCConnection
_NSXPCConnectionFunction
_initPKService
_PKServiceFunction
_initNSXPCListener
_NSXPCListenerFunction
_initNSBundle
_NSBundleFunction
__NSExtensionIsSafeKeyForObject
__NSExtensionIsOfSafeCollectionClassForPredicates
__NSExtensionIsSafeKeyPathForObjectsInCollection
___NSExtensionIsSafeKeyPathForObject_block_invoke
___NSExtensionIsSafeKeyPathForObject_block_invoke_2
__NSExtensionIsSafeKeyPathForSubcollectionsOfClassOfCollection
__NSExtensionIsSafePredicateForObjectWithSubquerySubstitutions
__NSExtensionIsSafeExpressionForObjectWithSubquerySubstitutions
____NSExtensionIsSafeKeyPathForSubcollectionsOfClassOfCollection_block_invoke
+[NSExtension(Filtering) initializeFiltering]
+[NSExtension(Filtering) evaluateActivationRule:withExtensionItemsRepresentation:]
___82+[NSExtension(Filtering) evaluateActivationRule:withExtensionItemsRepresentation:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
__NSExtensionPredicateForActivationRule
+[NSExtension(Filtering) predicateForActivationRule:]
____NSExtensionGenerateNSPredicateFromActivationDictionary_block_invoke
___Block_byref_object_copy_
___Block_byref_object_dispose_
____NSExtensionGatherPredicatesFromActivationDictionary_block_invoke
____NSExtensionGatherPredicatesFromActivationDictionary_block_invoke_2
___copy_helper_block_53
___destroy_helper_block_54
____NSExtensionGatherPredicatesFromActivationDictionary_block_invoke58
___copy_helper_block_61
___destroy_helper_block_62
____NSExtensionGatherPredicatesFromActivationDictionary_block_invoke66
___Block_byref_object_copy_67
___Block_byref_object_dispose_68
____NSExtensionGatherPredicatesFromActivationDictionary_block_invoke69
___copy_helper_block_91
___destroy_helper_block_92
___copy_helper_block_100
___destroy_helper_block_101
____NSExtensionGatherPredicatesFromActivationDictionary_block_invoke105
___copy_helper_block_110
___destroy_helper_block_111
_initNSCompoundPredicate
_NSCompoundPredicateFunction
_initNSMutableArray
_NSMutableArrayFunction
____NSExtensionGetActivationRules_block_invoke
_initNSPredicate
_NSPredicateFunction
_initNSDictionary
_NSDictionaryFunction
-[NSItemProvider init]
-[NSItemProvider initWithItem:typeIdentifier:]
___46-[NSItemProvider initWithItem:typeIdentifier:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NSItemProvider initWithContentsOfURL:]
___40-[NSItemProvider initWithContentsOfURL:]_block_invoke
___copy_helper_block_23
___destroy_helper_block_24
-[NSItemProvider dealloc]
-[NSItemProvider description]
-[NSItemProvider copyWithZone:]
+[NSItemProvider supportsSecureCoding]
-[NSItemProvider initWithCoder:]
___32-[NSItemProvider initWithCoder:]_block_invoke
___32-[NSItemProvider initWithCoder:]_block_invoke_2
___copy_helper_block_72
___destroy_helper_block_73
___copy_helper_block_76
___destroy_helper_block_77
___32-[NSItemProvider initWithCoder:]_block_invoke83
___copy_helper_block_86
___destroy_helper_block_87
___32-[NSItemProvider initWithCoder:]_block_invoke90
___32-[NSItemProvider initWithCoder:]_block_invoke_291
___copy_helper_block_94
___destroy_helper_block_95
-[NSItemProvider encodeWithCoder:]
-[NSItemProvider registerItemForTypeIdentifier:loadHandler:]
-[NSItemProvider hasItemConformingToTypeIdentifier:]
-[NSItemProvider registeredTypeIdentifiers]
-[NSItemProvider loadItemForTypeIdentifier:options:completionHandler:]
___70-[NSItemProvider loadItemForTypeIdentifier:options:completionHandler:]_block_invoke
___copy_helper_block_114
___destroy_helper_block_115
-[NSItemProvider _loadItemOfClass:forTypeIdentifier:options:coerceForCoding:completionHandler:]
-[NSItemProvider _loadPreviewImageOfClass:options:coerceForCoding:completionHandler:]
___85-[NSItemProvider _loadPreviewImageOfClass:options:coerceForCoding:completionHandler:]_block_invoke
___copy_helper_block_125
___destroy_helper_block_126
-[NSItemProvider _loadItemOfClass:withLoadHandler:options:coerceForCoding:completionHandler:]
___93-[NSItemProvider _loadItemOfClass:withLoadHandler:options:coerceForCoding:completionHandler:]_block_invoke
___copy_helper_block_138
___destroy_helper_block_139
-[NSItemProvider userInfo]
-[NSItemProvider setUserInfo:]
-[NSItemProvider _loadOperator]
-[NSItemProvider set_loadOperator:]
-[NSItemProvider _loadHandlers]
-[NSItemProvider set_loadHandlers:]
-[NSItemProvider(NSPreviewSupport) previewImageHandler]
-[NSItemProvider(NSPreviewSupport) setPreviewImageHandler:]
-[NSItemProvider(NSPreviewSupport) loadPreviewImageWithOptions:completionHandler:]
+[_NSItemProviderTypeCoercion typeCoercionForValue:targetClass:]
-[_NSItemProviderTypeCoercion dealloc]
-[_NSItemProviderTypeCoercion shouldCoerceForCoding]
-[_NSItemProviderTypeCoercion coerceValueAndReturnError:]
-[_NSItemProviderTypeCoercion _NSItemProviderTypeCoercion_coercedNSDataValueFromNSURLValue:error:]
-[_NSItemProviderTypeCoercion _NSItemProviderTypeCoercion_coercedNSFileWrapperValueFromNSURLValue:error:]
-[_NSItemProviderTypeCoercion _NSItemProviderTypeCoercion_coercedNSFileWrapperValueFromNSDataValue:error:]
+[_NSItemProviderTypeCoercion selectorForCoercionFromValue:toClass:]
+[_NSItemProviderTypeCoercion coercionClassStringFromClass:]
___60+[_NSItemProviderTypeCoercion coercionClassStringFromClass:]_block_invoke
-[_NSItemProviderTypeCoercion value]
-[_NSItemProviderTypeCoercion setValue:]
-[_NSItemProviderTypeCoercion targetClass]
-[_NSItemProviderTypeCoercion setTargetClass:]
_initNSImage
_NSImageFunction
_initNSFileWrapper
_NSFileWrapperFunction
____NSItemProviderExpectedValueClassAndProtocolsFromCompletionBlock_block_invoke
____NSItemProviderExpectedValueClassAndProtocolsFromCompletionBlock_block_invoke_2
___copy_helper_block_300
___destroy_helper_block_301
_initNSRegularExpression
_NSRegularExpressionFunction
___Block_byref_object_copy_
___Block_byref_object_dispose_
____NSItemProviderLoadHandlerForTypeConformingToTypeIdentifier_block_invoke
___copy_helper_block_312
___destroy_helper_block_313
_initUTTypeConformsTo
_initNSXPCCoder
_NSXPCCoderFunction
_initkUTTypeData
_kUTTypeDataFunction
_initkUTTagClassFilenameExtension
_kUTTagClassFilenameExtensionFunction
_initUTTypeCreatePreferredIdentifierForTag
_initkUTTypeFileURL
_kUTTypeFileURLFunction
_initkUTTypeURL
_kUTTypeURLFunction
-[_NSItemProviderExtensionVendorLoadOperator initWithExtensionContextIdentifier:]
-[_NSItemProviderExtensionVendorLoadOperator dealloc]
+[_NSItemProviderExtensionVendorLoadOperator supportsSecureCoding]
-[_NSItemProviderExtensionVendorLoadOperator initWithCoder:]
-[_NSItemProviderExtensionVendorLoadOperator encodeWithCoder:]
-[_NSItemProviderExtensionVendorLoadOperator loadItemForTypeIdentifier:completionHandler:expectedValueClass:options:]
___117-[_NSItemProviderExtensionVendorLoadOperator loadItemForTypeIdentifier:completionHandler:expectedValueClass:options:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[_NSItemProviderExtensionVendorLoadOperator loadPreviewImageWithCompletionHandler:expectedValueClass:options:]
___111-[_NSItemProviderExtensionVendorLoadOperator loadPreviewImageWithCompletionHandler:expectedValueClass:options:]_block_invoke
___copy_helper_block_37
___destroy_helper_block_38
-[_NSItemProviderExtensionVendorLoadOperator identifier]
-[_NSItemProviderExtensionVendorLoadOperator setIdentifier:]
-[_NSItemProviderExtensionVendorLoadOperator extensionContextIdentifier]
-[_NSItemProviderExtensionVendorLoadOperator setExtensionContextIdentifier:]
-[_NSItemProviderCopyingLoadOperator initWithItemProvider:]
-[_NSItemProviderCopyingLoadOperator dealloc]
+[_NSItemProviderCopyingLoadOperator supportsSecureCoding]
-[_NSItemProviderCopyingLoadOperator initWithCoder:]
-[_NSItemProviderCopyingLoadOperator encodeWithCoder:]
-[_NSItemProviderCopyingLoadOperator loadItemForTypeIdentifier:completionHandler:expectedValueClass:options:]
-[_NSItemProviderCopyingLoadOperator loadPreviewImageWithCompletionHandler:expectedValueClass:options:]
-[_NSItemProviderCopyingLoadOperator _loadItemsForTypeIdentifiers:itemProvider:]
___Block_byref_object_copy_
___Block_byref_object_dispose_
___80-[_NSItemProviderCopyingLoadOperator _loadItemsForTypeIdentifiers:itemProvider:]_block_invoke
___80-[_NSItemProviderCopyingLoadOperator _loadItemsForTypeIdentifiers:itemProvider:]_block_invoke_2
___copy_helper_block_147
___destroy_helper_block_148
___copy_helper_block_154
___destroy_helper_block_155
-[_NSItemProviderCopyingLoadOperator _sandboxedResourceForItemIfNeeded:error:]
-[_NSItemProviderCopyingLoadOperator itemProvider]
-[_NSItemProviderCopyingLoadOperator setItemProvider:]
-[_NSItemProviderCopyingLoadOperator loadedItems]
-[_NSItemProviderCopyingLoadOperator setLoadedItems:]
-[_NSItemProviderSandboxedResource initWithContentsOfURL:error:]
-[_NSItemProviderSandboxedResource dealloc]
+[_NSItemProviderSandboxedResource supportsSecureCoding]
-[_NSItemProviderSandboxedResource initWithCoder:]
-[_NSItemProviderSandboxedResource encodeWithCoder:]
-[_NSItemProviderSandboxedResource copyWithZone:]
-[_NSItemProviderSandboxedResource resolveURLAndReturnError:]
-[_NSItemProviderSandboxedResource resourceURL]
-[_NSItemProviderSandboxedResource setResourceURL:]
-[_NSItemProviderSandboxedResource sandboxExtensionToken]
-[_NSItemProviderSandboxedResource setSandboxExtensionToken:]
-[_NSItemProviderSandboxedResource isAccessingSecurityScopedResource]
-[_NSItemProviderSandboxedResource setAccessingSecurityScopedResource:]
_initNSPOSIXErrorDomain
_NSPOSIXErrorDomainFunction
_initNSUUID
_NSUUIDFunction
_initPKService
_PKServiceFunction
GCC_except_table15
GCC_except_table18
GCC_except_table29
GCC_except_table57
GCC_except_table101
GCC_except_table105
GCC_except_table110
GCC_except_table115
GCC_except_table155
GCC_except_table20
GCC_except_table1
GCC_except_table5
GCC_except_table17
GCC_except_table29
GCC_except_table31
GCC_except_table35
GCC_except_table52
GCC_except_table24
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke._d
-[NSExtension _completeRequestReturningItems:forExtensionContextWithUUID:completion:]._d
-[NSExtension _cancelRequestWithError:forExtensionContextWithUUID:completion:]._d
___33-[NSExtension _safelyBeginUsing:]_block_invoke._d
___31-[NSExtension _safelyEndUsing:]_block_invoke._d
-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]._d
___54-[_NSExtensionContextVendor _tearDownContextWithUUID:]_block_invoke._d
-[NSExtensionContext completeRequestReturningItems:completionHandler:]._d
-[NSExtensionContext cancelRequestWithError:]._d
-[NSExtensionContext openURL:completionHandler:]._d
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke_2._m
___64+[NSExtension beginMatchingExtensionsWithAttributes:completion:]_block_invoke_2._m203
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke293._m
___86-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:]_block_invoke314._m
___78-[NSExtension _cancelRequestWithError:forExtensionContextWithUUID:completion:]_block_invoke_2._m
___33-[NSExtension _safelyBeginUsing:]_block_invoke_4._m
___33-[NSExtension _safelyBeginUsing:]_block_invoke_4._m498
___33-[NSExtension _safelyBeginUsing:]_block_invoke_3._m
___33-[NSExtension _safelyBeginUsing:]_block_invoke503._m
___33-[NSExtension _safelyBeginUsing:]_block_invoke_3._m520
___33-[NSExtension _safelyBeginUsing:]_block_invoke_3._m528
__NSExtensionTearDownRequestCompletion._m
__NSExtensionTearDownRequestWithIdentifier._m
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke102._m
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke109._m
___105-[_NSExtensionContextVendor _beginRequestWithExtensionItems:listenerEndpoint:withContextUUID:completion:]_block_invoke130._m
-[NSExtensionContext completeRequestReturningItems:completionHandler:]._m
-[NSExtensionContext completeRequestReturningItems:completionHandler:]._m343
-[NSExtensionContext completeRequestReturningItems:completionHandler:]._m344
___70-[NSExtensionContext completeRequestReturningItems:completionHandler:]_block_invoke._m
__NSExtensionCompleteRequestReturningItemsContinuation._m
__NSExtensionCompleteRequestReturningItemsContinuation._m482
__NSExtensionCompleteRequestReturningItemsContinuation._m484
__NSExtensionCompleteRequestReturningItemsContinuation._m485
__NSExtensionCompleteRequestReturningItemsContinuation._m497
__NSExtensionCompleteRequestReturningItemsContinuation._m498
___block_descriptor_tmp
___block_descriptor_tmp92
___block_descriptor_tmp111
___block_descriptor_tmp185
___block_descriptor_tmp200
___block_descriptor_tmp209
___block_descriptor_tmp216
___block_descriptor_tmp220
___block_descriptor_tmp283
___block_descriptor_tmp287
___block_descriptor_tmp292
___block_descriptor_tmp300
___block_descriptor_tmp309
___block_descriptor_tmp313
___block_descriptor_tmp319
___block_descriptor_tmp326
___block_descriptor_tmp330
___block_descriptor_tmp342
___block_descriptor_tmp358
___block_descriptor_tmp368
___block_descriptor_tmp372
___block_descriptor_tmp382
___block_descriptor_tmp411
___block_literal_global
___block_descriptor_tmp418
___block_descriptor_tmp430
___block_descriptor_tmp435
___block_descriptor_tmp439
___block_descriptor_tmp445
___block_descriptor_tmp449
___block_descriptor_tmp458
___block_descriptor_tmp464
___block_descriptor_tmp468
___block_descriptor_tmp474
___block_descriptor_tmp482
___block_descriptor_tmp502
___block_descriptor_tmp508
___block_descriptor_tmp513
___block_descriptor_tmp517
___block_descriptor_tmp525
___block_descriptor_tmp533
___block_descriptor_tmp537
___block_descriptor_tmp541
___block_descriptor_tmp545
___block_descriptor_tmp551
___block_descriptor_tmp555
_NSExtensionIdentifierNameL
_NSExtensionProtocolNameL
_NSExtensionPointNameL
_NSExtensionVersionNameL
___block_descriptor_tmp762
___block_literal_global763
___block_descriptor_tmp768
___block_literal_global769
___block_descriptor_tmp776
___block_descriptor_tmp785
___block_descriptor_tmp790
___block_descriptor_tmp798
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp21
___block_literal_global22
___block_descriptor_tmp38
___block_literal_global39
___block_descriptor_tmp49
___block_literal_global50
___block_descriptor_tmp59
___block_literal_global60
___block_descriptor_tmp63
___block_literal_global64
___block_descriptor_tmp66
___block_literal_global67
___block_descriptor_tmp106
___block_descriptor_tmp113
___block_descriptor_tmp121
___block_descriptor_tmp137
___block_descriptor_tmp143
___block_descriptor_tmp153
___block_descriptor_tmp157
___block_descriptor_tmp251
___block_literal_global252
___block_descriptor_tmp278
___block_descriptor_tmp283
___block_descriptor_tmp286
___block_literal_global287
___block_descriptor_tmp300
___block_descriptor_tmp348
___block_descriptor_tmp354
___block_descriptor_tmp358
___block_descriptor_tmp362
___block_descriptor_tmp367
___block_descriptor_tmp372
___block_descriptor_tmp378
___block_descriptor_tmp382
___block_descriptor_tmp389
___block_descriptor_tmp404
___block_literal_global405
___block_descriptor_tmp409
___block_descriptor_tmp489
___block_descriptor_tmp494
___block_descriptor_tmp503
___block_descriptor_tmp507
___block_descriptor_tmp511
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp27
___block_literal_global28
___block_descriptor_tmp128
___block_literal_global129
___block_descriptor_tmp
___block_descriptor_tmp27
___block_literal_global
___block_descriptor_tmp50
___block_descriptor_tmp57
___block_descriptor_tmp65
___block_descriptor_tmp95
___block_descriptor_tmp104
___block_descriptor_tmp114
___block_descriptor_tmp144
___block_literal_global145
___block_descriptor_tmp
___block_descriptor_tmp26
___block_descriptor_tmp75
___block_descriptor_tmp80
___block_descriptor_tmp89
___block_descriptor_tmp93
___block_literal_global
___block_descriptor_tmp97
___block_descriptor_tmp118
___block_descriptor_tmp128
___block_descriptor_tmp142
___block_descriptor_tmp243
___block_literal_global244
___block_descriptor_tmp283
___block_literal_global284
___block_descriptor_tmp304
___block_descriptor_tmp316
__NSItemProviderIdentifierPayloadKey
__NSItemProviderTypeIdentifierPayloadKey
__NSItemProviderExpectedValueClassPayloadKey
__NSItemProviderOptionsPayloadKey
___block_descriptor_tmp
___block_descriptor_tmp40
___block_descriptor_tmp151
___block_descriptor_tmp158
_OBJC_IVAR_$_NSExtensionItem._userInfo
_OBJC_IVAR_$_NSExtension.__plugIn
_OBJC_IVAR_$_NSExtension._identifier
_OBJC_IVAR_$_NSExtension._version
_OBJC_IVAR_$_NSExtension._attributes
_OBJC_IVAR_$_NSExtension._infoDictionary
_OBJC_IVAR_$_NSExtension._extensionPointIdentifier
_OBJC_IVAR_$_NSExtension.__safePluginQueue
_OBJC_IVAR_$_NSExtension.__extensionServiceConnections
_OBJC_IVAR_$_NSExtension.__extensionExpirationIdentifiers
_OBJC_IVAR_$_NSExtension.__extensionContexts
_OBJC_IVAR_$_NSExtension._requestCompletionBlock
_OBJC_IVAR_$_NSExtension._requestCancellationBlock
_OBJC_IVAR_$_NSExtension._requestInterruptionBlock
_OBJC_IVAR_$_NSExtension.__requestPostCompletionBlock
_OBJC_IVAR_$_NSExtension.__requestPostCompletionBlockWithItems
_OBJC_IVAR_$_NSExtension.__extensionBundle
_OBJC_IVAR_$__NSExtensionContextVendor.__extensionPrincipalObjects
_OBJC_IVAR_$__NSExtensionContextVendor.__extensionServiceConnections
_OBJC_IVAR_$__NSExtensionContextVendor.__extensionContexts
_OBJC_IVAR_$_NSExtensionContext.__UUID
_OBJC_IVAR_$_NSExtensionContext._inputItems
_OBJC_IVAR_$_NSExtensionContext.__auxiliaryConnection
_OBJC_IVAR_$_NSExtensionContext.__auxiliaryListener
_OBJC_IVAR_$_NSExtensionContext.__requestCleanUpBlock
_OBJC_IVAR_$_NSExtensionContext.__extensionHostProxy
_OBJC_IVAR_$_NSExtensionContext.__extensionVendorProxy
_OBJC_IVAR_$_NSExtensionContext.__principalObject
_OBJC_IVAR_$_NSItemProvider.__loadHandlers
_OBJC_IVAR_$_NSItemProvider._userInfo
_OBJC_IVAR_$_NSItemProvider.__previewImageHandler
_OBJC_IVAR_$_NSItemProvider.__loadOperator
_OBJC_IVAR_$__NSItemProviderTypeCoercion._value
_OBJC_IVAR_$__NSItemProviderTypeCoercion._targetClass
_OBJC_IVAR_$__NSItemProviderExtensionVendorLoadOperator._identifier
_OBJC_IVAR_$__NSItemProviderExtensionVendorLoadOperator._extensionContextIdentifier
_OBJC_IVAR_$__NSItemProviderCopyingLoadOperator._itemProvider
_OBJC_IVAR_$__NSItemProviderCopyingLoadOperator._loadedItems
_OBJC_IVAR_$__NSItemProviderSandboxedResource._resourceURL
_OBJC_IVAR_$__NSItemProviderSandboxedResource._sandboxExtensionToken
_OBJC_IVAR_$__NSItemProviderSandboxedResource._accessingSecurityScopedResource
_OBJC_CLASS_$__NSItemProviderTypeCoercion
_OBJC_METACLASS_$__NSItemProviderTypeCoercion
_OBJC_CLASS_$__NSItemProviderExtensionVendorLoadOperator
_OBJC_METACLASS_$__NSItemProviderExtensionVendorLoadOperator
_OBJC_CLASS_$__NSItemProviderCopyingLoadOperator
_OBJC_CLASS_$__NSItemProviderSandboxedResource
_OBJC_METACLASS_$__NSItemProviderCopyingLoadOperator
_OBJC_METACLASS_$__NSItemProviderSandboxedResource
_getNSCalendarClass
_getNSDateClass
_getNSDictionaryClass
_getNSDocumentTypeDocumentAttribute
_getNSRTFTextDocumentType
_getNSAttributedStringClass
_getkUTTypeURL
_getkUTTypeData
_getPKHostClass
_getNSXPCConnectionClass
_getNSBundleClass
_getNSXPCInterfaceClass
_getNSBundleClass
_getNSXPCListenerClass
_getPKServiceClass
_getNSXPCConnectionClass
_getNSXPCInterfaceClass
_getNSUUIDClass
_getNSDictionaryClass
_getNSMutableArrayClass
_getNSCompoundPredicateClass
_getNSPredicateClass
_getkUTTypeURL
_getkUTTypeFileURL
_getkUTTagClassFilenameExtension
_getkUTTypeData
_getNSXPCCoderClass
_getNSFileWrapperClass
_getNSImageClass
_getNSRegularExpressionClass
_softLinkUTTypeConformsTo
_softLinkUTTypeCreatePreferredIdentifierForTag
_getNSUUIDClass
_getNSPOSIXErrorDomain
_getPKServiceClass
_classNSDictionary
_FoundationLibrary.frameworkLibrary
_classNSDate
_classNSCalendar
__NSExtensionAssertionLoggingEnabled
__NSExtensionDiscoveryLoggingEnabled
-[NSExtension _reallyBeginExtensionRequestWithInputItems:listenerEndpoint:completion:].one_shot_key
___33-[NSExtension _safelyBeginUsing:]_block_invoke_3.kRunOnceKey
___NSExtensionPingLaunchdObserver
__NSExtensionGetBundleHelperConnection.bundleHelperConnection
__NSExtensionGetBundleHelperConnection.onceToken
_classNSXPCInterface
_FoundationLibrary.frameworkLibrary
_classNSBundle
_classNSXPCConnection
_classPKHost
_PlugInKitLibrary.frameworkLibrary
_constantkUTTypeData
_CoreServicesLibrary.frameworkLibrary
_constantkUTTypeURL
_classNSAttributedString
_UIFoundationLibrary.frameworkLibrary
_constantNSRTFTextDocumentType
_constantNSDocumentTypeDocumentAttribute
+[_NSExtensionContextVendor _sharedExtensionContextVendor].__instance
+[_NSExtensionContextVendor _sharedExtensionContextVendor].onceToken
+[_NSExtensionContextVendor _startListening].listener
+[_NSExtensionContextVendor _startListening].onceToken
+[_NSExtensionContextVendor _extensionDictionary].onceToken
+[_NSExtensionContextVendor _extensionDictionary].__extensionDictionary
+[_NSExtensionContextVendor _extensionPrincipalClass].__extensionPrincipalClass
+[_NSExtensionContextVendor _extensionPrincipalClass].onceToken
+[_NSExtensionContextVendor _extensionContextClass].__extensionContextClass
+[_NSExtensionContextVendor _extensionContextClass].onceToken
+[_NSExtensionContextVendor _completionConcurrentQueue].onceToken
+[_NSExtensionContextVendor _completionConcurrentQueue].queue
+[_NSExtensionContextVendor _expirationConcurrentQueue].onceToken
+[_NSExtensionContextVendor _expirationConcurrentQueue].queue
__kNSExtensionTransacationHolderKey
_item_provider_and_extension_context_classes
_whitelist_class_array_length
+[NSExtensionContext _extensionContextHostProtocolAllowedClassesForItems].onceToken
+[NSExtensionContext _extensionContextHostProtocolAllowedClassesForItems].__allowedClassesForItems
+[NSExtensionContext _extensionContextHostProtocol].__xpcInterface
+[NSExtensionContext _extensionContextHostProtocol].onceToken
+[NSExtensionContext _extensionContextVendorProtocol].__xpcInterface
+[NSExtensionContext _extensionContextVendorProtocol].onceToken
-[NSExtensionContext _derivedExtensionAuxiliaryHostProtocol].protocol_creation_queue
-[NSExtensionContext _derivedExtensionAuxiliaryHostProtocol].onceToken
_classNSUUID
_FoundationLibrary.frameworkLibrary
_classNSXPCInterface
_classNSXPCConnection
_classPKService
_PlugInKitLibrary.frameworkLibrary
_classNSXPCListener
_classNSBundle
__NSExtensionUseAlternateRules
__NSExtensionGenerateNSPredicateFromActivationDictionary.predicateCache
__NSExtensionGenerateNSPredicateFromActivationDictionary.once
_classNSCompoundPredicate
_FoundationLibrary.frameworkLibrary
_classNSMutableArray
__NSExtensionGetActivationRules.onceToken
__NSExtensionGetActivationRules._activation_rules
__NSExtensionGetActivationRules._anchor
_classNSPredicate
_classNSDictionary
+[_NSItemProviderTypeCoercion coercionClassStringFromClass:].__supportedClasses
+[_NSItemProviderTypeCoercion coercionClassStringFromClass:].__once
_classNSImage
_AppKitLibrary.frameworkLibrary
_classNSFileWrapper
_FoundationLibrary.frameworkLibrary
__NSItemProviderExpectedValueClassAndProtocolsFromCompletionBlock.__tokenizer
__NSItemProviderExpectedValueClassAndProtocolsFromCompletionBlock.onceToken
_classNSRegularExpression
_CoreServicesLibrary.frameworkLibrary
_classNSXPCCoder
_constantkUTTypeData
_constantkUTTagClassFilenameExtension
_constantkUTTypeFileURL
_constantkUTTypeURL
_constantNSPOSIXErrorDomain
_FoundationLibrary.frameworkLibrary
_classNSUUID
_classPKService
_PlugInKitLibrary.frameworkLibrary
_NSExtensionAdditionalServiceName
_NSExtensionErrorDomain
_NSExtensionIdentifierName
_NSExtensionInternalErrorException
_NSExtensionIsPredicateSafeToExecuteWithObject
_NSExtensionIsSafeKeyPathForObject
_NSExtensionItemAttachmentsKey
_NSExtensionItemAttributedContentTextKey
_NSExtensionItemAttributedTitleKey
_NSExtensionItemsAndErrorsKey
_NSExtensionJavaScriptFinalizeArgumentKey
_NSExtensionJavaScriptPreprocessingResultsKey
_NSExtensionMain
_NSExtensionPointName
_NSExtensionPointUIServices
_NSExtensionUUIDName
_NSExtensionVersionName
_NSItemProviderErrorDomain
_NSItemProviderOptionsDispatchModeAsynchronous
_NSItemProviderOptionsDispatchModeKey
_NSItemProviderPreferredImageSizeKey
_NSTypeIdentifierAddressText
_NSTypeIdentifierDateText
_NSTypeIdentifierPhoneNumberText
_NSTypeIdentifierTransitInformationText
_OBJC_CLASS_$_NSExtension
_OBJC_CLASS_$_NSExtensionContext
_OBJC_CLASS_$_NSExtensionItem
_OBJC_CLASS_$_NSItemProvider
_OBJC_CLASS_$__NSExtensionContextTransactionHolder
_OBJC_CLASS_$__NSExtensionContextVendor
_OBJC_METACLASS_$_NSExtension
_OBJC_METACLASS_$_NSExtensionContext
_OBJC_METACLASS_$_NSExtensionItem
_OBJC_METACLASS_$_NSItemProvider
_OBJC_METACLASS_$__NSExtensionContextTransactionHolder
_OBJC_METACLASS_$__NSExtensionContextVendor
__NSExtensionInstallRunloopObserverToPingLaunchdAfterEvent
_APP_SANDBOX_READ
_CFAbsoluteTimeGetCurrent
_CFAutorelease
_CFDataCreateWithBytesNoCopy
_CFErrorCopyDescription
_CFErrorCreate
_CFLog
_CFNumberCreate
_CFPreferencesCopyAppValue
_CFPreferencesGetAppBooleanValue
_CFPropertyListCreateWithData
_CFRelease
_CFRunLoopAddObserver
_CFRunLoopAddTimer
_CFRunLoopGetMain
_CFRunLoopObserverCreate
_CFRunLoopTimerCreateWithHandler
_CFRunLoopTimerInvalidate
_CFSetCreate
_CFStringCreateWithCString
_CFStringCreateWithFormat
_CFStringGetFileSystemRepresentation
_CFStringGetLength
_CFStringGetMaximumSizeOfFileSystemRepresentation
_CFURLStartAccessingSecurityScopedResource
_CFURLStopAccessingSecurityScopedResource
_NSInternalInconsistencyException
_NSInvalidArgumentException
_OBJC_CLASS_$_NSArray
_OBJC_CLASS_$_NSCache
_OBJC_CLASS_$_NSData
_OBJC_CLASS_$_NSDate
_OBJC_CLASS_$_NSDictionary
_OBJC_CLASS_$_NSException
_OBJC_CLASS_$_NSInvocation
_OBJC_CLASS_$_NSMethodSignature
_OBJC_CLASS_$_NSMutableArray
_OBJC_CLASS_$_NSMutableDictionary
_OBJC_CLASS_$_NSMutableSet
_OBJC_CLASS_$_NSObject
_OBJC_CLASS_$_NSURL
_OBJC_METACLASS_$_NSObject
__Block_has_signature
__Block_object_assign
__Block_object_dispose
__Block_signature
__CFURLAttachSecurityScopeToFileURL
__CFURLCopySecurityScopeFromFileURL
__NSConcreteGlobalBlock
__NSConcreteStackBlock
__Unwind_Resume
___CFConstantStringClassReference
___error
___objc_personality_v0
___stack_chk_fail
___stack_chk_guard
___strlcat_chk
___strlcpy_chk
__dispatch_main_q
__dispatch_queue_attr_concurrent
__objc_empty_cache
__os_activity_initiate
__os_activity_start
__os_trace_with_buffer
_abort
_calloc
_class_getName
_dispatch_after
_dispatch_async
_dispatch_get_global_queue
_dispatch_get_specific
_dispatch_once
_dispatch_queue_attr_make_with_qos_class
_dispatch_queue_create
_dispatch_queue_get_specific
_dispatch_queue_set_specific
_dispatch_release
_dispatch_semaphore_create
_dispatch_semaphore_signal
_dispatch_semaphore_wait
_dispatch_sync
_dispatch_time
_dladdr
_dlopen
_dlsym
_free
_getsectiondata
_kCFAllocatorMalloc
_kCFAllocatorNull
_kCFErrorLocalizedDescriptionKey
_kCFPreferencesAnyApplication
_kCFRunLoopCommonModes
_malloc
_objc_allocateProtocol
_objc_assign_global
_objc_assign_ivar
_objc_assign_strongCast
_objc_autoreleasePoolPop
_objc_autoreleasePoolPush
_objc_collectingEnabled
_objc_enumerationMutation
_objc_getClass
_objc_getProperty
_objc_getProtocol
_objc_memmove_collectable
_objc_msgSend
_objc_msgSendSuper2
_objc_registerProtocol
_objc_setAssociatedObject
_objc_setProperty
_os_activity_end
_protocol_addProtocol
_protocol_getName
_sandbox_extension_issue_file
_sel_registerName
_strerror
_strlen
_xpc_dictionary_set_string
_xpc_transaction_begin
_xpc_transaction_end
dyld_stub_binder
