/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:52:19 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Reminders.app/Contents/MacOS/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSMenuItem.h>

@interface RemindersPriorityMenuItem : NSMenuItem
+(void)validateSubmenuItem:(id)arg1 withReminders:(id)arg2 ;
-(id)initIsContextual:(char)arg1 ;
-(void)validateWithReminders:(id)arg1 ;
-(id)submenuItemWithTitle:(id)arg1 keyEquivalent:(id)arg2 tag:(unsigned long long)arg3 isContextual:(char)arg4 ;
-(void)setTarget:(id)arg1 ;
-(void)setAction:(SEL)arg1 ;
@end

