/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:52:19 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Reminders.app/Contents/MacOS/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <AppKit/NSView.h>

@interface RemindersLayerView : NSView {

	/*^block*/id _remindersUpdateLayerHandler;

}

@property (copy) id remindersUpdateLayerHandler;              //@synthesize remindersUpdateLayerHandler=_remindersUpdateLayerHandler - In the implementation block
-(id)remindersUpdateLayerHandler;
-(void)setRemindersUpdateLayerHandler:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)updateLayer;
-(id)hitTest:(CGPoint)arg1 ;
-(char)isFlipped;
-(char)wantsUpdateLayer;
@end

