/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:52:19 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Reminders.app/Contents/MacOS/Reminders
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Reminders/Reminders-Structs.h>
#import <AppKit/NSTextView.h>

@class ShadowTextFieldCell;

@interface ShadowTextView : NSTextView {

	ShadowTextFieldCell* _shadowCell;

}

@property (retain) ShadowTextFieldCell * shadowCell;              //@synthesize shadowCell=_shadowCell - In the implementation block
-(void)setShadowCell:(ShadowTextFieldCell *)arg1 ;
-(ShadowTextFieldCell *)shadowCell;
-(char)resignFirstResponder;
-(char)becomeFirstResponder;
-(void)setTypingAttributes:(id)arg1 ;
-(char)isRichText;
-(char)readSelectionFromPasteboard:(id)arg1 ;
-(void)setMarkedText:(id)arg1 selectedRange:(NSRange)arg2 replacementRange:(NSRange)arg3 ;
@end

