/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:03 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/CleanMyMac 2.app/Contents/Frameworks/DevMateIssues.framework/Versions/A/Frameworks/CrashReporter.framework/Versions/A/CrashReporter
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <CrashReporter/CrashReporter-Structs.h>
@interface PLCrashSignalHandler : NSObject {

	darwin_sigaltstack* _sigstk;

}
+(id)sharedHandler;
-(char)registerHandlerForSignal:(int)arg1 error:(id*)arg2 ;
-(char)registerHandlerWithCallback:(/*function pointer*/void*)arg1 context:(void*)arg2 error:(id*)arg3 ;
-(id)init;
@end

