/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:05:15 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /usr/libexec/MiniTerm.app/Contents/MacOS/MiniTerm
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MiniTerm/MiniTerm-Structs.h>
#import <MiniTerm/NSApplicationDelegate.h>

@class NSString;

@interface PromptChat : NSObject <NSApplicationDelegate> {

	id text;
	int fromline;
	int match;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)input:(id)arg1 ;
-(void)display:(char*)arg1 length:(unsigned)arg2 ;
-(void)continuechat:(id)arg1 ;
-(void)cancelchat:(id)arg1 ;
-(char)textView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(void)awakeFromNib;
@end

