/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:11:03 AM Central European Standard Time
* Operating System: Versie 10.10.2 (build 14C109)
* Image Source: /Applications/HWMonitor.app/Contents/MacOS/HWMonitor
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@interface HWMValueFormatter : NSObject
+(id)formattedValue:(id)arg1 usingRulesOfGroup:(id)arg2 configuration:(id)arg3 ;
+(id)strippedValue:(id)arg1 usingRulesOfGroup:(id)arg2 configuration:(id)arg3 ;
+(char)float:(float)arg1 between:(float)arg2 and:(float)arg3 ;
@end

