/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:11:03 AM Central European Standard Time
* Operating System: Versie 10.10.2 (build 14C109)
* Image Source: /Applications/HWMonitor.app/Contents/MacOS/HWMonitor
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <HWMonitor/PopupSensorCell.h>

@class NSImage, NSNumber;

@interface PopupBatteryCell : PopupSensorCell {

	NSImage* _gaugeImage;
	NSNumber* _gaugeLevel;

}

@property (nonatomic,retain) NSNumber * gaugeLevel;              //@synthesize gaugeLevel=_gaugeLevel - In the implementation block
-(void)colorThemeChanged:(id)arg1 ;
-(void)deallocate;
-(NSNumber *)gaugeLevel;
-(void)setGaugeLevel:(NSNumber *)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)initialize;
@end

