/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:15:49 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsAnalysisCore.framework/Versions/A/InstrumentsAnalysisCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <InstrumentsAnalysisCore/InstrumentsAnalysisCore-Structs.h>
@class XRAnalysisCoreTableSpec, XRAnalysisCoreTableSchema, XRStorageManager, NSURL;

@interface XRIndexedStorage : NSObject {

	XRAnalysisCoreTableSpec* _spec;
	XRAnalysisCoreTableSchema* _schema;
	XRStorageManager* _store;
	NSURL* _baseFileURL;

}

@property (nonatomic,readonly) XRAnalysisCoreTableSpec * spec;                  //@synthesize spec=_spec - In the implementation block
@property (nonatomic,readonly) XRAnalysisCoreTableSchema * schema;              //@synthesize schema=_schema - In the implementation block
@property (nonatomic,readonly) XRStorageManager * store;                        //@synthesize store=_store - In the implementation block
@property (nonatomic,readonly) NSURL * baseFileURL;                             //@synthesize baseFileURL=_baseFileURL - In the implementation block
+(id)storageWithSchema:(id)arg1 baseFileURL:(id)arg2 spec:(id)arg3 ;
+(id)storageWithSchema:(id)arg1 baseFileURL:(id)arg2 ;
-(void)query:(id)arg1 tableID:(unsigned)arg2 handler:(id)arg3 ;
-(void)grantExternalReadOnlyAccess:(XRStorageManagerExternalAccessPack*)arg1 ;
-(NSURL *)baseFileURL;
-(void)grantExternalReadWriteAccess:(XRStorageManagerExternalAccessPack*)arg1 ;
-(id)initWithSchema:(id)arg1 baseFileURL:(id)arg2 spec:(id)arg3 ;
-(id)initWithSchema:(id)arg1 baseFileURL:(id)arg2 ;
-(XRAnalysisCoreTableSchema *)schema;
-(XRStorageManager *)store;
-(XRAnalysisCoreTableSpec *)spec;
-(char)optimize;
@end

