/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:30:04 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Dictionary.app/Contents/MacOS/Dictionary
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class DictionaryObj, NSString, NSArray, NSOperationQueue;

@interface DictionarySearchOperation : NSOperation {

	DictionaryObj* _dictionary;
	NSString* _searchString;
	long long _searchMethod;
	long long _maxRecord;
	char _allowGuess;
	NSArray* _guessedWords;
	long long _transactionID;
	NSOperationQueue* _queue;
	void* _userInfo;

}
-(id)_commonInitWithDictionary:(id)arg1 searchString:(id)arg2 transactionID:(long long)arg3 queue:(id)arg4 userInfo:(void*)arg5 ;
-(id)initWithDictionary:(id)arg1 searchString:(id)arg2 searchMethod:(long long)arg3 maxRecord:(long long)arg4 allowGuess:(char)arg5 transactionID:(long long)arg6 queue:(id)arg7 userInfo:(void*)arg8 ;
-(id)initWithDictionary:(id)arg1 searchString:(id)arg2 guessedWords:(id)arg3 transactionID:(long long)arg4 queue:(id)arg5 userInfo:(void*)arg6 ;
-(void)dealloc;
-(void)main;
@end

