/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 12:17:08 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Dictionary.app/Contents/MacOS/Dictionary
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct CGPoint {
	double x;
	double y;
} CGPoint;

typedef struct CGSize {
	double width;
	double height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct ULocaleDisplayNames* ULocaleDisplayNamesRef;

typedef struct __CFArray* CFArrayRef;

typedef struct __DCSRecord* DCSRecordRef;

typedef struct _NSZone* NSZoneRef;

typedef struct __DCSDictionary* DCSDictionaryRef;

