/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:30:04 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Dictionary.app/Contents/MacOS/Dictionary
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <Dictionary/Dictionary-Structs.h>
@class NSMutableDictionary, NSString, NSArray, DictionaryRecordArray;

@interface DictionaryRecordRepository : NSObject {

	NSMutableDictionary* _recordArrays;
	NSString* _searchString;
	NSString* _lastFilterID;
	char _needToBuildHeadwords;
	NSArray* _lastHeadwords;
	char _needToBuildHeadwordRecords;
	NSString* _lastHeadwordFilter;
	unsigned long long _lastHeadwordRefsCount;
	const _CFArray* _lastHeadwordRefs;
	DictionaryRecordArray* _lastHeadwordRecords;
	NSMutableDictionary* _properties;

}
+(id)recordRepositoryWithSearchString:(id)arg1 ;
-(id)recordsWithHeadword:(id)arg1 inDictionary:(id)arg2 ;
-(char)hasRecordInDictionary:(id)arg1 ;
-(id)propertyForDictionary:(id)arg1 withKey:(id)arg2 ;
-(void)removeRecordsFromDictionary:(id)arg1 ;
-(void)addRecordsFromRecordArray:(id)arg1 fromDictionary:(id)arg2 ;
-(void)setProperty:(id)arg1 forDictionary:(id)arg2 withKey:(id)arg3 ;
-(id)headwordsInDictionary:(id)arg1 ;
-(id)searchKeyForHeadword:(id)arg1 ;
-(id)recordsWithKeyword:(id)arg1 inDictionary:(id)arg2 ;
-(void)_addRecords:(id)arg1 withIdentifier:(id)arg2 ;
-(id)_recordArrays;
-(unsigned long long)_createRecordRefList:(const _CFArray*)arg1 filterID:(id)arg2 ;
-(void)addRecordsFromRepository:(id)arg1 ;
-(id)currentFirstRecord;
-(id)_searchString;
-(void)_setSearchString:(id)arg1 ;
-(id)_properties;
-(void)dealloc;
-(unsigned long long)count;
-(void)setProperty:(id)arg1 forKey:(id)arg2 ;
-(id)propertyForKey:(id)arg1 ;
@end

