/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 1:31:17 PM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/VoiceOver Utility.app/Contents/MacOS/VoiceOver Utility
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <VoiceOver Utility/VoiceOver Utility-Structs.h>
#import <AppKit/NSButtonCell.h>

@class NSImage;

@interface EjectButtonCell : NSButtonCell {

	NSImage* _onIcon;
	NSImage* _offIcon;

}
-(void)_resetImage:(char)arg1 ;
-(void)dealloc;
-(void)highlight:(char)arg1 withFrame:(CGRect)arg2 inView:(id)arg3 ;
-(void)mouseEntered:(id)arg1 ;
-(void)mouseExited:(id)arg1 ;
-(void)awakeFromNib;
@end

