/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:47:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Preview.app/Contents/MacOS/Preview
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preview/Preview-Structs.h>
#import <AppKit/NSView.h>

@class NSView;

@interface PVCollapsibleToolView : NSView {

	NSView* _expandedView;
	NSView* _collapsedView;
	char _isShowingExpandedView;
	double _expandedWidth;

}

@property (assign,nonatomic) char isShowingExpandedView;              //@synthesize isShowingExpandedView=_isShowingExpandedView - In the implementation block
@property (readonly) double expandedWidth;                            //@synthesize expandedWidth=_expandedWidth - In the implementation block
-(void)setIsShowingExpandedView:(char)arg1 ;
-(char)isShowingExpandedView;
-(id)initWithExpandedView:(id)arg1 collapsedView:(id)arg2 ;
-(double)expandedWidth;
-(void)dealloc;
-(id)description;
-(char)requiresConstraintBasedLayout;
-(CGSize)intrinsicContentSize;
-(void)layout;
@end

