/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:47:26 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Preview.app/Contents/MacOS/Preview
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preview/Preview-Structs.h>
#import <Preview/PVImageEditOperation.h>

@interface PVImageEditOperationFlip : PVImageEditOperation {

	unsigned long long _mode;

}

@property (assign) unsigned long long mode;              //@synthesize mode=_mode - In the implementation block
-(void)concatOperation:(id)arg1 ;
-(id)filterChainForSourceImage:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)mode;
-(void)setMode:(unsigned long long)arg1 ;
-(id)initWithMode:(unsigned long long)arg1 ;
@end

