/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:47:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Preview.app/Contents/MacOS/Preview
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AppKit/NSSegmentedCell.h>

@interface PVSegmentedCell : NSSegmentedCell {

	char _menuHasDelay;

}

@property (assign) char menuHasDelay;              //@synthesize menuHasDelay=_menuHasDelay - In the implementation block
-(id)realMenuForSegment:(long long)arg1 ;
-(void)setMenuHasDelay:(char)arg1 ;
-(char)menuHasDelay;
-(double)_menuDelayTimeForSegment:(long long)arg1 ;
@end

