/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:47:27 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Preview.app/Contents/MacOS/Preview
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preview/Preview-Structs.h>
#import <QuartzCore/CALayer.h>

@class NSMutableArray, CALayer;

@interface PVSelectionHandlesLayer : CALayer {

	NSMutableArray* _selectionHandles;
	CALayer* _borderLayer;
	long long _handleStyle;
	char _showsBorder;
	CGPoint _startPt;
	CGPoint _endPt;
	unsigned long long _parentOrientation;

}

@property (assign,nonatomic) char showsBorder;              //@synthesize showsBorder=_showsBorder - In the implementation block
+(double)borderWidth;
+(CGColorRef)borderColor;
-(id)initWithFrame:(CGRect)arg1 handleStyle:(long long)arg2 andViewScale:(double)arg3 ;
-(void)animateViewScaleFrom:(double)arg1 to:(double)arg2 withDuration:(double)arg3 ;
-(id)_selectionHandleLayer;
-(void)_updateViewScale:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 handleStyle:(long long)arg2 parentOrientation:(unsigned long long)arg3 andViewScale:(double)arg4 ;
-(id)initWithStartPoint:(CGPoint)arg1 andEndPoint:(CGPoint)arg2 inFrame:(CGRect)arg3 withViewScale:(double)arg4 ;
-(void)setShowsBorder:(char)arg1 ;
-(char)showsBorder;
-(void)setEndPoint:(CGPoint)arg1 ;
-(void)dealloc;
-(void)layoutSublayers;
-(void)setStartPoint:(CGPoint)arg1 ;
-(void)setViewScale:(double)arg1 ;
@end

