/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 4:47:26 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Preview.app/Contents/MacOS/Preview
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Preview/Preview-Structs.h>
#import <Preview/NSCoding.h>

@interface TRPenOutline : NSObject <NSCoding> {

	double _penSize;
	char _pathClosed;
	TRLinkedPoint* _firstPoint;
	TRLinkedPoint* _lastPoint;
	TRLinkedPoint* _enumPoint;

}

@property (assign) double penSize;                                    //@synthesize penSize=_penSize - In the implementation block
@property (assign) char pathClosed;                                   //@synthesize pathClosed=_pathClosed - In the implementation block
@property (readonly) double adjustedPointMaxDist; 
@property (readonly) double adjustedPointMaxOutlierDist; 
@property (readonly) double adjustedPointMinDist; 
-(void)setPathClosed:(char)arg1 ;
-(void)resetEnum;
-(TRLinkedPoint*)_linkedPointAtIndex:(long long)arg1 ;
-(double)penSize;
-(void)setPenSize:(double)arg1 ;
-(char)pathClosed;
-(void)deleteAllPoints;
-(CGPoint*)nextPoint:(char*)arg1 ;
-(CGPoint*)nextPoint:(char*)arg1 forEnum:(TRLinkedPoint*)arg2 ;
-(long long)numPoints;
-(TRLinkedPoint*)newEnum;
-(void)deleteSelectedPoints;
-(void)deletePointAtIndex:(long long)arg1 ;
-(TRLinkedPoint*)insertPoint:(CGPoint)arg1 atIndex:(long long)arg2 ;
-(CGPoint)pointAtIndex:(long long)arg1 selected:(char*)arg2 ;
-(void)decreasePenSize;
-(void)increasePenSize;
-(void)cloneFromOutline:(id)arg1 ;
-(void)movePointAtIndex:(long long)arg1 toPoint:(CGPoint)arg2 ;
-(void)shiftPointAtIndex:(long long)arg1 byX:(double)arg2 byX:(double)arg3 ;
-(void)shiftSelectedPointsByX:(double)arg1 byY:(double)arg2 ;
-(void)selectPointAtIndex:(long long)arg1 maintainingSelection:(char)arg2 ;
-(void)setPointAtIndex:(long long)arg1 selected:(char)arg2 ;
-(double)adjustedPointMaxDist;
-(double)adjustedPointMaxOutlierDist;
-(double)adjustedPointMinDist;
-(TRLinkedPoint*)addPoint:(CGPoint)arg1 ;
-(void)clearPoints;
-(void)selectAll;
-(id)init;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)closePath;
-(void)deselectAll;
@end

