/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 10:35:19 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/AirPort Utility.app/Contents/MacOS/AirPort Utility
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AirPort Utility/AirPort Utility-Structs.h>
#import <AirPort Utility/NSApplicationDelegate.h>
#import <AirPort Utility/NSWindowDelegate.h>
#import <AirPort Utility/NSTableViewDataSource.h>
#import <AirPort Utility/NSTableViewDelegate.h>
#import <AirPort Utility/NSPopoverDelegate.h>
#import <AirPort Utility/AUConfigureSessionDelegate.h>
#import <AirPort Utility/NSMenuDelegate.h>

@class NSWindow, AUSmallSummaryViewController, AUTopologyViewController, AUWPSViewController, AUAboutBoxController, AUPreferencesController, AirPortAssistantController, NSMutableArray, NSMenuItem, NSMenu, AUDocument, NSString;

@interface AirPortUtilityMacAppDelegate : NSObject <NSApplicationDelegate, NSWindowDelegate, NSTableViewDataSource, NSTableViewDelegate, NSPopoverDelegate, AUConfigureSessionDelegate, NSMenuDelegate> {

	NSWindow* window;
	AUSmallSummaryViewController* ssvc;
	AUTopologyViewController* autvc;
	AUWPSViewController* wpsView;
	AUAboutBoxController* _aboutBoxController;
	AUPreferencesController* _auPrefsController;
	AirPortAssistantController* _assistantController;
	char _finishedRestoringWindows;
	char _runningAssistant;
	char _scanningState;
	char _didPreviouslyBecomeActive;
	char _didPreviouslyResignActive;
	char _isURLAction;
	char _checkForURLActionAutoQuit;
	NSMutableArray* urlActionBases;
	NSMenuItem* viewMenu;
	NSMenuItem* diagsMenuItem;
	NSMenu* baseStationMenu;
	AUDocument* curDoc;
	NSMutableArray* configSessions;
	char userInteractedWithApp;

}

@property (assign) NSWindow * window; 
@property (nonatomic,retain) AUTopologyViewController * autvc; 
@property (nonatomic,retain) AUWPSViewController * wpsView; 
@property (nonatomic,readonly) char runningAssistant;                             //@synthesize runningAssistant=_runningAssistant - In the implementation block
@property (nonatomic,readonly) char canQuit; 
@property (nonatomic,readonly) char canWriteToBaseStation; 
@property (nonatomic,readonly) char canImport; 
@property (nonatomic,readonly) char canExport; 
@property (nonatomic,readonly) char canConfigureOther; 
@property (nonatomic,readonly) char canClose; 
@property (nonatomic,readonly) char canRestartBaseStation; 
@property (nonatomic,readonly) char canShowPasswords; 
@property (nonatomic,readonly) char canRestoreBaseStationToDefaults; 
@property (nonatomic,readonly) char canViewDiagsAndStats; 
@property (nonatomic,readonly) char canAddWiFiPrinter; 
@property (nonatomic,readonly) char canZoomToActualSize; 
@property (nonatomic,readonly) char canZoomIn; 
@property (nonatomic,readonly) char canZoomOut; 
@property (nonatomic,retain) NSMutableArray * urlActionBases; 
@property (assign,nonatomic) char userInteractedWithApp; 
@property (nonatomic,readonly) char topoViewEnabled; 
@property (nonatomic,readonly) char editingViewEnabled; 
@property (nonatomic,retain) NSMenuItem * viewMenu; 
@property (nonatomic,retain) NSMenuItem * diagsMenuItem; 
@property (assign,nonatomic) NSMenu * baseStationMenu; 
@property (nonatomic,retain) AUDocument * curDoc; 
@property (nonatomic,retain) NSMutableArray * configSessions; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)initialize;
-(void)setupCompleteWithResult:(int)arg1 baseStationInfo:(id)arg2 forController:(id)arg3 ;
-(void)setupProgressUpdated:(int)arg1 status:(int)arg2 paramDict:(id)arg3 forController:(id)arg4 ;
-(void)setUrlActionBases:(NSMutableArray *)arg1 ;
-(void)setConfigSessions:(NSMutableArray *)arg1 ;
-(void)windowsDidFinishRestoring:(id)arg1 ;
-(void)getUrl:(id)arg1 withReplyEvent:(id)arg2 ;
-(void)setAutvc:(AUTopologyViewController *)arg1 ;
-(void)setWpsView:(AUWPSViewController *)arg1 ;
-(void)setViewMenu:(NSMenuItem *)arg1 ;
-(void)setCurDoc:(AUDocument *)arg1 ;
-(NSMenu *)baseStationMenu;
-(char)canQuit;
-(void)documentController:(id)arg1 didCloseAll:(char)arg2 contextInfo:(void*)arg3 ;
-(void)checkPrefs;
-(void)checkForAUUpdate:(id)arg1 ;
-(void)informMacAUUpdate:(id)arg1 ;
-(void)suggestMacOSXUpdate:(id)arg1 ;
-(void)softwareUpdateSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)restartBaseStationDoIt;
-(AUTopologyViewController *)autvc;
-(void)enablePopoverEditButton:(char)arg1 ;
-(void)restoreBaseStationModalSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)updateOnRestartSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)askUserIfTheyReallyWantToRestartTheirBaseStation:(id)arg1 ;
-(char)mainWindowHasSheet;
-(char)canWriteToBaseStation;
-(char)_nodeIsBaseStationNode:(id)arg1 ;
-(id)setupControllerForCurrentItem;
-(AUWPSViewController *)wpsView;
-(char)canViewDiagsAndStats;
-(NSMenuItem *)diagsMenuItem;
-(void)configureOtherWithRemoteInfo:(id)arg1 ;
-(void)setUserInteractedWithApp:(char)arg1 ;
-(void)importConfigurationFile:(id)arg1 ;
-(void)exportConfigurationFile:(id)arg1 ;
-(char)userInteractedWithApp;
-(void)startAssistantWithMAC:(id)arg1 ;
-(void)checkForUpdates:(id)arg1 ;
-(void)selectBaseStationInTopology:(id)arg1 ;
-(void)askUserIfTheyReallyWantToRestoreTheirBaseStation:(id)arg1 ;
-(void)configureSessionEnded:(id)arg1 ;
-(void)settingsSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void*)arg3 ;
-(void)restoreBaseStationToDefaultsDoIt;
-(void)restartBaseStation:(id)arg1 ;
-(void)edit:(char)arg1 unconfiguredDevice:(id)arg2 ;
-(char)canImport;
-(char)canExport;
-(char)canConfigureOther;
-(char)canClose;
-(char)canRestartBaseStation;
-(char)canShowPasswords;
-(char)canRestoreBaseStationToDefaults;
-(void)showDiagsAndUsage:(id)arg1 ;
-(char)canAddWiFiPrinter;
-(void)addWiFiPrinter:(id)arg1 ;
-(char)topoViewEnabled;
-(char)editingViewEnabled;
-(void)terminateHandler:(id)arg1 ;
-(void)configureOther:(id)arg1 ;
-(void)showAboutBox:(id)arg1 ;
-(void)showPasswords:(id)arg1 ;
-(void)showServiceAndSupport:(id)arg1 ;
-(void)showAcknowledgements:(id)arg1 ;
-(void)showRegulatory:(id)arg1 ;
-(void)deviceWasChanged:(id)arg1 ;
-(void)airPortAssistantComplete:(id)arg1 result:(int)arg2 ;
-(char)canZoomToActualSize;
-(void)restoreBaseStationToDefaults:(id)arg1 ;
-(char)runningAssistant;
-(NSMenuItem *)viewMenu;
-(void)setDiagsMenuItem:(NSMenuItem *)arg1 ;
-(void)setBaseStationMenu:(NSMenu *)arg1 ;
-(AUDocument *)curDoc;
-(NSMutableArray *)urlActionBases;
-(NSMutableArray *)configSessions;
-(void)applicationDidFinishLaunching:(id)arg1 ;
-(void)applicationDidResignActive:(id)arg1 ;
-(void)applicationWillTerminate:(id)arg1 ;
-(void)showPreferences:(id)arg1 ;
-(void)zoomOut:(id)arg1 ;
-(void)zoomIn:(id)arg1 ;
-(char)canZoomIn;
-(char)canZoomOut;
-(void)actualSize:(id)arg1 ;
-(id)init;
-(void)dealloc;
-(NSWindow *)window;
-(unsigned long long)applicationShouldTerminate:(id)arg1 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)awakeFromNib;
-(void)setWindow:(NSWindow *)arg1 ;
-(void)menuWillOpen:(id)arg1 ;
-(char)windowShouldClose:(id)arg1 ;
@end

