/*
* This header is generated by classdump-dyld 0.7
* on Sunday, February 15, 2015 at 10:35:20 AM Central European Standard Time
* Operating System: Version 10.10.2 (Build 14C109)
* Image Source: /Applications/Utilities/AirPort Utility.app/Contents/MacOS/AirPort Utility
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AirPort Utility/AUDataModel.h>

@class NSMutableArray, NSString, NSPredicate, AUNetworkOptions;

@interface AUNetworkModel : AUDataModel {

	char loadingData;
	char canChangeRouterMode;
	NSMutableArray* routerModes;
	int routerMode;
	char enableDHCP;
	char enableNAT;
	NSString* dhcpNATRange;
	char firewallEnabled;
	char showGuestDHCPRange;
	char guestNetworkEnabled;
	NSMutableArray* dhcpReservations;
	NSMutableArray* portMappings;
	NSPredicate* portMappingIPv6Predicate;
	char shouldHideNATOnlySettings;
	char enableTimedAccessControl;
	char enableFirewallTable;
	char enableNetworkOptions;
	char fixingGuestNetworkRange;
	AUNetworkOptions* networkOptions;

}

@property (assign,nonatomic) char loadingData; 
@property (assign,nonatomic) char canChangeRouterMode; 
@property (nonatomic,retain) NSMutableArray * routerModes; 
@property (assign,nonatomic) int routerMode; 
@property (assign,nonatomic) char enableDHCP; 
@property (assign,nonatomic) char enableNAT; 
@property (assign,nonatomic) char firewallEnabled; 
@property (assign,nonatomic) char guestNetworkEnabled; 
@property (assign,nonatomic) char showGuestDHCPRange; 
@property (nonatomic,retain) NSString * dhcpNATRange; 
@property (assign,nonatomic) char shouldHideNATOnlySettings; 
@property (assign,nonatomic) char enableTimedAccessControl; 
@property (assign,nonatomic) char enableFirewallTable; 
@property (assign,nonatomic) char enableNetworkOptions; 
@property (nonatomic,retain) NSMutableArray * dhcpReservations; 
@property (nonatomic,retain) NSMutableArray * portMappings; 
@property (nonatomic,retain) NSPredicate * portMappingIPv6Predicate; 
@property (nonatomic,retain) AUNetworkOptions * networkOptions; 
-(char)saveData;
-(id)firewallEntries;
-(void)setFirewallEntries:(id)arg1 ;
-(AUNetworkOptions *)networkOptions;
-(NSMutableArray *)routerModes;
-(int)routerMode;
-(NSPredicate *)portMappingIPv6Predicate;
-(NSMutableArray *)dhcpReservations;
-(NSMutableArray *)portMappings;
-(char)enableNAT;
-(char)validateModel:(id)arg1 ;
-(void)setLoadingData:(char)arg1 ;
-(char)loadingData;
-(void)setPortMappings:(NSMutableArray *)arg1 ;
-(void)setPortMappingIPv6Predicate:(NSPredicate *)arg1 ;
-(void)setDhcpReservations:(NSMutableArray *)arg1 ;
-(void)setNetworkOptions:(AUNetworkOptions *)arg1 ;
-(void)setRouterModes:(NSMutableArray *)arg1 ;
-(void)setDhcpNATRange:(NSString *)arg1 ;
-(void)setRouterMode:(int)arg1 ;
-(void)adjustRouterModes;
-(void)adjustDHCPNATRange;
-(void)adjustDHCPOnlyRange:(id)arg1 ;
-(void)setEnableFirewallTable:(char)arg1 ;
-(void)setFirewallEnabled:(char)arg1 ;
-(void)setGuestNetworkEnabled:(char)arg1 ;
-(void)adjustGuestHostRange;
-(char)enableDHCP;
-(void)setEnableNetworkOptions:(char)arg1 ;
-(void)setShouldHideNATOnlySettings:(char)arg1 ;
-(void)setEnableTimedAccessControl:(char)arg1 ;
-(char)guestNetworkEnabled;
-(void)adjustDHCPNATForRouterMode:(int)arg1 ;
-(void)setShowGuestDHCPRange:(char)arg1 ;
-(void)setCanChangeRouterMode:(char)arg1 ;
-(char)enableNetworkOptions;
-(char)enableFirewallTable;
-(char)enableTimedAccessControl;
-(char)canChangeRouterMode;
-(void)setEnableDHCP:(char)arg1 ;
-(char)showGuestDHCPRange;
-(NSString *)dhcpNATRange;
-(char)shouldHideNATOnlySettings;
-(void)setEnableNAT:(char)arg1 ;
-(char)firewallEnabled;
-(void)adjustIPv6BlockIncomingForIPv6Config:(int)arg1 ipv6Mode:(int)arg2 shareIPConnection:(char)arg3 ;
-(id)errors;
-(id)init;
-(void)dealloc;
-(char)valid;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)didChangeValueForKey:(id)arg1 ;
-(char)validateValue:(inout id*)arg1 forKeyPath:(id)arg2 error:(out id*)arg3 ;
-(void)loadData;
@end

